### ISSUE TITLE
UAT | Judge home page shows incorrect count of cases

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#1034]
Logged in as judge, I see count of 7 cases->All(7), but no cases are listed below
<img width="1443" alt="image" src="https://github.com/user-attachments/assets/78f8efb5-dbcc-4144-b21e-c06c1d1d6e22">

**Comment by Amityadav012** [comment]
Hi Team, this issue is fixed and working as expected.
