### ISSUE TITLE
UI : Advocate should able to update or remove the complaint while the case saved as draft.

### ISSUE THREAD

**Issue by mustakim-egov** [pucardotorg/dristi#1048]
**Describe the bug**
While advocate filling the case, added complaint and verified complaint and saved the case in draft , Now when he again open the same case then he should able to update or remove the complaint.

**To Reproduce**
Steps to reproduce the behaviour:
1.Login as advocate
2.Click on File Case button
3.In Litigant Details section select Complainant Details radio button
4.Verify  Complainant Phone Number and Verify Complainant’s ID 
5.Enter valid pin code to add address
6.Now save the case as draft by clicking on 'Save as Draft' button
7.Again open the same case 
8.Try to update or remove the complainant 

**Expected behaviour**
It should able update or remove the complainant 

**Actual behaviour**
It is not possible to update or remove the complainant 

**Desktop (please complete the following information):**
OS: windows
Browser: chrome

**Comment by Amityadav012** [comment]
Hi @mustakim-egov  This issue is fixed as working as expected.

Note: Once advocate verify the mobile number or id then he can't update mobile number or id for complainant
