### ISSUE TITLE
UI: Case submitted by the advocate should display on advocate console (UI).

### ISSUE THREAD

**Issue by mustakim-egov** [pucardotorg/dristi#1049]
**Describe the bug**
When the case is submitted by the advocate and case is in Pending Payments state , then the same case should display in the advocate UI

**To Reproduce**
Steps to reproduce the behaviour:
1.Login as advocate
2.Click on File Case button
3.Fill all mandatory details as Litigant Details, Case Specific Details, Additional Details and Review & Sign 
5.Click on Submit button to submit case
6.logout as advocate
7.Again login as same advocate

**Expected behaviour**
The submitted case should display for advocate as  Pending Payments

**Actual behaviour**
The submitted case is not displaying for advocate as  Pending Payments

**Desktop (please complete the following information):**
OS: windows
Browser: chrome

**Comment by Amityadav012** [comment]
Hi @mustakim-egov  this is working as expected.
If u again face this issue then please share the login credential and env details.

**Comment by Amityadav012** [comment]
There is role changes for the advocate user that why previous user is not working.
Can u create new advocate user and try again.

I tried with this mobile number 9846546547, it is working fine.
