### ISSUE TITLE
UI : All the cases assigned to judge should display when judge click on the 'All' link

### ISSUE THREAD

**Issue by mustakim-egov** [pucardotorg/dristi#1052]
**Describe the bug**
When judge login ,All the cases assigned to him should display when judge click on the 'All' link or All the cases should display default

**To Reproduce**
Steps to reproduce the behaviour:
1.login as advocate file a case 
2. login as Nya Mitra make a payment 
3. login as FSO verify case and allocate the judge 
4. login as judge click on 'ALL' link in Your Cases section

**Expected behaviour**
All the cases assigned to him should display

**Expected behaviour**
All the cases assigned to him are not displaying

**Screenshots**
![Screenshot (168)](https://github.com/user-attachments/assets/525c36e4-4d66-4376-b7d1-7ce154f87a5b)

**Desktop (please complete the following information):**
 - OS: window
 - Browser : chrome

**Comment by Amityadav012** [comment]
Hi @mustakim-egov Please use the correct user for judge, i checked with **EMP-0-000010** user, it is working as expected.

User cred sheet :- https://docs.google.com/spreadsheets/d/1owYqsURYunnF5xYICtfFH-a2690iLJenYbQ6znOu9TA/edit?usp=sharing
