### ISSUE TITLE
UI : Respondent details are automatically removed while filling case 

### ISSUE THREAD

**Issue by mustakim-egov** [pucardotorg/dristi#1064]
**Describe the bug**
while filling case all the respondent  details are automatically removed while filling case  are automatically removed .

**To Reproduce**
Steps to reproduce the behaviour:
1. login as advocate
2. In Litigant Details add both Complainant Details and respondent Details ,click on continue
3. Fill all Case Specific Details  ,click on continue
4. Fill all Additional Details ,click on continue
5. Click  on continue on mandatory fields pending popup

**Expected behaviour**
Respondent  details should not automatically removed.

**Actual behaviour**
Respondent  details are not automatically removed.

**Desktop (please complete the following information):**
 - OS: window
 - Browser :chrome

**Comment by Amityadav012** [comment]
Hi @mustakim-egov,  Becuae of encryption services there is a change in respondent details now roll backed the services now the issue will not reproduced,
