### ISSUE TITLE
Functional || browser file button not available if advocate wants to upload Complainant's document other than adhar 

### ISSUE THREAD

**Issue by mustakim-egov** [pucardotorg/dristi#1073]
**Describe the bug**
browser file button or other text not available for button while uploading Complainant's document other than adhar 

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as advocate
2. Click on 'File Case' button
3. Select Select Case Type and click on 'Start Filing' button to file case
4. click on Complainant Details radio button
5. Upload Other ID Proof link

**Expected behaviour**
There should be proper button with text like browse file to upload document

**Actual  behaviour**
There is a button but no text available on button upload document

**Screenshots**
![Screenshot (170)](https://github.com/user-attachments/assets/c94810b5-6295-40fe-8776-49cf486626f2)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser : chrome

**Comment by Amityadav012** [comment]
Hi @mustakim-egov , This issue is related to browser/CSS. It is not happening in all browser.

Reference video:- https://jam.dev/c/d4b0d454-e7df-4d18-8786-55ed61faa0dd

One more issue is raised for same :- https://github.com/pucardotorg/dristi/issues/1193
