### ISSUE TITLE
UAT | Cheque Details| Cheque Amount should not be zero

### ISSUE THREAD

**Issue by mustakim-egov** [pucardotorg/dristi#1095]
**Describe the bug**
While Filling cheque bunch case, Cheque Amount in the Cheque Details Section should not be zero

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as advocate 
2. Click on 'File Case' button
3. Click on 'Case Specific Details' link
4. Click on Cheque Details radio button
5. Enter all mandatory check specific details 
6.Enter Cheque Amount as 0
7.Click on Continue

**Expected behaviour**
Cheque Amount text field  should not be zero

**Actual behaviour**
Cheque Amount text field  accepting zero

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Browser : chrome

![Uploading Screenshot (183).png…]()

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected in UAT env.
Ref:- 


![Image](https://github.com/user-attachments/assets/6ff360f3-270b-4d53-afb1-7c63097444eb)

**Comment by mustakim-egov** [comment]
Yes It is working fine
