### ISSUE TITLE
UAT | Debt/ Liability Details | The Partial Liability amount should not be greater then total cheque amount

### ISSUE THREAD

**Issue by mustakim-egov** [pucardotorg/dristi#1099]
**Describe the bug**
The Partial Liability amount should not be greater then total cheque amount , 

**To Reproduce**
Steps to reproduce the behaviour:
1.Login as advocate
2.Click on 'File Case' button
3.Click on 'Case Specific Details' link
4.Click on Cheque Details radio button
5.Enter all mandatory check specific details
6.Enter Cheque Amount as 1000 in the Cheque Amount text field and click on 'continue' button
7.Select nature of debt as Loan in Nature of debt radio button
8.Select Partial Liability radio button for 'Was cheque received for full liability or part liability?'
9.Now enter 10000 as total amount the cheque(s) covered? 
10.Click on 'continue' button 

**Expected behaviour**
The Partial Liability amount should not be greater then total cheque amount

**Actual behaviour**
What was the total amount the cheque(s) covered? text field should accept less than 1000 amount

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Browser : chrome

**Comment by Amityadav012** [comment]
Hi @mustakim-egov, i have checked with @anshumanth-egov about this filed validation and he told me that 

"we don't need this validation. Would be an issue if we have multiple cheques"
