### ISSUE TITLE
[BUG]: Application search does not return onBehalfOf field

### ISSUE THREAD

**Issue by subhashini-egov** [pucardotorg/dristi#1102]
**Describe the bug**
Searching for an application returns onBehalfOf as null.
**To Reproduce**
1. Go to any case
2. Click on "Make a Submission"
3. Create an application of any type
4. Go back to submissions list
5. Click on any application
6. Open the Network tab
7. Check of the "onBehalfOf" field in the application search API call

**Expected behavior**
The party on behalf of whom the advocate has filed the submission should be populated in the "onBehalfOf" API attribute.
**Screenshots**
Please see below screenshot:
![Screenshot 2024-07-31 at 4 56 34 PM](https://github.com/user-attachments/assets/4ff34085-af8f-4353-9789-5ecf4b4c4cef)

**Additional context**
The Response payload is pasted here along with the original request.

{"ResponseInfo":{"apiId":"Rainmaker","ver":null,"ts":null,"resMsgId":"uief87324","msgId":"1722424812997|en_IN","status":"successful"},"application":{"responseRequired":true,"id":"f158d36f-6083-4946-8acc-2bb4d327c377","tenantId":"pg","caseId":"f4eed9aa-a1ff-4bcc-ae15-ca630f89a811","filingNumber":"F-C.1973.002-2024-001344","cnrNumber":"KLJL01-001344-2024","referenceId":null,"createdDate":"31-07-2024","createdBy":null,"onBehalfOf":["d71e37fb-def2-47bf-9d8e-0399eded18e2"],"applicationType":"SURETY","applicationNumber":"APPLICATION-NO-2024-07-31-000487","issuedBy":null,"status":"PENDINGESIGN","comment":null,"isActive":true,"statuteSection":{"id":"3387e541-7dd4-4f66-9c36-219a2edf76a9","tenantId":"pg","statute":null,"sections":null,"subsections":null,"additionalDetails":null,"auditdetails":{"createdBy":"d71e37fb-def2-47bf-9d8e-0399eded18e2","lastModifiedBy":"d71e37fb-def2-47bf-9d8e-0399eded18e2","createdTime":1722424813262,"lastModifiedTime":1722424813262},"strSections":null,"strSubsections":null},"documents":[],"additionalDetails":{"formdata":{"submissionType":{"code":"APPLICATION","name":"APPLICATION"},"applicationType":{"id":8,"type":"SURETY","isactive":true,"name":"APPLICATION_TYPE_SURETY"},"applicationDate":"2024-07-31","nameOfSurety":"Sample","bailAmount":"50000"},"onBehalOfName":"Ayan Adv","partyType":"complainant.primary","isResponseRequired":true},"auditDetails":{"createdBy":"d71e37fb-def2-47bf-9d8e-0399eded18e2","lastModifiedBy":"d71e37fb-def2-47bf-9d8e-0399eded18e2","createdTime":1722424813262,"lastModifiedTime":1722424813262},"workflow":{"action":"CREATE","comments":"Workflow comments","documents":[{"id":null,"documentType":null,"fileStore":null,"documentUid":null,"additionalDetails":null}],"assignes":null,"rating":null}}}

**Response JSON**:

{"ResponseInfo":{"apiId":"Rainmaker","ver":null,"ts":null,"resMsgId":"uief87324","msgId":"1722425027306|en_IN","status":"successful"},"TotalCount":1,"applicationList":[{"responseRequired":false,"id":"f158d36f-6083-4946-8acc-2bb4d327c377","tenantId":"pg","caseId":"f4eed9aa-a1ff-4bcc-ae15-ca630f89a811","filingNumber":"F-C.1973.002-2024-001344","cnrNumber":"KLJL01-001344-2024","referenceId":null,"createdDate":"31-07-2024","createdBy":null,"onBehalfOf":null,"applicationType":"SURETY","applicationNumber":"APPLICATION-NO-2024-07-31-000487","issuedBy":null,"status":"PENDINGESIGN","comment":null,"isActive":true,"statuteSection":{"id":"3387e541-7dd4-4f66-9c36-219a2edf76a9","tenantId":"pg","statute":null,"sections":null,"subsections":null,"additionalDetails":null,"auditdetails":{"createdBy":"d71e37fb-def2-47bf-9d8e-0399eded18e2","lastModifiedBy":"d71e37fb-def2-47bf-9d8e-0399eded18e2","createdTime":1722424813262,"lastModifiedTime":1722424813262},"strSections":null,"strSubsections":null},"documents":null,"additionalDetails":{"formdata":{"bailAmount":"50000","nameOfSurety":"Sample","submissionType":{"code":"APPLICATION","name":"APPLICATION"},"applicationDate":"2024-07-31","applicationType":{"id":8,"name":"APPLICATION_TYPE_SURETY","type":"SURETY","isactive":true}},"partyType":"complainant.primary","onBehalOfName":"Ayan Adv","isResponseRequired":true},"auditDetails":{"createdBy":"d71e37fb-def2-47bf-9d8e-0399eded18e2","lastModifiedBy":"d71e37fb-def2-47bf-9d8e-0399eded18e2","createdTime":1722424813262,"lastModifiedTime":1722424813262},"workflow":{"action":"PENDINGESIGN","comments":"Workflow comments","documents":null,"assignes":null,"rating":null}}]}

**Comment by Amityadav012** [comment]
Manimaaran fixed this issue and working as expected.
