### ISSUE TITLE
UAT | Registration | Only two id options

### ISSUE THREAD

**Issue by AyushiSinghalLaw** [pucardotorg/dristi#1108]
**Describe the bug**
Apart from Aadhar, the only option for id card is PAN. In addition, Aadhar is available as an option both for OTP verification as well as manual id upload. 

**To Reproduce**
1. Go to 'citizen login page'
2. Click on 'Register'
3. Scroll down to 'upload document' -> manual id 

**Expected behavior**
User should get other options apart from PAN for manual verification. Aadhar should not show in manual verification. 

**Screenshots**

![Image](https://github.com/user-attachments/assets/ad1c8eb0-b5ba-4d16-b5fb-33f3a2fa0df4)

**Desktop (please complete the following information):**
 - OS: Windows [e.g. iOS]
 - Browser: Edge [e.g. chrome, safari]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Taherabharmal** [comment]
master data in solution

**Comment by Ramu-kandimalla** [comment]
@shambhavigoel1002  can you please add the Master data

**Comment by shambhavigoel1002** [comment]
Completed can be moved for qa testing @Ramu-kandimalla

**Comment by shambhavigoel1002** [comment]
Hi @Ramu-kandimalla Please move this too

**Comment by Ramu-kandimalla** [comment]
Hi @rajeshcherukumalli  Please verify and confirm in UAT environment

**Comment by kashish384** [comment]
- Regarding_Type of ID
- Env.UAT
- url: https://dristi-kerala-uat.pucar.org/digit-ui/citizen/dristi/home/registration/upload-id
- reference link:  
           -                 Litigant_ https://jam.dev/c/2174f88e-63b8-456a-96ef-d97b9b640ce2
           -                  Advocate_https://jam.dev/c/1b92d33f-e090-4e74-88e2-029adcfe30d8
           -                  Advocate Clerk_https://jam.dev/c/3cc8b3af-88f6-443b-a2a6-21c8f48c2e3e

-  Test cases:
 1.verify that in 'Type of ID' dropdown, for user all the option are enable.
 2.verify that user able to select 'Passport' type of id.
 3.verify that user able to select 'Pan Card' type of id.
 4.verify that user able to select 'Driving License' type of id.
 5.verify that user able to select 'Voter ID' type of id.
 6.verify that user able to select 'Aadhar' type of id.
 7.verify that selected option by user,visible in 'Type of ID' dropdown.

**Comment by Ramu-kandimalla** [comment]
Hi All This issue is fixed and deployed in UAT
