### ISSUE TITLE
UAT | Join a case | User name not visible

### ISSUE THREAD

**Issue by AyushiSinghalLaw** [pucardotorg/dristi#1110]
**Describe the bug**
My name in place of "digit-user"

**To Reproduce**
1. Go to 'login'

**Expected behavior**
The user name should be visible on the screen, after I have registered and signed in, and not 'digit-user'. 

**Screenshots**

![Image](https://github.com/user-attachments/assets/2fa33817-4c87-4d27-83d5-85a2cd18e345)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Amityadav012** [comment]
Once the user will successfully register in application then only he will able to view details/name.

While registration process user will not able to view user name.
