### ISSUE TITLE
[BUG]: [Title] UAT | Home screen | use of 'pucar'

### ISSUE THREAD

**Issue by AyushiSinghalLaw** [pucardotorg/dristi#1111]
**Describe the bug**
The name PUCAR should not be used anywhere. 

**To Reproduce**
1. Go to 'home page'. After logging in. 

**Expected behavior**

**Screenshots**

![Image](https://github.com/user-attachments/assets/89f6df73-d001-458f-8382-d1f574bb4514)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Taherabharmal** [comment]
Replace with 'On Courts'

**Comment by Amityadav012** [comment]
Removed the name PUCAR from all screen.
