### ISSUE TITLE
[BUG]: [Title] UAT | Home Screen | Shows Join as Advocate upon logging in as litigant

### ISSUE THREAD

**Issue by AyushiSinghalLaw** [pucardotorg/dristi#1112]
**Describe the bug**
Description to join a case says: "Seeking to represent a client in an ongoing case?
Join in as an advocate"

**To Reproduce**
1. Go to '.Home page'

**Expected behavior**
Litigant should be able to join the case as litigant. 

**Screenshots**

![Image](https://github.com/user-attachments/assets/d228c5b7-b8db-4061-979c-b10c44aa01d4)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Amityadav012** [comment]
Hi @AyushiSinghalLaw, As per figma the text was mentioned if required will update the same.

**Comment by Taherabharmal** [comment]
Updated text 'Want to track an ongoing case where you are a party? Join the case'

**Comment by rajeshcherukumalli** [comment]
![Screenshot from 2024-08-21 23-10-25](https://github.com/user-attachments/assets/e588aba1-3448-43ac-a932-a8db91a88ba3)
The mentioned text is updated.

**Comment by Ramu-kandimalla** [comment]
This issue is fixed and working fine in UAT Env
