### ISSUE TITLE
[BUG]: [Title] UAT| Filling | Download button doesn't work

### ISSUE THREAD

**Issue by AyushiSinghalLaw** [pucardotorg/dristi#1115]
**Describe the bug**
Download button doesn't work - upload docs screen

**To Reproduce**
1. Go to 'file a case'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Amityadav012** [comment]
the download PDF format is not integrated yet, once this is integrated issue will be resolved.
