### ISSUE TITLE
[BUG]: [Title] UAT | Filing | View case

### ISSUE THREAD

**Issue by AyushiSinghalLaw** [pucardotorg/dristi#1116]
**Describe the bug**
View case window doesn't show unless you've filed a case. 

**To Reproduce**
1. Go to '.Home screen'

**Expected behavior**
 show the view case option anyway, and show it empty. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Amityadav012** [comment]
Currently we are allowing to view a case option, once judge will admit the case.

**Comment by Ramu-kandimalla** [comment]
Since this issue is invalid we are closing this issue
