### ISSUE TITLE
[BUG]: [Title] UAT | Filing | Complainant 2 id verified

### ISSUE THREAD

**Issue by AyushiSinghalLaw** [pucardotorg/dristi#1117]
**Describe the bug**
Complainant 2's id shows verified, when only Complainant 1's id was verified. 

**To Reproduce**
1. Go to '.File a case'
2. Click on 'Add complainant'

**Expected behavior**
Complainant 2's id should show verified only if it has actually been verified. 

**Screenshots**

![Image](https://github.com/user-attachments/assets/10cfabce-d7ed-4f35-92ac-889494fb922b)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Amityadav012** [comment]
Not able to reproduce this issue "Complainant 2's id shows verified, when only Complainant 1's id was verified".

Tried multiple times, working as Expected in UAT env.
