### ISSUE TITLE
UAT | Filing | Delete Complainant 2/ Respondent 2

### ISSUE THREAD

**Issue by AyushiSinghalLaw** [pucardotorg/dristi#1123]
**Describe the bug**
No option to Delete Complainant 2/ Respondent 2 once added. 

**To Reproduce**

**Expected behavior**
Users should be able to delete additional complainants or respondents. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Beehyv-Vinod** [comment]
Tested in QA env, Working fine. User can delete Complainant / Respondent.

Ref,
https://jam.dev/c/afc6d1c1-173a-40ea-b752-fc0b8d16b41e
