### ISSUE TITLE
UAT | Selected date not populated in order

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#1125]
Logged in as judge, I have selected a date and proceeded to schedule a hearing. But the hearing date field is blank, doesn't reflect the selected date. Video attached

https://github.com/user-attachments/assets/687538a4-05ee-4540-88f3-4bece195fe22

Desktop:**
 - OS: macos, chrome

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected.
