### ISSUE TITLE
UAT | Litigant can see deleted orders

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#1126]
While logged in as a judge, I created 3 drafts of orders.
Deletd 2 drafts.
Published 1 order.

While logged in as complainant, I can see the deleted orders too.

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/b6dcc5ac-3482-4b45-88a5-fb4f60645799">

**Comment by Taherabharmal** [comment]
List of who can see what is here

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected in UAT env.
