### ISSUE TITLE
UAT | Wrong options shown for hearing that hasnt started yet

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#1127]
When I click on the action button for a hearing that hasn't started yet, I see the below options

<img width="1449" alt="image" src="https://github.com/user-attachments/assets/f8d508f7-d52a-4abc-b296-54c066ff8f09">

My understanding is we should see these options instead:
<img width="105" alt="image" src="https://github.com/user-attachments/assets/2ac72448-93c7-47f4-b291-d5a2f6237787">

**Comment by rajeshcherukumalli** [comment]
Issue is fixed, please find the reference 
https://jam.dev/c/973b4465-702d-4122-814d-f24253d4e52a

**Comment by anshumanth-egov** [comment]
at 0:05: you clicked on a hearing that had not started yet ( the option said "Start Hearing"), but options showed View Transcript and Deposition). My understanding is this is wrong, those options are visible only after hearing is concluded. 
@Taherabharmal can confirm.
