### ISSUE TITLE
UAT| Case Filling | Litigant raises the case ,Case got admitted but still not displaying in Litigant screen

### ISSUE THREAD

**Issue by mustakim-egov** [pucardotorg/dristi#1135]
**Describe the bug**
Litigant raises the case ,Case got admitted but still not displaying in Litigant screen

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as Litigant
2. Click on 'File Case' button
3. Fill all mandatory details submit case
5. Login as the Nya Mitra accept the payment
6. Login as the FSO register the case 
7. Login as judge admit the case
8. Now login as Litigant

**Expected behaviour**
Case should display in Litigant screen

**Actual behaviour**
Case got admitted but still not displaying in Litigant screen

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome

**Comment by Amityadav012** [comment]
Hi @mustakim-egov Please check with new user.
I think this issue occurred due to new role mapping. 

If you still facing this issue let me know.
