### ISSUE TITLE
UAT | Nyayamitra | Case which are in Cognizance, Evidence state should be visible to Nyayamitra 

### ISSUE THREAD

**Issue by mustakim-egov** [pucardotorg/dristi#1141]
**Describe the bug**
Case which are in Cognizance, Evidence state are not be visible to Nyayamitra

**To Reproduce**
Steps to reproduce the behaviour:
1. Once the judge admit the case
2. Login as judge and schedule a hiring
3. login as Nyayamitra and Search for same case

**Expected behaviour**
Case which are in Cognizance, Evidence state should  be visible to Nyayamitra

**Actual behaviour**
Case which are in Cognizance, Evidence state are not be visible to Nyayamitra

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
  - Browser :. chrome, safari]

**Smartphone (please complete the following information):**
 - Browser: chrome

**Comment by vaibhavct** [comment]
@mustakim-egov 
As per the expected behaviour, the only action which Nyaymitra user can perform is payment of the case, hence we're showing only cases which are under payment pending

**Comment by Beehyv-Vinod** [comment]
As mentioned by @vaibhavct , We are showing only the cases with pending payments to Nyayamitra in View Cases screen.
