### ISSUE TITLE
UAT | Filing | Court Fee

### ISSUE THREAD

**Issue by AyushiSinghalLaw** [pucardotorg/dristi#1170]
**Describe the bug**
not clear what is the difference between "Amount Due" and "Total Fees" on fee payment page. In addition, why does the litigant have to pay "Advocate Fees"? "Learn More" link is not working. Why does it say litigant has to come to court to make the fee payment?

**To Reproduce**
1. Go to '.Submit case file' (after filing)
2. Click on '.home -> pending tasks 
3. Scroll down to 'pay to file a case'

**Expected behavior**

Explain clearly what each fees is for. Enable online payment, and "learn more" link.

**Screenshots**

![Image](https://github.com/user-attachments/assets/05a07b93-2d98-4503-8f52-f6bcca218cbb)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Taherabharmal** [comment]
to be taken care of in solution
