### ISSUE TITLE
UAT | Home page | Filed case not shows on Home screen

### ISSUE THREAD

**Issue by AyushiSinghalLaw** [pucardotorg/dristi#1172]
**Describe the bug**

Cases already filed not seen on home page, though there is a pending task against it.

The Home page should share more about what the system means by "Join a case" (cases that have already been filed), "File a case" (i.e.. when a person wants to file a new case).  

**To Reproduce**
1. Go to 'Home Page' (after you have filed a case)

**Expected behavior**

Show filed case in Your Cases. plus, explain what "join a case" means

**Screenshots**

![Image](https://github.com/user-attachments/assets/756560c0-cb6f-4987-9484-650c0e993e1d)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Amityadav012** [comment]
Hi @AyushiSinghalLaw  Please check with new user.
I think this issue occurred due to new role mapping.

If you still facing this issue let me know.
