### ISSUE TITLE
UAT | Scheduling hearing

### ISSUE THREAD

**Issue by AyushiSinghalLaw** [pucardotorg/dristi#1175]
**Describe the bug**
"10 Hearings scheduled" doesn't change irrespective of the date I select. 

**To Reproduce**
1. Go to 'Schedule Hearing' - custom hearing - from the Judge's dashboard. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by anirudh-0** [comment]
@Beehyv-Vinod can you check if this is still present

**Comment by Beehyv-Vinod** [comment]
Tested in QA, Counts are changing Based on hearings scheduled for the day, 

Ref,
https://jam.dev/c/7297e5d1-e89d-43bc-ba2e-95bc319141d9
