### ISSUE TITLE
UAT | Admission | Shows hearing scheduled before admission

### ISSUE THREAD

**Issue by AyushiSinghalLaw** [pucardotorg/dristi#1178]
**Describe the bug**
not sure why it says "Hearing is schedule!" at the bottom, when the case is not admitted. 

**To Reproduce**

**Expected behavior**

**Screenshots**

Video added to testers whatsapp group 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Taherabharmal** [comment]
This is invalid;.

If an admission hearing is scheduled,it should hearing scheduled. Can we localize it to Admission hearing scheduled @SureshSoren

**Comment by Amityadav012** [comment]
Added the localisation.
