### ISSUE TITLE
UAT | Next case and Close do same thing

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#1187]
After FSO has admitted a case, the Next Case and Close button both do the same thing of returning to home page.

https://github.com/user-attachments/assets/2c2afe04-1f04-40ec-87c9-37475d647744

**Comment by Amityadav012** [comment]
Hi @anshumanth-egov , we don't have expected behaviour for this in PRD or in figma.

Can you share the expected behaviour for this?

**Comment by Taherabharmal** [comment]
@Amityadav012 next case should open the next case in the inbox list due for scrunity

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected.
