### ISSUE TITLE
UAT | E-Filing | 202 Inquiry Affadavit

### ISSUE THREAD

**Issue by deeshita** [pucardotorg/dristi#1188]
**Describe the bug**
In case pincode of the complainant is different from respondant, then the system nudges a 202 Inquiry affadavit. However, this depends on jurisdiction of court being different from respondant pincode and does not have anything to do with complainant pincode. 

Further, as per BNSS, this field should be renamed to 225 inquiry.

**To Reproduce**
1. Go to 'File Case'
2. Navigate to the section on 'Respondant Details'  
3. Scroll down to the '202 Inquiry affidavit' field

**Expected behavior**
Flag on 202 inquiry only to be made if respondant pincode is outside court jurisdiction. Kollam district in pilot court

Field to be displayed as '225 Inquiry'

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
![Screenshot 2024-08-01 133928](https://github.com/user-attachments/assets/085470d4-5e36-469b-b409-53a9a48dd328)

**Comment by Amityadav012** [comment]
Hi @deeshita , Will take a discussion with dev team and then get back to you.

**Comment by Taherabharmal** [comment]
@Amityadav012 @SureshSoren remove mandatory validation for 202 affidavit and rename field for now.

**Comment by Amityadav012** [comment]
Removed the mandatory validation for 225 inquiry affidavit and Renamed the NOTE Message as **Uploading a 225 inquiry affidavit is optional.**
