### ISSUE TITLE
UAT: Alignment of "Upload" button in screen is not right

### ISSUE THREAD

**Issue by deeshita** [pucardotorg/dristi#1193]
**Describe the bug**
In the screen for 'Prayer and Sworn Statement' Details, the upload button orientation for 'Memorandum of Complaint' is off  
![Screenshot 2024-08-01 134603](https://github.com/user-attachments/assets/d48bbeeb-4c25-4f11-b5df-b56661f29d48)

**To Reproduce**
1. Go to 'File Case'
2. Navigate to 'Prayer and Sworn Statement' Details
3. Scroll to field for 'Memorandum of Complaint'
4. Click on button for 'Browse in my files'

**Expected behavior**
The upload button should be aligned in the provided space

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by Amityadav012** [comment]
Hi @deeshita this issue is related to browser/CSS, changing the severity to medium. It is not Happening in all browser.

Reference video:-  [https://jam.dev/c/d4b0d454-e7df-4d18-8786-55ed61faa0dd](url)

**Comment by rajeshcherukumalli** [comment]
Issue is fixed, please find the reference
![Screenshot from 2024-08-21 23-20-25](https://github.com/user-attachments/assets/b86c7922-615b-484c-8c80-2586bb09bd98)

**Comment by Ramu-kandimalla** [comment]
This issue is fixed and working as expected in UAT
