### ISSUE TITLE
UAT | Filing | Advocate Details

### ISSUE THREAD

**Issue by deeshita** [pucardotorg/dristi#1194]
**Describe the bug**
In the section for "advocate details", there is no ability to edit the details that are auto-filled

**To Reproduce**
1. Go to 'File Case'
2. Navigate to 'Advocate Details'

**Expected behavior**
The advocate details section and all fields within should be editable by the user.
![Screenshot 2024-08-01 135231](https://github.com/user-attachments/assets/a29b4a07-34c5-4444-b25f-033111a6002f)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by subhashini-egov** [comment]
@Taherabharmal marking this as low priority right now. Please mark it as an enhancement if this is something we can pick up in later relases.
