### ISSUE TITLE
UAT | Orders| Preview 'Cross' Icon not working and PDF Preview not shown

### ISSUE THREAD

**Issue by deeshita** [pucardotorg/dristi#1197]
**Describe the bug**
When the PDF template of an order is generated after the form has been populated on clicking 'Review Order' - the preview of the order is not visible and the cross icon to exit that view is not working

**To Reproduce**
1. Go to 'Case Name' from the home screen  
2. Within the case page, click on the 'Generate Order' button and populate the form 
3. Click on the 'Review' Order button to see the pop-up

**Expected behavior**
The PDF preview of the order should have been visible and clicking on the 'cross' icon should have closed the pop-up and gone back to the form

**Screenshots**
![Screenshot 2024-08-01 141017](https://github.com/user-attachments/assets/14aa2e07-f1e6-4d76-8c8a-6fbfb2c3cb0d)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by subhashini-egov** [comment]
@anirudh-0 this is a must-fix.

**Comment by Beehyv-Vinod** [comment]
1. When user click on Cross icon user is navigating back to the Form, working fine
2. PDF preview templates are not there, This will be built in Solution.

https://github.com/user-attachments/assets/0a7af571-145b-44f2-bfd2-099761268069
