### ISSUE TITLE
UAT | Orders| Dropdown in ADR Order for Mode

### ISSUE THREAD

**Issue by deeshita** [pucardotorg/dristi#1214]
**Describe the bug**
In Order of Referal of Case to ADR, no dropdown value in "Mode for ADR"

**To Reproduce**
1. Go to any case in the home page of the judge
2. Click on the Take action button and within it on 'Generate Order'
3. In Order Type, select Order Type as 'Order of Referral of Case to ADR' 
4. Click on field for 'Mode of ADR' to see error

**Expected behavior**
Expected to see 'Mediation'. 'Arbitaration' and 'Conciliation' in the dropdown

**Screenshots**
![Screenshot 2024-08-06 191815](https://github.com/user-attachments/assets/77ae4de3-9cef-49e0-b7e4-6f21ad3df538)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by Taherabharmal** [comment]
@manimaarans please ensure this is in master data.
The following are the values: 
Arbitration, meditiation, Conviliation, Lok Adalat. 

cc @atulgupta2024 @subhashini-egov

**Comment by Taherabharmal** [comment]
Sorry, Conciliation

**Comment by Amityadav012** [comment]
Added the master data in "Mode for ADR" and working as expected.
