### ISSUE TITLE
UAT } Orders | Two Similar Orders

### ISSUE THREAD

**Issue by deeshita** [pucardotorg/dristi#1215]
**Describe the bug**
In Order Type Dropdown, there are orders for assigning date to rescheduled hearing and orders for assigning new hearing date

**To Reproduce**
1. Go to any case in the home page of the judge
2. Click on the Take action button and within it on 'Generate Order'
3. In Order Type, open the dropdown to see error

**Expected behavior**
Expected only one of the two orders to be present

**Screenshots**
![Screenshot 2024-08-06 192403](https://github.com/user-attachments/assets/5d3d467e-e880-4359-aa97-3cdf7f42bfd0)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by Taherabharmal** [comment]
@anirudh-0 what is functionality difference between the two?

**Comment by anirudh-0** [comment]
@Taherabharmal both order types are in functional specs. One is for finishing up hearing reschedule after Opt Out, one is for scheduling the next hearing after adjourn/end hearing

**Comment by Taherabharmal** [comment]
@anirudh-0 let's discuss, some confusion here

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected in UAT env.
