### ISSUE TITLE
UAT| Orders| Flagging of Dates in Mandatory Submissions Order

### ISSUE THREAD

**Issue by deeshita** [pucardotorg/dristi#1216]
**Describe the bug**
In Order for Mandatory Document Submissions and Responses, if response date is after submission date, the warning is given to the judge

**To Reproduce**
1. Go to any case in the home page of the judge
2. Click on the Take action button and within it on 'Generate Order'
3. In Order Type, open the dropdown and select ' Order for Mandatory Document Submissions and Responses'
4. Input fields for submission date and response date and see error

**Expected behavior**
Expected a flag to come up warning that the response date was put in before the submission date or in the response date field, dates before the submission date to be disabled

**Screenshots**
![Screenshot 2024-08-06 192851](https://github.com/user-attachments/assets/dc8e83b9-2432-49a3-a41a-d6fdf8b8cb39)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by Taherabharmal** [comment]
@anirudh-0 @Ramu-kandimalla all dates in the product to be in DD/MM/YYYY

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected in UAT env.
