### ISSUE TITLE
UAT|Orders| Fields that are dependent on a prior field in 'order for mandatory submissions' not disappearing

### ISSUE THREAD

**Issue by deeshita** [pucardotorg/dristi#1217]
**Describe the bug**
In the order for mandatory submission, in case no response is required, then the fields for parties to respond and deadline for response should not appear but these are visible and mandatory.

**To Reproduce**
1. Go to any case in the home page of the judge
2. Click on the Take action button and within it on 'Generate Order'
3. In Order Type, open the dropdown and select ' Order for Mandatory Document Submissions and Responses'
4. Input fields for response required as 'no' and see error

**Expected behavior**
Expected the fields for parties to respond and for the date of response to disappear

**Screenshots**
![Screenshot 2024-08-06 193339](https://github.com/user-attachments/assets/3bbcaf51-b96b-4cf5-993f-a6b87f18f5b9)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by Ramu-kandimalla** [comment]
This Issue Is Fixed and working as expected in UAT please refer to the above video
