### ISSUE TITLE
UAT | Orders | Field marked as optional should be mandatory

### ISSUE THREAD

**Issue by deeshita** [pucardotorg/dristi#1218]
**Describe the bug**
In the order for rejection of anything i.e extension request, submission, reschedule, etc., the reason for rejection field should be mandatory

**To Reproduce**
1. Go to any case in the home page of the judge
2. Click on the Take action button and within it on 'Generate Order'
3. In Order Type, open the dropdown and select ' Order for Rejection of Voluntary Submissions'

**Expected behavior**
Expected the fields for 'Reason for Rejection' to be mandatory to input

**Screenshots**
![Screenshot 2024-08-06 193851](https://github.com/user-attachments/assets/d946ad2d-3fdf-432b-9f08-532e22420e46)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected.
