### ISSUE TITLE
UAT: Single digit door number

### ISSUE THREAD

**Issue by atulgupta2024** [pucardotorg/dristi#1222]
Why is Door Number restricted to having at least 2 digits? Just 1 digit should also be allowed. 

![DoorNo Address](https://github.com/user-attachments/assets/dca15693-189b-488c-b0f8-7ca9db248adb)

**Comment by Taherabharmal** [comment]
yes, plus can we make door number alphanumeruc

**Comment by atulgupta2024** [comment]
agreed. We should make door number alpha numeric. Mini - 1. Max - 8 or to be safer, 16.

**Comment by subhashini-egov** [comment]
@manimaarans As discussed:

1. Please check-in the individual service code (that has been modified/upgraded) into the DRISTI repo under a 'common' folder.
2. Please copy the models the Individual service uses from the common library (HCM) and paste it into the Individual service itself. 
3. Make the validation modifications necessary for DRISTI, build and deploy these images.

**Comment by kashish384** [comment]
@TusharKatiyar2002 _please look on these issues
Qa env_regarding _Door Number
1.E-filing| With new user that is not registered in system_api issue.
https://jam.dev/c/151d64b2-f3c0-4d5d-ae06-c3a9dee56bc9
2.E-filing| more then one complainant so after giving input for address__api issue.
https://jam.dev/c/03d9c392-4ecf-42d3-8fdb-f09823402a99

**Comment by kashish384** [comment]
@Hi, Ramu-kandimalla _these all bugs are fixed.Here we have few scenario with the reference link,kindly verify.
DPG Qa env_regarding _Door Number
1.For user registration __https://jam.dev/c/f0669ad4-d5a6-45bf-9a2c-967bc531570a
2.While E-Filing as a Complainant__https://jam.dev/c/d6170939-f1c9-43b2-9a46-ff5cbcfc0e5d
3.With new user that is not registered in system___https://jam.dev/c/8ff52b4e-e8ba-47fd-a964-df58d33441d6
4.more then one complainant so after giving input for address__https://jam.dev/c/b059914d-5375-4e72-b497-7f7176cc66a5
5.While E-Filing as a Respondent__https://jam.dev/c/905325a8-ed53-4fc8-ac6e-0e3148890f44

**Comment by Ramu-kandimalla** [comment]
Hi @Taherabharmal, this issue is fixed and verified from my end, please check and confirm

**Comment by kashish384** [comment]
Hi @Ramu-kandimalla ,kindly verify this__
  -  Regarding_Single digit door number
  -  Env.UAT
  -  url: https://dristi-kerala-uat.pucar.org/digit-ui/citizen/dristi/home/registration/user-address
  - reference link:
       - Litigant_ https://jam.dev/c/2a4d20aa-247d-4173-b38e-41c886145bd6
       - Advocate_https://jam.dev/c/1c12948f-cc3d-4921-957f-81172594adbb
       - Advocate Clerk_https://jam.dev/c/5e254dad-2a63-4840-977f-8ef0fc16e2ef

**Comment by Ramu-kandimalla** [comment]
Hi @Taherabharmal  Please verify and confirm
