### ISSUE TITLE
UAT: Advocate Registration Approval

### ISSUE THREAD

**Issue by atulgupta2024** [pucardotorg/dristi#1224]
I logged in a Nyaymitra and went to Registration Requests page (see image below) 

![beforeverify](https://github.com/user-attachments/assets/8ef62543-30b0-4069-a7a7-2698c27db7e0)

I selected the last application (*-000336) and clicked on the application number to open it. It took me to application details page and it has a verify or reject button at the bottom. I clicked "Verify". It took me back to the registration requests page, and i could still see the last entry (even after approval). I clicked on the application number again, and got an error page and then back also didn't help. Had to refresh. Need to relook at the error page as well. 

![ErrorPage](https://github.com/user-attachments/assets/7230290c-bac2-4004-8131-f9eaa6aa0fba)

**Development Tasks:**

- [x] Creating a new model between the API call and return home page 
- [x] Model will create a time buffer to load the page 
- [ ] Localization of model text "Registration verified successfully"

**Comment by subhashini-egov** [comment]
@manimaarans two parts to this problem:

1. If data is not available in the elastic search due to async nature of events
2. If UI is not refreshing data from ES

Which one is happening here? Do we know for sure?

**Comment by atulgupta2024** [comment]
@manimaarans let's then add a message popup saying application approved successfully in between. Also i hope that when I am navigated back the page reloads. 

cc: @anirudh-0 @Taherabharmal @subhashini-egov

**Comment by rsi-MaheshVishwanath** [comment]
Tested in "DPG QA," and it is working as expected. Thanks!
https://jam.dev/c/3654c67d-f130-438b-8249-91c2c39d56cf

**Comment by rsi-MaheshVishwanath** [comment]
Hi @devarajd94 @Taherabharmal,

Description: When a Nyay Mitra approves a user registration, a pop-up message should appear that reads, "Registration request is accepted successfully." This message should include a "Go to Home" button and a cross icon, displayed in the "DPG QA" environment.

Test Cases:

1)Verify that the Nyay Mitra sees the pop-up message "Registration request is accepted successfully" with the "Go to Home" button and the cross icon after approving the user registration.
2) Verify that the user can click the "Go to Home" button successfully.
3)Verify that the user can click the cross icon successfully.
4) Verify that for old registration approvals, the pop-up message "Registration request is accepted successfully" with the "Go to Home" button and cross icon is displayed correctly.
5) Verify that for new registration approvals, the pop-up message "Registration request is accepted successfully" with the "Go to Home" button and cross icon is displayed correctly.
6)Verify that after clicking the "Go to Home" button or the cross icon, the user is redirected to the Home screen of registrations

Reference Link: https://jam.dev/c/3654c67d-f130-438b-8249-91c2c39d56cf
Advocate url: https://dristi-qa.pucar.org/digit-ui/citizen/select-language
Nyay Mitra url :https://dristi-qa.pucar.org/digit-ui/employee/user/login
nyay mitra users: https://docs.google.com/spreadsheets/d/1owYqsURYunnF5xYICtfFH-a2690iLJenYbQ6znOu9TA/edit?pli=1&gid=574770155#gid=574770155

**Comment by atulgupta2024** [comment]
@Taherabharmal @devarajd94 @Ramu-kandimalla 

The message text  -- "Registration request is accepted successfully." doesn't seems fine to me. Since the button says "Verify", I think the message should be "Registration verified successfully"

**Comment by Ramu-kandimalla** [comment]
Hi @atulgupta2024  Updated the localization Text as suggested

**Comment by kashish384** [comment]
Hi @Ramu-kandimalla, kindly verify this:
  -  Regarding_Advocate Registration Approval
  -  Env.UAT
  -  url: 
     - Citizen url : https://dristi-kerala-uat.pucar.org/digit-ui/citizen/dristi/home
     - Nyay Mitra url : https://dristi-kerala-uat.pucar.org/digit-ui/employee/dristi/registration-requests?type=advocate
     - Nyay mitra users: https://docs.google.com/spreadsheets/d/1w0RT8lHfx7T2-WaTW2DS-66THYjtyNYTw-FDoqJp5- o/edit?gid=0#gid=0
  -  reference link:
       - Advocate_https://jam.dev/c/859ee641-90ac-4a81-b49e-88c298c9f586
       - Advocate Clerk_https://jam.dev/c/022c77de-f3c1-42ab-b389-5232272d80ab

**Comment by Ramu-kandimalla** [comment]
Hi @Taherabharmal  please veridy and confirm
