### ISSUE TITLE
UAT: landing page after login

### ISSUE THREAD

**Issue by atulgupta2024** [pucardotorg/dristi#1226]
Here's what I see after login in. In most other pages, the "Good Morning, <name>" appears in a larger bold font. We may want to retain consistency. 

![LoginHomeScreen](https://github.com/user-attachments/assets/e09d0f0d-6ee0-471c-ad4e-ed46c49450cc)

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected.
Ref :- 

![Image](https://github.com/user-attachments/assets/bfe10f91-3276-4ad2-b2b2-187871e07073)
