### ISSUE TITLE
UAT | Submission | Still the status is in Pending Payment state , even when complainant's advocate have successfully made a submission 

### ISSUE THREAD

**Issue by mustakim-egov** [pucardotorg/dristi#1227]
**Describe the bug**
Still the status is in Pending Payment state , even when complainant's advocate have successfully made a submission

**To Reproduce**
Steps to reproduce the behaviour In **QA environment**:
1. After judge schedule the evidence hearing
2. Login as complainant advocative ( credentials :- mobile number -9874689999)
3. Select the case with Case Id -F-C.1973.002-2024-000486
4. Click on submission tab
5. Click on the application -APPLICATION-NO-2024-08-07-000030
6. Click on 'Make a Payment' button
7. After getting 'You have successfully made a submission' popup , click on close button

**Expected behaviour**
Still the status is in Pending Payment state 

**Desktop (please complete the following information):**
 - OS: windows
 - Browser : chrome

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected in UAT env.
