### ISSUE TITLE
UAT | END Hearing | The judge should be able to end the hearing

### ISSUE THREAD

**Issue by mustakim-egov** [pucardotorg/dristi#1236]
**Describe the bug**
When Judge Join's the hearing not able to end the hearing.

**To Reproduce**
Steps to reproduce the behaviour:
1.Login as judge with UserName =EMP-0-000010 and password= Beehyv@123
2. Click on view Hearing Select the today's date in the calendar
3.Click on 'Join Hearing' button on any case 
4. Click on 'End Hearing' Button, again click on ' End Hearing' (red button) button
5. Click on 'Set Next Hearing Date' Button
6. Select tomorrows date 
7. Click on 'Generate Order' button

**Expected behaviour**
Next Order should generate and Hearing should end

**Expected behaviour**
'Generate Order' button is not working

**Desktop (please complete the following information):**
 - OS: windows
 - Browser : chrome

**Comment by rajeshcherukumalli** [comment]
Issue is fixed, please find the reference
https://jam.dev/c/171ebbf5-d083-457f-9aa5-0c313b29cffe
