### ISSUE TITLE
UAT: Case filing - cannot edit mobile number

### ISSUE THREAD

**Issue by atulgupta2024** [pucardotorg/dristi#1241]
When adding complainant details, after adding mobile number, need to verify it with an OTP. Once done, the mobile number field gets disabled. If I want to change the number I cannot. Till the case is in draft stage, I should be allowed to change any value. 

![ComplainantDisabled-CannotChange](https://github.com/user-attachments/assets/a0b7df4d-0b97-4a3b-827a-7bd7a5c7ee89)

**Comment by ashishbeehyv** [comment]
Once a mobile number is registered, it can not be modified from case filing flow. If user need to change the number he/she has to contact nyay mitra for editing the details

**Comment by Beehyv-Vinod** [comment]
As Mentioned by @ashishbeehyv  Users are not allowed to edit their mobile number after OTP verification is complete. Once the OTP verification is done, the verified number will be registered in the system.
