### ISSUE TITLE
UAT | Filing | Mandatory Fields Check 

### ISSUE THREAD

**Issue by AyushiSinghalLaw** [pucardotorg/dristi#1245]
**Describe the bug**
Let's allow the users to toggle between complainant details, cheque details, etc. without filling in the mandatory fields. It would be nice to let the user explore the system freely and understand the details to be filled before they start filing. They will also be able to collect all details at one place before filing. 

We could let the check of filling mandatory details be there before clicking the Submit button.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Beehyv-Vinod** [comment]
Tested in QA env, Working as Expected, User can toggle between different sections without entering the details

Ref,
https://jam.dev/c/a72f71fe-7e6d-4955-86bf-7d970c5f1a60
