### ISSUE TITLE
UAT | Reschedule all hearings not working

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#1256]
On clicking Reschedule all hearings, blank page opens

![Image](https://github.com/user-attachments/assets/5361ddad-43ec-48b9-a879-c7fdd7b28b69)
![Image](https://github.com/user-attachments/assets/e198dc40-095b-4353-9edd-65f7ae2a65b1)

**Comment by Ramu-kandimalla** [comment]
Hi @Taherabharmal  Currently Solution layer is building this functionality
