### ISSUE TITLE
[BUG]: Logged in to the citizen portal and it is showing me a spinney

### ISSUE THREAD

**Issue by subhashini-egov** [pucardotorg/dristi#1267]
**Describe the bug**
Logged into the citizen portal and I keep seeing a spinney. 

**To Reproduce**
1. Go to https://dristi-dev.pucar.org/digit-ui/citizen/home/home-pending-task
2. Log in

**Expected behavior**
Home page should be displayed

**Screenshots**
[If applicable, add screenshots to help explain your problem.
](https://www.loom.com/share/ae5e39dc40d64621a182ca857e218c94)

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [e.g. chrome]

**Additional context**

**Comment by Amityadav012** [comment]
"I've tried multiple times but was not able to reproduce this issue. It may have occurred because a deployment was happening at that time."

This is working as expected in UAT env.
