### ISSUE TITLE
UAT | Schedule hearing

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#1274]
Schedule hearing order only allows for selection of parties who have joined a case
Please delink join a case from order

Expected behaviour:
All parties can be selected
Please provide following infobox below screen:

The following parties have not joined the case on the portal yet:
1) XXX
2) YYY (advocate for ZZZ)

XXX and YYY are placeholders

**Comment by rajeshcherukumalli** [comment]
Issue is fixed, please find the reference
https://jam.dev/c/73a3ced9-7459-4909-8e2b-fa2199996d58

**Comment by Ramu-kandimalla** [comment]
This issue is fixed and working as expected in UAT
