### ISSUE TITLE
UAT | Incorrect number of hearings

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#1277]
Home page shows a certain number of hearings in a slot
one you cick on view hearings, number of hearings is different

![Image](https://github.com/user-attachments/assets/2a69e795-a09a-4d36-a430-e13e3f0bb5aa)
![Image](https://github.com/user-attachments/assets/2a746beb-8cc7-41f3-97dd-55eaab150090)

**Comment by Beehyv-Vinod** [comment]
Tested in QA working fine.

Ref, 
 --https://jam.dev/c/a0ea82f9-eb60-45d0-aefa-6c95a5b54591
