### ISSUE TITLE
UAT | Confirmation message text

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#1286]
During e-filing, if advocate puts in complainant's number and verifies identity,  the following confirmation message is received

![Image](https://github.com/user-attachments/assets/ade9d53c-0836-45af-8389-6329b666ac6b)

Update text in this scenario to say:
1) The complainant's identity was verified during their registration on the platform

**Comment by Beehyv-Vinod** [comment]
Tested in QA env, Working as Expected.

Ref,
https://jam.dev/c/dd3b581d-5575-4f9c-b9f5-868d364c6736
