### ISSUE TITLE
UAT | Confirm Court

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#1290]
Currently, on submission of e-filing, the user is asked to confirm court. 

Expected behaviour
1) The confirm court pop up only appears if there are more than 1 courts in MDMS.
In case only 1 court is available, this step is not required

![Image](https://github.com/user-attachments/assets/af5280ad-bf8c-4a0a-8d99-4c43b2bcdcac)

**Comment by rajeshcherukumalli** [comment]
Issue is fixed, please find the reference
https://jam.dev/c/8ea56fd9-d88c-4da2-8c35-bac66a4dba69

**Comment by Ramu-kandimalla** [comment]
This Issue is fixed and working as expected in UAT
