### ISSUE TITLE
UAT | Overall case workflow | Show stage and sub stage

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#1294]
In the view a case page, only stage is visible
Show stage + substage + Final/Intermediate outcome (if appliicable)

![Image](https://github.com/user-attachments/assets/65332106-245d-41b1-a022-158e43cd42b9)

Design: https://www.figma.com/design/fwFYdlymVjggLOltqnXWsY/Hand-off-(Digit)?node-id=4065-12335&t=LEbLxBNkKETYHzmQ-0

**Comment by rajeshcherukumalli** [comment]
Issue is fixed, please find the reference
![Screenshot from 2024-08-22 00-07-48](https://github.com/user-attachments/assets/99234e3e-cc23-49c9-acf5-854aec715ea0)

**Comment by devarajd94** [comment]
Verified
