### ISSUE TITLE
UAT | Case in scrutiny stage

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#1313]
Case is in scrutiny stage but no appearing in the Your cases table for advocate/complainant

![Image](https://github.com/user-attachments/assets/80e095c5-698e-4bdd-b9fb-eeb225c30acd)
![Image](https://github.com/user-attachments/assets/5dd0425d-bf2e-4c06-80b3-607b4e5b4b4b)
![Image](https://github.com/user-attachments/assets/3ef23fba-7481-4af4-a57c-efaff603dd70)

![Image](https://github.com/user-attachments/assets/99328307-0122-4ee8-a8ab-939f01663774)
![Image](https://github.com/user-attachments/assets/cb54d725-81e1-4634-b9bf-e9db34c324b1)

**Comment by Amityadav012** [comment]
"I've tried multiple times but was not able to reproduce this issue. It may have occurred because role was updated.

This is working as expected in UAT env.
