### ISSUE TITLE
UAT | View hearing from advocate login

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#1318]
Hearing is scheduled for a case from 12-1 pm for the 13th of August
However, on the home screen, it shows as 12th of August
On clicking view hearing, the calendar for 12th opens which shows no hearings

![Image](https://github.com/user-attachments/assets/838b20b4-ad7c-4501-bf8a-6e51c5f00c87)
![Image](https://github.com/user-attachments/assets/342f5a38-9a02-4a07-b3a1-b2809ee19e16)
![Image](https://github.com/user-attachments/assets/406ec3bc-7578-43a5-88b1-0d9c9932dbe2)

**Comment by Beehyv-Vinod** [comment]
Tested in QA env Working fine, Hearings for the Specific day are showing. Below is the Ref,
 
https://jam.dev/c/6e13c55d-83a4-4390-9fb0-907ac57c7731
