### ISSUE TITLE
UAT | Prehearing modal | advocate

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#1320]
Action buttons missing in Prehearing modal for advocate
Reschedule hearing functionality is from here, and hence this is needed

![Image](https://github.com/user-attachments/assets/98996dfd-9326-49e4-8f9c-bbda472be6f7)

Design:
https://www.figma.com/design/fwFYdlymVjggLOltqnXWsY/Hand-off-(Digit)?node-id=4071-38015&t=ghUMDKuebnaVwM84-0

**Comment by Beehyv-Vinod** [comment]
As discussed in the call, Once the Judge Starts the Hearing, Join Hearing Button will appears to Litigant/Advocate & both can join the case
