### ISSUE TITLE
UAT | Advocate assigned to case not seeing hearing scheduled

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#1322]
See case 0057 Rep Bose vs Rep Gandhi 2.0

    1. 9999999960 - complainant
    2. 9999999961 - respondent
    3. 9999999951 - adv sc bose

advocate cannot see the case or hearing in their home screen or cases

**Comment by Beehyv-Vinod** [comment]
This issue is because of the Role updation, for new users it is working fine. Shared the Ref in whatsapp group.
