### ISSUE TITLE
UAT | Judgement Workflow

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#1333]
Incorrect judgement workflow - Status shows an pending stamping as against published

![Image](https://github.com/user-attachments/assets/3bbc5e4a-61be-436d-bdfa-3c2adb76a927)

**Comment by Taherabharmal** [comment]
@atulgupta2024 @subhashini-egov

**Comment by atulgupta2024** [comment]
This was shared with Mani and Rajat on 5th August @manimaarans @storm20198 

https://egov-talk.slack.com/archives/C06QTSJN83V/p1722841867697609

**Comment by rajeshcherukumalli** [comment]
Issue is fixed, please find the reference
https://jam.dev/c/e336f788-3341-4da1-ac64-f654bc675ac0

**Comment by Ramu-kandimalla** [comment]
This Issue is fixed and working as expected in UAT
