### ISSUE TITLE
UAT | Judgement Order

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#1337]
In the judgement order, the following issues exist:
1) details prepopulated from case details are not displayed in order
2) based on the holding, final outcome is not updated on view a case page
3) case is not appearing in closed cases
4) judgement update not available on view a case overview screen  (https://www.figma.com/design/fwFYdlymVjggLOltqnXWsY/Hand-off-(Digit)?node-id=7707-99424&t=ghUMDKuebnaVwM84-0)

enhacement:
Put note as follows below judgement heading:
All documents marked as evidence will automatically be attached to the judgement. In case any additional evidences are to be considred, please mark them as an evidence from the documents tab in the case.

**Comment by storm20198** [comment]
@vaibhavct go through this to implement judgement order types https://github.com/pucardotorg/mdms-data/blob/develop/data/pg/case/OutcomeType.json

**Comment by vaibhavct** [comment]
@Taherabharmal 
from where I should get these fields for judgement order?
Date of Occurence
Date of Apprehension
Date of Release on Bail
Date of Commencement of Trial
Date of close of trial
Date of sentence or Order
Offence

**Comment by Taherabharmal** [comment]
See mapping in functional specs sheet

Regards,
Tahera Bharmal
Product Manager
eGovernment Foundation
+91 9637295165

**Comment by vaibhavct** [comment]
From where should I pick these values, @atulgupta2024 ?

**Comment by Taherabharmal** [comment]
See here, field mapped to fields collected/generated during case:
https://docs.google.com/spreadsheets/d/12tJW0ipniwRyJ9mUo4bEVmm98VZqyQdiZih7wWJ43wc/edit?gid=250166509#gid=250166509

**Comment by vaibhavct** [comment]
@Taherabharmal  These fields are not coming in case search API. That is why I asked @atulgupta2024  From where I should collect these dates from
c.c. @Ramu-kandimalla

**Comment by atulgupta2024** [comment]
@vaibhavct  we discussed this yesterday evening. hope this is sorted out now.

**Comment by Ramu-kandimalla** [comment]
Hi @rajeshcherukumalli  Please verify and confirm the issue in UAT environment

**Comment by Mahesh-Vishwanath1** [comment]
Hi @ashishbeehyv
I am still encountering issues with the judgment of the order:
1)In the 'Finding/Holding' field dropdown, the 'Partially Allowed' option is currently displayed in all capital letters. It should be formatted in standard case, with only the first letter capitalized and the rest in lowercase. https://jam.dev/c/08eacd8b-056e-47c9-9868-07db12a987cd
2)The 'Complainant's Residence' or 'Description of Complainant' is missing. (If the residence is coming from the back end, there’s no need for the description; otherwise, the description field should be shown as an optional input.) https://jam.dev/c/6275713b-aaa7-4dbb-bf09-0b4facf9cc8e
3) The 'Content' field is supposed to have an audio option as per the Figma design, but it is incorrectly showing up in the 'Sentence of Order' field.https://jam.dev/c/f6ae60e4-6c29-4311-8d9c-5e754821a8bf

**Comment by Mahesh-Vishwanath1** [comment]
Hi @ashishbeehyv, I verified the issues mentioned earlier in the solution dev env, and they are working as expected. However, today I encountered two new issues related to this ticket. Please check and address them.
1)In the judgement order, if we select 'Partially Convicted' and 'Partially Allowed' in the finding/holding field, the case does not appear with a closed status after the judgement.https://jam.dev/c/98d6cc38-1b6d-4c06-b8d8-6d0afa441db9
2)After the judgment, I am unable to click on 'View Judgment Order' in the case overview screen.https://jam.dev/c/453f237a-9548-4418-b7b4-5abb1f6b512d

**Comment by Mahesh-Vishwanath1** [comment]
Hi @Ramu-kandimalla, I have verified this ticket in the Dev solution, and it is working as expected. However, the newly added fixes are not yet reflected in the UAT solution environment. Once the fixes are applied in UAT, I will test the ticket, attach the test cases, and proceed accordingly.

**Comment by Mahesh-Vishwanath1** [comment]
Hi @devarajd94,
I have verified the judgment order for all the fixes in the UAT solution environment, and all updates have been applied as expected.
url: https://dristi-kerala-uat.pucar.org/digit-ui/employee/user/language-selection

Test Cases: 
 1.Verify that the Case Number field is disabled and system-filled.
2.Verify that the Name of Judge field is disabled and system-filled (Known Issue).
3.Verify that the Name of Court field is disabled and system-filled.
4.Verify that the Description of the Accused field is optional, allowing the judge to fill in data as needed.
6.Verify that the Description of the Accused Residence field is disabled and system-filled.
7.Verify that the Date of Occurrence field is disabled and system-filled.
8.Verify that the Date of Complaint field is disabled and system-filled.
9.Verify that the Date of Apprehension field is disabled and system-filled.
10.Verify that the Date of Release on Bail field is disabled and system-filled.
11.Verify that the Date of Commencement of Trial field is disabled and system-filled.
12.Verify that the Date of Close of Trial field is disabled and system-filled.
13.Verify that the Date of Sentence or Order field is disabled and system-filled.
14.Verify that the Complainant Name field is disabled and system-filled.
15.Verify that the Description of the Complainant field is optional, allowing the judge to fill in data as needed.
16.Verify that the Complainant Advocate field is disabled and system-filled.
17.Verify that the Accused Advocate field is disabled and system-filled.
18.Verify that the Offence field is disabled and system-filled.
19.Verify that under the Plea section, there are two options (Guilty and Not Guilty), and only one option can be selected at a time.
20.Verify that under the Finding/Holding section, there is a dropdown with the options: Partially Convicted, Convicted, Partially Allowed, Allowed, and Dismissed, and that the judge is able to select an option.
21.Verify that the Sentence/Order is an alphanumeric text field that allows the judge to type data.
22.Verify that the Content is an alphanumeric text field that allows the judge to either type data or use the audio option to input data.
23.Verify that clicking the "click here" link in the Witnesses section navigates the judge to the Complaint page in the View Case for that particular case.
24.Verify that clicking the "click here" link in the Marked Evidence section navigates the judge to the Documents page in the View Case for that particular case.
25.Verify that with all the different combinations of Plea and Finding/Holding, the judge should be able to click on the "Review Order" button.
26.Verify that when the judge clicks on the "Review Order" button, a popup box is displayed, showing the review order details.
27.Verify that when the judge clicks on "View Document," the document is downloaded to the system.
Verify that after clicking "Add Signature" and completing the e-sign process, the judge should be able to click on "Issue Order."
28.Verify that after clicking "Issue Order," the order should be successfully saved.
29.Verify that the case for which the judgment is given is visible in the "Closed" section under "Your Cases" after the judge goes to the home page.
30.Verify that when the judge clicks on the case for which the judgment is given, they can then click on "View Judgment Order."
31.Verify that after clicking "View Judgment Order," the judge can see the judgment order displayed.
32. Verify that after clicking the "Download Order" button, the judge can successfully download the judgment order.

Reference link: https://jam.dev/c/f8b69e58-7f8e-4c04-978d-93df5023f412
User Ids link: https://docs.google.com/spreadsheets/d/1w0RT8lHfx7T2-WaTW2DS-66THYjtyNYTw-FDoqJp5-o/edit?gid=0#gid=0

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  This issue is fixed
