### ISSUE TITLE
UAT || Filling || While filling case , Showing 1 mandatory field is missing for 'Complainant Details'. (pin code for the address automatically removed).

### ISSUE THREAD

**Issue by mustakim-egov** [pucardotorg/dristi#1351]
**Describe the bug**
While filling case , Showing 1 mandatory field is missing for 'Complainant Details'. (pin code for the address automatically removed).

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as advocate
2. Click on 'File a Case' button
3. File all details of complainant , click on 'continue'
4. File all Respondent Details , click on 'continue'
5. File all Case Specific Details , click on 'continue'
6. File all Additional Details , click on 'continue'

**Expected behaviour**
Pin code for the address should not be automatically removed

**Actual behaviour**
Pin code for the address is automatically removed

**Desktop (please complete the following information):**
 - OS: windows
 - Browser : chrome

**Comment by Beehyv-Vinod** [comment]
Tested in QA env, Working as Expected. User able to file a case without encountering any issues.

Ref,
https://jam.dev/c/ecc7412e-43c7-447d-b9cc-56662cdb31be
