### ISSUE TITLE
UAT | 225 Inquiry Affidavit | Uploading 225 Inquiry Affidavit should be optional.

### ISSUE THREAD

**Issue by mustakim-egov** [pucardotorg/dristi#1369]
**Describe the bug**
Uploading 225 Inquiry Affidavit should be optional.

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as 'advocate'
2. Click on 'File a Case' button
3. File all Complainant details
4. In respondent details fill all mandatory fields
5. Leave 225 Inquiry Affidavit as empty or do not upload any documents. 

**Expected behaviour**
225 Inquiry Affidavit  should optional.

**Actual behaviour**
225 Inquiry Affidavit  is mandatory.

**Desktop (please complete the following information):**
 - OS: windows
 - Browser : chrome

**Screenshots**
![Screenshot (218)](https://github.com/user-attachments/assets/b37909ce-7d4e-453a-bf6d-af947ba5829d)

**Comment by Beehyv-Vinod** [comment]
Tested in QA env, Working as Expected.

Ref
https://jam.dev/c/0f1d4a6b-b128-4900-aa72-7ee56f2e4138
