### ISSUE TITLE
UAT | Hearing | When judge joins the hearing he/she should able to get proper case name.

### ISSUE THREAD

**Issue by mustakim-egov** [pucardotorg/dristi#1374]
**Describe the bug**
When judge joins the hearing he/she should able to get proper case name

**To Reproduce**
**Steps to reproduce the behaviour:**
1.Login as judge
2.Click on Click on 'View Hearings' button
3.Select any hearing date
4.Click on 'Join hearing' button

**Expected behaviour**
When judge join , the hearing he/she should able to get proper case name.

**Actual behaviour**
For each case in the hearing getting same name as 'Aparna vs. Subarna'

**Desktop (please complete the following information):**
OS: windows
Browser : chrome

**Comment by mustakim-egov** [comment]
![Screenshot (227)](https://github.com/user-attachments/assets/d24f19b7-2894-4ca0-967e-b761f19c039e)

**Comment by Beehyv-Vinod** [comment]
Tested in QA env, Working as Expected. Case name is showing inside the Hearing

![Screenshot from 2024-08-27 10-51-54](https://github.com/user-attachments/assets/d6ebdf31-571e-447f-80ad-1f787f52e52d)
