### ISSUE TITLE
UAT | Advocate Home screen | Empty State

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#1379]
As per design, the following is the advocate home screen when they have not created any case/have not joined any case:
https://www.figma.com/design/fwFYdlymVjggLOltqnXWsY/Hand-off-(Digit)?node-id=1853-22634&t=F1KmykXjCE3tP9z2-0

Current developed screen:
![Image](https://github.com/user-attachments/assets/98f4255a-a29a-44ac-97ee-6306f7ef6fc6)

Steps to replicate:
1) Creeate new advocate
2) Approve request
3) Login as advocate
4) See screen

**Comment by Beehyv-Vinod** [comment]
Tested in QA env, Working as Expected.

Ref,
https://jam.dev/c/637a8c76-4b00-4e65-99de-bb4379e7c989
