### ISSUE TITLE
Tech Debt: Pending tasks is slow to load

### ISSUE THREAD

**Issue by subhashini-egov** [pucardotorg/dristi#1392]
**Describe the bug**
The pending tasks section in the UI is very slow to load. Users see a spinner for a few seconds.
**To Reproduce**
Steps to reproduce the behaviour:

1. Go to the employee portal
2. Log in as a judge and go to the home screen.
3. Pending tasks will show a spinner and take a while to load

**Expected behavior**
Pending tasks should load sub second.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
Pending tasks are populated from ElasticSearch indexes. Code that fetches from the indexes and/or UI needs to be revisited and optimized.

**Comment by atulgupta2024** [comment]
another issue logged for this #1643 . so this is duplicate. will close.
