### ISSUE TITLE
Tech Debt: Case search API does not restrict access to data

### ISSUE THREAD

**Issue by subhashini-egov** [pucardotorg/dristi#1401]
**Describe the bug**

The case search API should restrict access to data only to parties of the case - Judge/Advocate/Litigant/Bench Clerk. 200 OK to be returned for these personas. Everyone else should get a 401 Unauthorized.

**To Reproduce**
1. Log in as a Judge 
2. Click on any case from the "My Cases" view.
3. Copy the case URL
4. Paste the URL in another browser (Safari) as an advocate.
5. An advocate who has no relation to the case will be able to see the details of the case. This is a breach of privacy/security.

**Expected behavior**
An error screen should be shown in the UI.

**Comment by subhashini-egov** [comment]
@Ramu-kandimalla @suresh12 why are the showstopper labels being removed without any comments or explanation? What's the plan for fixing these? CC: @atulgupta2024

**Comment by Ramu-kandimalla** [comment]
Hi @Subhashini ***@***.***>,

I have added new label called NFR this NFR & Security are the priority tasks we are planned post judges Demo for tracking purpose

We are been discussing these action plans on the standup call regularly.

Please go through the updated Sprint planning Sprint Plan<https://github.com/orgs/pucardotorg/projects/1/views/20?filterQuery=label%3ANFR>

Regards,
Ramu Kandimalla
Project Manager
Bee<https://www.beehyv.com/>Hyv<https://www.beehyv.com/> Software Solutions<https://www.beehyv.com/>
________________________________

**Comment by atulgupta2024** [comment]
closing as as there is a ticket #1455
