### ISSUE TITLE
Functional Debt | Order and Applications PDF Sept Demo

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#1470]
PDF gen for the following orders and applications:
1) Order for Referral of Case to ADR  - how often will it happen in NIA?
2) Order for Case Withdrawal - added, tahera to check
3) Order for Settlement
4) Order for Case Transfer 
5) Order of Issue for Warrants 
6) Bail Bond Application
7) Bail Application -  In person Surety
8) Application for Withdrawal
9) Application for Transfer
10 )Application for Settlement

**Comment by anirudh-0** [comment]
@Ramu-kandimalla the remaining templates were medium severity and already tracked in here instead of #1469 , I'll be asking QA to test for only those templates mentioned previously in the ticket, and a separate effort for this ticket. 

It was not communicated that this was part of the september demo

**Comment by vaibhavct** [comment]
@anirudh-0 @Ramu-kandimalla 
Some of the orders like Rejection of Settlement, Rejection of Case Transfer, Rejection of withdrawal, were not present in the orders, earlier we were redirecting these towards Generic Reject Voluntary Submission Order.
But now I've added one more field "Application Status" (Approved / Rejected) to Case Transfer, Withdrawal, Settlement, Extension of submission deadline which will tell us whether the order is for rejection or acceptance of that submission.
Kindly take a note of this @rajeshcherukumalli

**Comment by vaibhavct** [comment]
Below orders are not mentioned in the ticket but we're building their respective templates and handlers.
1. Order for SECTION_202_CRPC
2. Acceptance of Extension of submission deadline
3. Rejection of Extension of submission deadline

For Order of Judgement, we don't have template yet, so showing generic order template for it as of now.
c.c. @anirudh-0  @Ramu-kandimalla  @rajeshcherukumalli

**Comment by bhuvanyuguru** [comment]
Hi @Ramu-kandimalla, 

Everything is working as Expected in UAT.

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  This issue is fixedin UAT

**Comment by devarajd94** [comment]
Verified
