### ISSUE TITLE
Functional Debt | Offline payments

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#1471]
Offline payment collection for applications and summons by Nyay Mitra

**Comment by Ramu-kandimalla** [comment]
- [ ] Creating elastic index configuration  @manimaarans 
- [ ] Creating inbox search configuration @storm20198 
- [ ] Adding Kafka topic update the status @prasanna2400 
- [ ] Write a consumer logic in analytics service @prasanna2400

**Comment by Ramu-kandimalla** [comment]
Hi @TusharKatiyar2002  Please perform the devtesting in Dev environment

**Comment by TusharKatiyar2002** [comment]
Hi @Beehyv-Vinod, plz do the testing in kerala-dev

**Comment by Beehyv-Vinod** [comment]
Hi @Ramu-kandimalla @rajeshcherukumalli  Tested in Dev env below cases are working Fine,

1. Verify that Nyayamitra is able to do the Offline Payment for Case (  Case Filing Fee  )
2. Verify that Pending task which is created for  **Case Filing Fee** is clearing for the case 
3. Verify that Nyayamitra is able to do the Offline Payment for **Make a Submission** ( Application Filing Fee )
4. Verify that Pending task which is created for **Application Filing Fee** is clearing for the case
5. Verify that Nyayamitra is able to do the Offline Payment for Summons ( **Summons Post Court Fee** , **Summons Post Process Fee**)
6. Verify that Pending task which is created for **Summons Post Court Fee** is clearing for the case
7. Pending task which is created for **Summons Post Process Fee** is clearing for the case
8. Verify that Fuzzy search is working for Nyayamitra
9. Verify that filters working for Nyayamitra.

**Comment by Ramu-kandimalla** [comment]
Hi @Beehyv-Vinod  Please verify the same functionality in UAT env

**Comment by Beehyv-Vinod** [comment]
Summons Payment is not working in UAT, Already Shared the details with the team

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  This issue is fixed

**Comment by devarajd94** [comment]
Verified
