### ISSUE TITLE
ESign | Enabling Multiparty ESign

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1502]
Details:
Multi party esign needs to be enabled for Case PDF, Witness Deposition.

Working:
For Case PDF (once templatised and created in the system without getting uploaded):
1. The lawyer/litigant has to choose physical sign or esign as a mode of signing. Once selected they will be promted with a message. "Kindly note that all the litigants and advocates signing this document will have to sign using the chosen method"
2. There are 2 options: Download and sign, E Sign.
3. For Download and Sign, the document is downloaded. Once downloaded, there will be an upload option enabled.
4. For E SIgn it proceeds as per current flow
5. If E Sign is chosen then the second party (lawyer of litigant) will have to sign on it again using CDAC service. The position of the sign on the document should not overlap the first signature.

For Witness Deposition:
1. Only download and Upload is permitted. (No ESign).
2. The document is downloaded. Signed on court by witness and judge. There should be an upload button to re upload. It should show signed.

**Comment by prasanna2400** [comment]
**- If E Sign is chosen then the second party (lawyer of litigant) will have to sign on it again using CDAC service. The position of the sign on the document should not overlap the first signature.**

1. Research will require to avoid overlap on already signed doc

**-  The lawyer/litigant has to choose physical sign or esign as a mode of signing. Once selected they will be promted with a message. "Kindly note that all the litigants and advocates signing this document will have to sign using the chosen method"**

1.  blocking was suggested by @suresh U  (advocate will sign first then litigant ), will require tech details how to implement this   @manimaarans 
2. @anirudh-0  will require input on how ui can handle blocking for sign method on the basis of first signature

**Comment by Ramu-kandimalla** [comment]
Since the scope got changed we ahave created new ticket please refer to #1964
