### ISSUE TITLE
UAT | Change the validation on BAR Council Number

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1503]
Module: User Registration of Lawyer
Change the validation on BAR Council Number - K/003560/2022 for Kerala

**Comment by kashish384** [comment]
Fixed.
BAR Council Number__"K/003560/2024"
For user registration reference link: https://jam.dev/c/410aa9c7-194d-4849-8475-fd09be132368

For E-filing  reference link: https://jam.dev/c/9b662566-24bf-4162-976e-69e6455c9121

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  This issue fixed and verified from my end

**Comment by kashish384** [comment]
Hi @devarajd94 
These are the test cases for "Delay Condonation Change" page. verified in _QA Solution env._

- url: https://dristi-kerala-qa.pucar.org/digit-ui/citizen/dristi/home/registration/additional-details
- reference link: https://jam.dev/c/6f355f87-aba9-4121-87be-720ee2d5b14f

 Test cases:
1.verify that "BAR registration number"  should be in this format (K/000000/0000).
2.verify that user should not able to enter invalid format.
3.verify that for Registered user BAR registration number should be present while E-filing.
4.verify that after invalid input_'7658888888888',user should able to see error message.
5.verify that [Only capital letters, numbers and '/' ] allowed.

**Comment by devarajd94** [comment]
Verified

**Comment by kashish384** [comment]
Hi @Ramu-kandimalla ,please verify this:
 -  Regarding_User Registration of Lawyer
 -  Env.UAT
 -  BAR Council Number__"K/007800/2024"
 -  url: https://dristi-kerala-uat.pucar.org/digit-ui/citizen/dristi/home/registration/additional-details
 -  reference link: https://jam.dev/c/f5b145b6-6486-40de-b505-3740b76aed7f

**Comment by Ramu-kandimalla** [comment]
HI @devarajd94  This issue is fixed please verify and confirm
