### ISSUE TITLE
UAT| E-Filing | Representative details of Entity is optional

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1505]
- Module: Efiling
- Screen: Respondent Details -> Entity
- Make the Representative Details optional (First Name, Middle Name, Last Name)

**Comment by Ramu-kandimalla** [comment]
**Development Tasks**

- [ ] We have made middle name & last name was optional 
- [ ] In the registration and E-filling modules

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  We have made the middle name and last name as optional
