### ISSUE TITLE
UAT | EFiling | Delay Condonation Change

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1513]
Module: EFiling

Details: There is a text box for reason entry and there is a document upload. Either of them need to be mandated.

Remove the Note section

![Image](https://github.com/user-attachments/assets/2a4ba822-5ae9-4890-b845-a0b3c29e3ddd)

**Comment by kashish384** [comment]
It's fine now.

![image](https://github.com/user-attachments/assets/586ca602-f869-45b8-8585-5d2ee010f7e5)

**Comment by kashish384** [comment]
Hi @devarajd94 
These are the test cases for "Delay Condonation Change" page. verified in _QA Solution env._

-  Url: [https://dristi-kerala-qa.pucar.org/digit-ui/citizen/dristi/home/file-case/case?caseId=8a4d38a4-a0f0-4484-955a-fb80d5c0cc7d&selected=delayApplications]

- Reference link: https://jam.dev/c/06173c40-b67d-4515-85e5-36e8dd216a9b

Test cases:
1. verify that "Reason for delay" is mandatory field.
2.  verify that "Delay Condonation Application'' is a optional field.
3. verify that "Note section" will not present.

**Comment by devarajd94** [comment]
@kashish384 @shambhavigoel1002 please note either the user has to enter the reason in the box or has to upload the Delay Application. Both need not be mandated. 

Currently the upload of the Delay application of the file has been made optional which is not the requirement

**Comment by shambhavigoel1002** [comment]
Hi @devarajd94 Regarding the above it's a new type of validation .And little complex  , It will require new development. Do you want an estimation for that.
cc: @Ramu-kandimalla

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  Please confirm he requirements post that we will start working on this ticket

**Comment by anirudh-0** [comment]
We've had offline confirmation on the implementation need

**Comment by Ramu-kandimalla** [comment]
AS requested by Suresh we are moving this to backlog

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  @Taherabharmal  Can you please share the new screen design

**Comment by devarajd94** [comment]
@Ramu-kandimalla tahera and I will get back to you by EOD today
