### ISSUE TITLE
UAT | EFiling | Prayer and Sworn Statement

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1514]
Module: EFiling

Details: Rename Prayer as Complaint in the following marked places

Rename Memorandum of Complaint to Complaint

![Image](https://github.com/user-attachments/assets/f1bc7580-b0d3-491c-a542-d55005206387)

Change 'Type Details' -> 'You can either type details in the box below or upload a file'

![Image](https://github.com/user-attachments/assets/982f23b4-686f-41c7-b8c1-1a65cfe70cf7)

Change 'written affidavit' to 'affidavit'. Sworn Statement should be made mandatory submission

![Image](https://github.com/user-attachments/assets/0ff3890d-002f-45b1-aa3e-0a734f6df75b)

**Comment by rsi-MaheshVishwanath** [comment]
The "Solution QA" has been tested with both the advocate and the litigant, and it has been updated as expected. Thanks!
https://jam.dev/c/5aeb10b3-49ad-4188-b128-757fc416889b

**Comment by rsi-MaheshVishwanath** [comment]
Retested all the Changes in "Solution QA" all are updated as expected. Thanks
Litigant (7877656545):https://jam.dev/c/f7c22cec-98b1-438e-93cc-7bbbc0cc2818
Advocate (7879877877):https://jam.dev/c/e5b893c6-ab6c-4def-b238-cae8fbdb397d

**Comment by rsi-MaheshVishwanath** [comment]
Hi @devarajd94 @Taherabharmal,

Module: EFiling
Test cases for updated names and mandatory fields for "complaint and sworn statement in "solution QA"
Citizen URL: https://dristi-kerala-qa.pucar.org/digit-ui/citizen/select-language

1) Verify the renaming of "Prayer" as "Complaint."
 2) Verify the renaming of "Memorandum of Complaint" to "Complaint."
3) Verify the rename "Type Details" to "You can either type details in the box below or upload a file."
4) Verify the renaming of "written affidavit" to "affidavit" in the sworn statement.
4) Verify the sworn statement should be made mandatory submission.

reference link:
Litigant (7877656545):https://jam.dev/c/f7c22cec-98b1-438e-93cc-7bbbc0cc2818
Advocate (7879877877):https://jam.dev/c/e5b893c6-ab6c-4def-b238-cae8fbdb397d

**Comment by devarajd94** [comment]
Verified

**Comment by devarajd94** [comment]
@Ramu-kandimalla @manimaarans 

'Change 'Type Details' -> 'You can either type details in the box below or upload a file'

This issue is still there in UAT

**Comment by kashish384** [comment]
Hi @Ramu-kandimalla ,please verify this:
  -  Regarding_Prayer and Sworn Statement
  -  Env.solution_dev
  -  url: https://dristi-kerala-uat.pucar.org/digit-ui/citizen/dristi/home/file-case/case?caseId=b2756951-f537-4ba7-976e- 
           11df1e8a9718&selected=prayerSwornStatement
  -  reference link: https://jam.dev/c/294384fc-a0b9-451f-b9ff-4fa31ae7a538
