### ISSUE TITLE
[BUG]: Sql Injection

### ISSUE THREAD

**Issue by talele08** [pucardotorg/dristi#1519]
**Describe the bug**
Able to delete tables from database using APIs

**To Reproduce**
1. Hit the following cURL:
curl --location 'http://localhost:9090/case/v1/_exists' \
--header 'Content-Type: application/json' \
--data '{
  "RequestInfo": {
    "apiId": "string",
    "ver": "string",
    "ts": 0,
    "action": "string",
    "did": "string",
    "key": "string",
    "msgId": "string",
    "requesterId": "string",
    "authToken": "string"
  },
  "criteria": [
    {
      "caseId": "'\''; DROP TABLE dristi_cases; --"
    }
  ],
  "pagination": {
    "limit": 10,
    "offSet": 0,
    "sortBy": "DROP TABLE drishti_cases; --",
    "order": {}
  }
}'

**Expected behavior**
Should have converted values into string and not executed the query.  Please ensure all sql statements are being prepared using PreparedStatement in Java code. 

**Screenshots**

**Comment by eGovMan** [comment]
@atulgupta2024 @subhashini-egov - Please mark this as a showstopper. Kindly ensure all code is reviewed for similar mistake. PreparedStatement should be used while executing SQL queries.

**Comment by atulgupta2024** [comment]
@eGovMan @talele08 in the code that we have reviewed, in all places, I had seen use of PreparedStatements. Looks like this is a one of case. but will anyway revalidate. 

@manimaarans please check.

**Comment by talele08** [comment]
We have only checked in case service, we found it in 3 functions checkCaseExistQuery, addOrderByQuery and addRegistrationDateCriteria. Other services needs to be checked as well.

**Comment by eGovMan** [comment]
@atulgupta2024 please run OWASP ZAP - it should catch these errors. You can import the Open API specs directly into OWASP ZAP. ZAP will then automatically generate and test requests based on the definitions.

**Comment by atulgupta2024** [comment]
@eGovMan sure. is it something we can attach in github as part of PR progress? @subhashini-egov  we had this configured or you had run it locally?

**Comment by Beehyv-Vinod** [comment]
Hi @Ramu-kandimalla tested this issue in UAT env, working fine.

**Comment by subhashini-egov** [comment]
@Beehyv-Vinod did you actually use the same payload that was posted in the original ticket and try this?

**Comment by Beehyv-Vinod** [comment]
Yes @subhashini-egov
