### ISSUE TITLE
[BUG]: globalConfig.js is referring to eGov internal environment S3 bucket

### ISSUE THREAD

**Issue by subhashini-egov** [pucardotorg/dristi#1529]
**Describe the bug**
https://dristi-qa.pucar.org/digit-ui/citizen/dristi/home/login
In the QA environment, globalConfigs.js is referring to unified-dev assets.
**To Reproduce**
1. Go to ['...'](https://dristi-qa.pucar.org/digit-ui/citizen/dristi/home/login)
2. Click on developer console
3. Open assets that've been loaded for the page and open globalConfigs.js.
4. globalConfigs is referring to unified-dev.digit.org (see screenshot). egov-dev-assets is being referred to (second screenshot)
5. PUCAR image is shown.
6. http://pucarfilestore.blob.core.windows.net/ -- this needed?

**Expected behavior**
No dependency on unified-dev or any other eGov assets. Separate S3 buckets to be created for DRISTI.

**Screenshots**
![image](https://github.com/user-attachments/assets/ca520f34-7f4f-46d7-9163-6ff43b9fd2f2)

![image](https://github.com/user-attachments/assets/a9671b80-be31-4ea6-b799-abdbdfefd055)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by Rkum113** [comment]
![globalconfigs](https://github.com/user-attachments/assets/585e7da2-6ee1-4a08-840f-dc5f6f3cf49a)
![pucar-assets](https://github.com/user-attachments/assets/4ac11dd6-3e86-4f49-8904-1ccff8490df6)
globalConfigs has been updated to refers pucar-assets and pucarfilestore.

- pucarfilestore.blob.core.windows.net is blob store where all assets is kept on azure

**Comment by Ramu-kandimalla** [comment]
Hi @subhashini-egov  We have taken the necessary actions on this global config can you please confirm to close the ticket
