### ISSUE TITLE
[BUG]: "File a new case" section - text does not wrap properly

### ISSUE THREAD

**Issue by subhashini-egov** [pucardotorg/dristi#1530]
**Describe the bug**
Text wrapping is awkward in the "File a new case" section.

**To Reproduce**
1. Go to litigant portal
2. Login and view home page
3. "File case" and "Join Case" buttons are seen along with a descriptive para.
4. The "file a new case" section does not wrap properly.

**Expected behavior**
The text should be aligned properly in a visually pleasing manner.

**Screenshots**
![image](https://github.com/user-attachments/assets/0b6e4f3e-10b9-4797-a78d-91085f9d37b7)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by subhashini-egov** [comment]
This is a minor UX issue but will have great impact for end users. So would recommend fixing. @Taherabharmal @anirudh-0 you guys make the final call and deprioritize it to "Critical" or "Medium" if required.

**Comment by rkanala517** [comment]
The text "File a New Case" wrap has been fixed ,please check the video for reference https://jam.dev/c/5f647cc0-75cc-421c-af8d-8051b6e88c7d

**Comment by kashish384** [comment]
Hi @subhashini-egov

- regarding__For "file a new case" text__its looks fine.please verify.
- Env._solution_dev_
- Url: https://dristi-kerala-dev.pucar.org/digit-ui/citizen/home/home-pending-task
- reference link: 1.https://jam.dev/c/0ba869d5-8db2-4cea-b6da-b981d01b07cb
                                 OS: Ubuntu 22.04.4 LTS
                                 Browser Chromium[128.0.6613.84]
                          2.https://jam.dev/c/75069377-bb5c-4cdb-9831-7afc3a7cac79 
                                 OS: Ubuntu 22.04.4 LTS
                                 Browser Chrome[128.0.6613.119]
                          3.https://jam.dev/c/cce07a5a-f3d3-489d-afb0-78e20563cd3f
                                 OS: Ubuntu 22.04.4 LTS
                                 Browser Firefox[130.0]     
Test cases:
1.verify that login with advocate clerk user,user able to see "File a new case" text aligned properly.
    https://jam.dev/c/2c07e907-195e-4c8f-8e11-426047246f10
2.verify that login with advocate user,user able to see "File a new case" text aligned properly.
    https://jam.dev/c/d88dc8fe-809b-4be8-bcdb-e421c7c283dc
3.verify that login with  Litigant user,user able to see "File a new case" text aligned properly.
    https://jam.dev/c/196f87d1-b33a-4def-981c-dc2e43279745

**Comment by Ramu-kandimalla** [comment]
**Development Tasks**

- [ ] CSS & Localization fixes for text wrap

**Comment by Ramu-kandimalla** [comment]
Hi @Taherabharmal  @subhashini-egov  this issue is fixed please verify and confirm from your end

**Comment by kashish384** [comment]
Hi @Ramu-kandimalla, Kindly verify this:
-  Regarding_ "file a new case" text
- Env.UAT
- url: https://dristi-kerala-uat.pucar.org/digit-ui/citizen/home/home-pending-task
- reference link: https://jam.dev/c/7191d126-218d-48a3-b2d3-d5e6bcc60296
