### ISSUE TITLE
[BUG]: Reliance on external libraries from a SDC environment can pose challenges

### ISSUE THREAD

**Issue by subhashini-egov** [pucardotorg/dristi#1532]
**Describe the bug**
Relying on external libraries hosted on platforms like [unpkg.com](http://unpkg.com/) in a secure, private data center environment can introduce several risks and challenges. 

**To Reproduce**
1. Go to litigant home screen
2. Click on developer tools
3. Open the "Sources" tab
4. See left hand side of the toolbox.

**Expected behavior**
Include the necessary libraries in your build process, so they are bundled and minified with the UI code.

**Screenshots**
![image](https://github.com/user-attachments/assets/1c72744a-8c2f-4c4a-9f5c-e13db77b3e89)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by subhashini-egov** [comment]
@anirudh-0 please comment on this.

**Comment by Ramu-kandimalla** [comment]
**Development Tasks**

- [ ] Adding the dependency version in in the micro UI internals & Web 
- [ ] in the APP.JS import these file for  web pack compile

**Comment by Ramu-kandimalla** [comment]
Hi @subhashini-egov  this issue is fixed can you verify and confirm from your end
