### ISSUE TITLE
UAT | EFiling | Document name to be corrected

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1562]
Name of uploaded docs mentioned as Attached Documents.

They should be updated as Complaint (Currently Memorandum of Complaint) and Prayer for Relief

Instead of Not Available -> Document Uploaded

![Image](https://github.com/user-attachments/assets/d6849bd4-4adb-4773-b853-4e608ef5b683)

**Comment by TusharKatiyar2002** [comment]
https://jam.dev/c/6f3e99eb-ec6c-4e81-a8cc-6b456c8a7d7e

This has been fixed in dpg dev and qa env. Plz refer to the above link. Will update in solution after drop from dpg

**Comment by kashish384** [comment]
https://jam.dev/c/cc06b9aa-3a89-4994-b8e5-3186e497d255
This is working in Dpg dev but Still bug in solution dev env.

**Comment by Ramu-kandimalla** [comment]
Hi @TusharKatiyar2002  Can you please look into It

**Comment by TusharKatiyar2002** [comment]
Hi @kashish384 plz check in solution dev. Already fixed it

**Comment by kashish384** [comment]
- Regarding_Document name
- Env.solution_dev
- url: https://dristi-kerala-dev.pucar.org/digit-ui/citizen/dristi/home/file-case/case?caseId=b4cb5a9f-faff-4e8e-8771-86c4e3453f1f&selected=reviewCaseFile
-  reference link: https://jam.dev/c/f91aff7a-bc4b-415d-8e69-c14425779179
- Test cases:
1.verify that user able to see for 'Complaint', status of document should be Document Attached.
2..verify that user able to see for 'Complaint for relief', status of document should be Document Attached.
3.verify that user able to see for 'Sworn Statement', status of document should be Document Attached.
4.verify that user able to see for 'Additional Details' textbar,text should displayed.
5.verify that user able to see for 'Mention the additional acts or sections you want to charge the respondent with, if any' textbar, 
   text should displayed.
6.verify that for 'Documents' fields, user able to see name fields for 'uploaded docs'.

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  Please verify and confirm

**Comment by kashish384** [comment]
Hi @Ramu-kandimalla, kindly verify this: 
-  Regarding_ Document name to be corrected
-  Env.UAT
-  url: https://dristi-kerala-uat.pucar.org/digit-ui/citizen/dristi/home/view-case?caseId=2b3e4e52-069f-4220-b1a2-c6dd81bb9b78&filingNumber=F-C.1973.002-2024-000114&tab=Complaint
-  reference link: https://jam.dev/c/81b0b1c1-33cb-44e8-a45d-a1fc12c658bf

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  this issue is fixed please check and confirm
