### ISSUE TITLE
UAT Bug | E Filing |Download action on checklist does not work

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1563]
Download action on checklist does not work. When clicked on download button the following.

The PDF document can be uploaded for download.

Also update the checklist to the following:

01. Proof of Identity 
PAN Card, Aadhar card, Passport, Driving license, Voter ID, Ration card or Bank passbook
_Upload .pdf or .jpg. Maximum upload size of 50MB_
 
02. Bounced Cheque
A copy of the bounced cheque on the basis which this case is being filed
_Upload .pdf or .jpg. Maximum upload size of 50MB_
 
03. Cheque Return Memo
The document received from the bank that has the information that the cheque has bounced
_Upload .pdf or .jpg. Maximum upload size of 50MB_
 
04. Legal Demand Notice
Any intimation you provided to the respondent to informing them that their cheque had bounced and they still owed you the cheque amount
_Upload .pdf or .jpg. Maximum upload size of 50MB_
 
05. Postal acknowledgement (Issue of legal demand notice)
The acknowledgement provided by the postal department when sending the letter/RPAD/anything else containing legal demand notice (see number 4 in the list) to the accused.
_Upload .pdf or .jpg. Maximum upload size of 50MB_
 
06. Postal acknowledgement (Delivery of legal demand notice)
The acknowledgement provided by the postal department when the letter/RPAD/anything else containing legal demand notice (see number 4 in the list) is received by the accused
_Upload .pdf or .jpg. Maximum upload size of 50MB_
 
07. Any other document you deem necessary
Please include any additional documents you believe will strengthen your case and that will be crucial in substantiating your claims when filing the complaint
_Upload .pdf or .jpg. Maximum upload size of 50MB_

[Checklist for EFiling_Revised.pdf](https://github.com/user-attachments/files/16843684/Checklist.for.EFiling_Revised.pdf)

**Comment by kashish384** [comment]
Hi @devarajd94 
regarding_Download link.

- url: https://dristi-kerala-dev.pucar.org/digit-ui/citizen/dristi/home/file-case
- reference link: https://jam.dev/c/37d2da8f-b7ab-4d4c-8e75-8a10c4537de5 
- Test case:
1.Verify with Advocate clerk_creds[99988-89999]
    https://jam.dev/c/60ff50d9-2321-49fd-8637-ee63f4c89755
2..Verify with Advocate _creds[99110-00000]
    https://jam.dev/c/2b0c4b14-7ae0-4e83-b268-dc81fadce1d9
3.Verify with Litigant _creds[99998-88000]
    https://jam.dev/c/bd6a5ccf-1e99-4658-91ba-9eeb114b4b9f

**Comment by kashish384** [comment]
Hi @Ramu-kandimalla , kindly verify this:
  -  Regarding_Download link.
  -  Env.UAT
  -  url: https://dristi-kerala-uat.pucar.org/digit-ui/citizen/dristi/home/file-case
  -  reference link: https://jam.dev/c/58aa6662-120c-4a6f-b19a-dc514ce29621

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  This issue is fixed, please check and confirm
