### ISSUE TITLE
UAT | E Filing | Authorisation document cannot be mandatory in Entity

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1564]
The authorisation document connecting representative (Upload document establishing the authorized representative of the company (for example POA)). This document is optional

**Comment by rkanala517** [comment]
Uploading this document is optional now, please check video https://jam.dev/c/b6393a20-e4ee-432d-adb2-9f84bbdc9e82

otherwise, it will throw this field is required error.

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  Please verify and confirm from your end

**Comment by kashish384** [comment]
Hi @Ramu-kandimalla, kindly verify this:
-  Regarding_Authorisation document is optional.
-  Env.UAT
-  url: https://dristi-kerala-uat.pucar.org/digit-ui/citizen/dristi/home/file-case/case?caseId=edc5f059-71e1-454d-9c96-f14c41189c59
-  reference link: https://jam.dev/c/edef4227-94f9-4733-972c-3d4380b49aed

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  This issue is fixed please verify and confirm
