### ISSUE TITLE
Bug | Case PDF Download button not working

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1566]
Case PDF download button not working

https://github.com/user-attachments/assets/36500504-4489-4c30-a982-f8cd19139fef

**Comment by shambhavigoel1002** [comment]
Hi @devarajd94 These changes have been on the dev Environment. The Qa environment where testing is being it's quite an old one. It will be reflect once qa is updated
Thanks.
cc @Ramu-kandimalla

**Comment by kashish384** [comment]
Hi @devarajd94 

- regarding_Download case File.
-  url: https://dristi-kerala-dev.pucar.org/digit-ui/citizen/dristi/home/view-case?caseId=156dcf72-fa30-477e-b8b9-
          aeefd65b4485&filingNumber=F-C.1973.002-2024-001283&tab=Complaint
-  reference link: https://jam.dev/c/ed30fda6-33c1-494d-99df-58d5a08f3146
- Test cases:
 1.verify with litigant user_Creds[99888-89999]
   https://jam.dev/c/246d5a14-5799-4449-a11b-3c74b927b940
 2.verify with Advocate user_Creds[99888-99999]
   https://jam.dev/c/3c8ceb72-ff55-4102-bdef-27afd7885b36 
 3.verify with Advocate Clerk user_Creds[76767-63736]
   https://jam.dev/c/a9edab92-3916-477f-bb96-9f969d1a73a8

**Comment by kashish384** [comment]
Hi @Ramu-kandimalla ,please verify this:
  -  Regarding_Download Case File
  -  Env.UAT
  -  url: https://dristi-kerala-uat.pucar.org/digit-ui/citizen/dristi/home/view-case?caseId=2b3e4e52-069f-4220-b1a2-c6dd81bb9b78&filingNumber=F-C.1973.002-2024-000114&tab=Complaint
  - reference link: https://jam.dev/c/17d47070-17c7-4a61-82de-b71ccbc37d0a

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94 this issue is fixed and please verify and confirm
