### ISSUE TITLE
UAT: Court assignment for Case

### ISSUE THREAD

**Issue by atulgupta2024** [pucardotorg/dristi#1572]
In case e-filing, the last step is to select State, District and Court, for where to file the case.

![image](https://github.com/user-attachments/assets/3b8828c9-2297-4e9b-8de6-0bea70100540)

1. Change the third drop to show the value as "ON Courts"
2. in the case, set courtID = KLKM52. Hard code for now. Later once we add more master data, this will get assigned by pulling right value from HRMS and MDMS

@Taherabharmal @anirudh-0 @manimaarans  please note

**Comment by atulgupta2024** [comment]
These values should ideally come from Master data

**Comment by shambhavigoel1002** [comment]
HI @Taherabharmal  About the above issue can you please mention what exactly should be name of the court . Because that same will be used in orders pdf as well.

**Comment by Ramu-kandimalla** [comment]
Hi @atulgupta2024  @Taherabharmal  Can you check the above question

**Comment by atulgupta2024** [comment]
I had already said it should be "ON Courts". 

@Taherabharmal please confirm

**Comment by Ramu-kandimalla** [comment]
Currently we are having one court we are not showing this model anymore in UI

**Comment by atulgupta2024** [comment]
@Ramu-kandimalla  ok. that's fine.
