### ISSUE TITLE
Dependabot Alert: Sandbox Bypass Leading to Arbitrary Code Execution in constantinople

### ISSUE THREAD

**Issue by subhashini-egov** [pucardotorg/dristi#1581]
**Describe the bug**
Linked to [dependabot alert](https://github.com/pucardotorg/dristi/security/dependabot/48) here. Flagging this for manual fixing.

**Comment by TusharKatiyar2002** [comment]
Removed the jade package

**Comment by Beehyv-Vinod** [comment]
Checked with @TusharKatiyar2002 , the file changes were done. Did a quick testing of flow to make sure any dependency change, didn't affect anything. It's working fine

**Comment by Ramu-kandimalla** [comment]
Hi @subhashini-egov  This alert resolved and taken care
