### ISSUE TITLE
Dependabot: Incorrect Handling of Non-Boolean Comparisons During Minification in uglify-js

### ISSUE THREAD

**Issue by subhashini-egov** [pucardotorg/dristi#1582]
Dependabot [alert](https://github.com/pucardotorg/dristi/security/dependabot/46) to be fixed. Flagging this for manual fix.

**Comment by TusharKatiyar2002** [comment]
Hi @subhashini-egov, this is coming from jade package which we are using for view ( jade is depricated). Shall we remove views from utilitis/pdf as it is not used?

**Comment by subhashini-egov** [comment]
Yes.

**Comment by TusharKatiyar2002** [comment]
Removed the jade package

**Comment by Beehyv-Vinod** [comment]
Checked with @TusharKatiyar2002 , the file changes were done. Did a quick testing of flow to make sure any dependency change, didn't affected anything. It's working fine

**Comment by Ramu-kandimalla** [comment]
Hi @subhashini-egov  This alert resolved and taken care
