### ISSUE TITLE
Dependabot: SheetJS Regular Expression Denial of Service (ReDoS)

### ISSUE THREAD

**Issue by subhashini-egov** [pucardotorg/dristi#1584]
Dependabot [alert here](https://github.com/pucardotorg/dristi/security/dependabot/53).

**Comment by TusharKatiyar2002** [comment]
removed xlsx package

**Comment by Beehyv-Vinod** [comment]
Checked with @TusharKatiyar2002  ,xlsx package is removed. Did a quick testing of flow to make sure any dependency change, didn't affect anything. It's working fine

**Comment by Ramu-kandimalla** [comment]
Hi @subhashini-egov  This alert resolved and taken care
