### ISSUE TITLE
Dependabot: Prototype Pollution in sheetJS

### ISSUE THREAD

**Issue by subhashini-egov** [pucardotorg/dristi#1585]
Dependabot [alert here](https://github.com/pucardotorg/dristi/security/dependabot/50). If we are not using XSLX, this can be removed from the package.

**Comment by TusharKatiyar2002** [comment]
Removed xlsx package

**Comment by Beehyv-Vinod** [comment]
Checked with @TusharKatiyar2002  , the xlsx package is removed. Did a quick testing of flow to make sure any dependency change, didn't affect anything. It's working fine
