### ISSUE TITLE
Dependabot: tschaub gh-pages vulnerable to prototype pollution

### ISSUE THREAD

**Issue by subhashini-egov** [pucardotorg/dristi#1588]
https://github.com/pucardotorg/dristi/security/dependabot/34
https://github.com/pucardotorg/dristi/security/dependabot/29
https://github.com/pucardotorg/dristi/security/dependabot/26
https://github.com/pucardotorg/dristi/security/dependabot/21

**Comment by Beehyv-Vinod** [comment]
Checked with @TusharKatiyar2002 , the file changes were done. Did a quick testing of flow to make sure any dependency change, didn't affect anything. It's working fine

**Comment by Ramu-kandimalla** [comment]
Hi @subhashini-egov  This alert resolved and taken care
