### ISSUE TITLE
UI: Fix secret scanning alerts

### ISSUE THREAD

**Issue by subhashini-egov** [pucardotorg/dristi#1606]
Fix all secret scanning alerts under the GitHub Security tab. Most of it is in the globalConfigs.js.

**Comment by TusharKatiyar2002** [comment]
Deleted the globalConfigs file in pucar-ui

**Comment by Beehyv-Vinod** [comment]
As discussed with the @TusharKatiyar2002 , the issues is completed and the file changes were done. Did a quick testing of flow to make sure any dependency change didn't affect anything. It's working fine

**Comment by Ramu-kandimalla** [comment]
Hi @subhashini-egov  This alert resolved and taken care
