### ISSUE TITLE
Enhancement - MDMS Configuration (v2 and court specific master data)

### ISSUE THREAD

**Issue by krishnaprasadsannidhi** [pucardotorg/dristi#161]
Adding provided MDMS configuration:
Roles
Actions
Role-Action Mappings
Feedback updates
Cleaning MDMS data
Updates regarding for MDMS V2 enhancements
Adding new roles, actions and mappings as we add new modules

**Comment by subhashini-egov** [comment]
@krishnaprasadsannidhi what's this task? Is this moving from MDMS v1 to v2?
