### ISSUE TITLE
Bug | The Dates for Opt out should start post the dates as entered in application for reschedule

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1635]
During application filing for reschedule the litigant is asked the date post which they are available.

During Opt out the list of dates suggested should be post that date.

**Comment by Ramu-kandimalla** [comment]
Hi @prasanna2400  @shambhavigoel1002  Please add the development tasks and estimated effort details to resolve this ticket

**Comment by Ramu-kandimalla** [comment]
Hi @rajeshcherukumalli  Please test in Dev environment

**Comment by rajeshcherukumalli** [comment]
Hi @Ramu-kandimalla , this issue is fixed in UAT environement, please find the reference
https://jam.dev/c/f7fad115-f53d-4975-b681-aef73dae9c18

**Comment by Ramu-kandimalla** [comment]
Hi Team this issue is fixed
