### ISSUE TITLE
Bug | Court Staff unable to see any issued summon

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1637]
https://github.com/user-attachments/assets/26da9147-65c6-43f9-8056-55f267b763c9

**Comment by Ramu-kandimalla** [comment]
Hi @shambhavigoel1002  Please add the development tasks and estimated effort details to resolve this ticket

**Comment by shambhavigoel1002** [comment]
Hi @Ramu-kandimalla  This is fixed.

**Comment by Ramu-kandimalla** [comment]
Hi @rajeshcherukumalli  Please verify and confirm in UAT environment

**Comment by rajeshcherukumalli** [comment]
Hi @devarajd94 , issue is fixed in UAT environment , please find the reference
 https://jam.dev/c/f848798b-b227-47b6-a848-e87dc3270b88
