### ISSUE TITLE
Bug | Order PDF

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1638]
Order PDF generation failing

![Image](https://github.com/user-attachments/assets/473c6c39-4015-4259-a64c-292ead9f9f36)

**Comment by Ramu-kandimalla** [comment]
We have a ticket for this issue please refer ticket number #1469

**Comment by Ramu-kandimalla** [comment]
Hi @tusharphalke19995  Please make sure the Order and application templates are working in UAT

**Comment by TusharKatiyar2002** [comment]
Hi @rajeshcherukumalli, can you plz check this in uat and confirm. Changes are deployed

**Comment by kashish384** [comment]
- Order templates are working in UAT

![Image](https://github.com/user-attachments/assets/10fc42fe-43a9-4ea8-ac13-a74f6544178a)

**Comment by devarajd94** [comment]
@Ramu-kandimalla @kashish384 This is a generic pdf. For all orders it is showing the same order. 

![Image](https://github.com/user-attachments/assets/70c7ee93-909b-4586-8fbb-345d408c6678)

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  currently we are enabled the generic order PDF in UAT environment we are working getting all the orders and applications to move to UAT 

reference ticket ID #1469
