### ISSUE TITLE
Bug | UAT Env | The message for Bar Council violation is wrong

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1639]
Only capital letters, numbers and '/' allowed. (Expected Format: K/000000/0000)

![Image](https://github.com/user-attachments/assets/5e18df68-5133-4bbe-a97f-a494c836f741)

**Comment by Ramu-kandimalla** [comment]
Hi @shambhavigoel1002  Please add the development tasks and estimated effort details to resolve this ticket

**Comment by shambhavigoel1002** [comment]
Hi @Ramu-kandimalla  This is fixed

**Comment by Ramu-kandimalla** [comment]
Hi @rajeshcherukumalli  Please verify and confirm in UAT environment

**Comment by rajeshcherukumalli** [comment]
Hi @devarajd94 , issue is fixed in UAT environement please find the reference
![Screenshot from 2024-09-09 20-56-32](https://github.com/user-attachments/assets/1dcc817d-79d0-42de-8346-f91bc98c72b5)
