### ISSUE TITLE
Localisation: Terms and Conditions is showing junk string

### ISSUE THREAD

**Issue by subhashini-egov** [pucardotorg/dristi#164]
Env: UAT 
Login: Citizen and register as "Litigant"

Terms and Conditions are on a separate page and is showing some junk string. 
<img width="612" alt="Screenshot 2024-05-02 at 6 37 13 PM" src="https://github.com/pucardotorg/dristi/assets/107110442/54f99ce8-3943-4742-a903-b5853cb068f4">

**Comment by SureshSoren** [comment]
Couldn't reproduce this @subhashini-egov .
