### ISSUE TITLE
UAT Localization feedback from Judges

### ISSUE THREAD

**Issue by Ramu-kandimalla** [pucardotorg/dristi#1641]
Updating the localization as per the judges Feedback

https://docs.google.com/spreadsheets/d/1iRyG_wycBxCz4mi38z2E3kxwp-WI6Xf6/edit?gid=1048499600#gid=1048499600

**Comment by Ramu-kandimalla** [comment]
HI @TusharKatiyar2002  Please complete the dev testing the update in the ticket

**Comment by TusharKatiyar2002** [comment]
Updated localization in kerala-uat

**Comment by Ramu-kandimalla** [comment]
Hi @rajeshcherukumalli  Please verify and confirm in UAT environment

**Comment by Ramu-kandimalla** [comment]
Hi All localization was updated in UAT environment
