### ISSUE TITLE
User Registration: Advocate API has /advocate/advocate in PATH

### ISSUE THREAD

**Issue by subhashini-egov** [pucardotorg/dristi#1645]
**Describe the bug**
Advocate API is not API compliant even in basic URL path. We have /advocate/advocate which is wrong. The paths should be as [per API spec](https://github.com/pucardotorg/dristi-solutions/blob/develop/api_specifications/advocate-api-0.1.0.yaml), namely:

```
/advocate/v1/_create
/advocate/v1/_update
/advocate/v1/_search
/advocate/clerk/v1/_create
/advocate/clerk/v1/_update
/advocate/clerk/v1/_search
```

**Comment by ashishbeehyv** [comment]
hi @rajeshcherukumalli it is fixed. please test this in QA. cc: @Ramu-kandimalla
