### ISSUE TITLE
All Modules: Remove traces console error 

### ISSUE THREAD

**Issue by subhashini-egov** [pucardotorg/dristi#1647]
**Describe the bug**
Whenever any page loads on DRISTI, there's a traces error that gets replicated multiple times in the developer console. Remove this library that's causing so many errors on the console.

**To Reproduce**
1. Go to DRISTI home
2. Click on Login
3. Open the Chrome developer console
4. See errors

**Expected behavior**
Console should be clear unless there's an actionable problem.

**Screenshots**
<img width="1134" alt="Screenshot 2024-09-10 at 3 00 10 PM" src="https://github.com/user-attachments/assets/ddad18ed-3d74-4892-b935-789dd4fe8e95">

**Comment by anirudh-0** [comment]
disabled entry point for telemetry script
