### ISSUE TITLE
User registration: After registering, user is taken back to the "Register" screen. 

### ISSUE THREAD

**Issue by subhashini-egov** [pucardotorg/dristi#165]
Env: UAT
Logged into the portal and registered as a litigant. Submitted Aadhar ID proof and clicked on "Register". Registration successful is shown. Then, litigant is taken back to a home screen that again shows "Register". Please see attached screenshot.

<img width="520" alt="Screenshot 2024-05-02 at 6 37 25 PM" src="https://github.com/pucardotorg/dristi/assets/107110442/25958e42-30aa-4a9d-b084-a509bb7f203f">

**Comment by SureshSoren** [comment]
Fixed and pushed to UAT
