### ISSUE TITLE
Tech Debt: Master data for court complex and related establishments

### ISSUE THREAD

**Issue by atulgupta2024** [pucardotorg/dristi#1650]
Various search on home screen or by logged in user like for say clerk, they would want to be able to search data by first selecting court complex or establishment

Need to have relevant masters which have state, district, court complex and establishment mapping. Similar table is required to have court rooms per establishment where specific judges are assigned. This is what provides the courtId and is the basis for CNR number 

While doing this, need to ensure that the data stores is searchable using court complex or establishment.

@suresh12 @subhashini-egov @devarajd94

**Comment by Ramu-kandimalla** [comment]
HRMS Dependency #2349

**Comment by atulgupta2024** [comment]
closing this as referenced in 2349
