### ISSUE TITLE
Adding Rediess Cache for case search for case ID

### ISSUE THREAD

**Issue by Ramu-kandimalla** [pucardotorg/dristi#1653]
Hi @radheshjoshi1  Please add the development tasks

**Comment by radheshjoshi1** [comment]
added the redis cache for case service. saving case in redis cache while update, create and search
for search in redis cache defaultfields should be false and caseId should be present.

**Comment by radheshjoshi1** [comment]
did the sanity checks in dev @Ramu-kandimalla , ready to test in qa

**Comment by kashish384** [comment]
Hi @Ramu-kandimalla,

- Env_[dristi-kerala-dev]
- for case search testing done_here we we have few scenario's..
1. (a)search_case_Judge:"criteria": "status": 
                                          "PENDING_ADMISSION",
                                          "ADMISSION_HEARING_SCHEDULED",
                                          "CASE_ADMITTED"
          url: https://dristi-kerala-dev.pucar.org/case/v1/_search
         "limit"- 10 | Total Count-38 | Status Code-200 ok | 1St Time-721 ms | 2nd Time-672 ms
   (b)search_case_Judge:"criteria": "status": 
                                         "PENDING_ADMISSION",
                                         "ADMISSION_HEARING_SCHEDULED",
                                         "CASE_ADMITTED"
           url: https://dristi-kerala-dev.pucar.org/case/v1/_search
          "limit"- 50 | Total Count-38 | Status Code-200 ok | 1St Time-2.01 s | 2nd Time-8.76 s

2.search_case_Litigant:criteria":
                                                   "filingNumber": "",
                                                   "caseType": "NIA S138",
                                                    "substage": "",
                                                    "tenantId": "kl",
                                                   "searchKey": "filingNumber",
                                                   "defaultFields": true,
                                                  "litigantId": "IND-2024-09-06-000701",
                                                  "pagination": {
                                                  "limit": 10,
                                                  "offSet": 0
              url: https://dristi-kerala-dev.pucar.org/case/v1/_search
             "limit"- 10 | Total Count-14 | Status Code-200 ok | 1St Time-665 ms | 2nd Time-629 ms

3.search_case_FSO:"criteria": 
                                   "status": "UNDER_SCRUTINY"
             url: https://dristi-kerala-dev.pucar.org/case/v1/_search?_=1726232463563
             "limit"- 1 | Total Count-5 | Status Code-200 ok | 1St Time-10.40 s | 2nd Time-216 ms 

4.search_case_Advocate:"criteria": 
                                           "filingNumber": "",
                                           "caseType": "NIA S138",
                                           "substage": "",
                                           "tenantId": "kl",
                                           "searchKey": "filingNumber",
                                          "defaultFields": true,
                                          "advocateId": "c90fbe06-8608-4e82-86e1-787c55aeeb1f",
                                          "pagination": 
                                          "limit": 10,
                                         "offSet": 0
                url: https://dristi-kerala-dev.pucar.org/case/v1/_search
               "limit"- 10 | Total Count-4 | Status Code-200 ok | 1St Time-384 ms | 2nd Time-338 ms
