### ISSUE TITLE
UAT: Ability to delete files permanently 

### ISSUE THREAD

**Issue by atulgupta2024** [pucardotorg/dristi#1654]
There are times when a PDF is generated during a draft process like in order or application creation or in case e-filing, we may generate a few PDFs as the file goes back and forth between scrutiny. 

need to clearly call out if all PDFs need to be stored or there are some files that can be deleted. 

For deletion, need to upgrade the filestore platform service

cc @subhashini-egov @suresh12

**Comment by Ramu-kandimalla** [comment]
Closing this ticket as duplicate #1924
