### ISSUE TITLE
Localisation | Upload Malayalam localisation in UAT

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1660]
- Update localisation in Malayalam
- This should be accessible when the user selects Malayalam as the language of choice at the start of the landing page
- Or when they change the language at the top right hand corner in the screen
- Use the document below:
https://docs.google.com/spreadsheets/d/1iRyG_wycBxCz4mi38z2E3kxwp-WI6Xf6/edit?gid=1664592567#gid=1664592567

Use Sheet 1-> Scroll to the right -> Text (Malayalam)

**Comment by TusharKatiyar2002** [comment]
in this link for submissions and hearings module no localizations are there @devarajd94 @Ramu-kandimalla, for other modules I have added it. 
Plz check this link 
https://beehyv0-my.sharepoint.com/:x:/g/personal/sureshsoren_beehyv_com/Edd5m8hMtbVMl_p4cD4eNH4B6mbsuzVP7HCQOmmMj__56A?e=sftFI8

**Comment by devarajd94** [comment]
@TusharKatiyar2002 the link is inaccessible to me

**Comment by TusharKatiyar2002** [comment]
@devarajd94, not able to see any sheet with name submissions or hearings

**Comment by TusharKatiyar2002** [comment]
The text is now updated for last two modules also
