### ISSUE TITLE
Bug | Cheque details get reset if the file uploaded is large

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1662]
Uploading a large file resets the fields without saving in E FIling. Size of the file uploaded 12.4 MB uploaded 3 times

https://drive.google.com/file/d/147Fz-XLwx0Akm1wCKMUSsGKMsOuPd2ft/view?usp=sharing

**Comment by devarajd94** [comment]
All testing is happening on UAT @manimaarans

**Comment by TusharKatiyar2002** [comment]
It is working fine in both kerala dev and uat for large file upload (used 30 mb file). 

ocr-service/verify is still giving 400, error is (The data value transmitted exceeds the capacity limit.)
@ankitSharmaBeehyv plz look into it.

**Comment by Beehyv-Vinod** [comment]
Hi @Ramu-kandimalla  @rajeshcherukumalli I tested by uploading the 47mb it is working fine. 
When network is Stable working fine without any issues, checked with low network connection working fine without encountering any issues, below are the reference for the same,

1. Litigant details = https://jam.dev/c/f59cd2c8-8153-411e-ab15-c529423546d6
2. Cheque details = https://jam.dev/c/457b3c6c-3645-4eff-bde3-e7bce6da0365
3. Debt/Liability = https://jam.dev/c/bcbd5430-ffe0-41bd-9842-41ea236643c0
4. Legal Demand Notice = https://jam.dev/c/c5a1d2d9-24fd-43d5-a31b-77565e343bcc
5. Complainant & Sworn Statement -- https://jam.dev/c/85a66eed-036d-47c6-b871-8460e669e142
6. Advocate details screen -- https://jam.dev/c/662f89b9-4047-4f7d-88cd-2421852c1d7e

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  Can you please verify and confirm
