### ISSUE TITLE
[BUG]: Create API gives 400

### ISSUE THREAD

**Issue by Beehyv-Vinod** [pucardotorg/dristi#1663]
When user clicks on Make Payment button Second time **Create** API gives 400

**To Reproduce**

1. Make a Submission
2. Click on Make Payment 
3. Make a Online Payment
5. Close the new window (Payment window) 
6. Click on Make Payment button
7. Now we can see Create API gives 400

Expected : Two Demands should not create for the same Submission

**Comment by TusharKatiyar2002** [comment]
Hi @Beehyv-Vinod , plz check this issue in dev env

**Comment by Beehyv-Vinod** [comment]
Hi @Ramu-kandimalla @rajeshcherukumalli,  Tested in **Kerala-dev** Working fine, Demand is creating only once.

**Comment by Beehyv-Vinod** [comment]
Hi @Ramu-kandimalla  @rajeshcherukumalli, Tested in UAT environment, Demand is creating only once. Working as expected
