### ISSUE TITLE
Static Causelist Generation

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1669]
The static Causelist PDF needs to be generated. Refer the following document
https://docs.google.com/document/d/1MdN4M-3XoDSoLV5M9WmXSGqA6YxY9Hj2Z4w8348XO5I/edit

PDF Format:
https://docs.google.com/document/d/1JrX9CcKqa1g0QrZQuG3CEiv9dTibNEZGyTzNHpeaq44/edit#heading=h.kgedar2r93vk

PRD: 
https://docs.google.com/document/d/1MdN4M-3XoDSoLV5M9WmXSGqA6YxY9Hj2Z4w8348XO5I/edit#heading=h.5noq3ylh6iih

**Comment by Ramu-kandimalla** [comment]
Hi All new design changes are finalized on Friday 4PM  we are working on development now

**Comment by radheshjoshi1** [comment]
dev testing is done we can move it to qa @Ramu-kandimalla

**Comment by Ramu-kandimalla** [comment]
Hi @rajeshcherukumalli  plesse test

**Comment by rajeshcherukumalli** [comment]
Hi @radheshjoshi1 ,
Pending applications are displayed empty for the casue list , please find the reference
https://github.com/pucardotorg/dristi/issues/1811

**Comment by radheshjoshi1** [comment]
resolved the issue you can test @rajeshcherukumalli

**Comment by rajeshcherukumalli** [comment]
Hi @Ramu-kandimalla , The following scenarios are tested for the cause list 

Verify the cause list is downloaded for the Judge user , if we click on ‘View Hearings → Download Cause List’
Verify the cause list is downloaded for the litigent user , if we click on ‘View Hearings → Download Cause List’
Verify all the hearing types are displayed in the cause list.
Verify the sequence is displayed based on first ST and then CMP cases are displayed
Verify the slots are displayed based on the hearing list.
Verify all the today cases are displayed in the cause list.
Verify the case name and case id is displayed correctly for the case
Verify the advocates are not there displayed empty for a particular case .
Verify the advocates are added for complainant display only the complainant for the case
Verify the advocates are added for accused display only the accused for the case.
Verify all the ‘Under Review’ applications are displayed for the case in the Application section.

Please find the reference documents for the cause list
[cause_list_2024-10-01.pdf](https://github.com/user-attachments/files/17249431/cause_list_2024-10-01.pdf)
[cause_list_2024-10-03-3.pdf](https://github.com/user-attachments/files/17249444/cause_list_2024-10-03-3.pdf)

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  Please verify and confirm

**Comment by Hemadri-Chinna** [comment]
Hi @rajeshcherukumalli it is deployed in qa can you please check

**Comment by rajeshcherukumalli** [comment]
Hi @Ramu-kandimalla , the causelist document is updated with mentioned logo
![Image](https://github.com/user-attachments/assets/faafac76-aef7-46b3-aa89-4ae8a0f42ad3)
[cause_list_2024-10-16 (1).pdf](https://github.com/user-attachments/files/17393621/cause_list_2024-10-16.1.pdf)

**Comment by devarajd94** [comment]
Verified
