### ISSUE TITLE
Advocate registration: Bar council ID is not asked for in the advocate registration screen

### ISSUE THREAD

**Issue by subhashini-egov** [pucardotorg/dristi#168]
Env: UAT

Logged in as a user and registered. Went through uploading Aadhar and clicked on "Advocate". Clicked on accept terms and conditions. The UI did not ask for the bar council ID. For advocates to be registered, bar council ID should be asked for and an approval workflow triggered.

**Comment by SureshSoren** [comment]
@subhashini-egov  as per the current flow we are logging out the user when he selects Advocate or Advocate Clerk after Individual Registration then when user is re-login we are asking for additional details such as Bar Registration Number and Bar Council ID.

cc: @manimaarans
