### ISSUE TITLE
UAT: Change courtCaseNumber to ccstNumber

### ISSUE THREAD

**Issue by atulgupta2024** [pucardotorg/dristi#1686]
One of the numbers case has is called - courtCaseNumber. rename this to ccstNumber as that is more relevant to what the number really is. 

Should be possible to do a find-replace. 

@suresh12 FYI as well.

**Comment by iknoorkaur** [comment]
Hi @atulgupta2024 , this issue was covered in BNSS Flow
Please find this below video for reference: 
[CCST_No.webm](https://github.com/user-attachments/assets/23bf3ccf-27c2-4175-86da-9ef15043f78d)
cc: @Ramu-kandimalla @rajeshcherukumalli

**Comment by atulgupta2024** [comment]
@iknoorkaur @Ramu-kandimalla  if already addressed, we can close this ticket
