### ISSUE TITLE
[BUG]: USER REGISTRATION

### ISSUE THREAD

**Issue by supriyasankarangill** [pucardotorg/dristi#1690]
When I registered the first time as a lawyer, I got a confirmation that I am registered and it is waiting for approval. 
<img width="1470" alt="Screen Shot 2024-09-17 at 3 36 33 PM" src="https://github.com/user-attachments/assets/4e81ca09-c5dc-431d-9acf-cb5623c62529">

But when I logged in as a  Nyay Mitra, I could not see the application as pending to approve. 

The second time I did the registration- following the exact same process, however, it worked. Not sure what the glitch was that it didn't work the first time

**Comment by ashishbeehyv** [comment]
@Ramu-kandimalla i am not able to reproduce this issue. @Beehyv-Vinod  can you please try to reproduce this issue and make a recording for the steps and also the network details.
