### ISSUE TITLE
[BUG]: Efiling - Delay Condonation Application

### ISSUE THREAD

**Issue by supriyasankarangill** [pucardotorg/dristi#1692]
For the page "Delay Condonation Application", I am unable to click the button "No". It is by default "yes" and I cant change it if I want. 

I should be able to Click "No" and submit a condonation application.

**Comment by shambhavigoel1002** [comment]
Hi @supriyasankarangill  About this is issue. The yes and no values are dependent on "date of accrual of cause of action" . 
The info of which we can see in legal and demand notice. Which is again dependent on cheque details
Attaching a Video reference below for the same.

https://jam.dev/c/2b767ec6-0181-4200-8b86-dcfd9869ceca
