### ISSUE TITLE
Bug - Actual Case File : User Registration I Special characters allowed in the name

### ISSUE THREAD

**Issue by mehulseg24** [pucardotorg/dristi#1693]
The Name and Last Name fields not accept the special characters 

1. Start User Registration

**Expected behavior**
User Name: unable to enter the user name : T.N. Suresh 
<img width="1440" alt="Screenshot 2024-09-18 at 6 22 29 PM" src="https://github.com/user-attachments/assets/17bd1c74-4a1d-4672-ad8b-d4aeabd51909">

<img width="1440" alt="Screenshot 2024-09-18 at 6 22 52 PM" src="https://github.com/user-attachments/assets/5e1250bc-8cca-44a3-8288-c73f4c84ddcf">

**Comment by ashishbeehyv** [comment]
@mehulseg24  we are not allowing any special characters here (including .), only letters are allowed. this has been finalised already.

**Comment by Ramu-kandimalla** [comment]
Hi @mehulseg24  @devarajd94  These are text fields it wont allow any special characters in this fields this is not Bug
