### ISSUE TITLE
[BUG]: Infobox text to be updated

### ISSUE THREAD

**Issue by mehulseg24** [pucardotorg/dristi#1694]
**Describe the bug**
Status / Act: Negotiable Instrument Act to be changed to Negotiable Instruments Act

Steps to reproduce the behavior: Click on File a Case

<img width="1440" alt="Screenshot 2024-09-18 at 6 35 58 PM" src="https://github.com/user-attachments/assets/6f21adec-0670-4175-984e-08d7654c13d7">

**Comment by ashishbeehyv** [comment]
@rajeshcherukumalli  this issue is fixed. please test it in UAT.

**Comment by Mahesh-Vishwanath1** [comment]
Hi @devarajd94,
I have verified this ticket in the UAT solution, and the changes have been updated as expected.
 **Negotiable Instrument Act** to be changed to **Negotiable Instruments Act**

Citizen URL: https://dristi-kerala-uat.pucar.org/digit-ui/citizen/dristi/home/login
Reference Link: https://jam.dev/c/d0ac4590-7b83-46a7-9e07-496112394da4

litigant no. :7876876676
advocate no. :8798789788

**Comment by devarajd94** [comment]
Verified
