### ISSUE TITLE
Bug | Join a case is crashing

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1695]
Refer video below @manimaarans Please mark this ticket as showstopper and resolve at priority
https://github.com/user-attachments/assets/50f6a231-8f33-4e2f-8005-aa40d1d9e842

**Comment by Beehyv-Vinod** [comment]
Hi @Ramu-kandimalla  @rajeshcherukumalli  Tested in UAT environment Join a case flow is working fine for English language. Please Find the below reference,
 
1. Respondent Join a case flow --https://jam.dev/c/a67f6b9a-9f4e-4622-9927-fda918b6e9d5
2. Advocate Join a case flow & New Advocate Replacing Existing Advocate Flow --https://jam.dev/c/b20f75df-88c7-4bfc-8207-1f30efbeec0f

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  Please verify and confirm

**Comment by devarajd94** [comment]
Verified
