### ISSUE TITLE
Bug | Judge receiving pending task for Response

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1696]
Why is judge receiving pending task for response of a submission. On clicking it is redirecting to login page.

![Image](https://github.com/user-attachments/assets/280f2b25-016c-48e9-922d-6cc0e1afaec3)

**Comment by vaibhavct** [comment]
@prasanna2400  I just checked, UI is not creating pending task manually for judge to review the submission.
c.c. @manimaarans  @Ramu-kandimalla

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  This issue is fixed in UAT env

**Comment by Ramu-kandimalla** [comment]
Hi @rajeshcherukumalli  Please verify and confirm in UAT Env

**Comment by bhuvanyuguru** [comment]
Hi @Ramu-kandimalla, 

This bug is resolved in UAT. 

![Image](https://github.com/user-attachments/assets/1ecbb5de-de7a-4c33-b7b8-53c44d2421aa)

**Comment by Ramu-kandimalla** [comment]
HI @devarajd94  This issue is fixed

**Comment by devarajd94** [comment]
Verified
