### ISSUE TITLE
Bug | Court Staff screen issues

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1697]
- [ ] Issue 1

Login to Court Staff
Click on a summon
The summons document should be shown when clicked on. It is currently blank

![Image](https://github.com/user-attachments/assets/b52f6843-8908-40c5-918a-665c3d0203cb)

- [x] Issue 2

UI for sign options need to change. Refer Application E Sign screens

![Image](https://github.com/user-attachments/assets/039b7315-5fd7-4990-9373-c8bdecd9d169)

**Comment by shambhavigoel1002** [comment]
The issue 2 has been fixed. Issue 1 is backend issue .

**Comment by Susmitabe** [comment]
@shambhavigoel1002 will recheck and confirm

**Comment by shambhavigoel1002** [comment]
Still an issue @Susmitabe 
cc @manimaarans

**Comment by kashish384** [comment]
Hi @Ramu-kandimalla,**Issue-2** verified in UAT env.
- url: https://dristi-kerala-uat.pucar.org/digit-ui/employee/orders/Summons&Notice
-  reference link: https://jam.dev/c/72086462-47bf-409c-882f-181fb09e1df7
![image](https://github.com/user-attachments/assets/2c42ceed-436a-43c2-9f72-41f01f87d4c8)

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94 This issue is fixed

**Comment by devarajd94** [comment]
Verified
