### ISSUE TITLE
Bug | Mark as sent button not working

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1698]
The mark as sent button not working. High Priority bug as it is a showstopper for summons

https://github.com/user-attachments/assets/99bad024-3af0-4256-a276-b6b4a2e24710

**Comment by kashish384** [comment]
Hi @Ramu-kandimalla
Env._UAT
url: https://dristi-kerala-uat.pucar.org/digit-ui/employee/orders/Summons&Notice
reference link: https://jam.dev/c/89cbbd86-320f-452e-bf58-d2e687c2d292
                        https://jam.dev/c/92485641-613d-4842-8e90-725e15f8a7fc

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  This issue is resolved and working as expected

**Comment by devarajd94** [comment]
Verfied
