### ISSUE TITLE
Bug | The list of applications is getting truncated

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1699]
https://github.com/user-attachments/assets/01a1a57a-5fce-4825-866d-a68c4eafe7d5

**Comment by Ramu-kandimalla** [comment]
Hi @rajeshcherukumalli  Please check and confirm once

**Comment by Mahesh-Vishwanath1** [comment]
Hi @devarajd94,
I have verified it in the UAT solution, and it is now displaying properly.

Citizen URL: https://dristi-kerala-uat.pucar.org/digit-ui/citizen/dristi/home/login
Reference Link: https://jam.dev/c/0038b37b-39d5-4282-b514-54fae218ef1b

advocate no. :8798789788

**Comment by devarajd94** [comment]
Verified
