### ISSUE TITLE
Bug | Hearings are getting scheduled on weekends

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1700]
The scheduler is suggesting dates on weekends to the judge during hearing scheduling and rescheduling (Opt out dates)

**Comment by Mahesh-Vishwanath1** [comment]
Hi @shambhavigoel1002,
I verified this ticket in both the dev and UAT environments, and I'm still getting hearing dates on weekends. I'm also able to schedule hearings on weekends. Could you please check this.
Steps to reproduce: Create a new case >>Admit the case for the judge>>Click "I am sure" on the confirmation pop-up>>Click "Schedule next hearing>>Observe the pop-up suggesting weekend dates for the hearing.

Reference link (Dev env):https://jam.dev/c/3825c462-2451-4b71-b279-c4aa63d30a3a
Reference link (UAT env):https://jam.dev/c/ffd145a7-ba4b-48e0-8ff0-b11fba730bb2

**Comment by prasanna2400** [comment]
Hi @devarajd94  is opt out suggested date also weekends? , can u please share caseId or hearingId so i can check and verify

**Comment by devarajd94** [comment]
Verified
