### ISSUE TITLE
UAT | Testing with an Actual Case | Witness name is Compulsory

### ISSUE THREAD

**Issue by deeshita** [pucardotorg/dristi#1706]
**Describe the bug**
Witness name need not be compulsory - can substitute with designation. E.g a bank manager may change during the course of proceedings - them being a witness here links to designation

**To Reproduce**
1. Go to 'File a Case' and in that 'Witness Details'

**Expected behavior**
Ability to record designation of witness instead of name

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [Chrome]

**Comment by shambhavigoel1002** [comment]
Hi @deeshita ,
About this issue either of first name ,middle name, last name  has to be compulsory . This has been implemented as per agreement with @devarajd94 and team.
Thanks.
cc @Ramu-kandimalla

**Comment by Ramu-kandimalla** [comment]
Please refer to #1505

**Comment by devarajd94** [comment]
Change the Field name from 'Name' to 'Name/Designation'. Please take this up in next sprint

**Comment by shambhavigoel1002** [comment]
Hi @devarajd94 
attaching below the reference of the screen . We have 3 input field for name and changing  either with text 'Name/Designation' won't be meaningful . Hence unable to pick it up for now
cc:- @anirudh-0 @Ramu-kandimalla 
![Image](https://github.com/user-attachments/assets/7aac6588-113d-44a8-9564-a4daa5d4bdc6)

**Comment by Taherabharmal** [comment]
Yes, a witness as an org is a change.

**Comment by Ramu-kandimalla** [comment]
Since its new feature and have huge scope we are not taking issue in this sprint once scope is finalizes PM can create new ticket
