### ISSUE TITLE
UAT | Payment Calculator Amount

### ISSUE THREAD

**Issue by deeshita** [pucardotorg/dristi#1708]
**Describe the bug**
The payment calculator amounts are yet to be updated - advocate and advocate clerk welfare fund amounts.

**To Reproduce**
1. Go to 'File a Case' and under that to 'Review and Sign' on a fully signed case
2. Complete signature on the case file and submit the case to go to the success screen. Then go to the 'Make Payment' button to see the payment breakup

**Expected behavior**
The amounts for welfare funds should comply with the Rules shared and further, the petition fee amount should be in slabs.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [Chrome]

**Comment by shambhavigoel1002** [comment]
Hi @deeshita  changes have been updated
below is the reference
![Image](https://github.com/user-attachments/assets/81673eeb-47a8-4e63-a8f1-2b809a7575dc)

**Comment by Ramu-kandimalla** [comment]
Hi @deeshita @devarajd94 this issue is fixed

**Comment by kashish384** [comment]
Hi @Ramu-kandimalla, verified in **UAT env**

-  url: https://dristi-kerala-uat.pucar.org/digit-ui/citizen/dristi/home/file-case/e-filing-payment?caseId=6567f02f-b3e0-4686-b0ba-172cfaa355ff
- reference link: https://jam.dev/c/0c21afb9-0b31-4913-bd9b-783774f99a15
                      https://jam.dev/c/9603139a-3e51-4fd6-b294-99fb3651b858

- Test cases:
1.verify that user able to see Petition Fee according following logic:
if Cheque Amount <= 50000 , then Petition fee is Rs 250
if Cheque Amount > 50000 && Cheque Amount <= 200000, then Petition fee is Rs 500
if Cheque Amount > 200000 && Cheque Amount <= 500000, then Petition fee is Rs 750
if Cheque Amount > 500000 && Cheque Amount <= 1000000, then Petition fee is Rs 1000
if Cheque Amount > 1000000 && Cheque Amount <= 2000000, then Petition fee is Rs 2000
if Cheque Amount > 2000000 && Cheque Amount <= 5000000, then Petition fee is Rs 5000
if Cheque Amount > 5000000, then Petition fee is Rs 10000
2.verify that Application Fee per Application = INR 2
3.verify that Vakalathnama Fee = INR 6
4.verify that Advocate Welfare Fund = INR 25
5.verify that Advocate Clerk’s Welfare Fund = INR 12
6.verify that if there is a delay of more than 1 month in filing a case for Delay Condonation Application, Delay Condonation Application Fee = INR 2

**Comment by devarajd94** [comment]
Verfied
