### ISSUE TITLE
Bug | The adv is not able to see the full transcript

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1709]
The transcript is truncated during the hearing:
The Exit Hearing text is misaligned

![Image](https://github.com/user-attachments/assets/36f69e7b-d294-4938-aa0c-31c15605643a)

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  This Issue is fixed

**Comment by bhuvanyuguru** [comment]
Hi @Ramu-kandimalla 

This issue is resolved in UAT. 

STEPS TO REPRODUCE: 

> 1) Start Hearing of a Case by Judge.
> 2) Join hearing by Advocate/Litigant. 
> 3) Add Transcription, check scroll option in both users hearing page.
> 


![image](https://github.com/user-attachments/assets/1ebb14cd-70e9-4602-8cd1-61812067a1d9)

**Comment by devarajd94** [comment]
Verified
