### ISSUE TITLE
UAT| Testing on Actual Case File | Re-upload not working for defect correction post scrutiny

### ISSUE THREAD

**Issue by deeshita** [pucardotorg/dristi#1710]
**Describe the bug**
The FSO marked a document as error and sent it back for correction - but as an advocate I am unable to re-upload. However, I can still re-submit the case

**To Reproduce**
1. File a case as an advocate
2. FSO to mark a document as defect
3. Go back to advocate login and open the file
4. Go to the marked defect and re-upload button is disabled. However, then skip to review and sign. You can add signature and submit.

**Expected behavior**
1. Re-upload option should have been available
2. Signing and submitting of file should not be possible unless error iscorrected. 

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [Microsoft Edge]

**Comment by shambhavigoel1002** [comment]
Hi @deeshita 
We are unable to reproduce the issue below is the jam
https://jam.dev/c/ee846b8f-b66f-4535-8f4f-aeab00b012a6
we are able to re upload the files . 
cc: @Ramu-kandimalla

**Comment by devarajd94** [comment]
Verified. The FSO is able to send it back for correction and the advocate is able to upoload in R1
