### ISSUE TITLE
UAT | Judge home screen very slow and a case post scrutiny appearing in judge login but opens an empty details page

### ISSUE THREAD

**Issue by deeshita** [pucardotorg/dristi#1711]
**Describe the bug**
The judge home screen in the UAT environment is loading very slowly and when i open a case, all details disappear 

**To Reproduce**
1. Login using judge credentials
2. Open any case that has come in for cognizance

**Expected behavior**
Faster loading of case and visibility of case details

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome]

**Comment by Mahesh-Vishwanath1** [comment]
Hi @devarajd94,
I have verified this ticket in the UAT solution using the configuration: OS [e.g., Windows], Browser [e.g., Chrome, Edge]. The case details now load faster and are quickly visible.
Reference Links:
OS: windows browser: chrome >>https://jam.dev/c/a6a2e27a-555e-4aab-ab0e-bf079df0a825
OS: windows browser: Edge >>https://jam.dev/c/c151bfcd-77d6-4235-bf75-b8c8cc6e6f92

User Ids link: https://docs.google.com/spreadsheets/d/1w0RT8lHfx7T2-WaTW2DS-66THYjtyNYTw-FDoqJp5-o/edit?gid=0#gid=0
