### ISSUE TITLE
UAT Bug | Nyay Mitra Home Screen

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#1712]
![Image](https://github.com/user-attachments/assets/bed89132-dc8a-4e7a-a868-9d2100153075)

Subheading below Pending Payments should state:
Record offline payments for Case Filing, Summons, Notices and Applications

**Comment by bhuvanyuguru** [comment]
Resolved in UAT Nyay-Mitra

![Image](https://github.com/user-attachments/assets/b7d6b8c4-d853-4114-bc82-db6146aa16b4)

**Comment by devarajd94** [comment]
Verified
