### ISSUE TITLE
UAT Bug | List of Documents Required

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#1715]
List of documents required for Case and File downloaded are different

![Image](https://github.com/user-attachments/assets/df734f1a-c4bc-4497-bf1c-826f58495ea0)
![Image](https://github.com/user-attachments/assets/be7dbc47-3eeb-46a1-be76-21b0569a4f45)

[1725956196893TXHStLfHUS.pdf](https://github.com/user-attachments/files/17055586/1725956196893TXHStLfHUS.pdf)

**Comment by ashishbeehyv** [comment]
hi @rajeshcherukumalli this issue is fixed. please test this in UAT.

**Comment by kashish384** [comment]
@Ramu-kandimalla 

- Env._UAT
-  url: https://dristi-kerala-uat.pucar.org/digit-ui/citizen/dristi/home/file-case

* for old user_List of documents required for Case and File downloaded are **different**
-  reference link for old user : https://jam.dev/c/2efe675b-38d0-4aff-af90-b6fdd45b5fc3

* for new user_List of documents required for Case and File downloaded are **same**
-  reference link for new user : https://jam.dev/c/d2d517aa-ed27-4e02-9a6d-e6f97d50f712

**Comment by devarajd94** [comment]
Verified
