### ISSUE TITLE
[BUG]: Download Case File button not working

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1716]
**Describe the bug**
Download Case File button not working

**To Reproduce**
1. Complete E Filing and make payment
2. Open the case from home screen
3. Click on Download Case File - Not downloading

**Expected behavior**
The Case File should download

https://github.com/user-attachments/assets/5de34018-9583-43c1-98dc-42e02ea8c93e

**Comment by shambhavigoel1002** [comment]
Hi @devarajd94 for now if the case file does not exist the download file button will be disabled .
cc:- @Ramu-kandimalla

**Comment by bhuvanyuguru** [comment]
Hi @Ramu-kandimalla, 

This issue is resolved in UAT
[uat-case pdf issue.webm](https://github.com/user-attachments/assets/f1746671-4f08-47cd-9ea8-71741808b263)
