### ISSUE TITLE
Bug | Documents not visible on opening in the 'Documents Tab'

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1719]
https://github.com/user-attachments/assets/04fc9590-0255-4214-83b8-43f56738a102

**Comment by TusharKatiyar2002** [comment]
Hi @rajeshcherukumalli , plz test this in UAT

**Comment by RohiniKanala517** [comment]
Hi, it looks good now. Please check video for the same,
https://jam.dev/c/05195289-a923-4099-9ad7-8ca328490b96

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  This issue is  fixed

**Comment by devarajd94** [comment]
Verified
