### ISSUE TITLE
[BUG]: The payment calculation for Warrant is wrong

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1720]
**Describe the bug**

The payment calculation for Warrants is wrong.

**To Reproduce**
1. Issue a warrant
2. The lawyer opens up the pending task to make payment for summons
3. It shows E Filing Fee instead of I Cops fee
4. The pay button is also not working

**Expected behavior**
Only Court Fee needs to be paid at the time of Icops Warrant
The Pay button should redirect to E Treasury

**Screenshots**

https://github.com/user-attachments/assets/c8549ad7-674f-4d8a-88dc-d30464a5e4b6

**Comment by prasanna2400** [comment]
Hi @Ramu-kandimalla Can you please add Ajith with this ticket? I'm not sure whether the UI is calling the endpoint or the backend.

**Comment by prasanna2400** [comment]
@devarajd94 , we don't have any payment information for a warrant in the payment calculator document, and the same goes for notice. Could you please update the document accordingly?

**Comment by shambhavigoel1002** [comment]
Hi @Ramu-kandimalla @devarajd94 Payment calculator api is just called for E-Filing as far as i know. Please Provide further details on requirements for it's integration.

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  this is a duplicate ticket please refer the original [ticket](https://github.com/pucardotorg/dristi/issues/1724)
