### ISSUE TITLE
[BUG]: The signature is getting displayed in place of the orders

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1723]
**Describe the bug**
The signature is getting displayed in place of the orders

**To Reproduce**

https://github.com/user-attachments/assets/183e0f22-174c-4100-8be7-c49100cd0bdb

**Comment by bhuvanyuguru** [comment]
If you E-sign the order, order is shown as preview. 

If you want to upload signature, you need to download the file by clicking on click here button, manually sign and then upload signature, preview is shown as the uploaded signature. 

CC: @Ramu-kandimalla

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  This is not an issue

**Comment by devarajd94** [comment]
Change the wording to Upload Order Document with Signature instead of Upload Digital Signature Certificate

![image](https://github.com/user-attachments/assets/459e2284-0044-458a-bd75-30dc7caa6874)

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  Please verify and confirm

**Comment by bhuvanyuguru** [comment]
Hi @Ramu-kandimalla, 

Issue Resolved in UAT. 

STEPS: 
1) Generate Order from Judge. 
2) Click on Add Signature button.
3) Check "Upload Order Document with Signature" button. **(Verified across multiple orders)** 




![image](https://github.com/user-attachments/assets/820b53fc-0341-4702-a30d-b5aec6cf82dc)

**Comment by devarajd94** [comment]
Closed
