### ISSUE TITLE
Bug | Accused Address details should not be autofilled

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1725]
The complainant advocate is very unlikely to file the case from the location of the accused. Hence autofilling of the address shoud not happen

![Image](https://github.com/user-attachments/assets/16ef7909-714a-4972-aa75-58b08802f8e5)

**Comment by devarajd94** [comment]
@ashishbeehyv Dont add Kollam High Court address. Keep it as it is until issue is resolved where it captures the pin address.

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  Please add the necessary permission to allow the localhost  as well

**Comment by ashishbeehyv** [comment]
hi @rajeshcherukumalli this issue is resolved in UAT. please test it. cc: @Ramu-kandimalla

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  This issue is fixed can you please check and confirm

**Comment by devarajd94** [comment]
Verified
