### ISSUE TITLE
[BUG]: Court Staff Not able to see Summons Document

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1727]
**Describe the bug**
Court Staff unable to see summons document

**To Reproduce**

https://github.com/user-attachments/assets/4615b79e-f22c-4c1b-8ab5-fc9586551c30

**Comment by shambhavigoel1002** [comment]
Hi @devarajd94  This issue is now fixed.
You'll be able see the documents for new summons. 
Jam video for reference. 
https://jam.dev/c/b29eed89-e25c-4096-9b97-139341ef6ccf
cc :- @Ramu-kandimalla

**Comment by kashish384** [comment]
Hi @Ramu-kandimalla,verified in UAT env.
Court Staff able to see summons document.
https://jam.dev/c/0e71c1b0-0db8-431e-b57f-a2b64fa14825

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  This issue is fixed

**Comment by devarajd94** [comment]
Verified
