### ISSUE TITLE
[BUG]: Accused Name not filled in, in Join a Case Screen

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1728]
**Describe the bug**
Accused Name not filled in, in Join a Case Screen

**To Reproduce**

https://github.com/user-attachments/assets/c007f995-2c1d-477e-9c2b-b1ba61d01749

**Comment by ashishbeehyv** [comment]
hi @devarajd94 had respondent joined this case till this step? If not so then what should we display in front of "Accused" ?

**Comment by ashishbeehyv** [comment]
hi @rajeshcherukumalli this is fixed in UAT. please test this.

**Comment by bhuvanyuguru** [comment]
Hi @Ramu-kandimalla,

This bug is resolved in UAT.

![image](https://github.com/user-attachments/assets/2cb5bd1d-0e7f-4d00-9f9b-4456858c0517)

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94 This issue is fixed

**Comment by devarajd94** [comment]
Verified
