### ISSUE TITLE
[BUG]: Acknowledge Summons not working

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1732]
**Describe the bug**
Confirm receipt of Summons not working

**To Reproduce**

https://github.com/user-attachments/assets/ea6513ec-3634-483f-80d3-592dc5939233

**Comment by anirudh-0** [comment]
what should this button do @devarajd94 ?

**Comment by Ramu-kandimalla** [comment]
As discussed with @devarajd94  we are closing this ticket
