### ISSUE TITLE
[BUG]: Localisation Change, Join a Case

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1736]
**Describe the bug**
Change text to I'm an Associate Advocate
**To Reproduce**
1. Join as an advocate in a case

![image](https://github.com/user-attachments/assets/0c0288af-8581-4749-8d34-043b0a6fea10)

**Comment by TusharKatiyar2002** [comment]
@rajeshcherukumalli, plz confirm

**Comment by kashish384** [comment]
HI @Ramu-kandimalla,verified in UAT env.
![image](https://github.com/user-attachments/assets/d63b980b-6739-401f-a36d-7a4260bd6b5e)

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94 This issue is fixed
