### ISSUE TITLE
Bug| Pay Button issues for summons

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1739]
Issue 1:Pay Button not leading to any action

https://github.com/user-attachments/assets/fa80b2e0-2708-4d38-b51a-1f18c28844b4

Isssue 2: The pending task for Post is closed when court fee pay is clicked on. It should be closed only when both channel fee and court fee are paid (clicked)

**Comment by Ramu-kandimalla** [comment]
Hi @Beehyv-Vinod  Please test in UAT env

**Comment by Beehyv-Vinod** [comment]
Hi @Ramu-kandimalla @rajeshcherukumalli , Tested in UAT environment, User able to Perform the action on Pay Online button.
Ref,
[Pay_Online.zip](https://github.com/user-attachments/files/17131418/Pay_Online.zip)

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  Please verify and confirm
