### ISSUE TITLE
UAT | Scrutiny | FSO Issues

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1740]
- [x] Screen: FSO opens the case for review

In the FSO Checklist add: 
Dates entered match the dates in the documents (This requirement is P1 @Ramu-kandimalla )

![Image](https://github.com/user-attachments/assets/7e1e5e12-ccf6-49b5-9bf5-cdfc8fd27e48)

- [ ] FSO should be able to send correction to all issues in Round 2 of scrutiny after the lawyer has corrected R1. (This Requirement is P2 @Ramu-kandimalla )

To be fixed in DPG

![Image](https://github.com/user-attachments/assets/0370792d-0a49-493e-97b7-3bf94e48b246)

**Comment by shambhavigoel1002** [comment]
Hi @rajeshcherukumalli  Please check 
Issue 1 fixed, Issue 2 yet to address since p2.
cc:- @Ramu-kandimalla

**Comment by kashish384** [comment]
Hi @Ramu-kandimalla, **verified in UAT env**_Issue 1 fixed.
![Image](https://github.com/user-attachments/assets/5a5648f4-09a0-4a6a-951e-becd9b7e5fb2)

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  This issue is fixed

**Comment by devarajd94** [comment]
Issue 1 Fixed and Closed - Verified.

Leaving the ticket open for Issue 2 to be fixed
