### ISSUE TITLE
BUG | E-Filing | Bug / Language Change / Master Data / Production Config. | Complainant Advocate | Internal testing | Deeshita

### ISSUE THREAD

**Issue by muhammed-sawad** [pucardotorg/dristi#1748]
**Describe the bug**

Even for respondent, taking current address from geo location of the complainant and complainant’s lawyer by default - this should be blank

**Screenshots**
[compl_location.webm](https://github.com/user-attachments/assets/ee92c588-6b9f-4fb5-9ee6-654c97b3cbd2)

**Comment by devarajd94** [comment]
Fixed
