### ISSUE TITLE
[Bug]: [Summons] : [incorrect amount showing for summons fee offline payment ]

### ISSUE THREAD

**Issue by muhammed-sawad** [pucardotorg/dristi#1750]
**Describe the bug**
The offline payment module for summons fees shows calculation for filing fees. The online payment amount and offline payment amount are mismatching. When we are doing offline payment, it is showing the amount needed to pay for filing a case

**Expected behavior**
Fee should be same for both offline payment and online payment 

**Screenshots**
[summons_fee_mismatch_summons.webm](https://github.com/user-attachments/assets/7b5527ce-733a-4c11-8711-a7f3c2f4cb8e)

**Comment by devarajd94** [comment]
Verified on UAT
