### ISSUE TITLE
Analyze code scanning issues and create action plan

### ISSUE THREAD

**Issue by atulgupta2024** [pucardotorg/dristi#1765]
Analyze, group and prioritize all critical and high severity issues identified by various security code scanning tools  and create a plan to fix them. 

issues in DIGIT platform will be fixed as per guidance provided by DIGIT team (already shared on email and a reference commit)

**Comment by Ramu-kandimalla** [comment]
Hi @atulgupta2024 We have same issue logged by @subhashini-egov . We are closing this ticket. Please [refer](https://github.com/pucardotorg/dristi/issues/1603)
