### ISSUE TITLE
[Bug]: [Summons] : [ Filing payment calculator appearing for payment of warrant ]

### ISSUE THREAD

**Issue by muhammed-sawad** [pucardotorg/dristi#1783]
**Describe the bug**
Filing payment calculator appearing for payment of warrant

**Expected behavior**
Should show the payment calculator for Warrant

**Screenshots**
![Screenshot from 2024-09-25 16-35-18](https://github.com/user-attachments/assets/cae33bff-c7e1-430f-8552-77ccc17302ec)

**Comment by devarajd94** [comment]
Verified and closed
