### ISSUE TITLE
[BUG]: Pending task for response not created for opposite party advocate

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1784]
**Describe the bug**
When a submission is made by complainant advocate, the pending task for respondent to submit the response is not visible
**To Reproduce**

https://github.com/user-attachments/assets/0f887a9d-75ff-406b-99d5-919980acdcaf

**Comment by devarajd94** [comment]
@Ramu-kandimalla @manimaarans  this ticket needs to be taken up at priority. This was part of August demo requirement and no further changes have come in the requirements. Dont understand what the issue is.

**Comment by Ramu-kandimalla** [comment]
This ticket is duplicate so closing this ticket @devarajd94
