### ISSUE TITLE
[BUG]: BAR registration number already registered message showing up

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1785]
**Describe the bug**
BAR registration number already registered message showing up even when the number is not registered

**To Reproduce**
1. Randomly came up - even when number was changed the error was showing up
2. Think the error stays if a reg number already registered is entered and then changed, the error continues to show

https://github.com/user-attachments/assets/cfc17248-158f-4b3c-aada-06f05106d8f6

**Comment by shambhavigoel1002** [comment]
Hi @devarajd94 
This is an issue being faced because of the digit component. Already spent more than half a day to debug it .But no luck. Will pick this up sometime later. 
cc:- @Ramu-kandimalla

**Comment by devarajd94** [comment]
@shambhavigoel1002 So advocate registrations cannot be done is it?

**Comment by shambhavigoel1002** [comment]
No @devarajd94  registration is working fine. Just the one edge case if u enter already entered bar registration number and continue then the blocker you shared is happening. Or else with new bar registration number it's working totally fine

**Comment by shambhavigoel1002** [comment]
As per discussion removing the validation (Temporarily ) . Will be picked up later

**Comment by Ramu-kandimalla** [comment]
Hi @rajeshcherukumalli  PLease test

**Comment by rajeshcherukumalli** [comment]
Hi @Ramu-kandimalla , The validation check is removed tested the below scenarios in Dev environment working fine.

Verified the new advocate user is able to register.
Verify the system needs to allow the user to register with same bar registration number which is approved.
Verify the system needs to allow the user to register with same bar registration number which is Rejected.
Verify the alert message is displayed if the format is not matching
Verify the alert message is displayed if the bar registration number is empty

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  Please verify and confirm

**Comment by devarajd94** [comment]
@Ramu-kandimalla @shambhavigoel1002 lets take this ticket up in this sprint

**Comment by utpalBeehyv** [comment]
hi @rajeshcherukumalli  changes done, pls check in qa env
cc : @Ramu-kandimalla

**Comment by RohiniKanala517** [comment]
Issue has been fixed. This looks like as expected now. No duplicates are allowed.Pleases check the videos for reference,
https://jam.dev/c/11c5911b-6215-4930-9ccb-b49cb7eb0db2
https://jam.dev/c/b35d9471-13c5-4e54-94aa-89b35bdcc113

**Comment by Mahesh-Vishwanath1** [comment]
Verified in the UAT solution environment, and it is working as expected.

Reference link: https://jam.dev/c/1ff69795-de4c-4a29-ac0f-d0c20bb1bd4a

**Comment by devarajd94** [comment]
Verified
