### ISSUE TITLE
[BUG]: Hardcoded values in Court Staff screens

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1787]
**Describe the bug**
The values of new summons issued  and  Orders Issued is always 40 new and 11 new

**To Reproduce**
<img width="1014" alt="Screenshot 2024-09-26 at 5 58 32 PM" src="https://github.com/user-attachments/assets/de2efb90-34bd-4523-9222-90924b6b02a5">

**Comment by shambhavigoel1002** [comment]
As per discussion the the Count to be totally removed . To avoid unnecessary api calls.

**Comment by Ramu-kandimalla** [comment]
Hi @rajeshcherukumalli  please test

**Comment by kashish384** [comment]
Hi @Ramu-kandimalla, verified in Dev[Sol].

- url: https://dristi-kerala-dev.pucar.org/digit-ui/employee/home/home-pending-task
- reference link: https://jam.dev/c/25d625ef-bf4b-4513-b37f-d5fcef0a672f
![image](https://github.com/user-attachments/assets/26149c15-e709-4065-891d-c0e35c76b27c)
- Test cases:
1.verify that for "Review Summons, Notices & Warrants" , no hardcoded values shown.
2.verify that for "View issued orders" , no hardcoded values shown.

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  Please verify and confirm
