### ISSUE TITLE
[Localisation]: Change Register Case to Forward to Judge

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1797]
**Describe the bug**
The judge is in charge of registering a case. Hence in FSO screen it should read Forward to Judge instead of Register Case

**To Reproduce**
Open a case in FSO Screen

V0.3

![image](https://github.com/user-attachments/assets/c8bc6072-bb29-49ed-bb33-410d0f12ec17)

**Comment by rajeshcherukumalli** [comment]
Hi @devarajd94 , the mentioned change is implemented for the FSO user,

Verify the case is admitted to judge with no errors
Verity the case is sent back if any errors are marked 
Verify the returned case is  forwarded to judge

Reference: 
![Screenshot from 2024-09-30 23-25-14](https://github.com/user-attachments/assets/0ca2f6cc-9b7f-4eda-bb9e-bd4550a79a8e)

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  Please verify and confirm

**Comment by devarajd94** [comment]
Verified
