### ISSUE TITLE
[BUG]: Notice PDF Issues

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1798]
**Describe the bug**
Check the comments in the attached PDF.

[1727683329141LNNhAaxDIF.pdf](https://github.com/user-attachments/files/17186373/1727683329141LNNhAaxDIF.pdf)

Please adhere to template. @manimaarans (Unable to tag ajith). Please cross check the template for QA testing @rajeshcherukumalli  

Template: https://docs.google.com/document/d/1WwJBOxotx6jwSaNT_iPgrQjiohLYdZoRDraZlZzwhgs/edit#heading=h.4emgxvs3m6c

**Comment by devarajd94** [comment]
@Ajith-beehyv @manimaarans please provide an update on this ticket as this is priority for tomorrow mornings demo

**Comment by kashish384** [comment]
Its working fine for 'Notice to Accused' template, verified in **QA[sol] env.**
recent:///a3edfd6662a239d467a27b4d66feb388

**Comment by kashish384** [comment]
Its working fine for 'Notice to Accused' template, verified in **UAT env.**
[1728038485326KTDSWFjYGG.pdf](https://github.com/user-attachments/files/17257469/1728038485326KTDSWFjYGG.pdf)
