### ISSUE TITLE
[BUG]: Mark as Sent not working

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1799]
**Describe the bug**

- [x] Mark as Sent not working in the courtstaff screen for marking summons sent.
- [x] SENT_NOTICE_VIA_POST to be renamed as Send Notice via Post

**To Reproduce**
https://drive.google.com/file/d/1nEdx03idvwmz1cRgCsvoGVpN2c4tgMpt/view?usp=sharing

V0.3

**Comment by TusharKatiyar2002** [comment]
Hi @devarajd94 , can you try again, use new creds for courtStaff (uatCourt01). Updated the same in the role sheet also.

**Comment by devarajd94** [comment]
Verfied
