### ISSUE TITLE
[BUG]: Case PDF creation failing

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1801]
**Describe the bug**
Case PDF creation failing

Login details: Advocate: 9447155992

**To Reproduce**

1. Upload a file greater than 50 MB in any one of the fields
2. Then error message pops up
3. Upload another file and go till the end of filing. The issue may be noticed

https://github.com/user-attachments/assets/7e9b9cbf-27d6-4996-a926-c0e1344ba8ee

**Comment by Ajith-beehyv** [comment]
@devarajd94   i tried uploading a 50 MB file got error, then re uploaded peoper file in bounced cheque/  But not able to re produce error.  I triesd in dev.

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  this issue is not reproducible
