### ISSUE TITLE
[BUG]: Random Document Submission screen popping up

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1802]
**Describe the bug**
Random Document Submission screen popping up when case is opened from advocate screen

**To Reproduce**

https://github.com/user-attachments/assets/7983e212-e51f-4e92-96c8-677dbe55b615

**Comment by kashish384** [comment]
verified in **QA[sol] env**, its working fine.
https://jam.dev/c/c1769855-221d-4e4f-a59d-b1485e099f16

**Comment by Mahesh-Vishwanath1** [comment]
It is working as expected in the UAT solution environment.
reference link: https://jam.dev/c/8c708268-24a9-4dfe-a5ba-e3b5ecfc3df1

**Comment by devarajd94** [comment]
Verified
