### ISSUE TITLE
[BUG]: Pending Task for summons not created for advocate

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1803]
**Describe the bug**
Pending task for summons/notice not created in the advocate screens

**To Reproduce**
https://drive.google.com/file/d/1najGBxpgJQNCaP2SjcBalfSctsQxXryU/view?usp=sharing

**Comment by SureshSoren** [comment]
Hi @devarajd94 , This issue is occurring because the same Bar Registration Number is associated with different advocates. As a result, when we search for an advocate using the mapped bar registration number, the pending task is being assigned to the wrong user.

**Comment by SureshSoren** [comment]
When we will restrict duplicate advocate bar registration number this issue won't occur.

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  Issue occurred due to BAR registration validation bypassing

**Comment by devarajd94** [comment]
Verified
