### ISSUE TITLE
UAT | Pending Task Localization

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#1804]
Localization of Case name not appearing in Pending Taks

![Image](https://github.com/user-attachments/assets/dc740e54-e0a5-485f-ab29-0326530cdde0)

**Comment by TusharKatiyar2002** [comment]
Hi @Taherabharmal  Can you please provide more context for this?
The case name is made with this name only it seems.
cc:- @Ramu-kandimalla

**Comment by Taherabharmal** [comment]
this is not an issue
