### ISSUE TITLE
UAT| after online payment failed_offline case filing fee shown as 0

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#1812]
https://jam.dev/c/c7fc7849-a9c5-4635-ba37-1af59a0b8d2f

**Comment by TusharKatiyar2002** [comment]
@kashish384 , can you add network calls also in video not able to reproduce on my end

**Comment by kashish384** [comment]
Working fine

![image](https://github.com/user-attachments/assets/273f727e-85b1-4f69-9730-0296bffc40dd)

**Comment by kashish384** [comment]
Working fine in **UAT env.**
Test case: Verified that after online payment failed_offline case filing should not fee shown as 0 .

![image](https://github.com/user-attachments/assets/ea54e749-f57a-4540-ace6-d98fa533c4ac)

**Comment by devarajd94** [comment]
Verified
