### ISSUE TITLE
UAT| pending task not created for FSO, after case returned from Judge.

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#1813]
https://jam.dev/c/591547f6-520b-40a5-a129-579dc326f72d

**Comment by vaibhavct** [comment]
For cases, backend is creating pending task based on roles and workflow.
@nileshkg  @manimaarans Can you please look into this once?

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  please confirm

**Comment by kashish384** [comment]
Its working fine.
![image](https://github.com/user-attachments/assets/e48edc30-f53f-4028-abb6-ca1457a3330d)
Test cases:
1.verified that judge able to returned case to citizen.
2.verified that citizen able to do correction & submit case to FSO.
3.verified that FSO able to Forward the case to judge.

**Comment by kashish384** [comment]
Its working fine in **UAT env.**

**Comment by kashish384** [comment]
https://jam.dev/c/7073fa3c-dc24-47d9-99d2-826ce57b2f31

**Comment by nileshgupta111** [comment]
@kashish384 can you retest mdms is updated

**Comment by kashish384** [comment]
Its working fine in UAT env.
https://jam.dev/c/6584cd7e-3d3e-4733-a14e-737768b4e19f
