### ISSUE TITLE
UAT | Treasury Integration for Registered Post

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#1814]
Court Fees Payment for Registered post is still bypassed.
1) clicking on Pay Online should redirect to online payment gateway.
Currently, it is auto-collecting payment.
2) Payment Fees is reflected as 0
3) Clicking on Print Receipt does not generate a receipt

**Comment by shambhavigoel1002** [comment]
Hi @Taherabharmal About this by passing of etreasury has been done as per discussion due to the pending integration of sbi payment gateway . This issue will be sorted and aligned as soon as it is done. 
cc:_ @Ramu-kandimalla  @anirudh-0

**Comment by shambhavigoel1002** [comment]
Hi @rajeshcherukumalli  made the changes related to payment amount please check.
cc- @Ramu-kandimalla

**Comment by kashish384** [comment]
Issue still there in **UAT env.**
![image](https://github.com/user-attachments/assets/25d6ab4d-4435-482c-b27e-4fc127738c50)
https://jam.dev/c/d4758fc0-4b98-4d37-9898-84cfcfb22d34

**Comment by kashish384** [comment]
verified in **QA[sol] env**., **Not** working as expected.
https://jam.dev/c/1592ff9c-0c04-45c3-ba73-ab96162fe529

**Comment by Ramu-kandimalla** [comment]
Hi @Taherabharmal  We have  ticket logged by Devaraj for SBI Epost integration  [Refer](https://github.com/pucardotorg/dristi/issues/1516)
