### ISSUE TITLE
UAT| for schedule of hearing date- e-sign not working.[Inconsistent issue]

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#1815]
https://jam.dev/c/241f4d32-a257-4bf6-8a77-80be433568ca

**Comment by ashishbeehyv** [comment]
hi @kashish384 i am not able to reproduce this issue. cc: @Ramu-kandimalla

**Comment by Ramu-kandimalla** [comment]
Hi @kashish384  Please try to reproduce the issue and share the details to @ashishbeehyv

**Comment by kashish384** [comment]
@ashishbeehyv , please look on this.
https://jam.dev/c/720c39f9-2bdf-45fd-a8fb-bfeecff594a9

**Comment by kashish384** [comment]
Test cases: verify that for schedule of hearing date- e-sign working.

**Comment by ashishbeehyv** [comment]
hi @kashish384  I am not able to debug the issue because it is not reproducible and it is happening very infrequently. cc: @Ramu-kandimalla

**Comment by kashish384** [comment]
Its working fine in **UAT env.**
https://jam.dev/c/c1fe30a1-861a-454c-bb16-fc529cb4d1ba
