### ISSUE TITLE
UAT| Payment for Notice/summons via post_in Delivery Channel -Post (undefined, undefined, undefined, undefined, undefined)

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#1816]
![image](https://github.com/user-attachments/assets/e66914a0-f43f-4f46-a9c9-181903269859)
https://jam.dev/c/ed1ecb1d-2bac-46b9-9726-c28147b5e588

**Comment by vaibhavct** [comment]
@kashish384  I looked into your filingNumber and the pending task has been closed.
Can you please provide a filing number where this issue persists or tell me how I can reproduce it?
c.c. @anirudh-0

**Comment by kashish384** [comment]
@vaibhavct while generate notice & summons select all the channels like_post,email,sms,police,then if you go for pay__online you able to see for __post(undefined, undefined, undefined, undefined, undefined).

**Comment by kashish384** [comment]
Hi @vaibhavct,please look on this
![image](https://github.com/user-attachments/assets/f70c23d9-a0ee-480e-9742-2861459d09bb)
https://jam.dev/c/943c9b8c-9428-477b-84ac-fd30b888af5f

**Comment by vaibhavct** [comment]
@kashish384 I've merged my changes in uat-v0.3 branch which is deployed in qa env.
Can you once check there?
We're merging changes in uat only after it's been tested in qa env

**Comment by kashish384** [comment]
Test cases: Verify that, Payment for Notice/summons via post_in Delivery Channel -Post should not be (undefined, undefined, undefined, undefined, undefined).

**Comment by kashish384** [comment]
Its working fine in **UAT env.**
![image](https://github.com/user-attachments/assets/36f5fc27-6241-49dd-9ae8-54147b6da8b3)
