### ISSUE TITLE
UAT| Payment for Notice/summons via Email / iCops /SMS showing zero rupees(

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#1817]
Summons__https://jam.dev/c/a1ab60e2-073b-4969-a04d-064ac54602f6
![image](https://github.com/user-attachments/assets/4cc02bc9-0c4f-4aae-92da-24c6b2bcc6fe)

Notice__https://jam.dev/c/bba55114-3d91-4bfd-80f2-408afea8d128
![image](https://github.com/user-attachments/assets/75af9472-e37b-43c5-875a-bcab285c523b)

**Comment by TusharKatiyar2002** [comment]
@Ramu-kandimalla this is a backend issue. While fetching channelId from taskDetails, sometime I am getting taskDetails as object sometime as a JsonString

**Comment by kashish384** [comment]
Its working fine in QA[sol] env.
1.Verified that Summons iCops Court Fee should not be zero.
![image](https://github.com/user-attachments/assets/1fe58062-b697-4332-a7ee-9c2b4a8bf051)
2.Verified that  Summons Email Court Fee should not be zero.
![image](https://github.com/user-attachments/assets/21041ce4-d199-4973-987c-1815aead77a9)
3.Verified that  Summons SMS Court Fee should not be zero.
![image](https://github.com/user-attachments/assets/c179113e-a9dd-4f09-a7bc-7145bb398e77)

4.Verified that Notice SMS Court Fee should not be zero.
![image](https://github.com/user-attachments/assets/7ee31243-5f76-44f9-9a47-cd4e457fc112)
5. Verified that Notice Email Court Fee should not be zero.
![image](https://github.com/user-attachments/assets/12f365ec-37fa-40b8-9b09-acc2ce778e7b)

**Comment by kashish384** [comment]
Its working fine in **UAT env.**
![image](https://github.com/user-attachments/assets/519f180c-5507-4fc4-b7e4-e54f2cfd4486)

**Comment by devarajd94** [comment]
Verified
