### ISSUE TITLE
UAT| IF we complete the payments for Summons ,Notice  by online still the payment details are displaying for nayamitra user

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#1818]
https://jam.dev/c/08d20844-58ef-4edc-b82c-48d2ef5cdcd9
![image](https://github.com/user-attachments/assets/e6f8d779-60d8-415b-b498-c73edd5f17d1)

**Comment by vaibhavct** [comment]
@kashish384 
It was discussed in the standup itself that for now, when we're doing online payment for summons or notice, the demand will always remain on Nyaymitra.
It will be removed once proper end to end online payment integration is done
c.c. @Ramu-kandimalla @rajeshcherukumalli

**Comment by Ramu-kandimalla** [comment]
Hi @kashish384  @rajeshcherukumalli  We have same ticket logged by Client. i'm closing this ticket
