### ISSUE TITLE
UAT| judge_parites shown as N/A. 

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#1819]
![image](https://github.com/user-attachments/assets/30cad4ba-3ef1-467e-abc6-c98b264faaca)

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  please confirm

**Comment by vaibhavct** [comment]
Schedule of Hearing - Name of parties required to attend that hearing
Schedule Next Hearing - Name of parties required to attend that hearing
Warrant - warrantFor person
Notice - noticeFor person
summon - SummonsFor person
Order for Mandatory Submission - submissionParties and Respondent Parties
Order Section 202 CRPC - detailsSeekedOf

Order for Bail - partyName for which the submission was made
Voluntary Accept - partyName for which the submission was made
Voluntary Reject - partyName for which the submission was made
Reject Reschedule Hearing Request - partyName for which the submission was made
Checkout Rejection - partyName for which the submission was made
Others Order - All the parties
Transfer to ADR - All the parties
Initiate Reschedule - All the parties
Judgement - All the parties
Order of Case Settlment - All the parties
Order of Case Withdrawal - All the parties
Order of Case Transfer - All the parties
ASSIGNING_DATE_RESCHEDULED_HEARING - All the parties
Reschedule of Hearing Date - All the parties
Checkout Acceptance - All the parties
Submission Extension - All the parties

@rajeshcherukumalli @Ramu-kandimalla  @anirudh-0 
These are the orderTypes and respective parties for the same. Kindly take a note

**Comment by Beehyv-Vinod** [comment]
Hi @Ramu-kandimalla  @rajeshcherukumalli , Tested in QA env, Facing the issue's in Orders flow, will check & will confirm once the issues are fixed, below are the issue link for the references,    

https://github.com/pucardotorg/dristi/issues/1918   
https://github.com/pucardotorg/dristi/issues/1917

**Comment by kashish384** [comment]
1. Verified that parties name is displayed.
Test cases:
https://docs.google.com/document/d/1VWn0Ev_pQKbPcfMNIP01EqGaWUj6bMTi_5Bi2du3Uro/edit?tab=t.0

**Comment by kashish384** [comment]
Verified in UAT env, Working a Expected
https://jam.dev/c/04775488-d843-481c-b0a4-a4b2f55714b2
https://jam.dev/c/ca04797b-e557-449d-90bf-8b564f95c345
