### ISSUE TITLE
UAT | Issues with Notice

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#1821]
1) 6 DIGIT Code not published
![Image](https://github.com/user-attachments/assets/910db51c-859f-47fd-bdfc-48605658ff4b)

**Comment by vaibhavct** [comment]
@Ramu-kandimalla 
Since @Ajith-beehyv has worked on notice pdfs, assigning ticket to him and unassigned Suresh.

**Comment by kashish384** [comment]
Its working fine in **UAT env.**
![image](https://github.com/user-attachments/assets/fc0846a4-7973-4a4a-81c7-609ec52bf54e)

**Comment by devarajd94** [comment]
Verified
