### ISSUE TITLE
UAT | Localization Missing | E-sign Completed of Notice by CMO

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#1823]
Localization missing in following screen:
![Image](https://github.com/user-attachments/assets/4b6e450e-f41d-43b7-ba4a-f95dbb997008)

Correct Message;
Notice Signed successfully.

**Comment by kashish384** [comment]
Test case: verified that SUCCESSFULLY_SIGNED_NOTICE message displayed.
![Image](https://github.com/user-attachments/assets/cbdfb7b8-0b33-42ef-aef0-465fdd6b177b)

**Comment by devarajd94** [comment]
The message should be 'Notice Signed successfully.' @kashish384 @nitish-beehyv. Please correct this

**Comment by maruthiPhanendra** [comment]
![image](https://github.com/user-attachments/assets/de093862-ca0f-4126-93ac-189810f8fdb6)
hi @devarajd94 , can you please verify the updated text

**Comment by kashish384** [comment]
its working fine **QA[sol] env.**
![image](https://github.com/user-attachments/assets/90e97221-8a06-4fcc-a3ae-95f34a9e1425)
Test case: verified that mesaage should state Notice Signed successfully.

**Comment by kashish384** [comment]
its working fine **UAT env.**
![image](https://github.com/user-attachments/assets/7aa69422-8deb-46b9-9c72-f1995b5f5105)

**Comment by devarajd94** [comment]
Verified
