### ISSUE TITLE
UAT| court staff_mark as sent not working for warrent + summons + notices

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#1824]
https://jam.dev/c/2e80278d-4e91-4064-a598-c0cf98610e3e
![image](https://github.com/user-attachments/assets/974e20bb-8f23-4a04-b746-c15ed65cc504)

**Comment by Ramu-kandimalla** [comment]
Hi @rajeshcherukumalli  Please verify in Sol QA env

**Comment by kashish384** [comment]
Its working fine QA[sol] env.
![image](https://github.com/user-attachments/assets/22a5de61-9589-4d7e-be20-9fa3c3ad18b2)
test cases:
1. verified that user able to mark as sent for summons
2. verified that user able to mark as sent for notices
3. verified  that after mark as sent case lands on the sent minor tab.

**Comment by kashish384** [comment]
Its working fine **UAT env.**
![image](https://github.com/user-attachments/assets/a6d3fe17-c81b-4dcd-8d34-97066dc7e514)
