### ISSUE TITLE
UAT| Summons and Warrants Status_shown 'Channel' null & 'Remarks' N/A

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#1827]
https://jam.dev/c/971df370-bb1c-4c73-b746-060a7c9b9116
![image](https://github.com/user-attachments/assets/f5de188a-75d4-49ef-ab89-fb7bc66fae65)

**Comment by ashishbeehyv** [comment]
hi @kashish384  this issue is fixed now, and currently Remarks field will show N/A because we don't have corresponding data from back end currently. please test this. cc: @rajeshcherukumalli cc: @Ramu-kandimalla

**Comment by kashish384** [comment]
Its working fine in **QA[sol] env.**
![image](https://github.com/user-attachments/assets/b1fa3d8b-455c-4b17-89fb-2a3b315725f8)
test case: verified that for summons Status not shown as 'Channel' null.

**Comment by kashish384** [comment]
Its working fine in UAT env.
![image](https://github.com/user-attachments/assets/96e411f3-fd33-4841-94a3-ea046524c046)

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  Please verify and confirm

**Comment by devarajd94** [comment]
Verified
