### ISSUE TITLE
[BUG]: ESign on orders not working

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1829]
**Describe the bug**
ESign on orders not working

**To Reproduce**

https://github.com/user-attachments/assets/a7788b63-dad3-40df-992f-3dc9475c8ca5

**Comment by shambhavigoel1002** [comment]
Hi @rajeshcherukumalli Please recheck the issue.

**Comment by kashish384** [comment]
Its working fine in **UAT env.**
![image](https://github.com/user-attachments/assets/04e67fc7-9962-4d09-be2a-feac33be57f3)
https://jam.dev/c/e6b43324-aa75-4009-afa5-8fd72d46d5c4

**Comment by devarajd94** [comment]
Closing ticket as it is not reproducible
