### ISSUE TITLE
[Bug]: [User Registration] : [Logo Change]

### ISSUE THREAD

**Issue by muhammed-sawad** [pucardotorg/dristi#1832]
**Describe the bug**
Logo to be updated to the emblem of Satyamev Jayate & then OnCourts logo. This should be in all screens - citizen and employee

**Expected Result**
Upload the following Oncourts logo in the purple box shown below
https://drive.google.com/file/d/1eFYgzacSnFmMfUERb-bE2DcxyqFON8as/view?usp=sharing

![Crafting_ON_24x7_final](https://github.com/user-attachments/assets/4dd05add-14f1-4443-9eed-87d8ee93231d)

![image](https://github.com/user-attachments/assets/25b514cc-fe9c-441e-8b7c-52aafecfa1d3)

**Comment by utpalBeehyv** [comment]
hi @devarajd94 , it is resolved 
![image](https://github.com/user-attachments/assets/a75b924b-f421-46bd-b082-f78df18560a7)


cc : @Ramu-kandimalla
