### ISSUE TITLE
[BUG]: [User Registration] : [Location not fetching accurately]

### ISSUE THREAD

**Issue by muhammed-sawad** [pucardotorg/dristi#1838]
**Describe the bug**
Location not fetching accurately. It is showing about 18 km difference when we register from Hyd Office

**Expected behavior**
Location should be taken accurately

**Screenshots**
![image](https://github.com/user-attachments/assets/c52326d4-f898-486b-9dfc-6f56b47c31c1)

**Comment by devarajd94** [comment]
It is accurate in Kerala
