### ISSUE TITLE
[BUG]: [User Registration] : [Font and sentence change under Your registration is waiting approval]

### ISSUE THREAD

**Issue by muhammed-sawad** [pucardotorg/dristi#1849]
**Describe the bug**
"Bold title: ""Your registration is awaiting approval"" in bold
Next line: Your registration number is (ID: XXX) is in progress 
You will receive an SMS confirmation within 24 hours with the approval status."

**Screenshots**
![image](https://github.com/user-attachments/assets/e016f2be-b84b-4822-a059-f8873197d514)

**Comment by Ramu-kandimalla** [comment]
CLosing this ticket since its duplicate tickets
