### ISSUE TITLE
|BUG|User Registration |Change the text disclaimer which comes after registration 

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#1870]
**Describe the bug**
For Advocate user registration, Change the text,"Your registration (ID: KL-ADV-000018-2024).is in progress. It takes 2-3 days for verification. You'll get an SMS when it's done." change to "Your registration (ID: KL-ADV-000018-2024) is in progress. You will get an SMS when it's done."

**To Reproduce**
After filing and completing the registration.

**Expected behavior**
"Your registration (ID: KL-ADV-000018-2024) is in progress. You will get an SMS when it's done."

Screenshot
![image](https://github.com/user-attachments/assets/06c4450b-cd20-4f38-95a8-27187b0d48dd)

**Comment by devarajd94** [comment]
@Ramu-kandimalla please take up this change. This is a judge feedback

**Comment by utpalBeehyv** [comment]
hi @rajeshcherukumalli changes are done.
![Image](https://github.com/user-attachments/assets/b8736256-a81a-4b41-911d-008e9f19ece1)


cc : @Ramu-kandimalla

**Comment by devarajd94** [comment]
Verified
