### ISSUE TITLE
Writing a Test cases for E-filing, Scrutiny and Admission , Pending Tasks

### ISSUE THREAD

**Issue by krishnaprasadsannidhi** [pucardotorg/dristi#188]
This testcase document includes the following workflows -:
1) Efiling (When user wants to file a case)
2) Scrutiny
3) Admission
4) SMS Notification

**Comment by Amityadav012** [comment]
Please refer to the test cases for  E-filing.


[E-filing test cases.xlsx](https://github.com/pucardotorg/dristi/files/15220880/E-filing.test.cases.xlsx)
