### ISSUE TITLE
|Bug|Nyaymitra|Payment fail for Demand Draft & Cheque

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#1886]
**Describe the bug**
"Payment Failed for some reason when selected ""Cheque"" & ""Demand Draft"" - why?? 
for some cases. Only Cash was fully done right and the amount reflected different numbers at different steps."

**To Reproduce**
1.Login Nyaymitra'
2. Click on Cheque/stamp for payment

**Expected behavior**
The payment should process

**Screenshots**
![payment](https://github.com/user-attachments/assets/48401f43-d032-4daf-bec5-dd8225a02f96)

**Comment by devarajd94** [comment]
Verified in UAT
