### ISSUE TITLE
UAT | E-filing| View on map not working_Advocate

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#1892]
https://jam.dev/c/32bb72b5-d36c-44ed-81ad-b38acb832f5a

**Comment by ashishbeehyv** [comment]
hi @kashish384 this is fixed. please test it in QA. cc: @Ramu-kandimalla

**Comment by kashish384** [comment]
Verified in **QA [sol] env,** its working fine.
https://jam.dev/c/ebf21ad9-3644-432e-99bd-465c5122103c

**Comment by kashish384** [comment]
Verified in **UAT env,** its working fine.
https://jam.dev/c/1d2d2b25-ea12-4b71-9209-6f28eea73978
