### ISSUE TITLE
UAT| Court staff_for add signature page_localisation issue.

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#1897]
Issue 1.change as per releated task_it should be Notice Document [task related to Notice]
![image](https://github.com/user-attachments/assets/f5992d44-5446-4143-883a-96db0dad9487)
https://jam.dev/c/d332b749-5e0d-4a28-937b-966d91306eb1

Issue 2.change as per releated task_it should be Warrent Document [task related to Warrent]
![image](https://github.com/user-attachments/assets/54dfeb2a-cb1f-44cc-bcc3-427288d01b95)
https://jam.dev/c/4fcdacd2-a5fb-4f26-8b0c-69b1634f9241

**Comment by maruthiPhanendra** [comment]
updated the localization ,can you verify it @kashish384 
cc @Ramu-kandimalla

**Comment by kashish384** [comment]
still issue is there in **UAT env.**[for freshj user]
Issue 1:
![image](https://github.com/user-attachments/assets/5792c4a0-613e-4b81-9d21-7c26e43275d1)
Issue 2:
![image](https://github.com/user-attachments/assets/469ffb14-93c4-4057-a08c-228cc7af6b08)

**Comment by kashish384** [comment]
verified in **QA[sol] env.**, its working fine.
Issue 1:
![image](https://github.com/user-attachments/assets/cac6831d-3d77-45b4-853b-37a5dff15156)
Issue 2:
![image](https://github.com/user-attachments/assets/63f8a91f-c7d2-4284-88a3-b8236b094fbb)
*for summons task_
![image](https://github.com/user-attachments/assets/bea4ae80-af9a-4ff0-8365-5738b54d4d00)

**Comment by kashish384** [comment]
verified in **UAT env**., its working fine.
Issue 1:
![image](https://github.com/user-attachments/assets/206c6e63-c907-4dce-b345-2c61268a03ac)
Issue 2:
![image](https://github.com/user-attachments/assets/9847463e-30f4-43de-a9a9-8b6795263552)
*for summons task_
![image](https://github.com/user-attachments/assets/e04f8419-3338-4ba5-9905-f1069080b807)
