### ISSUE TITLE
UAT| Court staff_for Print & Send Documents page_localisation issue.

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#1898]
Issue 1.change as per releated task_it should be: Summons Document.[task related to summons]
![image](https://github.com/user-attachments/assets/4b94d08d-c511-4ab9-863f-9b3997eed909)

Issue 2.change as per releated task_it should be: Notice Document.[task related to Notice]
https://jam.dev/c/b7759729-f535-4764-811b-9d067a32d0d1

Issue 3.change as per releated task_it should be: warrent Document.[task related to Warrent]
https://jam.dev/c/e0d18777-06f8-41b3-9397-b9377f47b878

**Comment by maruthiPhanendra** [comment]
updated the localization ,can you verify it @kashish384 
cc @Ramu-kandimalla

**Comment by kashish384** [comment]
still issue is there in **UAT env.**[for freshj user]
Issue 1: this is fixed
![image](https://github.com/user-attachments/assets/2d23fdb7-08d3-469a-84c5-a19ce262e715)

Issue 2: this is fixed
![image](https://github.com/user-attachments/assets/79d849a3-13a4-4ef0-b10c-29f673c26d57)

**Comment by kashish384** [comment]
still issue is there in **UAT env.**
Issue 3:
![image](https://github.com/user-attachments/assets/09d29d95-bf9e-40ce-9f41-b9e20583ea45)

**Comment by kashish384** [comment]
verified in **QA[sol] env.**, its working fine.
Issue 1:
![image](https://github.com/user-attachments/assets/b243b1d0-6d37-4be1-acee-c372b70a1fef)
Issue 2:
![image](https://github.com/user-attachments/assets/79f53d00-6523-4113-a788-5020dfd646c2)
Issue 3:
![image](https://github.com/user-attachments/assets/fe5f7c79-e29b-482f-8884-0aa9c983c2a0)

**Comment by kashish384** [comment]
verified in **UAT env.**, its working fine.
Issue 1:
![image](https://github.com/user-attachments/assets/f3fd9236-9b80-4928-b341-e37d9ac0dc6a)
Issue 2:
![image](https://github.com/user-attachments/assets/4cf8ea3d-6a02-4a53-9df0-257d285ece22)
Issue 3:
![image](https://github.com/user-attachments/assets/56d43f4a-4da4-4dad-936c-721045569d7d)

**Comment by kashish384** [comment]
verified in **UAT env**., its working fine.
Issue 1:
![image](https://github.com/user-attachments/assets/3492720e-dc25-49e9-bdf5-c2c31b5fa8cb)
Issue 2:
![image](https://github.com/user-attachments/assets/334e1268-529a-4065-82a1-60b7390e6b3e)
Issue 3:
![image](https://github.com/user-attachments/assets/c094f12d-73f3-4cc5-866f-abf4ecbba840)

**Comment by devarajd94** [comment]
Verified
