### ISSUE TITLE
UAT| Court staff_Review Document _______ Document_localisation issue.

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#1899]
Issue 1.change as per releated task_it should be : Review Document **Warrent** Document  [task related to Warrent]
![image](https://github.com/user-attachments/assets/7eff6108-f390-400b-bbc5-4a4351ffed46)
https://jam.dev/c/7a2c03a3-b765-4aa6-a50e-b2092b5dc80a

Issue 2.change as per releated task_it should be : Review Document **Notice** Document  [task related to Notice]
![image](https://github.com/user-attachments/assets/434e0b3f-408b-4140-9dc1-b921195f50d6)
https://jam.dev/c/188dd9c0-dc78-4ba0-aec1-878c12447307

**Comment by maruthiPhanendra** [comment]
updated the localization ,can you verify it @kashish384 
cc @Ramu-kandimalla

**Comment by kashish384** [comment]
still issue is there in **UAT env.**[for freshj user]
Issue 1
![image](https://github.com/user-attachments/assets/e4d39758-f38e-4027-8373-08242d0862a5)
Issue 2.
![image](https://github.com/user-attachments/assets/79933288-95b0-48d4-828e-1a979aa7cb9b)

**Comment by kashish384** [comment]
verified in **QA[sol] env.**, its working fine.
Issue 1:
![image](https://github.com/user-attachments/assets/43b2edc9-168a-4a5c-90a2-c5a55e5eae33)
Issue 2:
![image](https://github.com/user-attachments/assets/31716b4d-deb0-48ef-af35-53515859e7f6)
*for summons task_
![image](https://github.com/user-attachments/assets/39b97c27-fc86-4017-9713-e7677481cfe6)

**Comment by RohiniKanala517** [comment]
This issue has been fixed in UAT. 
Issue 1,
![Image](https://github.com/user-attachments/assets/6d94306f-f12b-4b59-a240-a0346c8831de)

Issue 2,
![Image](https://github.com/user-attachments/assets/872d2eb8-4e5e-4490-b76a-680e1437c975)

Issue 3,
![Image](https://github.com/user-attachments/assets/38872940-9fbd-43c7-9411-e22cc59de058)

**Comment by kashish384** [comment]
*verified in **UAT env**, its working fine.
Issue 1:
![image](https://github.com/user-attachments/assets/f04cadde-924a-4a70-80d6-b28383b684e5)
Issue 2:
![image](https://github.com/user-attachments/assets/e21a40a3-5bdb-4879-bc39-07dbe29d7e24)
*for summons task_
![image](https://github.com/user-attachments/assets/04067a7f-1cfb-45d2-95c9-345d63237739)
