### ISSUE TITLE
UAT| court staff_for 'warrent task' after mark as sent, not able to see warrent task in sent minor tab.

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#1900]
https://jam.dev/c/8004d918-f2bb-4fda-ae14-6ad510614905
![image](https://github.com/user-attachments/assets/3ed63440-d58c-4aa8-bedc-6af7565d4638)

**Comment by TusharKatiyar2002** [comment]
Hi @rajeshcherukumalli , can you plz confirm it

**Comment by kashish384** [comment]
verified in **QA[sol] env**, its working fine.
![image](https://github.com/user-attachments/assets/359c9f48-2234-4ca0-b424-923b359d81dd)
