### ISSUE TITLE
UAT| Citizen_for summons not able to see icops_for online payment.

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#1901]
![image](https://github.com/user-attachments/assets/d2820140-3c21-4fbb-b01a-98b877ec4e24)

**Comment by prasanna2400** [comment]
@Ramu-kandimalla  pending task is not created for icops, this is generated on ui side please assign it to respected dev.

**Comment by TusharKatiyar2002** [comment]
Hi @kashish384 plz check this

**Comment by kashish384** [comment]
*verified in QA[sol] env, its working fine.
![image](https://github.com/user-attachments/assets/65f3eee2-1221-431b-8688-2f5c94e5c130)

**Comment by kashish384** [comment]
*verified in **UAT env**, its working fine.
![image](https://github.com/user-attachments/assets/f3345435-b1a5-4cec-9741-e602b7da7079)

**Comment by devarajd94** [comment]
Verified
