### ISSUE TITLE
[BUG]: Size of the un selected language text needs to be smaller

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1910]
**Describe the bug**

- [ ] Size of the un selected language text needs to be smaller on the landing page
- [ ] Center align the english text

**To Reproduce**
![image](https://github.com/user-attachments/assets/d9d4898e-9713-485c-8378-43eee915bb34)

**Comment by maruthiPhanendra** [comment]
![Image](https://github.com/user-attachments/assets/e3a8360c-8b91-4bfc-948b-39107a058e1b)
![Image](https://github.com/user-attachments/assets/6ae67f54-99f2-4ff1-a323-d095488a1fb5)

**Comment by Mahesh-Vishwanath1** [comment]
Hi @maruthiPhanendra @shambhavigoel1002, when selecting the English language option, the text size appears inconsistent. I have verified this issue on both Chrome and Edge browsers in Windows. Can you please check and resolve this?
![Image](https://github.com/user-attachments/assets/432ce653-32da-4734-8279-cb8c941a54a8)
![Image](https://github.com/user-attachments/assets/e3dd2967-c7f1-411d-b36c-9b81fd938879)

**Comment by Mahesh-Vishwanath1** [comment]
Hi @Ramu-kandimalla, I have verified this ticket in the QA solution, and based on our discussion, it is functioning as expected.

URL: https://dristi-kerala-qa.pucar.org/digit-ui/citizen/select-language
Test Cases:
1. verify that the text size for unselected languages on the landing page is smaller and ensure that the languages are centre aligned.
a. When we select the English language result in the below screen shot
![Image](https://github.com/user-attachments/assets/d9ab7bd9-cc66-4972-8fae-fecf22a142ba)
b. When we select the Malayalam language result in the below screen shot
![Image](https://github.com/user-attachments/assets/79188061-61b6-4e05-9d82-1ec8840966cf)

**Comment by devarajd94** [comment]
Verified
