### ISSUE TITLE
UAT Bug | OTP for Aadhar

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#192]
Module: User Registration
User: Litigant/Advocate

Issue: During registration, once the user enters Aadhar Card for Verification, the user is redirected to a screen for OTP. The OTP screens displays the mobile number.

Image: 
![Image](https://github.com/pucardotorg/dristi/assets/132061840/7de9957b-bf75-4085-882a-71dc26e2cd73)

Expected behaviour:
The text states "Enter OTP sent to the mobile number registered to your aadhar"

**Comment by Vanshikajain02** [comment]
Working fine in dev environment now

**Comment by Taherabharmal** [comment]
This is still open.
This now shows as 'undefined'


![Image](https://github.com/user-attachments/assets/52933d20-f7ae-474b-bad4-b1cac05948e7)

**Comment by Beehyv-Vinod** [comment]
Tested in QA Working fine, 
Ref, https://jam.dev/c/82544cdd-b739-4677-a1c2-a41ffc6f4283
