### ISSUE TITLE
[BUG]: Notice not visible on the Court Staff

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#1922]
**Describe the bug**
Payment made by advocate. But notice not visible in the Court Staff screen
Case Details: 
Filing No.KL-000151-2024

**To Reproduce**
https://drive.google.com/file/d/1AAqT6fAYpCBDUwu6SoWz9sgvUhvkA3lU/view?usp=sharing

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  we tried not able to reproduce the tickets

**Comment by devarajd94** [comment]
Closing as the issue could not be reproduced
