### ISSUE TITLE
[BUG]: [QA| Screen UI Issue for view case]

### ISSUE THREAD

**Issue by rajeshcherukumalli** [pucardotorg/dristi#1932]
**Describe the bug**
Once we scrolled down in the view case the details are over laped on the screen
![Screenshot from 2024-10-09 01-43-03](https://github.com/user-attachments/assets/c4d5efba-566d-4be8-bd5f-f5d7e0ce5f31)

**Comment by Beehyv-Vinod** [comment]
Hi @rajeshcherukumalli  @Ramu-kandimalla  Tested in QA env Working fine
