### ISSUE TITLE
BUG || CSS Issues in Join Case flow

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#1938]
Css issue in submit button, shown in Submit response for Accused Advocate 

![Image](https://github.com/user-attachments/assets/6fcb2897-412b-49c4-a814-373026eeaa86)

**Comment by bhuvanyuguru** [comment]
Hi @nitish-beehyv please look into this issue.

**Comment by bhuvanyuguru** [comment]
Bug not fixed till Now 

CC: @nitish-beehyv @anirudh-0 


![image](https://github.com/user-attachments/assets/21f759cc-c1db-41d7-8031-041da6230b4b)

**Comment by bhuvanyuguru** [comment]
HI @nitish-beehyv please look into these CSS Issues in Join case flow. 

2. Verify with OTP button if Accused Litigant is not registered.

![image](https://github.com/user-attachments/assets/dfeacbef-ebb4-4125-ab4c-db6f275f5eb0)


3. Verify with OTP modal box
![image](https://github.com/user-attachments/assets/f91b824d-b466-495b-9e27-8d2f19337574)


4. Register Respondant button after OTP screen 
![image](https://github.com/user-attachments/assets/f75fff38-e2b0-4d0c-a5cf-cc2ca0836d36)


CC: @anirudh-0, @rajeshcherukumalli

**Comment by bhuvanyuguru** [comment]
Hi @nitish-beehyv 

CSS issue for submit button is fixed in QA 

![image](https://github.com/user-attachments/assets/5f1510ee-0740-4495-99ec-7cdec3e02441)

**Comment by Beehyv-Vinod** [comment]
1. Verify with OTP CSS issue is fixed
2. Submit Response CSS issue is fixed 
3. Register Respondent CSS issue is fixed
4. OTP CSS issue is not fixed @nitish-beehyv 
![image](https://github.com/user-attachments/assets/5dae1c93-1889-42cc-8200-00600eb7b6fe)
![image](https://github.com/user-attachments/assets/061e240d-e60c-4f5f-a7e7-f3a9f88a8457)
![image](https://github.com/user-attachments/assets/2ecbd7dd-09ea-4ab9-a81d-5a4f7bda1b96)
![image](https://github.com/user-attachments/assets/ba577655-d550-4a11-a669-772773fd5b35)

**Comment by nitish-beehyv** [comment]
Hi @Beehyv-Vinod otp modal ui fixed in dev and qa. Please verify it.

**Comment by bhuvanyuguru** [comment]
OTP Issue also fixed in UAT

![image](https://github.com/user-attachments/assets/d29ae459-15da-4a0e-b4c1-ddd23d807583)
