### ISSUE TITLE
[BUG]:Court staff_Review Document Summons/Notice/Warrant  Document  page,_'Issued to' & 'Channel Details' missing.[UAT]

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#1939]
**Expected behavior**
'Issued to' & 'Channel Details' details should be display

**Screenshots**
Summons :
![image](https://github.com/user-attachments/assets/0bc26f01-fcb7-4e9a-97d3-057e44e88afa)
Notice:
![image](https://github.com/user-attachments/assets/c72e43b7-fb9a-4a96-99f2-d38b016f0c92)
 Warrant :
![image](https://github.com/user-attachments/assets/b5544ecc-efa4-4bc0-ba44-8ebcb03a24aa)

**Comment by ashishbeehyv** [comment]
hi @kashish384 this is fixed. please test in QA. cc: @Ramu-kandimalla

**Comment by kashish384** [comment]
*verified in **QA[sol] env**, its working fine.
![image](https://github.com/user-attachments/assets/51bb597d-2725-47a5-a4e7-971a03a3e084)
![image](https://github.com/user-attachments/assets/9394178c-aae7-46dd-953b-4d65a6c6fb26)
![image](https://github.com/user-attachments/assets/4bb6dfe5-e4d8-450e-a8cb-59c393505a54)

**Comment by kashish384** [comment]
Its working fine in UAT env.
https://jam.dev/c/1dd06890-641c-4f27-a5a4-de63b87ead47
