### ISSUE TITLE
[BUG]: court staff_Localisation issue for Warrent.[UAT]

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#1942]
**Describe the bug**
Now: it showing_You have successfully sent notice via undefined.
it showing_ Notice document'

**Expected behavior**
Issue 1:It should be shown as 'Warrent Signed successfully'.
Issue 2: it should be shown as 'Warrent document'

reference link:
Issue 1: ![image](https://github.com/user-attachments/assets/2ddb20c3-5f3f-4b29-bb0d-5cb5c8b97009)
Issue 2: ![image](https://github.com/user-attachments/assets/afa24126-65be-478a-b09f-b7c6875b3e39)

**Comment by kashish384** [comment]
*verified in **UAT env,** **Not** working.
![image](https://github.com/user-attachments/assets/bcda32de-0c6c-4c11-9101-d1134182097e)

**Comment by ashishbeehyv** [comment]
hi @kashish384  this issue is fixed. can you please test this. cc: @Ramu-kandimalla

**Comment by kashish384** [comment]
Hi @ashishbeehyv verified in **QA[sol] env.** **Not** fixed.
https://jam.dev/c/0513dacb-7817-4133-853e-f36b30f0d34a

**Comment by kashish384** [comment]
*verified in **UAT env**, its working fine.
![image](https://github.com/user-attachments/assets/d29b99b4-e47d-4846-a0a7-3e91a99fde68)

**Comment by kashish384** [comment]
*verified in UAT, its working fine.
https://jam.dev/c/c8c6e908-440c-48c6-9846-f57870d61f07

**Comment by kashish384** [comment]
Its working fine in UAT env.
