### ISSUE TITLE
[BUG]: [UAT|In Accused details map is not loading ]

### ISSUE THREAD

**Issue by rajeshcherukumalli** [pucardotorg/dristi#1948]
https://jam.dev/c/d438b619-36b7-43e6-8b1d-a65706f8565f

**Comment by ashishbeehyv** [comment]
hi @rajeshcherukumalli this is fixed. please test in QA. cc: @Ramu-kandimalla

**Comment by RohiniKanala517** [comment]
Looks as expected now, please check
https://jam.dev/c/cc5d1be2-0379-4155-bdd0-7b26db34fd28
