### ISSUE TITLE
UAT Bug | Issue with Map

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#196]
Module: User Registration
User: Litigant/Advocate
Screen: Registration Details

Issue: 
1) On moving the PIN location in the map, the corresponding address in the 1) Field above map 2) Address Fields are not changing
2) On editing Pincode field, all other details remain as it.

Expected behaviour: 
1) When the PIN is moved in the map, the corresponding address in the 1) Field above map 2) Address Fields should change
2) On editing pincode field 1) all other details in the address field become blank  2) The Map should repoint to new pincode

**Comment by SureshSoren** [comment]
@Taherabharmal 
1. I need more clarity since it is working for me.
2. the google maps api that we are using doesn't have the functionality to give the address based on searching the pincodes.

cc: @manimaarans @krishnaprasadsannidhi

**Comment by Vanshikajain02** [comment]
Working fine in dev environment now

**Comment by Taherabharmal** [comment]
resolved
