### ISSUE TITLE
 [BUG]: Judge_Summons and Warrants Status_showing N/A for 'RPAD' [UAT]

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#1961]
reference link:
![image](https://github.com/user-attachments/assets/1c5878b1-bbe1-4006-a4d7-2db74b66b89b)

**Comment by ashishbeehyv** [comment]
hi @kashish384 this issue is fixed. can you please test this. cc: @Ramu-kandimalla

**Comment by kashish384** [comment]
verified in **QA[sol] env.** working fine.
![image](https://github.com/user-attachments/assets/779ae0d1-c070-4e44-94d4-623689b28859)

**Comment by kashish384** [comment]
Its working fine in UAT env.
