### ISSUE TITLE
UAT Bug | Remember me Functionality

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#197]
Module: User Registration

Issue: Remember me functionality does not remember the user

**Comment by SureshSoren** [comment]
@Taherabharmal need clarity on what is the expected behavior for this functionality.

**Comment by Taherabharmal** [comment]
@SureshSoren @Ramu-kandimalla this is still open
i see we have removed the remember me functionality altogether?

**Comment by Ramu-kandimalla** [comment]
The functionality was removed as per the design we are closing this issue
