### ISSUE TITLE
UAT Bug | Additional Details | Advocate Registration

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#198]
Module: User Registration
User: Advocate

Issue: 
On Selecting advocate, the user is redirected to Terms and Conditions and is shown that they have successfully been registered. Post this, an additional details page is displayed. This page is not viewable until refreshed.

Expected Behavior:
On selecting advocate, the user is redirected to:
- Additional Details page
- Once these details are captured, the terms and conditions page is displayed
-  Post this, the user is displayed success screen with message that Your registration will be approved shortly

Recording:

**Comment by SureshSoren** [comment]
@Taherabharmal  as per the current flow we are logging out the user when he selects Advocate or Advocate Clerk after Individual Registration then when user is re-login we are asking for additional details such as Bar Registration Number and Bar Council ID.

cc: @manimaarans @krishnaprasadsannidhi

**Comment by Taherabharmal** [comment]
resolved
