### ISSUE TITLE
Bug: Submission button missing in some cases

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#2003]
The Submission button is missing in some cases. Please update if there is any precondition to make submission?

https://github.com/user-attachments/assets/4f3cc40e-3792-414c-84a8-4d0734220d07

**Comment by nitish-beehyv** [comment]
Hi @devarajd94 after the investigating the above bug, I found that three advocates are present with the same bar registeration number("K/000000/0000"), because of that the different advocate uuid is saving in additional details of the representative.
cc: @vaibhavct @anirudh-0 @Ramu-kandimalla

**Comment by devarajd94** [comment]
Verified
