### ISSUE TITLE
[BUG]: [UAT] Judge _parites shown as [object Object].

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#2004]
reference link:
![image](https://github.com/user-attachments/assets/1cb53ac5-9e4c-4ecd-8f15-c1e13ec74586)

**Comment by vaibhavct** [comment]
@kashish384  I've deployed some changes regarding this in QA env which are yet to be merged in uat, hence these issues are coming. Once those changes are deployed in uat, this issue will be fixed (for new orders/submissions. For old ones it will remain as it is)
c..c @Ramu-kandimalla  @rajeshcherukumalli

**Comment by kashish384** [comment]
Its working fine in **QA[sol] env.**
![image](https://github.com/user-attachments/assets/6ac47c34-0bb8-43f3-a06d-66cfcd3e6b31)
