### ISSUE TITLE
Master Data promotion to stable environments

### ISSUE THREAD

**Issue by anirudh-0** [pucardotorg/dristi#2007]
Workflow, Localization and MDMS data updates are a manual operation and cause issues every release

**Comment by Ramu-kandimalla** [comment]
This script was tested in V.0.4  release and its working as expected, we still want to optimize the script for frequent releases

**Comment by atulgupta2024** [comment]
@Ramu-kandimalla  more than optimization, we need to clean up. We cannot go live with incorrect data. related ticket is #2268 

@suresh12  FTI. Should get addressed before go live

**Comment by Ramu-kandimalla** [comment]
Closing this ticket since we are using script to promote MDMS data
