### ISSUE TITLE
BUG || QA Unknown respondant shown in Parties

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#2009]
*In qa env, When we issue warrant, by default "warrant for party" field is coming as "Unknown Respondent", and on selecting this field, the parties field is also reflecting as same. 

![image](https://github.com/user-attachments/assets/46803f9b-628a-4d6b-9e93-a8e5c8ca6a16)

**Comment by iknoorkaur** [comment]
This bug is resolved in QA. 
Attaching the screenshot for reference.
![image](https://github.com/user-attachments/assets/11c30811-e87a-45d2-a6e4-d429e4abcd77)
