### ISSUE TITLE
[BUG]: Submission Order issuance by judge showing only complainant in dropdown

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#2010]
**Describe the bug**
Submission Order issuance by judge showing only complainant in dropdown. The Accused, their advocate have joined the case. Yet the list shows only complainant name.

**To Reproduce**
https://drive.google.com/file/d/15ZTZxdk4LtfgFE-kd5tCQXAmU3e821mN/view?usp=sharing

**Comment by ashishbeehyv** [comment]
hi @devarajd94  I am not able to reproduce this issue in UAT, can you share the steps to reproduce it. cc: @Ramu-kandimalla

**Comment by devarajd94** [comment]
Please use login: 9447155990 (Dasarathan - Advocate)
Case PA Saranya vs Xavier
@ashishbeehyv

**Comment by devarajd94** [comment]
Verified
