### ISSUE TITLE
BUG || Hearing Status in QA

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#2018]
**QA**

Describe the bug
After admitting a case, hearing changes from Start Now to Join Hearing

To Reproduce
1.Register a case from Judge user
2. Schedule Admission hearing and issue notice.
3. Admit a case
4. Check Hearing status

Expected behavior
Hearing status should not be changed.

![image](https://github.com/user-attachments/assets/674645cf-1355-4762-a4e3-40783cdde995)

**Comment by ashishbeehyv** [comment]
hi @bhuvanyuguru this is fixed. please test it. cc: @Ramu-kandimalla

**Comment by bhuvanyuguru** [comment]
Hi @ashishbeehyv this issue is Resolved in QA 

![image](https://github.com/user-attachments/assets/2f320330-06d2-408d-9381-9e1e3090d679)
