### ISSUE TITLE
[BUG]: QA|Application number not generating in proper sequence

### ISSUE THREAD

**Issue by Mahesh-Vishwanath1** [pucardotorg/dristi#2024]
Step to check the Issue:
1. Check the CMP number of the application.
2. Generate the application and ensure it is approved by the judge. The application number must be greater than the CMP number and unique.
 
Issue : The generated application number is less than the CMP number and is not unique.
![Image](https://github.com/user-attachments/assets/8dee9305-b8f0-4b27-b5c7-934313ae371b)
![Image](https://github.com/user-attachments/assets/78308cbd-88c5-4533-bce3-919778f02283)

**Comment by nileshgupta111** [comment]
@Mahesh-Vishwanath1 can you retest and confirm if it's working since it was not deployed

**Comment by Mahesh-Vishwanath1** [comment]
Verified in QA and it is working as expected.
