### ISSUE TITLE
[BUG]: [QA] Incorrect Stage is showing

### ISSUE THREAD

**Issue by Beehyv-Vinod** [pucardotorg/dristi#2025]
Once the case is filed, the case stage shows as **Scrutiny** before the payment is made

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as a valid User (Litigant /Advocate)
2. File a case
3. Check the Stage, showing as Scrutiny
5. Now we can check Payment pending task is present for the User / Nyayamitra

Case stage should change once the Payment is done,

![image](https://github.com/user-attachments/assets/df97f2ab-b1ad-4714-9375-a0fda720c02b)
![image](https://github.com/user-attachments/assets/745d8d69-51d5-4e1e-abae-6015010f6faa)

**Comment by nileshgupta111** [comment]
@Beehyv-Vinod  did changes in the mdms can you test again

**Comment by rajeshcherukumalli** [comment]
Resolved:
![Screenshot from 2024-10-22 00-02-27](https://github.com/user-attachments/assets/d70f3578-9230-484f-8f6a-1e188103b366)
