### ISSUE TITLE
UAT Bug | Advocate Clerk View Screen

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#203]
Module: User Registration
User: Nyay Mitra

Issue: Advocate Clerk View Screen shows BAR ID details with default bar registration ID and image attached

Image:
![Image](https://github.com/pucardotorg/dristi/assets/132061840/c9ca56d6-ecbe-4cb4-9334-aa0e084f948a)

**Comment by Beehyv-Vinod** [comment]
Steps for the issue,

1. Login as Nyaya Mitra
2. Select the role as Clerk
3. Click on Application number or Verify button
4. Check that BAR details or Additional details are showing in the Advocate clerk application details

Expected: BAR details or additional details should not be displayed for the Advocate clerk role in the application details.

Status: Working as expected in dev environment

![Image](https://github.com/pucardotorg/dristi/assets/132478659/fb04c378-4a89-4120-9e33-6c6200ba9108)

**Comment by Taherabharmal** [comment]
resolved
