### ISSUE TITLE
[BUG]: case search_summary issue.

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#2044]
Endpoint: https://dristi-kerala-dev.pucar.org/case/v1/search/_summary

Request:
"criteria": {
        "tenantId": "kl",
        //  "caseId": [
        //    "d20772fc-302d-4e44-86ba-ce980f7361ed"
        //    ],
        "filingNumber": [
            "KL-000190-2024"
        ]
        // "cnrNumber": []
    }

Response:
 "pagination": {
        "limit": 100,
        "offSet": 0,
        "totalCount": 482.0,
        "sortBy": "drop dristi_cases",
        "order": null
    }

**Comment by prasanna2400** [comment]
@kashish384  please retest

**Comment by kashish384** [comment]
Verifed in **Dev [sol] env**, its working fine.
[Case search1.xlsx](https://github.com/user-attachments/files/17406775/Case.search1.xlsx)
