### ISSUE TITLE
Document the installation steps & the configuration steps ( MDMS) Git Book Documentation

### ISSUE THREAD

**Issue by Ramu-kandimalla** [pucardotorg/dristi#2072]
Based on the experiences of having done multiple internal deployments and with SDC, we want to document the installation steps and also the configuration steps (including MDMS). 

Can people aligned for these tasks help document the work as steps to be followed? The team need not worry about the formatting of the content, but only getting the basic information out there keeping in mind that a newbie may use it. 

We will help with proper formatting and putting into the git book structure. 

If required the team can refer to some of the existing guides published here - https://core.digit.org/guides/installation-guide

**Comment by atulgupta2024** [comment]
there are separate tickets for installation and configuration guide. so closing this
