### ISSUE TITLE
[BUG]: [QA | Add the cross button on the top right corner of the pop up screen.]

### ISSUE THREAD

**Issue by iknoorkaur** [pucardotorg/dristi#2078]
**Describe the bug**
Cross button should be present at the top right corner of below 2 screens.

**Screenshots**
![image](https://github.com/user-attachments/assets/e04b0bfe-b25a-4b74-b24b-23e2c440073b)
![image](https://github.com/user-attachments/assets/f99ee028-e07f-42db-9164-46d15ff0ab87)

**Comment by utpalBeehyv** [comment]
hi @Ramu-kandimalla this need to clarify, Cross button should be present at the top right corner of below 2 screens,  this is not present in figma and qa teams marked as bug, pls check if it is needed or not??

**Comment by iknoorkaur** [comment]
Tested, working fine in QA env: 
![image](https://github.com/user-attachments/assets/0206e483-6af8-46e4-bb5a-5aca22cfd51b)
![image](https://github.com/user-attachments/assets/62d85bbc-bf31-4f36-98fd-8c2c224e6a53)
