### ISSUE TITLE
[BUG]:QA| No filter for Scrutiny Stage.

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#2109]
**Describe the bug**
file a case, after payment for Advocate/Litigant we have case in scrutiny but there is not stage for **Scrutiny.**

reference link:
![image](https://github.com/user-attachments/assets/aa3b79aa-d234-449d-9daf-dd04ce6a1ca5)
https://jam.dev/c/b235d88c-6d99-40ef-9dda-6fa15589acdf

**Comment by vaibhavct** [comment]
Added Scrutiny in substage mdms in both QA and dev env, Raushan has raised PR for the github @anirudh-0 
The changes are visible in QA env.

**Comment by kashish384** [comment]
Its working fine in Qa[sol env.
https://jam.dev/c/58aefc1c-003a-408a-a221-e2c363af29b7

**Comment by kashish384** [comment]
Its working fine in UAT env
