### ISSUE TITLE
Enhancement |  225 Inquiry Affidavit not needed

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#2117]
**Describe the bug**
225 Inquiry Affidavit (optional) is not needed as the sworn statement is already being asked for

Reproduce -

1. User Registration 
2. Fill details 
3. 
![image](https://github.com/user-attachments/assets/af355fa6-dece-463e-9436-790b6226751e)

Expected - 
Remove it

**Comment by devarajd94** [comment]
cloased as part of bnss
