### ISSUE TITLE
BUG || FSO Getting Flags in Empty fields in QA  

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#2123]
FSO Getting Flags in Empty fields in QA  

![image](https://github.com/user-attachments/assets/3d815159-c2a9-4501-9b31-71cb46b845e2)

**Comment by vaibhavct** [comment]
@bhuvanyuguru  Kindly update the status accordingly

**Comment by bhuvanyuguru** [comment]
Closing the Bug as Invalid
