### ISSUE TITLE
E Filing | Payment Calculator

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#2124]
Describe -
Vakaalatnama and delay condodonation fees, not disabled from the payments calculator

Reproduce -
![image](https://github.com/user-attachments/assets/babc5610-0429-43c8-9895-4ee04f5a7baa)

Expected Behaviour -
@devarajd94  will confirm

**Comment by devarajd94** [comment]
This requirement no longer exists. Hence closing the ticket.
