### ISSUE TITLE
[BUG]: [QA | Not able to generate the PDF on Complainant's Details Screen]

### ISSUE THREAD

**Issue by iknoorkaur** [pucardotorg/dristi#2125]
**To Reproduce**
1. Go to 'https://dristi-kerala-qa.pucar.org/digit-ui/citizen'
2.Login as litigant
3.File a new case
4.Click on add complainant button.
5.Select the complainant type as "Individual"
6.Upload other id proof and fill all other mand fields.

**Screenshots**
![image](https://github.com/user-attachments/assets/15417995-4093-4106-beab-b80b11da2f1f)

**Comment by ashishbeehyv** [comment]
hi @iknoorkaur  this issue is fixed in QA. please test it. cc: @Ramu-kandimalla

**Comment by iknoorkaur** [comment]
Hi @ashishbeehyv , tested this issue, working fine in QA. cc: @Ramu-kandimalla
