### ISSUE TITLE
BUG|| Order Status is wrong if box is closed in QA  

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#2130]
In Order Signing, If document is uploaded and modal box is closed, then Status is shown as signed. 

Attaching video for reference. 

[qa order signed issue.webm](https://github.com/user-attachments/assets/6fdd6bee-931f-4766-8f02-74c839782eb6)

**Comment by utpalBeehyv** [comment]
hi @bhuvanyuguru changes are done, pls check

cc : @rajeshcherukumalli

**Comment by bhuvanyuguru** [comment]
Resolved in QA 


![image](https://github.com/user-attachments/assets/0cb94037-e435-49d9-86d2-e5cb0ee4aa65)
