### ISSUE TITLE
BUG || Wrong Admit Case Pending Task shown after Issue Notice in QA

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#2132]
After Registering Case and Issuing Notice, Admit case button and pending task is not shown in Judge UI. 

 Attaching Video reference. 
 
 
[BLOCKER ADMIT CASE NOT AVAILABLE.webm](https://github.com/user-attachments/assets/dc87fa58-6e86-4471-97af-a75437c93fcd)

**Comment by bhuvanyuguru** [comment]
Hi @ashishbeehyv 

Admit Case button is shown but no Pending Task is shown. 


Button Screenshot 

![image](https://github.com/user-attachments/assets/6027ed47-4ec7-4935-bd2f-3f3cdc2a887f)



No Pending Task 

![image](https://github.com/user-attachments/assets/0bbd3202-0545-4d8f-8159-a6d392c1d4c5)

**Comment by nileshgupta111** [comment]
@bhuvanyuguru  changes done , please re-test.

**Comment by bhuvanyuguru** [comment]
Not resolved @nileshgupta111 

Pending task is still not shown

CC: @Ramu-kandimalla , @manimaarans 

![image](https://github.com/user-attachments/assets/f209cbc3-e78e-4576-bf00-367fb5e6e7e6)

**Comment by nileshgupta111** [comment]
@bhuvanyuguru  updated the mdms check again

**Comment by bhuvanyuguru** [comment]
HI @nileshgupta111, please check this issue 


[admit case .webm](https://github.com/user-attachments/assets/2d9aaf62-57bc-4651-870d-3ae2b1eef512)

**Comment by bhuvanyuguru** [comment]
Bug is not resolved in QA  @ashishbeehyv, 

CC: @anirudh-0 

![image](https://github.com/user-attachments/assets/1df2a749-7b86-4327-9843-633768930c46)

**Comment by ashishbeehyv** [comment]
hi @bhuvanyuguru this is fixed in QA. please test again. cc: @Ramu-kandimalla
