### ISSUE TITLE
BUG || E-Post Payment BLOCKER in QA

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#2134]
**BUG QA**
After Notice is Issued, In Advocate's Pending Task for E-Post Payment, Getting Access Denied. 

**To Reproduce**
1. Go to 'Pending Task for Payment (**NOTICE**)'
2. Click on 'Delivery Partner Fees'
3. See error

**Expected behavior**
Payment UI should be shown

**CURL** 

`curl 'https://dristi-kerala-qa.pucar.org/sbi-backend/payment/v1/_processTransaction?_=1729316202446' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'content-type: application/json;charset=UTF-8' \
  -H 'origin: https://dristi-kerala-qa.pucar.org' \
  -H 'priority: u=1, i' \
  -H 'referer: https://dristi-kerala-qa.pucar.org/digit-ui/citizen/home/sbi-epost-payment' \
  -H 'sec-ch-ua: "Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36' \
  --data-raw '{"TransactionDetails":{"OperatingMode":"DOM","MerchantCountry":"IN","MerchantCurrency":"INR","PostingAmount":41.86,"OtherDetails":"NA","PayMode":"NB","billId":"ede54a83-2164-47c3-9160-946d842bdfcf","tenantId":"kl","totalDue":41.86,"businessService":"task-notice","serviceNumber":"KL-000280-2024-TK1","mobileNumber":"7100000002","paidBy":"Bhuvanyu ADV null","payerName":"Bhuvanyu ADV null","amountDetails":[{"accountIdentifier":"GRPT","postingAmount":41.86,"merchantCurrency":"INR"}]},"RequestInfo":{"apiId":"Rainmaker","authToken":"1ab8c6c2-0bfe-4c1b-8b16-376a6e988116","userInfo":{"id":261,"uuid":"65f31a97-cc09-4657-9cc8-1e8be2f63608","userName":"7100000002","name":"Bhuvanyu ADV null","mobileNumber":"7100000002","emailId":null,"locale":null,"type":"CITIZEN","roles":[{"name":"HEARING_VIEWER","code":"HEARING_VIEWER","tenantId":"kl"},{"name":"CASE_VIEWER","code":"CASE_VIEWER","tenantId":"kl"},{"name":"DEPOSITION_VIEWER","code":"DEPOSITION_VIEWER","tenantId":"kl"},{"name":"Citizen","code":"CITIZEN","tenantId":"kl"},{"name":"ADVOCATE_ROLE","code":"ADVOCATE_ROLE","tenantId":"kl"},{"name":"APPLICATION_CREATOR","code":"APPLICATION_CREATOR","tenantId":"kl"},{"name":"SUBMISSION_DELETE","code":"SUBMISSION_DELETE","tenantId":"kl"},{"name":"HEARING_ACCEPTOR","code":"HEARING_ACCEPTOR","tenantId":"kl"},{"name":"CASE_RESPONDER","code":"CASE_RESPONDER","tenantId":"kl"},{"name":"DEPOSITION_CREATOR","code":"DEPOSITION_CREATOR","tenantId":"kl"},{"name":"SUBMISSION_RESPONDER","code":"SUBMISSION_RESPONDER","tenantId":"kl"},{"name":"ORDER_VIEWER","code":"ORDER_VIEWER","tenantId":"kl"},{"name":"CASE_EDITOR","code":"CASE_EDITOR","tenantId":"kl"},{"name":"SUBMISSION_CREATOR","code":"SUBMISSION_CREATOR","tenantId":"kl"},{"name":"APPLICATION_VIEWER","code":"APPLICATION_VIEWER","tenantId":"kl"},{"name":"TASK_VIEWER","code":"TASK_VIEWER","tenantId":"kl"},{"name":"CASE_CREATOR","code":"CASE_CREATOR","tenantId":"kl"}],"active":true,"tenantId":"kl","permanentCity":null},"msgId":"1729316202446|en_IN","plainAccessRequest":{}}}'`

**Screenshots**

![image](https://github.com/user-attachments/assets/f6f270cb-0e1d-4727-9c8a-4115d3d0115d)

**Comment by shambhavigoel1002** [comment]
Hi @bhuvanyuguru , This should work in office network . not in home network due to whitelisting of ip. 
cc :- @Ramu-kandimalla

**Comment by bhuvanyuguru** [comment]
Working fine on office network. @shambhavigoel1002
