### ISSUE TITLE
BUG || Amount Paid shown is In-Correct in Court Staff User

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#2136]
Amount Paid shown is In-Correct in Court Staff User in QA after Successful Payment by Advocate in Pending Task.

Expected : 0.75 (shown in Pending Task) (@manimaarans please re-confirm this once by a DEV) 

Actual Shown : 100

Refer Screenshot
![image](https://github.com/user-attachments/assets/6b6fe1ba-615c-4276-83e0-3e60e45df69f)

**Comment by Beehyv-Vinod** [comment]
Tested in Kerala-QA Working fine,
![image](https://github.com/user-attachments/assets/53547861-451f-4aa7-adf6-b79de46081c0)
