### ISSUE TITLE
BUG || Accused Adv name (null) shown in Attendence in Hearing in QA

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#2139]
Accused Adv is not shown in Attendence in Hearing in QA

Refer Screenshot
![image](https://github.com/user-attachments/assets/15e085c9-319c-444f-8f13-9e943c4172cd)

![image](https://github.com/user-attachments/assets/31c601a0-35a4-44e9-b3e7-d2b5d7358b77)

**Comment by ashishbeehyv** [comment]
hi @bhuvanyuguru  after joining a case, the advocate should mark attendance for the hearing. please test this once and let me know if there is still any issue. cc: @Ramu-kandimalla

**Comment by bhuvanyuguru** [comment]
Hi @ashishbeehyv, modal box is not shown for confirm attendance. 

[join case.webm](https://github.com/user-attachments/assets/2dab30a4-fd1a-4788-b2d3-064860816786)

**Comment by bhuvanyuguru** [comment]
Hi @nitish-beehyv, @ashishbeehyv getting Null in name of Accesed advocate after confirming receipt in summons 


Refer Screenshot
![image](https://github.com/user-attachments/assets/bd3ccce0-84c7-4126-83e8-cda25351032a)

**Comment by bhuvanyuguru** [comment]
Hi @nitish-beehyv 

This Issue is not Fixed in QA, getting Null in name of Accesed advocate after confirming receipt in summons.

![image](https://github.com/user-attachments/assets/23c7955d-2a75-4af4-8fef-5be6816923e0)

**Comment by nitish-beehyv** [comment]
Hi @bhuvanyuguru please test it with new case case?

**Comment by bhuvanyuguru** [comment]
I tested it with a new case @nitish-beehyv, today morning

**Comment by bhuvanyuguru** [comment]
Working fine in UAT. 

![image](https://github.com/user-attachments/assets/0ecf6e13-2b29-46fd-a418-cf2ade68ed34)
