### ISSUE TITLE
BUG || After Order UI has a box shown behind successful modal box in QA 

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#2140]
Please look into this UI issue, dialoge box is shown behind successful modal box.

![image](https://github.com/user-attachments/assets/87ebcbeb-dc72-4485-982b-43e721b054f1)

**Comment by utpalBeehyv** [comment]
hi @bhuvanyuguru i am not able to reproduce
![Image](https://github.com/user-attachments/assets/f70fc3a0-b4c7-48ba-bb68-4f971d537509)


cc : @Ramu-kandimalla @rajeshcherukumalli

**Comment by bhuvanyuguru** [comment]
One time issue, not able to reproduce now.
