### ISSUE TITLE
BUG || [BLOCKER] Internal Server Error while Order Signing

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#2142]
Getting this Error when Signing Order for Reschedule via Judge. 

![image](https://github.com/user-attachments/assets/e0c46890-834d-49bc-b968-61fe7b2036ef)

Response : {
    "errorMessage": "Failed to query details of order to Assign New Hearing Date after Rescheduling",
    "errorCode": 500
}

CURL : `curl 'https://dristi-kerala-qa.pucar.org/egov-pdf/order?tenantId=kl&orderId=2e09f8fb-0be8-429d-835f-5d7d72fe2d46&cnrNumber=KLKM520001082024&qrCode=false&orderType=new-hearing-date-after-rescheduling' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'content-type: application/json;charset=UTF-8' \
  -H 'origin: https://dristi-kerala-qa.pucar.org' \
  -H 'priority: u=1, i' \
  -H 'referer: https://dristi-kerala-qa.pucar.org/digit-ui/employee/orders/generate-orders?filingNumber=KL-000280-2024&orderNumber=KL-000280-2024-OR9' \
  -H 'sec-ch-ua: "Brave";v="129", "Not=A?Brand";v="8", "Chromium";v="129"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36' \
  --data-raw '{"RequestInfo":{"authToken":"e88d194d-a7c8-4886-bd79-12192d3a1e63","userInfo":{"id":219,"uuid":"bb6467df-9b44-40b6-9f16-c081ad4ff0dc","userName":"gJudge","name":"super","mobileNumber":"1002335566","emailId":null,"locale":null,"type":"EMPLOYEE","roles":[{"name":"HEARING_VIEWER","code":"HEARING_VIEWER","tenantId":"kl"},{"name":"DEPOSITION_EDITOR","code":"DEPOSITION_EDITOR","tenantId":"kl"},{"name":"WORKFLOW_ABANDON","code":"WORKFLOW_ABANDON","tenantId":"kl"},{"name":"ORDER_ESIGN","code":"ORDER_ESIGN","tenantId":"kl"},{"name":"Workflow Admin","code":"WORKFLOW_ADMIN","tenantId":"kl"},{"name":"DEPOSITION_PUBLISHER","code":"DEPOSITION_PUBLISHER","tenantId":"kl"},{"name":"TASK_APPROVER","code":"TASK_APPROVER","tenantId":"kl"},{"name":"HEARING_START","code":"HEARING_START","tenantId":"kl"},{"name":"HEARING_APPROVER","code":"HEARING_APPROVER","tenantId":"kl"},{"name":"ORDER_VIEWER","code":"ORDER_VIEWER","tenantId":"kl"},{"name":"SUBMISSION_RESPONDER","code":"SUBMISSION_RESPONDER","tenantId":"kl"},{"name":"ORDER_REASSIGN","code":"ORDER_REASSIGN","tenantId":"kl"},{"name":"CASE_EDITOR","code":"CASE_EDITOR","tenantId":"kl"},{"name":"APPLICATION_APPROVER","code":"APPLICATION_APPROVER","tenantId":"kl"},{"name":"TASK_CREATOR","code":"TASK_CREATOR","tenantId":"kl"},{"name":"HEARING_DATE_REQUESTOR","code":"HEARING_DATE_REQUESTOR","tenantId":"kl"},{"name":"Employee","code":"EMPLOYEE","tenantId":"kl"},{"name":"ORDER_DELETE","code":"ORDER_DELETE","tenantId":"kl"},{"name":"CASE_VIEWER","code":"CASE_VIEWER","tenantId":"kl"},{"name":"APPLICATION_REJECTOR","code":"APPLICATION_REJECTOR","tenantId":"kl"},{"name":"ORDER_APPROVER","code":"ORDER_APPROVER","tenantId":"kl"},{"name":"HEARING_CLOSER","code":"HEARING_CLOSER","tenantId":"kl"},{"name":"ORDER_CREATOR","code":"ORDER_CREATOR","tenantId":"kl"},{"name":"JUDGE_ROLE","code":"JUDGE_ROLE","tenantId":"kl"},{"name":"CASE_APPROVER","code":"CASE_APPROVER","tenantId":"kl"},{"name":"DEPOSITION_CREATOR","code":"DEPOSITION_CREATOR","tenantId":"kl"},{"name":"SUBMISSION_APPROVER","code":"SUBMISSION_APPROVER","tenantId":"kl"},{"name":"TASK_UPDATOR","code":"TASK_UPDATOR","tenantId":"kl"},{"name":"TASK_VIEWER","code":"TASK_VIEWER","tenantId":"kl"},{"name":"HEARING_SCHEDULER","code":"HEARING_SCHEDULER","tenantId":"kl"}],"active":true,"tenantId":"kl","permanentCity":null},"msgId":"1729320808912|en_IN","apiId":"Rainmaker"}}'`

**Comment by bhuvanyuguru** [comment]
Hi @vaibhavct 

Please look into this HIGH PRIORITY issue 

Opt-OUT dates not shown in pending task for Advocate

![image](https://github.com/user-attachments/assets/63956ca8-2c48-46df-aeb2-7feefba29f16)


CC: @Ramu-kandimalla

**Comment by bhuvanyuguru** [comment]
HI @prasanna2400 

If there is only one advocate in case, Opt-out dates are shown but no pending task is shown for judge after opt-out dates are chosen. 

![image](https://github.com/user-attachments/assets/e47e164d-916e-42aa-8a83-316a959ffbba)


CC: @manimaarans , @rajeshcherukumalli

**Comment by Beehyv-Vinod** [comment]
Hi @rajeshcherukumalli @Ramu-kandimalla Tested in Kerala-qa, both the flows are working fine,

**Opt-out flows,**
Opt-out flow before admitting the case
Opt-out flow after admitting the case


https://jam.dev/c/abdc5243-371b-43f6-80f5-3be498673005

Cc: @bhuvanyuguru
