### ISSUE TITLE
UAT: Judge able to access case in draft stage 

### ISSUE THREAD

**Issue by atulgupta2024** [pucardotorg/dristi#2156]
Log a new case and keep it in draft mode. from the request info, capture the caseID and filingNumber. 

Login as Judge. Go to view case, by selecting any case the Judge has access to. In the URL replace the caseID and FilingNumber with the one copied from previous step and hit enter. the said case opens up for the judge. This should not happen. Draft case should not be visible to the judge. 

sample URL for draft case 

https://dristi-kerala-uat.pucar.org/digit-ui/employee/dristi/home/view-case?caseId=dbc1788d-5b2d-4eaf-bcde-ba49babd0cd2&filingNumber=KL-000264-2024&tab=Overview

@suresh12 @subhashini-egov

**Comment by shambhavigoel1002** [comment]
Hi @rajeshcherukumalli Can you please test this. 
cc:- @anirudh-0  @Ramu-kandimalla

**Comment by atulgupta2024** [comment]
@shambhavigoel1002 what's the code change done? Is that only with regards the constants or did we write some logic to check if the Judge is party to the case or not?

**Comment by shambhavigoel1002** [comment]
Hi @atulgupta2024 the code changes that has been done is that we are redirecting using history.push to home page in the basis of the stage on which the case is in .

**Comment by iknoorkaur** [comment]
Tested in the QA environment, and all scenarios worked as expected. The following cases were verified:
1. Judge, FSO, and Nyay Mitra were unable to access the case in the draft stage, if we try to access the case through URL, screen is re-directed to home screen.
2. When the case was assigned to FSO, no other user roles were able to access it.
3. Similarly, when the case was assigned to the Judge, access was restricted for all other roles.
4. When the FSO or Judge sent the case back for correction, it remained inaccessible for roles except litigent.
5. Cases with statuses pending admission hearing,pending notice, response were validated.
6. For cases marked as "DISMISSED," UI access was restricted. However, an edge case was encountered where the case could still be accessed and is able to start the hearing using the case number and filing number directly through the URL (https://github.com/pucardotorg/dristi/issues/2264).
for reference:
https://jam.dev/c/87cb641f-7427-47a0-8f67-03d62043d6f1
https://jam.dev/c/b6bb2d0a-1209-4dcf-b5da-3575b60faa27

cc: @rajeshcherukumalli @Ramu-kandimalla

**Comment by atulgupta2024** [comment]
@Ramu-kandimalla  i will create a new Tech Debt ticket for change of logic. If you want you can close this ticket once it is tested and validated to be working

**Comment by Ramu-kandimalla** [comment]
Hi @atulgupta2024  Thank-you for the confirmation
