### ISSUE TITLE
[BUG]: QA| Search api failing while offline payment.

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#2157]
url: https://dristi-kerala-qa.pucar.org/digit-ui/employee/dristi/pending-payment-inbox/pending-payment-details?filingNumber=KL-000289-2024&businessService=task-notice&consumerCode=KL-000289-2024-TK2_POST_COURT&paymentType=Notice%20Post%20Court%20Fee
Reference link:
https://jam.dev/c/63130494-ec8e-48c5-91d9-1b955a76a7a5

 Response:
{"ResponseInfo":null,"Errors":[{"code":"CustomException","message":"You are not authorized to access this resource","description":"You are not authorized to access this resource","params":null}]}

curl:
curl 'https://dristi-kerala-qa.pucar.org/order/v1/search' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'content-type: application/json;charset=UTF-8' \
  -H 'origin: https://dristi-kerala-qa.pucar.org' \
  -H 'priority: u=1, i' \
  -H 'referer: https://dristi-kerala-qa.pucar.org/digit-ui/employee/dristi/pending-payment-inbox/pending-payment-details?filingNumber=KL-000285-2024&businessService=task-summons&consumerCode=KL-000285-2024-TK3_ICOPS_COURT&paymentType=Summons%20iCops%20Court%20Fee' \
  -H 'sec-ch-ua: "Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36' \
  --data-raw '{"criteria":{"tenantId":"kl","id":"6d05fa20-f17e-4891-930a-47a5b32bbc76"},"RequestInfo":{"apiId":"Rainmaker","authToken":"f25e1b0f-1f21-4229-ab4c-9b73496b2a00","userInfo":{"id":102,"uuid":"949c975c-e2d4-43e3-add1-cb793a178e16","userName":"qaNM01","name":"qaNM01","mobileNumber":"1002335566","emailId":null,"locale":null,"type":"EMPLOYEE","roles":[{"name":"CASE_VIEWER","code":"CASE_VIEWER","tenantId":"kl"},{"name":"ADVOCATE_CLERK_APPROVER","code":"ADVOCATE_CLERK_APPROVER","tenantId":"kl"},{"name":"PAYMENT_COLLECTOR","code":"PAYMENT_COLLECTOR","tenantId":"kl"},{"name":"NYAY_MITRA_ROLE","code":"NYAY_MITRA_ROLE","tenantId":"kl"},{"name":"CASE_EDITOR","code":"CASE_EDITOR","tenantId":"kl"},{"name":"Employee","code":"EMPLOYEE","tenantId":"kl"},{"name":"TASK_VIEWER","code":"TASK_VIEWER","tenantId":"kl"},{"name":"ADVOCATE_APPROVER","code":"ADVOCATE_APPROVER","tenantId":"kl"},{"name":"CASE_CREATOR","code":"CASE_CREATOR","tenantId":"kl"}],"active":true,"tenantId":"kl","permanentCity":null},"msgId":"1729502100243|en_IN","plainAccessRequest":{}}}'

**Comment by TusharKatiyar2002** [comment]
adding the role ORDER_VIEWER for nyay mitra user

**Comment by kashish384** [comment]
Its working fine.
https://jam.dev/c/da29b044-2df9-43bb-802b-002c7155992e

**Comment by anirudh-0** [comment]
@kashish384 can you update status on this

**Comment by kashish384** [comment]
https://jam.dev/c/04fed44c-639f-425d-ab0b-14b3dc9b62d2

**Comment by kashish384** [comment]
its working fine in UAT Env.
