### ISSUE TITLE
[BUG]: [Upload document establishing the authorized representative of the company]

### ISSUE THREAD

**Issue by rajeshcherukumalli** [pucardotorg/dristi#2162]
**Describe the bug**
Same file is displayed for both accused and complainant
https://jam.dev/c/56303fe0-541c-4338-82b0-7f74021f6d8b

**Comment by kashish384** [comment]
Not able to reproduce.
https://jam.dev/c/b9417830-f4f3-4d74-a8c3-dbcec9b6b7da
