### ISSUE TITLE
BUG || Epost record not shown in E-post Admin in QA

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#2163]
**QA**

After Court-staff signed the post record, record is not shown in E-post admin. 

![image](https://github.com/user-attachments/assets/070be656-9a9f-4944-b6f5-102272a27310)

**Comment by vaibhavct** [comment]
https://github.com/pucardotorg/dristi-solutions/pull/714
Merged the PR, changes should be visible in QA env
c.c. @anirudh-0

**Comment by bhuvanyuguru** [comment]
Issue Resolved in QA 

![image](https://github.com/user-attachments/assets/8d10cc1a-bc63-4561-9a19-cb1f98cfa6f5)
