### ISSUE TITLE
[BUG]: [QA | Invalid Pincode error message appearing twice on accused details screen for individual and entity]

### ISSUE THREAD

**Issue by iknoorkaur** [pucardotorg/dristi#2166]
**Describe the bug**
Invalid Pincode error message appearing twice on accused details screen for individual and entity while we enter last alphabet/ digit.

**To Reproduce**
1. File a new case
2. Go to accused details screen
3. Scroll down
4. Enter incorrect pincode, when we enter the last digit/ alphabet, error message appearing twice.

**Expected behavior**
Error message should appear only once.

**Additional context**
[pincode.webm](https://github.com/user-attachments/assets/77d559d1-81f3-4e4c-9daf-cc1a333f4ff1)

**Comment by ashishbeehyv** [comment]
hi @iknoorkaur  this is fixed in QA. please test again. cc: @Ramu-kandimalla

**Comment by iknoorkaur** [comment]
Tested in qa, working fine: 
![image](https://github.com/user-attachments/assets/4721080e-41ab-4b7a-a154-ac1dd5c65142)

cc: @Ramu-kandimalla @rajeshcherukumalli
