### ISSUE TITLE
[BUG] QA|Witness issue.

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#2171]
Expected: When no witness is added, during review it should state “No witnesses added”
https://jam.dev/c/e0c5fd71-0699-4d96-aaaf-955f2197c1e4

**Comment by rajeshcherukumalli** [comment]
Resolved
![Screenshot from 2024-10-22 00-00-31](https://github.com/user-attachments/assets/03b4115e-45f0-4cc7-a6c3-b2cb4851fe87)
