### ISSUE TITLE
[BUG]: [QA] E-Filing issues

### ISSUE THREAD

**Issue by Beehyv-Vinod** [pucardotorg/dristi#2174]
**Describe the bug**
Below are not working,

1. On review of complaint, if no reply was received, the field on “date of reply to legal notice” should say “No reply received”
2. Include fields for both payee bank and payer bank with **payer bank branch name**
3. "Type of Entity"  is working as Optional for Complainant

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as valid user
2. Click on File Case
3. In E-Filing flow we can found the issues

**Expected behaviour**
Above 3 issues should work as expected

**Comment by rajeshcherukumalli** [comment]
Resolved
