### ISSUE TITLE
BUG || If payment is declined in SBI-Epayment completed status is shown in QA

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#2217]
**Describe the bug**
In Pending task for POST Notice and Summons, if payment is declined from SBI portal, Completed status is shown in Pending Task.

**To Reproduce**
1. Go to 'Pending Task for POST'
2. Click on 'Delivery Partner Fee'
3. Click on Net Banking, Go to Net Banking in SBI portal 
4. Choose SBI test bank in dropdown and click on Pay Now 
4. Click on Decline and Check Pending Task, See error

**Expected behavior**
User should be able to see Pay Online button as Transaction is not Completed.

**Reference Screenshots/ Videos**
[payment fail but completed shown .webm](https://github.com/user-attachments/assets/8f804154-dd83-4b43-9348-0179f44daabb)

**Comment by anirudh-0** [comment]
@bhuvanyuguru I think in test environments the Payments show up as failed intentionally

@shambhavigoel1002 @Ajith-beehyv can one of you comment on this ?

**Comment by shambhavigoel1002** [comment]
Hi @anirudh-0  so the completed that is being shown is on the basis of bill status as "PAID" ideally it should be active if the sbi payment is failed. Backend guy is looking into it

**Comment by harshkumar8789** [comment]
Hi @bhuvanyuguru, can you retest this issue?

**Comment by shambhavigoel1002** [comment]
Hi @rajeshcherukumalli  Can you please assign someone for testing this.

**Comment by kashish384** [comment]
@harshkumar8789 __issue still there.QA[sol]env.
after click  decline  button__Payment successful screen showing.
https://jam.dev/c/4ad538ee-95de-48d0-88a9-a803f23da68a

**Comment by bhuvanyuguru** [comment]
HI @rajeshcherukumalli 

Working fine in UAT 

![image](https://github.com/user-attachments/assets/f209b37d-060a-40d5-919b-da96385cb404)

![image](https://github.com/user-attachments/assets/7739057f-ccf4-45b2-8aa7-86c38a2e1860)
