### ISSUE TITLE
BUG || Submitted On Date is In-correct in Join Case Flow in QA

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#2218]
**Describe the bug**
Submitted On date is shown wrong in Modal box for Join case flow in QA 

**To Reproduce**
1. Go to 'Accused Advocate'
2. Click on 'Join Case' button
3. Enter mandatory fields and successfully join case.
4. See Submitted date error in successfully joined modal box

**Expected behavior**
Submitted date should be correct.

**Screenshots**

Judge screen 
![image](https://github.com/user-attachments/assets/6aafe0ef-e992-40c2-bdd2-26d73b6c8f5b)

Accused advocate Screen 
![image](https://github.com/user-attachments/assets/4b77786c-837d-45d4-883d-221f469f9a55)

**Comment by shambhavigoel1002** [comment]
Hi @rajeshcherukumalli  the issue is fixed and working as expected in qa , Please check .
cc:- @anirudh-0

**Comment by bhuvanyuguru** [comment]
HI @rajeshcherukumalli 

Working as expected in UAT 

![image](https://github.com/user-attachments/assets/ca4cb4d8-56ce-4fab-958e-23a7dd6ba8d2)
