### ISSUE TITLE
BUG || Court Staff CSS Issues in QA 

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#2220]
Court Staff CSS Issues in QA 

1. E-Sign Button 

![image](https://github.com/user-attachments/assets/9973f097-5274-4aa0-ba4f-0b4308d53fdc)

2. Proceed to Send button in next window. 
![image](https://github.com/user-attachments/assets/4179f963-59b0-46bf-8f37-53118247a337)

3. Update Status CSS button Issue
![image](https://github.com/user-attachments/assets/a892ba1c-b5d4-4e60-abfd-b3ffc4a304ec)

**Comment by Beehyv-Vinod** [comment]
1. E-Sign CSS issue is Fixed
2. Proceed to Send CSS issue is Fixed
3. Update Status CSS issue is Fixed

![image](https://github.com/user-attachments/assets/0e305bde-5658-4b80-bbd4-8c4ded3de9b8)
![image](https://github.com/user-attachments/assets/6e7238a5-b152-4b65-9636-3f8818ce6999)
![image](https://github.com/user-attachments/assets/464a2cb7-39bb-43db-9a6b-4165083a432c)
