### ISSUE TITLE
BUG || Submitted Date is In-correct for Case shown for Judge in QA

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#2221]
**Describe the bug**
Submitted Date is shown wrong for judge in QA  

**To Reproduce**
1. Before Registering case, check Submitted Date in judge screen (Stage : Cognizance) 
2. After Registering, Schedule hearing and Issue Notice
3. Admit Case check Case submitted date. 

**Expected behavior**
Correct submitted Date should be shown

**Screenshots**
![image](https://github.com/user-attachments/assets/38daba02-17a1-423c-a908-72ee486d59fb)

**Comment by shambhavigoel1002** [comment]
Hi @rajeshcherukumalli  It is now working as expected please check.
cc:- @anirudh-0

**Comment by kashish384** [comment]
Its working fine in QA [sol] env.
https://jam.dev/c/775e6b76-ceec-4ad3-b812-16367b465f6e
