### ISSUE TITLE
BUG || After Reschedule request is approved, Old admission hearing shown in Hearings Tab

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#2222]
**Describe the bug**
After Reschedule request for New hearing is approved by Judge, old Admission hearing is shown in Hearing and Overview Tab  

**To Reproduce**
1. Go to Judge, Accept Reschedule request 
2. Check Hearing and Overview Tab 

**Expected behavior**
No Hearing record should be shown in Hearing & Overview Tab   

 
**Screenshots**
![image](https://github.com/user-attachments/assets/04343b69-3937-49bd-b2d2-c5481b690d12)

**Comment by ashishbeehyv** [comment]
hi @bhuvanyuguru  this issue is fixed in QA. please test it.

**Comment by bhuvanyuguru** [comment]
Resolved in QA

![image](https://github.com/user-attachments/assets/9dcc76d8-ec00-4acd-ac0b-7010ac2b8f5c)
