### ISSUE TITLE
[BUG]: [QA | Workflow Exception in Rescheduling admission hearing ]

### ISSUE THREAD

**Issue by iknoorkaur** [pucardotorg/dristi#2227]
**Describe the bug**
If we reschedule the admission hearing a second time and attempt to add a signature, it displays an "internal error has occurred" message.

**To Reproduce**
1. Go to 'judge user role'
2. Register a case, issue order and notice
3. Reschedule admission hearing 
4. Reschedule admission hearing for the second time.

**Screenshots**
[reschedule admission hearing.webm](https://github.com/user-attachments/assets/94df4c6a-9c59-4079-9fcc-36279d71224d)

**Desktop:**
 - Browser [firefox]

**Additional context**
curl : `curl 'https://dristi-kerala-qa.pucar.org/hearing/v1/update?tenantId=kl&_=1729580428930' -X POST -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br, zstd' -H 'Content-Type: application/json;charset=utf-8' -H 'Origin: https://dristi-kerala-qa.pucar.org' -H 'DNT: 1' -H 'Sec-GPC: 1' -H 'Connection: keep-alive' -H 'Referer: https://dristi-kerala-qa.pucar.org/digit-ui/employee/orders/generate-orders?filingNumber=KL-000374-2024&orderNumber=KL-000374-2024-OR6' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'Priority: u=0' -H 'TE: trailers' --data-raw '{"hearing":{"id":"e1520965-d140-4547-b5a0-cdc84984252e","tenantId":"kl","hearingId":"KL-000374-2024-HR1","courtCaseNumber":null,"caseReferenceNumber":null,"cmpNumber":null,"filingNumber":["KL-000374-2024"],"cnrNumbers":["KLKM520001392024"],"applicationNumbers":[],"hearingType":"ADMISSION","status":"OPT_OUT","startTime":1729728000000,"endTime":1729728000000,"presidedBy":{"judgeId":["BENCH_ID"],"benchId":"JUDGE_ID","courtId":"KLKM52"},"attendees":[{"name":"qa user","individualId":"IND-2024-10-08-000062","type":"Complainant","associatedWith":null,"wasPresent":null,"isOnline":null},{"name":"pincode","individualId":null,"type":"Complainant","associatedWith":null,"wasPresent":null,"isOnline":null}],"transcript":[],"vcLink":null,"isActive":false,"documents":[],"additionalDetails":null,"auditDetails":{"createdBy":"cc91d677-5ab2-4bea-96ff-a07a299f0d6b","lastModifiedBy":"cc91d677-5ab2-4bea-96ff-a07a299f0d6b","createdTime":1729578486278,"lastModifiedTime":1729578533895},"workflow":{"action":"RESCHEDULE","assignes":[],"comments":"Update Hearing","documents":[{}]},"notes":null},"RequestInfo":{"apiId":"Rainmaker","authToken":"ae5f241e-7b48-40ae-83f0-99302833a4bc","msgId":"1729580428930|en_IN","plainAccessRequest":{}}}'`

Response:
Object { code: "WORKFLOW_SERVICE_EXCEPTION", message: 'ServiceCallException(error={"ResponseInfo":null,"Errors":[{"id":null,"parentId":null,"code":"INVALID ACTION","message":"Action RESCHEDULE not found in config for the businessId: KL-000374-2024-HR1","description":null,"params":null}]})', id: null, … }

**Comment by ashishbeehyv** [comment]
hi @iknoorkaur, the required changes have been made in develop branch. please check this when changes are deployed in QA. cc: @Ramu-kandimalla

**Comment by iknoorkaur** [comment]
Tested in QA env, working as expected
[hearingmessage.webm](https://github.com/user-attachments/assets/302b1231-5827-40b4-80a1-5dd89aa3ce94)
cc : @Ramu-kandimalla @rajeshcherukumalli
