### ISSUE TITLE
[BUG]: [QA | Admit case pop up closes automatically after few sec]

### ISSUE THREAD

**Issue by iknoorkaur** [pucardotorg/dristi#2234]
**To Reproduce**
1. Go to 'Judge user role'
2. Click on 'Register case-> issue order -> issue notice -> admit case'
3. See error

**Expected behavior**
Admit case pop up should not close automatically

**Screenshots**
[admit case.webm](https://github.com/user-attachments/assets/b7c8a82c-9efd-457c-bd68-299497b43479)

**Comment by ashishbeehyv** [comment]
hi @iknoorkaur, the required changes have been made in develop branch. please check this when changes are deployed in QA. cc: @Ramu-kandimalla

**Comment by iknoorkaur** [comment]
Hi @ashishbeehyv, earlier admit case pop up screen was closing automatically but now the below screen (after admitting the case) closes automatically:
![image](https://github.com/user-attachments/assets/68f1f811-1d15-4758-83ec-7298990a127b)
Attaching video for reference:
[schedule admission hearing.webm](https://github.com/user-attachments/assets/fccf82b5-7bd0-4223-b4f4-20918ba1649e)
cc: @Ramu-kandimalla @rajeshcherukumalli

**Comment by iknoorkaur** [comment]
Tested, working fine in uat
Attaching jam video for reference: https://jam.dev/c/f4ffc284-6233-4f7c-add5-0eaa16e3f0b3
