### ISSUE TITLE
[BUG]: [QA | Localization (some words are missing in Malayalam]

### ISSUE THREAD

**Issue by RohiniKanala517** [pucardotorg/dristi#2261]
**Describe the bug**
Some words need to be localized in Malayalam, still showing in English in Case Filing page

**To Reproduce**
1. Go to File a Case
2. Click on File a Case

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/02b34036-e780-4e4e-bc32-b77a708bb40b)
![image](https://github.com/user-attachments/assets/d9b08656-0132-4b1b-9022-b64a5ef7fa6b)
![image](https://github.com/user-attachments/assets/1c5a529a-7f61-4669-93a5-613d736356fb)
![image](https://github.com/user-attachments/assets/edb76705-9628-470a-9eb8-8ee84325dfc3)
![image](https://github.com/user-attachments/assets/5035da2f-706f-4deb-bf84-f15598d23d94)
![image](https://github.com/user-attachments/assets/aa36c7ae-c30f-42fd-9753-c6066d83b168)
![image](https://github.com/user-attachments/assets/5993f923-763e-4593-ad1b-1a46f1043c69)
![image](https://github.com/user-attachments/assets/553c6deb-48d3-40dc-b368-b344d8bbdffa)
![image](https://github.com/user-attachments/assets/46fd564a-6f8c-412a-b711-136d9a2c2157)
![image](https://github.com/user-attachments/assets/e7a74f94-958f-49ed-ab55-10da0e146915)
![image](https://github.com/user-attachments/assets/600bdab4-1c40-4cd3-8d4a-4b8b6148451d)
![image](https://github.com/user-attachments/assets/c56bb34d-1941-4a85-8067-4217bcc27e2e)
![image](https://github.com/user-attachments/assets/4500e135-19e7-4569-b010-7031474c2557)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by utpalBeehyv** [comment]
hi @devarajd94 i have added some new strings in loacalisation doc in commons and hearings, and in Cases some malayalam text is still missing
https://docs.google.com/spreadsheets/d/1Cbf1w77Khc8Z_U0QSRF9xy0EZ17YdzICQCcpfUkyK_4/edit?gid=790431664#gid=790431664


cc : @Ramu-kandimalla @rajeshcherukumalli

**Comment by rajeshcherukumalli** [comment]
Hi, issue is resolved
![Screenshot from 2024-11-16 13-49-01](https://github.com/user-attachments/assets/a7fe2bf2-a657-4136-9ec4-37a34d661baf)
![Screenshot from 2024-11-16 13-57-24](https://github.com/user-attachments/assets/952117b8-00a7-4ffd-abbd-ef90244daf41)
![Screenshot from 2024-11-16 13-58-36](https://github.com/user-attachments/assets/a3ff2ae2-f7fd-4200-9fff-80116475f54b)
![Screenshot from 2024-11-16 14-03-27](https://github.com/user-attachments/assets/ac32b26e-a0ea-4f90-a5bd-791e90c98709)
![Screenshot from 2024-11-16 17-34-26](https://github.com/user-attachments/assets/6a9c3193-7206-431e-8282-9e333897b575)
