### ISSUE TITLE
[BUG]: [QA, UAT] Case stage is not updating in Case details screen

### ISSUE THREAD

**Issue by Beehyv-Vinod** [pucardotorg/dristi#2262]
**Describe the bug**
When Case stage is changes, Case stage updating in Home screen, but not in Case details screen.

**To Reproduce**

1. File a case, Case stage is **Filing**
2. Make the Online payment or Make the payment by Nyayamitra
3. Case is Moved to Scrutiny, We can see in complainant Home screen case stage showing as **Scrutiny**.
4. Click on the Same Case
5. We can see case stage showing as **FIling** only.
6. If we refresh the case details screen, case stage will be updated to the **Scrutiny**

Note: We have the same issue for all the different stages, Case stage is not updating in Case details screen 

**Expected behavior**
When the case stage is changed, it should automatically reflect in Case details screen. instead of waiting for couple of minutes / Refreshing

**Screenshots**
https://jam.dev/c/c8f740ae-677b-4546-8997-076adfdcdfb1

**Comment by nileshgupta111** [comment]
this is due to delay in updating stage

**Comment by Beehyv-Vinod** [comment]
Tested in UAT environment, Working as expected
