### ISSUE TITLE
[BUG]: QA | Document not getting loaded in generate order page if we login as Judge 

### ISSUE THREAD

**Issue by RohiniKanala517** [pucardotorg/dristi#2266]
**Describe the bug**
Document not getting loaded in order which blocks further testing 

**To Reproduce**
1. Go to 'Case' in view case in Judge page
2. Click on 'Generate Order'
3. Scroll down to ''

**Expected behavior**

**Screenshots**
Please check the video for reference , https://jam.dev/c/f9fb438a-7194-4b82-bbb7-a8b438c35ee6

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by iknoorkaur** [comment]
Hi @rajeshcherukumalli: Tested in dpg-dev env, working fine as expected. Attaching video for reference:
https://jam.dev/c/b20f8108-5f0f-4e11-bcfc-3e6ec838473c
cc : @Ramu-kandimalla
