### ISSUE TITLE
[BUG]: [QA | Some words are missing in Malayalam in Judge login]

### ISSUE THREAD

**Issue by RohiniKanala517** [pucardotorg/dristi#2281]
**Describe the bug**
Some words still show in English even after language selection is Malayalam in Judge page. Please check

**To Reproduce**
1. Go to 'Login as Judge'
2. Click on 'View Case ' on any case

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/afb8647a-1566-48dc-854c-3467d33f1b64)
![image](https://github.com/user-attachments/assets/727908e3-fee1-44aa-9236-e8829b1d2017)
![image](https://github.com/user-attachments/assets/a7cd9a94-886c-4ed3-879d-687ba0cab1be)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Ramu-kandimalla** [comment]
Moving to sprint 13 release

**Comment by utpalBeehyv** [comment]
hi @rajeshcherukumalli all the localisation are done.....pls check

cc : @Ramu-kandimalla

**Comment by rajeshcherukumalli** [comment]
Hi @utpalBeehyv , issue is resolved please find the reference
![Image](https://github.com/user-attachments/assets/ccb3cfd4-8363-479b-ad4b-fa686bbc5dcc)
![Image](https://github.com/user-attachments/assets/3098e3d2-d642-42f3-936f-3ab43318e15c)
 ![Image](https://github.com/user-attachments/assets/fe8abb76-7477-4698-a6de-5654087bdbf0)

**Comment by rajeshcherukumalli** [comment]
Hi @Ramu-kandimalla , issue is fixed in UAT 
reference: ![Image](https://github.com/user-attachments/assets/1403400b-1d90-48f0-bdf1-c82695244d09)
