### ISSUE TITLE
[BUG]: courtId - during draft stage, this could null. 

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#2282]
**Describe the bug**
Its showing court Id - KLKM52

Endpoint: https://dristi-kerala-dev.pucar.org/case/v1/search/_summary
Request:  {
   "criteria": {
         "tenantId": "kl",
                //    "caseId": ["4c590e1d-0b1d-4973-879a-947c80cbb228"]
 "filingNumber": [
            "KL-000644-2024"
        ]
        // "filingNumber": [
        //     "KL-000644-2024"
        // ],
        //  "cnrNumber": [
        //    "KLKM520001312024"
        //  ]
    },  
    "tenantId": "kl",
    "RequestInfo": {
        "apiId": "Rainmaker",
        "authToken": "7f5c9cb5-b315-4329-878a-273c0d0f6916",
        "msgId": "1730110345085|en_IN",
        "plainAccessRequest": {}
    }
}

Response: {
    "responseInfo": {
        "apiId": "Rainmaker",
        "ver": null,
        "ts": null,
        "resMsgId": "uief87324",
        "msgId": "1730110345085|en_IN",
        "status": "successful"
    },
    "cases": [
        {
            "id": "4c590e1d-0b1d-4973-879a-947c80cbb228",
            "tenantId": "kl",
            "caseTitle": "complayyyyyy comp vs accXXXXXXXXXXX acc",
            "filingDate": 0,
            "statutesAndSections": " Negotiable Instrument Act, 02.",
            "stage": "Pre-Trial",
            "subStage": "Draft",
            "outcome": null,
            "litigants": [
                {
                    "partyCategory": "INDIVIDUAL",
                    "partyType": "complainant.primary",
                    "individualId": "IND-2024-10-17-001462",
                    "individualName": "complayyyyyy comp",
                    "organisationId": null,
                    "isPartyInPerson": null
                }
            ],
            "representatives": [
                {
                    "partyId": "4c590e1d-0b1d-4973-879a-947c80cbb228",
                    "advocateId": "3e8fad95-2a8b-4b6c-b63b-08be1726eb3a",
                    "advocateType": null
                }
            ],
            "judge": {
                "id": null,
                "name": null,
                "designation": null
            },
            "courtId": "KLKM52",
            "registrationDate": 0,
            "registrationNumber": null
        }
    ],
    "pagination": null
}

**Expected behavior**
courtId - during draft stage, this could null. 

**Screenshots**
https://jam.dev/c/9a901303-6d56-4776-bcf6-2d140b8a39d5

**Comment by rajeshcherukumalli** [comment]
Issue is resolved for Draft case :
{
    "ResponseInfo": {
        "apiId": "null",
        "ver": "null",
        "ts": null,
        "resMsgId": "uief87324",
        "msgId": null,
        "status": "successful"
    },
    "criteria": [
        {
            "caseId": null,
            "defaultFields": false,
            "cnrNumber": null,
            "filingNumber": "KL-000059-2024",
            "outcome": null,
            "courtCaseNumber": null,
            "caseSearchText": null,
            "filingFromDate": null,
            "filingToDate": null,
            "registrationFromDate": null,
            "registrationToDate": null,
            "judgeId": null,
            "stage": null,
            "substage": null,
            "litigantId": null,
            "advocateId": "1d08428a-1cf3-4161-a752-17335ffab1ec",
            "status": null,
            "responseList": [
                {
                    "id": "ff25e525-36f5-4931-8003-a1ca18d5aa41",
                    "tenantId": "kl",
                    "resolutionMechanism": "COURT",
                    "caseTitle": null,
                    "isActive": true,
                    "caseDescription": "Case description",
                    "filingNumber": "KL-000059-2024",
                    "courtCaseNumber": null,
                    "caseNumber": null,
                    "caseType": null,
                    "cnrNumber": null,
                    "cmpNumber": null,
                    "accessCode": null,
                    "outcome": null,
                    "courtId": null,
                    "benchId": "BENCH_ID",
                    "linkedCases": null,
                    "filingDate": 0,
                    "registrationDate": 0,
                    "judgementDate": 0,
                    "caseDetails": {},
                    "caseCategory": "CRIMINAL",
                    "judgeId": "JUDGE_ID",
                    "stage": null,
                    "substage": null,
                    "natureOfPleading": null,
                    "statutesAndSections": [
                        {
                            "id": "cf7be47e-13b6-42cd-bf15-aa21bbde8275",
                            "tenantId": "kl",
                            "statute": null,
                            "sections": [
                                "Negotiable Instrument Act",
                                "02."
                            ],
                            "subsections": [
                                "138",
                                "03."
                            ],
                            "additionalDetails": null,
                            "auditdetails": {
                                "createdBy": null,
                                "lastModifiedBy": null,
                                "createdTime": 0,
                                "lastModifiedTime": 0
                            },
                            "strSections": null,
                            "strSubsections": null
                        }
                    ],
                    "litigants": null,
                    "representatives": [
                        {
                            "id": "e8855193-3dd7-44d5-965c-cb203b958ea1",
                            "tenantId": "kl",
                            "advocateId": "1d08428a-1cf3-4161-a752-17335ffab1ec",
                            "caseId": "ff25e525-36f5-4931-8003-a1ca18d5aa41",
                            "representing": null,
                            "isActive": true,
                            "documents": null,
                            "auditDetails": {
                                "createdBy": "f0be783b-5eff-4beb-928b-8e342058c033",
                                "lastModifiedBy": "f0be783b-5eff-4beb-928b-8e342058c033",
                                "createdTime": 1731317131553,
                                "lastModifiedTime": 1731317131553
                            },
                            "additionalDetails": null
                        }
                    ],
                    "status": "DRAFT_IN_PROGRESS",
                    "documents": null,
                    "remarks": null,
                    "workflow": null,
                    "additionalDetails": {
                        "payerName": "kumar ad cn",
                        "payerMobileNo": "7857957897",
                        "advocateDetails": {
                            "formdata": [
                                {
                                    "data": {
                                        "isAdvocateRepresenting": {
                                            "code": "YES",
                                            "name": "Yes",
                                            "showForm": true,
                                            "isEnabled": true
                                        }
                                    },
                                    "isenabled": true,
                                    "displayindex": 0
                                }
                            ]
                        }
                    },
                    "auditDetails": {
                        "createdBy": "f0be783b-5eff-4beb-928b-8e342058c033",
                        "lastModifiedBy": "f0be783b-5eff-4beb-928b-8e342058c033",
                        "createdTime": 1731317131553,
                        "lastModifiedTime": 1731317131553
                    }
                }
            ],
            "pagination": null
        }
    ],
    "pagination": null
}
