### ISSUE TITLE
[BUG]: registrationDate - the case registration date. could be null, if the case has not yet been registered

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#2283]
**Describe the bug**
its showing zero.

Endpoint: https://dristi-kerala-dev.pucar.org/case/v1/search/_summary
Request:  {
   "criteria": {
         "tenantId": "kl",
                //    "caseId": ["4c590e1d-0b1d-4973-879a-947c80cbb228"]
 "filingNumber": [
            "KL-000644-2024"
        ]
        // "filingNumber": [
        //     "KL-000644-2024"
        // ],
        //  "cnrNumber": [
        //    "KLKM520001312024"
        //  ]
    },  
    "tenantId": "kl",
    "RequestInfo": {
        "apiId": "Rainmaker",
        "authToken": "7f5c9cb5-b315-4329-878a-273c0d0f6916",
        "msgId": "1730110345085|en_IN",
        "plainAccessRequest": {}
    }
}

Response:  {
    "responseInfo": {
        "apiId": "Rainmaker",
        "ver": null,
        "ts": null,
        "resMsgId": "uief87324",
        "msgId": "1730110345085|en_IN",
        "status": "successful"
    },
    "cases": [
        {
            "id": "4c590e1d-0b1d-4973-879a-947c80cbb228",
            "tenantId": "kl",
            "caseTitle": "complayyyyyy comp vs accXXXXXXXXXXX acc",
            "filingDate": 0,
            "statutesAndSections": " Negotiable Instrument Act, 02.",
            "stage": "Pre-Trial",
            "subStage": "Draft",
            "outcome": null,
            "litigants": [
                {
                    "partyCategory": "INDIVIDUAL",
                    "partyType": "complainant.primary",
                    "individualId": "IND-2024-10-17-001462",
                    "individualName": "complayyyyyy comp",
                    "organisationId": null,
                    "isPartyInPerson": null
                }
            ],
            "representatives": [
                {
                    "partyId": "4c590e1d-0b1d-4973-879a-947c80cbb228",
                    "advocateId": "3e8fad95-2a8b-4b6c-b63b-08be1726eb3a",
                    "advocateType": null
                }
            ],
            "judge": {
                "id": null,
                "name": null,
                "designation": null
            },
            "courtId": "KLKM52",
            "registrationDate": 0,
            "registrationNumber": null
        }
    ],
    "pagination": null
}

**Expected behavior**
 the case registration date. could be null, if the case has not yet been registered

**Screenshots**
https://jam.dev/c/9a901303-6d56-4776-bcf6-2d140b8a39d5

**Comment by atulgupta2024** [comment]
@manimaarans I am fine with 0 as the returned value. Need to make sure that UI understands 0 means no date.

**Comment by atulgupta2024** [comment]
datetime is stored as EPOCH value. A value of 0 would actually mean January 1, 1970, which is not really a valid date for us. also the data type is integer, so am not sure if we can set null value.

**Comment by rajeshcherukumalli** [comment]
Issue is resolved:
{
    "responseInfo": {
        "apiId": "null",
        "ver": "null",
        "ts": null,
        "resMsgId": "uief87324",
        "msgId": "8c11c5ca-03bd-11e7-93ae-92361f002671",
        "status": "successful"
    },
    "cases": [
        {
            "id": "5b638b48-0148-4449-9151-2adbba9a983b",
            "tenantId": "kl",
            "caseTitle": "undefined vs ",
            "filingDate": 0,
            "statutesAndSections": " Negotiable Instrument Act, 02.",
            "stage": "Pre-Trial",
            "subStage": "Draft",
            "outcome": null,
            "litigants": [],
            "representatives": [
                {
                    "partyId": "5b638b48-0148-4449-9151-2adbba9a983b",
                    "advocateId": "9cf432aa-be0a-4c17-8f72-685779ae040e",
                    "advocateType": null
                }
            ],
            "judge": {
                "id": null,
                "name": null,
                "designation": null
            },
            "courtId": null,
            "registrationDate": 0,
            "registrationNumber": null
        }
    ],
    "pagination": {
        "limit": 100,
        "offSet": 0,
        "totalCount": 1.0,
        "sortBy": "id; drop dristi_cases",
        "order": "desc"
    }
}
