### ISSUE TITLE
[BUG]: [QA | BLOCKER | Judge is unable to register and return the case for correction]

### ISSUE THREAD

**Issue by iknoorkaur** [pucardotorg/dristi#2288]
**Describe the bug**
Judge is not able to register and can't send the case back for correction

**To Reproduce**
1. Go to Judge user
2. Click on particular case
3. See error

**Expected behavior**
Judge should be able to register and should send the case back for correction

**Screenshots**
![image](https://github.com/user-attachments/assets/eae99c75-bf66-4d09-8bc0-b6ddb9a3c2ee)

**Comment by Ramu-kandimalla** [comment]
Hi @iknoorkaur  Please verify

**Comment by iknoorkaur** [comment]
Hi @Ramu-kandimalla, tested in QA env, working as expected.
![image](https://github.com/user-attachments/assets/2e0a5a57-64a3-4251-9a0d-47cd67a7b664)
