### ISSUE TITLE
UAT | Submissions by court Staff

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#2303]
Since this functionality is not built fully yet, this needs to be removed from court staff functionality

**Comment by Ramu-kandimalla** [comment]
Hi @Taherabharmal  this is a duplicate ticket Please refer [Ticket ](https://github.com/pucardotorg/dristi/issues/2113)

**Comment by Ramu-kandimalla** [comment]
Closing this ticket
