### ISSUE TITLE
[BUG]: UAT| Age value not showing in Review case file page.

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#2307]
**Describe the bug**
After given value for age field its not reflected on review case file page.

**To Reproduce**
1. While File a case
2. Click on 'Review case file' page
3. Scroll down to 'Accused details'

**Expected behavior**
Value should be appear.

**Screenshots**
https://jam.dev/c/a8002582-fad4-4dac-85d8-061e2aea5108

**Comment by kashish384** [comment]
Hi @TusharKatiyar2002, In QA[sol] env_Age value not showing in review case file page for complaint. kindly look...
https://jam.dev/c/9d0488ce-ff77-4e96-9c91-c0102d149280

**Comment by TusharKatiyar2002** [comment]
Hi @kashish384, can you check now

**Comment by kashish384** [comment]
Its working fine in QA [sol] env.
https://jam.dev/c/452452e4-d467-40ba-904e-7ea449da3c53

Its working fine in UAT env.
https://jam.dev/c/0e9a5324-0069-4cf4-8cf1-8afe560b8b9d
