### ISSUE TITLE
Write scripts for localisation to be loaded

### ISSUE THREAD

**Issue by subhashini-egov** [pucardotorg/dristi#2312]
Write a python script:

- [ ] Inputs will be the base server URL, user with LOC_ADMIN role, password, file path to Excel sheet containing localisation and list of locales to be configured
- [ ] Authenticate against the server with the provided user credentials. Throw exception if LOC_ADMIN role is not given to user.
- [ ]  Script to read from the localisation Excel sheet as mentioned in ticket #2158
- [ ] Script should call localisation API and configure the locales mentioned in the input.

**Comment by atulgupta2024** [comment]
it is critical that we have ways to upload the localization data in SDC UAT and Production environment. As long as the team is confidence is doing it in some way, not necessarily via scripts, it is ok. 

eventually we do need to have scripts as part of deployment pipeline. Please update the ticket as per, with appropriate comment on current status

**Comment by subhashini-egov** [comment]
@TusharKatiyar2002 you had shared the localisation scripts that are being used. I've enhanced it here --> https://github.com/pucardotorg/dristi-solutions/pull/1221. Can you please test this out and if it looks good, merge it? Have added a bit of error handling and input parameterization. CC: @anirudh-0 @Ramu-kandimalla @atulgupta2024 @suresh12

**Comment by rajeshcherukumalli** [comment]
As per the mentioned comments closing the ticket
