### ISSUE TITLE
[BUG]: [QA | Upload ID Proof field is not accepting the required format and the text should be changed]

### ISSUE THREAD

**Issue by iknoorkaur** [pucardotorg/dristi#2323]
**Describe the bug**
1. Upload ID Proof field is not accepting jpeg format
2. Upload ID Proof field is not accepting the .jpg/ .jpeg and png format.

**To Reproduce**
Steps to reproduce the behavior of point 1:
1. Go to new user -> register a new user with mobile no.
3. Click on upload your id

**Expected behavior**
1. Upload ID Proof field should accept the jpeg format and the text should be changed
2. Upload ID Proof field should accept the .jpg/ .jpeg and png format and the text should be changed

**Screenshots**
1. https://jam.dev/c/a1a823f2-df6e-46bb-901b-f6a3a3a21c52
3. ![image](https://github.com/user-attachments/assets/7021719a-0a1d-41ee-84ad-07362fa0d6ba)

**Comment by shambhavigoel1002** [comment]
Hi @rajeshcherukumalli this issue has been fixed in dev env please test.
cc:- @Ramu-kandimalla

**Comment by shambhavigoel1002** [comment]
Hi @iknoorkaur 
It seems the fix has been done for the upload in user registration not e-filing as per the details mentioned in steps to reproduce and jam that was attached . Will make the changes as per new video that is just attached .
cc:- @Ramu-kandimalla  @rajeshcherukumalli

**Comment by iknoorkaur** [comment]
Hi @shambhavigoel1002 , i was refering to the 2nd point for which the screenshot was attached.
cc : @Ramu-kandimalla @rajeshcherukumalli

**Comment by shambhavigoel1002** [comment]
Hi @iknoorkaur  made the changes in dev env please test
cc :- @rajeshcherukumalli @Ramu-kandimalla

**Comment by iknoorkaur** [comment]
Hi @shambhavigoel1002 Tested in dpg dev, but the changes are not reflecting. can you please recheck once.
Attaching the video for reference:
[upload.webm](https://github.com/user-attachments/assets/e6121a20-1db3-4d64-a5a6-89201027d0fd)
cc : @rajeshcherukumalli @Ramu-kandimalla

**Comment by iknoorkaur** [comment]
Tested in dpg-dev, working fine as expected:
https://jam.dev/c/ebcdf3a9-4e93-4dca-aa3e-089643b25bc6
@rajeshcherukumalli @Ramu-kandimalla
