### ISSUE TITLE
BUG || {BLOCKER} After Rejecting an Advocate from Nyay-Mitra, It cannot be registered again.

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#2324]
**QA & UAT**

After Advocate is rejected by Nyay-Mitra, then If it registers it self again on same number, UI is not responding after BAR Registration Number window.

ADV NUMBER : 7100000015

Refer screenshots

![image](https://github.com/user-attachments/assets/2dd2e8e1-6df6-47c5-83b4-2ff9a0cf4934)

**Comment by Ramu-kandimalla** [comment]
This Data has to be removed from DB then advocate can be registered with same information again

This is a Edge case scenario
