### ISSUE TITLE
[BUG]: [QA | Change the text of the e-filing case document fields]

### ISSUE THREAD

**Issue by iknoorkaur** [pucardotorg/dristi#2325]
**Describe the bug**
Upload .jpg, .pdf or .png. Maximum upload size of 50MB text should also include ".jpeg" word in the text.

**Expected behavior**
IT should be "Upload .jpeg, .jpg, .pdf or .png. Maximum upload size of 50MB"

**Screenshots**
(https://jam.dev/c/3c3b4120-32b8-466a-afda-f8aca0eb3611)

**Comment by shambhavigoel1002** [comment]
Hi @rajeshcherukumalli made the respective changes . please check .
cc:- @Ramu-kandimalla

**Comment by iknoorkaur** [comment]
Hi @rajeshcherukumalli, tested in QA Env, working as expected:
[format.webm](https://github.com/user-attachments/assets/3af35baa-80dc-43f8-925c-55be7fe665a5)
cc: @Ramu-kandimalla
