### ISSUE TITLE
[BUG]: Version numbering required in docker images

### ISSUE THREAD

**Issue by subhashini-egov** [pucardotorg/dristi#2356]
This was discussed in today's tech council. Ideal process for deployment to UAT:

1. Merge code from develop to main
2. Build docker images from main branch with version numbering. The first go live release is 1.0. Till then, 0.x will be the version. @suresh12 can provide the exact numbering
3. Deploy built images into UAT

CC: @Ramu-kandimalla @suresh12 @atulgupta2024

**Comment by Rkum113** [comment]
@Ramu-kandimalla , Now docker image tag will have tag release verion in it.
If we create tag with version like V0.5.1-uat image tag will also have v0.5.1-uat and tag will be created from main branch form now on for dristi-solution
