### ISSUE TITLE
[BUG]: [QA | Court staff user should be able to upload .png/.jpg and.jpeg and text should also be changed.]

### ISSUE THREAD

**Issue by iknoorkaur** [pucardotorg/dristi#2358]
**Describe the bug**
Court staff user is not able to upload .png/.jpg and.jpeg and text should also be changed.

**To Reproduce**
1. Go to 'court staff user'
2. Click on Review Summons, Notices & Warrants
3. Click on particular case for order tpe of Summons, Notices & Warrants
4. Click on esign
5. See error

**Expected behavior**
Court staff user should be able to upload .png/.jpg and.jpeg and text should also be changed.
Text should be: "Upload .pdf, .jpeg, .jpg, .png. Maximum upload size of 5MB"

**Screenshots**
[pdf.webm](https://github.com/user-attachments/assets/e3752718-590a-48e4-8c26-ed63252e6e29)

**Comment by shambhavigoel1002** [comment]
Hi @iknoorkaur updated the changes in dpg-qa env Please verify 
cc:- @rajeshcherukumalli @Ramu-kandimalla

**Comment by iknoorkaur** [comment]
Hi @shambhavigoel1002 Tested in dpg dev for notices, summons and warrants, 
Encountered an issue with warrants: When selecting a case with the "Warrant" order type, the review document is initially unavailable. However, after applying an e-signature, the document appears. This should not be the case, it should work in similar way as it is happening for notices and summons.
Attaching the video for reference:
[issue.webm](https://github.com/user-attachments/assets/2827cd43-5d61-4d35-b3a3-0b25841a16f3)
cc: @rajeshcherukumalli @Ramu-kandimalla

**Comment by iknoorkaur** [comment]
Raised this ticket: https://github.com/pucardotorg/dristi/issues/2367, so closing this one.
