### ISSUE TITLE
[Deployment]: [Prepare SDC Prod environment]

### ISSUE THREAD

**Issue by suresh12** [pucardotorg/dristi#2364]
**Describe the bug**
Prepare infra for production and verify a test deployment. Prepare Database, File Storage, Whitelisting, Access, etc.  

Pre Production Deployment Work
- Setup DB with master slave architecture
- Setup Minio
- Setup Elastic Search
- Setup Ingress
- implement HPA and cronjob in UAT

**Comment by atulgupta2024** [comment]
@suresh12 @Pasam6 all activities being done should be as per the installation guide. will be a good way to make sure that nothing is missed out from the guide including things like whitelisting, access, external integration settings, etc.

**Comment by Pasam6** [comment]
Implemented HPA with 2 pods as minimum number of pods for a service and trigger a new pod when 80% of resources like memory and cpu is crossed.

**Comment by atulgupta2024** [comment]
@Pasam6 is it a new when we hit 80%. I think we may want to do something like new pod if we remain above 75% for 2-3 min. Else we may end up creating a new pod even for sudden spikes.

**Comment by Pasam6** [comment]
@atulgupta2024 This is implemented,
stabilizationWindowSeconds: 120 sec for scaling up and 60sec for scaling down. 

Regarding memory requests for each service should i consider the actual service consumption in uat / sdc  and provide double the resource

**Comment by atulgupta2024** [comment]
@Pasam6 yes, that can be good value to start with

**Comment by Pasam6** [comment]
**Setup DB with master slave architecture** : Need to make the failover automatic and create a virtual ip which maps to both master & slave nodes.
**Setup Minio**: Need to create virtual ip and use rsync to make the data replicated into standby minio
**Setup Elastic Search**: Completed
**Setup Ingress**: Completed
**implement HPA and cronjob in UAT** : Implemented HPA for services in  pucar-prod namespace. Regarding cronjob , developer has to create an api for scheduler then only we can implement cronjob .

**Comment by Ramu-kandimalla** [comment]
Production deployment is completed and tested @suresh12
