### ISSUE TITLE
[Deployment]: [GOGS Test Deployment within PUCAR]

### ISSUE THREAD

**Issue by suresh12** [pucardotorg/dristi#2366]
- Pull source code from Dristi Release to OnCourts Repo

**Comment by Rkum113** [comment]
I have pushed source code to Oncourts repo on gogs

**Comment by Ramu-kandimalla** [comment]
[like]  Ramu Kandimalla reacted to your message:
________________________________

**Comment by Ramu-kandimalla** [comment]
Source Code is deployed the GoGS oncourts Repo @suresh12 @mehulseg24

**Comment by suresh12** [comment]
Checked the repo, looks fine. Any change we need, we will do it as part of the deployment task @Ramu-kandimalla
