### ISSUE TITLE
BUG || SDC Re-routing ERROR in URL 

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#2377]
on going to this https://oncourts-uat2.kerala.gov.in/digit-ui/citizen/, URL is being re-routed to https://oncourts-uat2.kerala.gov.in/digit-ui/citizen/error 

same for employee URL. 

![image](https://github.com/user-attachments/assets/3ad1c29a-4e51-4bcd-98b0-8e3adf240f15)

CURL : `curl 'https://oncourts-uat2.kerala.gov.in/egov-mdms-service/v1/_search?tenantId=kl' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  -H 'Cookie: 794378cd2e449209c1d4b58909347e26=9fa57062deb173d7f9d958c3be9e578a' \
  -H 'Origin: https://oncourts-uat2.kerala.gov.in' \
  -H 'Referer: https://oncourts-uat2.kerala.gov.in/digit-ui/citizen/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  --data-raw '{"MdmsCriteria":{"tenantId":"kl","moduleDetails":[{"moduleName":"common-masters","masterDetails":[{"name":"Department"},{"name":"Designation"},{"name":"StateInfo"},{"name":"wfSlaConfig"},{"name":"uiHomePage"}]},{"moduleName":"tenant","masterDetails":[{"name":"tenants"},{"name":"citymodule"}]},{"moduleName":"DIGIT-UI","masterDetails":[{"name":"ApiCachingSettings"}]}]},"RequestInfo":{"apiId":"Rainmaker","msgId":"1731132457254|en_IN","plainAccessRequest":{}}}'`

**Comment by Pasam6** [comment]
Resolved . This issue is caused due to mdms script for migration in uat.sql
