### ISSUE TITLE
BUG || OCR-Service ERROR in DPG-DEV

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#2378]
Getting this OCR-Service ERROR in DPG-DEV 

![image](https://github.com/user-attachments/assets/10ae1315-1342-49e3-8de5-fdd47305a731)

URL : 
https://dristi-dev.pucar.org/ocr-service/verify?_=1731133387269

Response : {
    "ResponseInfo": null,
    "Errors": [
        {
            "id": null,
            "parentId": null,
            "code": "ResourceAccessError",
            "message": "An error occurred while accessing a underlying resource",
            "description": null,
            "params": null
        }
    ]
}

CURL: `curl 'https://dristi-dev.pucar.org/ocr-service/verify?_=1731133387269' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'content-type: application/json;charset=UTF-8' \
  -H 'origin: https://dristi-dev.pucar.org' \
  -H 'priority: u=1, i' \
  -H 'referer: https://dristi-dev.pucar.org/digit-ui/citizen/dristi/home/file-case/case?caseId=2239a539-fad3-4584-9339-a2c01d19dcfc&selected=chequeDetails' \
  -H 'sec-ch-ua: "Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36' \
  --data-raw '{"documentType":"CHEQUE_RETURN_MEMO","fileStoreId":"d4237261-fc14-4b24-bf5a-c6a278f860bc","filingNumber":"KL-000034-2024","tenantId":"kl","RequestInfo":{"apiId":"Rainmaker","authToken":"b10bd7f6-caf1-485d-aa69-781fdb4a161d","userInfo":{"id":136,"uuid":"d2c10a02-9d9e-43c2-90f8-1d10feb42685","userName":"9990000000","name":"LIT GURU null","mobileNumber":"9990000000","emailId":null,"locale":null,"type":"CITIZEN","roles":[{"name":"CASE_VIEWER","code":"CASE_VIEWER","tenantId":"kl"},{"name":"HEARING_VIEWER","code":"HEARING_VIEWER","tenantId":"kl"},{"name":"DEPOSITION_VIEWER","code":"DEPOSITION_VIEWER","tenantId":"kl"},{"name":"Citizen","code":"CITIZEN","tenantId":"kl"},{"name":"APPLICATION_CREATOR","code":"APPLICATION_CREATOR","tenantId":"kl"},{"name":"SUBMISSION_DELETE","code":"SUBMISSION_DELETE","tenantId":"kl"},{"name":"CASE_RESPONDER","code":"CASE_RESPONDER","tenantId":"kl"},{"name":"HEARING_ACCEPTOR","code":"HEARING_ACCEPTOR","tenantId":"kl"},{"name":"DEPOSITION_CREATOR","code":"DEPOSITION_CREATOR","tenantId":"kl"},{"name":"ORDER_VIEWER","code":"ORDER_VIEWER","tenantId":"kl"},{"name":"SUBMISSION_RESPONDER","code":"SUBMISSION_RESPONDER","tenantId":"kl"},{"name":"CASE_EDITOR","code":"CASE_EDITOR","tenantId":"kl"},{"name":"APPLICATION_VIEWER","code":"APPLICATION_VIEWER","tenantId":"kl"},{"name":"SUBMISSION_CREATOR","code":"SUBMISSION_CREATOR","tenantId":"kl"},{"name":"TASK_VIEWER","code":"TASK_VIEWER","tenantId":"kl"},{"name":"CASE_CREATOR","code":"CASE_CREATOR","tenantId":"kl"}],"active":true,"tenantId":"kl","permanentCity":null},"msgId":"1731133387269|en_IN","plainAccessRequest":{}}}'`

**Comment by Rkum113** [comment]
This is known issue as we are not running ocr python service in dpg-dev.
