### ISSUE TITLE
[BUG]: [DPG-DEV | 2 input errors displaying on Advocate Details tab]

### ISSUE THREAD

**Issue by iknoorkaur** [pucardotorg/dristi#2384]
**Describe the bug**
When filing a case through the advocate user role, there isn’t a separate flag for ID proof. So, when we mark defect in the documents, it is currently showing up as " 2 input errors".

**To Reproduce**
1. Go to Advocate user -> file a case
2. Go to fso
3. Scroll down to Advocate Details screen
4. Click on flag -> mark defect
5. See error

**Expected behavior**
It should display as 1 input error, and a seperate flag for id proof.

**Screenshots**
https://jam.dev/c/bb06e8f3-3615-4501-9bea-e79092843ff0

**Comment by vaibhavct** [comment]
@iknoorkaur So whenever an error is marked on entire document section, all documents will be marked, hence two errors are getting displayed.
We don't have functionality to edit/update Advocate ID as of now, so you can close this bug
c.c. @Ramu-kandimalla
