### ISSUE TITLE
[BUG]: [DPG-DEV | Workflow Exception in "send for advocate sign" button]

### ISSUE THREAD

**Issue by iknoorkaur** [pucardotorg/dristi#2385]
**Describe the bug**
When we click on "Send for advocate sign" button, the update api is failing.

**To Reproduce**
1. Go to advocate user -> file a new case -> submit the case with signed pdf
2. Go to fso -> mark defect
3. Go to litigent -> update the defect field -> esign for litigent -> "send for advocate sign"

**Expected behavior**
Able to proceed further when we click on "send for advocate sign""

**Screenshots**
https://jam.dev/c/17bbe59c-7fb6-48a4-8efb-f1227fd0af3d

**Comment by utpalBeehyv** [comment]
hi @Ramu-kandimalla I guess this is a backend issue

**Comment by Ramu-kandimalla** [comment]
Hi @Hemadri-Chinna  can you please check

**Comment by iknoorkaur** [comment]
Tested in dpg-dev, working as expected
Attaching jam video for reference:
https://jam.dev/c/a505948a-5dc5-4e2d-a505-69fb9ad124a4
cc: @Ramu-kandimalla @rajeshcherukumalli
