### ISSUE TITLE
UAT: Disable the Vakalatnama fees in the payment calculator during E-Filing as it is calculating incorrect value

### ISSUE THREAD

**Issue by mehulseg24** [pucardotorg/dristi#2390]
**Describe the bug**
Disbale the following fees from the payment calculator & create an infobox in the upload vakalatnama textbox

**Expected behavior**
1. Disable the following fees items from the payment Calculator
    Vakalathnama Fee = INR 6
    Advocate Welfare Fund = AWF (Refer Section 3.3.4)
    Advocate Clerk’s Welfare Fund = INR 12
2. Create an infobox in upload vakalatnama field in e-filing and the Join a case saying, "Please attach stamps on the Vakalatnama and submit the same to the filing section of 24x7 On Courts, online payment facility is under development"

**Comment by Ramu-kandimalla** [comment]
Hi @mehulseg24  this will be covered in sprint 14

**Comment by Ramu-kandimalla** [comment]
Hi @Susmitabe  Please confirm this feature in production

**Comment by Susmitabe** [comment]
Its working fine
