### ISSUE TITLE
BUG || File Download Not working 

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#2394]
**SDC, DPG-DEV**

Getting 401 UnAuth Error in UI re-direct when clicking on Download File 

Refer Screenshot

![image](https://github.com/user-attachments/assets/c7fc00e8-3b8c-4e1d-a7b8-e31311bbe3c6)

**Comment by rajeshcherukumalli** [comment]
Hi @Ramu-kandimalla , the issue is resolved please find the reference
https://jam.dev/c/b2f51b59-8d12-4159-bb4a-88a8c9420027

**Comment by bhuvanyuguru** [comment]
HI @rajeshcherukumalli 

Working fine in UAT 

![image](https://github.com/user-attachments/assets/651ccd0a-75b8-412e-a7e5-01402840edaf)
