### ISSUE TITLE
BUG || APIs getting 200 Status without AuthToken 

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#2395]
**UAT**

While testing APIs in Postman these APIs are getting 200 Status OK without AuthToken

**BACK-END Services**
![image](https://github.com/user-attachments/assets/b615014b-71b7-4db9-8da2-fca964a03c57)

CURL : `curl --location 'https://dristi-kerala-uat.pucar.org/egov-pdf/order?tenantId=kl&orderId=bbe8ed4f-0d16-4dd4-ba4c-ef4dac2dfae7&cnrNumber=KLKM520001742024&qrCode=false&orderType=schedule-hearing-date' \
--header 'accept: application/json, text/plain, */*' \
--header 'accept-language: en-GB,en;q=0.9' \
--header 'content-type: application/json;charset=UTF-8' \
--header 'origin: https://dristi-kerala-uat.pucar.org' \
--header 'priority: u=1, i' \
--header 'referer: https://dristi-kerala-uat.pucar.org/digit-ui/employee/orders/generate-orders?filingNumber=KL-000105-2024&orderNumber=KL-000105-2024-OR6' \
--header 'sec-ch-ua: "Not?A_Brand";v="99", "Chromium";v="130"' \
--header 'sec-ch-ua-mobile: ?0' \
--header 'sec-ch-ua-platform: "Linux"' \
--header 'sec-fetch-dest: empty' \
--header 'sec-fetch-mode: cors' \
--header 'sec-fetch-site: same-origin' \
--header 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36' \
--data '{
    "RequestInfo": {
        "authToken":"",
        "userInfo": {
            "id": 143,
            "uuid": "c1c4a708-afd6-4c9c-91a5-fd6c8517fb39",
            "userName": "uatJudge01",
            "name": "uatJudge01",
            "mobileNumber": "1002335566",
            "emailId": null,
            "locale": null,
            "type": "EMPLOYEE",
            "roles": [
                {
                    "name": "HEARING_VIEWER",
                    "code": "HEARING_VIEWER",
                    "tenantId": "kl"
                },
                {
                    "name": "DEPOSITION_EDITOR",
                    "code": "DEPOSITION_EDITOR",
                    "tenantId": "kl"
                },
                {
                    "name": "WORKFLOW_ABANDON",
                    "code": "WORKFLOW_ABANDON",
                    "tenantId": "kl"
                },
                {
                    "name": "ORDER_ESIGN",
                    "code": "ORDER_ESIGN",
                    "tenantId": "kl"
                },
                {
                    "name": "Workflow Admin",
                    "code": "WORKFLOW_ADMIN",
                    "tenantId": "kl"
                },
                {
                    "name": "DEPOSITION_PUBLISHER",
                    "code": "DEPOSITION_PUBLISHER",
                    "tenantId": "kl"
                },
                {
                    "name": "TASK_APPROVER",
                    "code": "TASK_APPROVER",
                    "tenantId": "kl"
                },
                {
                    "name": "HEARING_START",
                    "code": "HEARING_START",
                    "tenantId": "kl"
                },
                {
                    "name": "HEARING_APPROVER",
                    "code": "HEARING_APPROVER",
                    "tenantId": "kl"
                },
                {
                    "name": "ORDER_VIEWER",
                    "code": "ORDER_VIEWER",
                    "tenantId": "kl"
                },
                {
                    "name": "SUBMISSION_RESPONDER",
                    "code": "SUBMISSION_RESPONDER",
                    "tenantId": "kl"
                },
                {
                    "name": "ORDER_REASSIGN",
                    "code": "ORDER_REASSIGN",
                    "tenantId": "kl"
                },
                {
                    "name": "CASE_EDITOR",
                    "code": "CASE_EDITOR",
                    "tenantId": "kl"
                },
                {
                    "name": "APPLICATION_APPROVER",
                    "code": "APPLICATION_APPROVER",
                    "tenantId": "kl"
                },
                {
                    "name": "TASK_CREATOR",
                    "code": "TASK_CREATOR",
                    "tenantId": "kl"
                },
                {
                    "name": "HEARING_DATE_REQUESTOR",
                    "code": "HEARING_DATE_REQUESTOR",
                    "tenantId": "kl"
                },
                {
                    "name": "Employee",
                    "code": "EMPLOYEE",
                    "tenantId": "kl"
                },
                {
                    "name": "ORDER_DELETE",
                    "code": "ORDER_DELETE",
                    "tenantId": "kl"
                },
                {
                    "name": "CASE_VIEWER",
                    "code": "CASE_VIEWER",
                    "tenantId": "kl"
                },
                {
                    "name": "APPLICATION_REJECTOR",
                    "code": "APPLICATION_REJECTOR",
                    "tenantId": "kl"
                },
                {
                    "name": "TASK_EDITOR",
                    "code": "TASK_EDITOR",
                    "tenantId": "kl"
                },
                {
                    "name": "ORDER_APPROVER",
                    "code": "ORDER_APPROVER",
                    "tenantId": "kl"
                },
                {
                    "name": "HEARING_CLOSER",
                    "code": "HEARING_CLOSER",
                    "tenantId": "kl"
                },
                {
                    "name": "ORDER_CREATOR",
                    "code": "ORDER_CREATOR",
                    "tenantId": "kl"
                },
                {
                    "name": "JUDGE_ROLE",
                    "code": "JUDGE_ROLE",
                    "tenantId": "kl"
                },
                {
                    "name": "CASE_APPROVER",
                    "code": "CASE_APPROVER",
                    "tenantId": "kl"
                },
                {
                    "name": "DEPOSITION_CREATOR",
                    "code": "DEPOSITION_CREATOR",
                    "tenantId": "kl"
                },
                {
                    "name": "SUBMISSION_APPROVER",
                    "code": "SUBMISSION_APPROVER",
                    "tenantId": "kl"
                },
                {
                    "name": "TASK_UPDATOR",
                    "code": "TASK_UPDATOR",
                    "tenantId": "kl"
                },
                {
                    "name": "TASK_VIEWER",
                    "code": "TASK_VIEWER",
                    "tenantId": "kl"
                },
                {
                    "name": "HEARING_SCHEDULER",
                    "code": "HEARING_SCHEDULER",
                    "tenantId": "kl"
                }
            ],
            "active": true,
            "tenantId": "kl",
            "permanentCity": null
        },
        "msgId": "1730978016647|en_IN",
        "apiId": "Rainmaker"
    }
}'`
 
 
 **COMMON SERVICES**
 
 
![image](https://github.com/user-attachments/assets/bc171680-ee01-4e9a-ac23-132828fbdacd)

CURL : `curl --location 'https://dristi-kerala-uat.pucar.org/localization/messages/v1/_search?tenantId=kl&locale=en_IN&module=notification&codes=null' \
--header 'Content-Type: application/json' \
--data '{
  "RequestInfo": {
    "apiId": "Rainmaker",
    "ver": ".01",
    "ts": "",
    "action": "_create",
    "did": "1",
    "key": "",
    "msgId": "20170310130900|en_IN",
    "authToken":""
  }
  }'`
  
  CURL :`curl --location 'https://dristi-kerala-uat.pucar.org/egov-mdms-service/v1/_search' \
--header 'Content-Type: application/json' \
--data '{
    "RequestInfo": {
        "apiId": "asset-services",
        "ver": null,
        "ts": null,
        "action": null,
        "did": null,
        "key": null,
        "msgId": "search with from and to values",
        "authToken":"",
        "correlationId": null,
        "userInfo": {
            "id": "1",
            "userName": null,
            "name": null,
            "type": null,
            "mobileNumber": null,
            "emailId": null,
            "roles": null,
            "uuid": "40dceade-992d-4a8f-8243-19dda76a4171"
        }
    },
    "MdmsCriteria": {
        "tenantId": "kl",
        "moduleDetails": [
            {
                "moduleName": "ACCESSCONTROL-ACTIONS-TEST",
                "masterDetails": [
                    {
                        "name": "actions-test"
                        
                    }
                ]
            },
            {
                "moduleName": "ACCESSCONTROL-ROLEACTIONS",
                "masterDetails": [
                    {
                        "name": "roleactions"
                        
                    }
                ]
            },
            {
                "moduleName": "ACCESSCONTROL-ROLES",
                "masterDetails": [
                    {
                        "name": "roles"
                        
                    }
                ]
            }
        ]
    }
}'`

CURL : `curl --location 'https://dristi-kerala-uat.pucar.org/filestore/v1/files/url?tenantId=kl&fileStoreIds=' \
--header 'accept: application/json, text/plain, */*' \
--header 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
--header 'priority: u=1, i' \
--header 'referer: https://dristi-kerala-uat.pucar.org/digit-ui/employee/dristi/home/view-case?caseId=1b75efe3-38a8-4555-9cab-81d301fb7d6d&filingNumber=KL-000451-2024&tab=Documents' \
--header 'sec-ch-ua: "Not?A_Brand";v="99", "Chromium";v="130"' \
--header 'sec-ch-ua-mobile: ?0' \
--header 'sec-ch-ua-platform: "Linux"' \
--header 'sec-fetch-dest: empty' \
--header 'sec-fetch-mode: cors' \
--header 'sec-fetch-site: same-origin' \
--header 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36'`

**Comment by radheshjoshi1** [comment]
/egov-mdms-service/v1/_search
/localization/messages/v1/_search
these two endpoints are being called before login so we cannot have any authorization for it @bhuvanyuguru

**Comment by bhuvanyuguru** [comment]
HI @radheshjoshi1 

Issue resolved in **DPG-DEV**

![Image](https://github.com/user-attachments/assets/5502ad52-cefa-4302-8784-48c440293825)

(These 2 APIs are white-listed)
![Image](https://github.com/user-attachments/assets/bfaec5f4-51ab-4470-9ed8-17d052aaeac6)

**Comment by bhuvanyuguru** [comment]
Hi @radheshjoshi1, 

APIs are working as expected in **UAT**

![Image](https://github.com/user-attachments/assets/1bc775fb-1808-4839-99ca-98b89221b937)

![Image](https://github.com/user-attachments/assets/ad6bdce1-b630-4c25-91bf-601ef141888f)
