### ISSUE TITLE
[BUG]: [DPG-DEV | Some words are missing in Malayalam in View Case]

### ISSUE THREAD

**Issue by rajeshcherukumalli** [pucardotorg/dristi#2420]
Reference:
![Screenshot from 2024-11-14 18-25-16](https://github.com/user-attachments/assets/9d8918fb-b09d-4a32-92e0-2a46849d38ef)

**Comment by rajeshcherukumalli** [comment]
![Screenshot from 2024-11-14 18-30-20](https://github.com/user-attachments/assets/8cc46b9a-0d47-40a9-8af6-66680947a4a5)
![Screenshot from 2024-11-14 18-30-46](https://github.com/user-attachments/assets/7f542ad1-e99d-4652-9688-55c0ed9e7e80)
![Screenshot from 2024-11-14 18-31-09](https://github.com/user-attachments/assets/655d2f74-a429-43dd-b1ef-40726272d922)
![Screenshot from 2024-11-14 18-31-30](https://github.com/user-attachments/assets/00984f83-d6dc-41b7-be8c-6eed5301ee02)
![Screenshot from 2024-11-14 18-32-38](https://github.com/user-attachments/assets/36c15b56-8df6-4038-afa3-5556473aee31)
![Screenshot from 2024-11-14 18-32-56](https://github.com/user-attachments/assets/616e5ea3-218b-47ed-a530-197ec60f35b6)

**Comment by utpalBeehyv** [comment]
hi @devarajd94 added some new string in sheet
https://docs.google.com/spreadsheets/d/1Cbf1w77Khc8Z_U0QSRF9xy0EZ17YdzICQCcpfUkyK_4/edit?gid=790431664#gid=790431664

cc : @rajeshcherukumalli

**Comment by rajeshcherukumalli** [comment]
![Screenshot from 2024-11-16 12-33-23](https://github.com/user-attachments/assets/d54079ea-b6ef-428a-b7a8-9ac2d1b5cda6)
![Screenshot from 2024-11-16 12-53-00](https://github.com/user-attachments/assets/7be21a71-c451-4dc2-9fce-88ed00560f2a)
![Screenshot from 2024-11-16 12-53-26](https://github.com/user-attachments/assets/bcd31132-4c27-4eba-9be5-d20fa1579c38)
![Screenshot from 2024-11-16 12-56-27](https://github.com/user-attachments/assets/6d0f8313-6132-4e05-9f2a-e30b231b5348)
