### ISSUE TITLE
PROD SUPPORT: A high number of lawyer registration requests are not reaching NyayMitra

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#2422]
A high number of lawyer registration requests are not reaching NyayMitra. They are unable to re-register as their Bar Id is already stored.

**Comment by Ramu-kandimalla** [comment]
I have raised a ticket with Digit Team to address this issue,  we will do lawyer data dump in production it wont be an issue 

 [Egov Ticket](https://github.com/egovernments/Digit-Core/discussions/613)

we can temporarily fix this issue from backend for training purposes if required 

Please provide your inputs as well @subhashini-egov  @atulgupta2024

**Comment by atulgupta2024** [comment]
@subhashini-egov has already suggested --- 

```
enrich workflow and mdms in advocate service and push to Kafka topic. Remove the enrichment config in indexer. This will work.
``` 

as a temporary stop gap, please create a script that calls that calls the advocate/update API and marks the registration as approved, to by pass the Nyay mitra approving the request

@Ramu-kandimalla @manimaarans

**Comment by Ramu-kandimalla** [comment]
Hi @atulgupta2024  We  have already uploaded 75% of advocate data in to production system we will complete the rest 25% also once we got the details from high court  @suresh12 

@subhashini-egov  @atulgupta2024  @suresh12 Please consider this request as a high we will be address this item once production is stable

**Comment by atulgupta2024** [comment]
@Ramu-kandimalla I am fine with that. Are the advocates trying to register into the system, those whose data we could not upload or are they new advocates? 

If we get new advocates who are trying to register on the site, we will keep hitting this issue.

**Comment by bhuvanyuguru** [comment]
Hi @rajeshcherukumalli 

Tested in UAT 

Nyay mitra is receiving all advocate requests in request section.

Refer screenshot

![image](https://github.com/user-attachments/assets/70db11b6-228a-4f7c-82df-1defea48e1a2)

**Comment by mehulseg24** [comment]
Please test and close @Taherabharmal @devarajd94 @ansh-egov

**Comment by Susmitabe** [comment]
This issue is not occurring now in production, we will reopen if it again happens   . CC- @devarajd94
