### ISSUE TITLE
BUG || BLOCKER in Pending Payment after Signing in Mandatory Submission 

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#2429]
**DPG-DEV**

> STEPS TO REPRODUCE 
> - After Signing Application, BLOCKER in Pending Payment for the same 

Refer Screenshot

![image](https://github.com/user-attachments/assets/6659b4ed-960e-4246-a9b8-5bd1fd61327b)

**Comment by Ramu-kandimalla** [comment]
Hi @bhuvanyuguru  Please retest this bug

**Comment by bhuvanyuguru** [comment]
Hi @nitish-beehyv, @Ramu-kandimalla, @rajeshcherukumalli 

This Issue is Resolved in **DPG-DEV** 

Refer Screenshot

![Image](https://github.com/user-attachments/assets/2051aa30-bc4c-4f5d-8281-ce2cadf53c66)

**Comment by bhuvanyuguru** [comment]
HI @Ramu-kandimalla , @rajeshcherukumalli 

Working fine in **UAT**

Refer Screenshots

![Image](https://github.com/user-attachments/assets/88f854ab-f9e6-4c91-9a4f-5a88c992b521)


![Image](https://github.com/user-attachments/assets/257ea6aa-e0b0-45bc-a818-ef136a9fbff3)
