### ISSUE TITLE
BUG || Undefined shown in Pending Submissions

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#2430]
**DPG-DEV**

Undefined shown in Pending Submissions 

Refer Screenshots

https://dristi-kerala-uat.pucar.org/digit-ui/citizen/dristi/home/login

**Comment by Ramu-kandimalla** [comment]
Hi @bhuvanyuguru Please retest this bug

**Comment by bhuvanyuguru** [comment]
HI @nitish-beehyv 

This Issue is not Resolved in **DPG-DEV**

Pending Payment for Submission is not show in MY PENDING SUBMISSIONS Section


Refer Screenshot 

![Image](https://github.com/user-attachments/assets/a296edce-4f8f-4b7c-b649-639d0ac7b865)

**Comment by bhuvanyuguru** [comment]
Hi @nitish-beehyv, @Ramu-kandimalla 

This Issue is resolved in **DPG-DEV**

Refer Screenshot
![Image](https://github.com/user-attachments/assets/8a03f4e5-2525-45dd-ae3e-046324e13c58)

![Image](https://github.com/user-attachments/assets/03b96c92-2994-4f31-91bd-f68f08a6a386)
