### ISSUE TITLE
Payment Breakup not visible

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#2438]
Payment breakup not visible during offline payments

steps to replicate:
1) File a case as complainant
2) Sign case
3) Go to home screen
4) Click on Pending task for payment
5) Click of pay online
6) Now close browser
7) Login as nyay mitra and try to collect payment

For video, see 'Payment breakup not visible' video on Dev coordination group

**Comment by kashish384** [comment]
Its working fine in UAT env.
-url: https://dristi-kerala-uat.pucar.org/digit-ui/citizen/home/home-pending-task
https://dristi-kerala-uat.pucar.org/digit-ui/employee/dristi/pending-payment-inbox/pending-payment-details?filingNumber=KL-000650-2024&businessService=case-default&consumerCode=KL-000650-2024_CASE_FILING&paymentType=Case%20Filing%20Fee

-reference link:https://jam.dev/c/065b99a4-4b29-41d1-9551-668d40c56145
-Test scenario:
1.Payment breakup is visible during offline payments.
-Test cases:
https://docs.google.com/document/d/1KPI5vxGIuplXoZTnPS-TIntdf_DtXUdhM-ujoOZb67Q/edit?tab=t.0
