### ISSUE TITLE
[BUG]: [QA] Stage is displaying as malayalam for few stages and english for few stages 

### ISSUE THREAD

**Issue by rajeshcherukumalli** [pucardotorg/dristi#2440]
![Screenshot from 2024-11-16 13-06-04](https://github.com/user-attachments/assets/07e49671-f1fc-4d43-82fe-f0da1b94b095)

**Comment by Hemadri-Chinna** [comment]
Hi @iknoorkaur 
![image](https://github.com/user-attachments/assets/3643b497-327e-44ec-95e5-2e74aea04bea)
can you please check now

**Comment by iknoorkaur** [comment]
Hi @rajeshcherukumalli tested in dpg-dev, malayalam text working fine in stage for judge and litigent user role:
![image](https://github.com/user-attachments/assets/9230f020-f4ab-4cb2-876c-f261a278b293)
