### ISSUE TITLE
[BUG]: [dpg-sol-dev | date of deposit cheque field is able to enter before date of cheque issue]

### ISSUE THREAD

**Issue by iknoorkaur** [pucardotorg/dristi#2442]
**Describe the bug**
date of deposit cheque field is able to enter before date of cheque issue

**To Reproduce**
1. Register a new litigent
2. Click on file a new case
3. See error

**Expected behavior**
date of deposit cheque field should not be able to enter before date of cheque issue

**Screenshots**
https://jam.dev/c/d85967ba-4671-4e23-8adb-b982c4e4c2f8

**Comment by utpalBeehyv** [comment]
hi @iknoorkaur not reproducible

cc: @Ramu-kandimalla @rajeshcherukumalli
