### ISSUE TITLE
[BUG]: cant make submission in arguments phase

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#2447]
my understanding is as an advocate i can make a submission at any stage. case is in arguments stage with hearing scheduked, dont see option to submit application
<img width="1467" alt="image" src="https://github.com/user-attachments/assets/b1904c4f-824c-447c-99f1-bb2b875d3a86">

**Comment by kashish384** [comment]
Its working fine in UAT env.
https://jam.dev/c/985f7db7-e8dc-4637-a196-11fd62f75bb2
