### ISSUE TITLE
[BUG]: [Print Case is not Working]

### ISSUE THREAD

**Issue by iknoorkaur** [pucardotorg/dristi#2456]
**Describe the bug**
Print Case is not Working

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rajeshcherukumalli** [comment]
Hi @maruthiPhanendra , issue is resolved please find the reference
https://jam.dev/c/fb4b8cba-dfcc-4198-80ad-b23885cdc62f

**Comment by iknoorkaur** [comment]
Tested in UAT Env, working as expected.
Attaching jam video for reference: https://jam.dev/c/b995c7b6-9f2a-4e36-abfc-41f05e30bcf3
