### ISSUE TITLE
[BUG]: [UAT | Epost option is not working]

### ISSUE THREAD

**Issue by iknoorkaur** [pucardotorg/dristi#2457]
**Describe the bug**
The update remarks are reflected in court staff user but not in the judge pending tasks.

**To Reproduce**
1. Go to court staff user.
2. Click on particular case and update the remarks and esign.
3. Go to judge -> pending tasks

**Screenshots**
![image](https://github.com/user-attachments/assets/7aa0b81b-6c64-476c-82a5-7fdbee1d2ecf)

**Additional context**
Getting RE_ISSUE after changing status of Request ot Delivered in Epost

**Comment by iknoorkaur** [comment]
Hi @Ajith-beehyv, Kindly assign this ticket to Harsh.

**Comment by bhuvanyuguru** [comment]
Hi @Ramu-kandimalla, it's partially working, will check in UAT.

**Comment by bhuvanyuguru** [comment]
HI @rajeshcherukumalli 

Working fine in UAT 

refer screenshot

![Image](https://github.com/user-attachments/assets/087dcf27-f2a6-4661-8dfc-b3997670fb30)
