### ISSUE TITLE
[BUG]: [UAT | Online payments are not working]

### ISSUE THREAD

**Issue by iknoorkaur** [pucardotorg/dristi#2458]
**Describe the bug**
Online payments are not working.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by iknoorkaur** [comment]
Hi @Ajith-beehyv, kindly assign this ticket to Harsh.

**Comment by Beehyv-Vinod** [comment]
Hi @Ramu-kandimalla  @rajeshcherukumalli Tested in UAT env, Payments are working Fine & Pending task also clearing from the list.
