### ISSUE TITLE
PROD SUPPORT: Vakalatnama Template is wrong

### ISSUE THREAD

**Issue by devarajd94** [pucardotorg/dristi#2493]
Upload the following file in the download template button

[Vakalat Template.docx](https://github.com/user-attachments/files/17815674/Vakalat.Template.docx)

Refer the following video for details

https://github.com/user-attachments/assets/643d36b1-94b8-4064-9172-a56dc0900ba9

**Comment by iknoorkaur** [comment]
Tested in UAT Env, working as expected:
https://jam.dev/c/9abb986b-d163-4c49-a040-54e2e57eb8a9
cc: @Ramu-kandimalla @rajeshcherukumalli

**Comment by Susmitabe** [comment]
@iknoorkaur did we tested this in UAT?

**Comment by iknoorkaur** [comment]
yes @Susmitabe, have attached jam video for reference in the above comment.

**Comment by mehulseg24** [comment]
Please test and close @Taherabharmal @devarajd94 @ansh-egov

**Comment by anshumanth-egov** [comment]
signed off

**Comment by TusharKatiyar2002** [comment]
It is already updated in Prod. Please confirm the same in Prod @Susmitabe

**Comment by Susmitabe** [comment]
resolved
