### ISSUE TITLE
UAT: Auto select city drop down for Employee login

### ISSUE THREAD

**Issue by atulgupta2024** [pucardotorg/dristi#2506]
![image](https://github.com/user-attachments/assets/16b447ed-3a78-4cbf-8a9f-7d454b2c7567)

there is only 1 city for now. have that auto selected in the drop down. Will mean 1 less (unnecessary) click for the judges and other court staff. Better user experience. 

@suresh12 @Ramu-kandimalla - this is not a showstopper or anything like, but definitely an irritant for login. it will greatly enhance the user experience at the time of login. We should get this addressed. Should be 1 line code change.

**Comment by atulgupta2024** [comment]
converting to PROD Hotfix, as it is easy to fix and good benefit for user convenience

**Comment by atulgupta2024** [comment]
| Column 1 | Column 2 | Column 3 |

|---|---|---|

| Data 1 | Data 2 | Data 3 |

| Data 4 | Data 5 | Data 6 |

**Comment by atulgupta2024** [comment]
| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |

**Comment by utpalBeehyv** [comment]
hi @rajeshcherukumalli chnages are done in uat, pls check

cc : @Ramu-kandimalla

**Comment by iknoorkaur** [comment]
Tested in UAT Env, working as expected.
Attaching screenshot for reference:
![image](https://github.com/user-attachments/assets/79de59b1-b115-4138-9245-820d9b2079d6)
cc: @Ramu-kandimalla @rajeshcherukumalli

**Comment by atulgupta2024** [comment]
@iknoorkaur @Ramu-kandimalla @rajeshcherukumalli @suresh12 @Taherabharmal @mehulseg24 @aditiphadnis93

I just realized - isn't KL - State. City would be Kollam i.e. KM. So if we are showing KL, should we change the label to "State"

**Comment by iknoorkaur** [comment]
Tested in UAT env, working as expected.
Attaching screenshot for reference:
![Uploading image.png…]()
cc: @Ramu-kandimalla @rajeshcherukumalli

**Comment by Susmitabe** [comment]
Need to be tested by @devarajd94 @ansh-egov

**Comment by anshumanth-egov** [comment]
tested, signed off
