### ISSUE TITLE
PROD Hotfix: reset CMP, CNR and ST series 

### ISSUE THREAD

**Issue by atulgupta2024** [pucardotorg/dristi#2511]
the first case registered in ONCourts got a CMP of CMP/49/2024. This is not correct. It should have started off with 1. Need to fix this from backend. 

1. update the case to modify the CMP
2. reset the sequence number in our DB 
3. similarly reset the sequence number in DB for CNR and ST

This should have been handled as part of PROD clean up before go live, but it was missed. So need to handle it now. 

@suresh12 @devarajd94

**Comment by atulgupta2024** [comment]
can be done via either of the two options below 

`ALTER SEQUENCE sequence_name RESTART WITH 1;`

OR 

`SELECT SETVAL('sequence_name', 1, false);`

**Comment by atulgupta2024** [comment]
@manimaarans no change in filing number. for the CMP, CNR and ST.. let's wait for @devarajd94  to confirm the number that is currently used, unless we can find from the DB directly.

**Comment by Pasam6** [comment]
![Screenshot from 2024-11-21 17-31-49](https://github.com/user-attachments/assets/6a4f1aff-dc63-4926-b712-5fa64ebf417e)
Modified the cmp and cnr value.

Note: Data in elastic search is not updated

**Comment by atulgupta2024** [comment]
@Pasam6 @manimaarans we need to ensure that we do update Elastic and more importantly update the PostgreSQL's SEQUENCE no as well. We need to ensure that the next CMP generated will be CMP/2/2024 and CNR will be KLKM520000022024

**Comment by Susmitabe** [comment]
Resolved
