### ISSUE TITLE
PROD Hotfix: Update Judge name on the Order Templates

### ISSUE THREAD

**Issue by mehulseg24** [pucardotorg/dristi#2512]
change the name of Judge on the orders from John Koshy to Smt. Soorya S Sukumaran

**Comment by atulgupta2024** [comment]
this would mean 
1. update the order template PDF with the right name? or we are picking up the name from HRMS ? 
2. we need to make sure we create Judge with the correct name 

@suresh12 @mehulseg24 @Ramu-kandimalla @manimaarans

**Comment by iknoorkaur** [comment]
Tested in the UAT environment and working fine with the following scenarios:
1. Generating an order as a judge.
2. Making submissions as a litigant/advocate, followed by the judge accepting or rejecting the submissions.
Attaching jam video for reference: https://jam.dev/c/544674e4-b664-4998-af0d-0ba3ca3c95a8
cc : @Ramu-kandimalla @rajeshcherukumalli

**Comment by atulgupta2024** [comment]
@iknoorkaur @Ramu-kandimalla @rajeshcherukumalli @manimaarans did we create the Judge using HRMS now? 

@suresh12

**Comment by rajeshcherukumalli** [comment]
Hi @atulgupta2024 , Previously it was hard coded but now we are getting from global config and environment variables , if we need to create user we need to check it @manimaarans  can you confirm the same.

**Comment by Pasam6** [comment]
The VARIABLES JUDGE_NAME, JUDGE_DESIGNATION were added to dristi-pdf .
VARIABLE JUDGE_NAME added to scheduler,
global config judge-designation, judge-name were added to digit-ui global config and latest code of digit-ui is deployed to Production environment. 
if possible can any of you test and confirm the same in prod. @mehulseg24 @suresh12

**Comment by Susmitabe** [comment]
The Judge name is visible now

**Comment by mehulseg24** [comment]
Signed off on UAT for Schedule a hearing and issuance of notice to move to production through a hotfix (as confirmed by Suresh on Development group as on 22 Nov)

**Comment by Susmitabe** [comment]
@TusharKatiyar2002  please deploy to production and update
