### ISSUE TITLE
Nyaymitra can't see the registration request of advoacte

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#2515]
**Describe the bug**
Advocate Registration flow is breaking 
Request not received to nyaymitra

![image](https://github.com/user-attachments/assets/15542052-e5d3-4276-a29b-a83dd64eb2f6)

**Comment by atulgupta2024** [comment]
similar to #2422. closing this

**Comment by mehulseg24** [comment]
Let's add a locatization text saying : If your registration hasn't been approved within 2 hours, don't worry! You can reach our Helpline at +91-472-2919099 or write to us at niacourtkollam@gmail.com
