### ISSUE TITLE
PROD SUPPORT: [Filing]: [Change heading to  Affidavit under section 223]

### ISSUE THREAD

**Issue by muhammed-sawad** [pucardotorg/dristi#2526]
**Describe the bug**
Now it is showing as Affidavit under Section 223 of BNSS Examination in chef

**Expected behavior**
Needs to be "Affidavit under Section 223 " only , remove examination in chief part - Showstopper

**Comment by muhammed-sawad** [comment]
screenshot:
![image](https://github.com/user-attachments/assets/6a6e00d8-aad3-475f-9d05-a461f51abc15)

**Comment by Susmitabe** [comment]
@mehulseg24  please connect with Abhishek for clarification

**Comment by mehulseg24** [comment]
1. Not a High Prioirity Bug
2. Will require explicit sign-off from HC to proceed. Taken a note of this langusge change - allow me to discuss with HC and get back.

**Comment by mehulseg24** [comment]
Signed off from High Court, to be planned as of 29/11

Actions required
1. Name change as described in the bug above
2. Section heading change - remove In Lieu of The cami nation in Chief
3. BNSS 2024 to be revised to BNSS 2023

**Comment by mehulseg24** [comment]
Please tag to concerned Dev. @rajeshcherukumalli @Susmitabe

**Comment by abhishekrao2024** [comment]
Currently it is:

**Affidavit in Lieu of Examination-in-Chief**
Upload Affidavit to be submitted in-lieu of statement under Section 223, Bharatiya Nagarik Suraksha Sanhita 2024

To

**Affidavit under section 223 of BNSS**
Upload Affidavit to be submitted under Section 223, Bharatiya Nagarik Suraksha Sanhita 2024

**Comment by Ramu-kandimalla** [comment]
Hi @Susmitabe @muhammed-sawad  

Please verify this in Production

**Comment by Susmitabe** [comment]
Its showing as expected
