### ISSUE TITLE
PROD SUPPORT: JPG file not supported 

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#2537]
**Describe the bug**
The advocate uploaded the documents, but while clicking on final step to upload sign it showed error as "Something went Wrong".
Later realised there was issue with jpg file , we converted the jpg file to  pdf.

**Comment by Susmitabe** [comment]
Please refer 2422  -https://github.com/orgs/pucardotorg/projects/1/views/37?pane=issue&itemId=87269558&issue=pucardotorg%7Cdristi%7C2422

**Comment by Ramu-kandimalla** [comment]
This issue is not reproducible in UAT & we have verified this file type in Production as well, Please verify and confirm @tanmaybhateja @mehulseg24  @devarajd94

**Comment by Susmitabe** [comment]
resolved
