### ISSUE TITLE
PROD SUPPORT: Complainant Address Details should be able to editable

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#2538]
**Describe the bug**
Complainant details should be edit address details

**Comment by atulgupta2024** [comment]
we discussed the approach - submit. FSO passes to the judge and the Judge reverts it back for update. That is when the other fields will be editable and address can be updated. If any other error is there, let it be shared offline

**Comment by atulgupta2024** [comment]
Discussed with @manimaarans. the case will be sent back by the Judge and then we will fix from backend. @Susmitabe let us know when the case is sent back. For completness, do provide the correct address here, which we need to use

@suresh12 @FYI

@Taherabharmal @mehulseg24 @aditiphadnis93 something to think about - while this may be a one off case, but not allowing complainant address to be modified - is this something we want to review?

**Comment by atulgupta2024** [comment]
Ok @manimaarans 

@Susmitabe can you close the ticket?
