### ISSUE TITLE
PROD SUPPORT: Case name and E-Filing id should have space between

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#2541]
**Describe the bug**
A minor correction required... there is no space between the case title and filing number. There should be a blank space after the comma (before the filing number).

![image](https://github.com/user-attachments/assets/c68f83c8-00d7-4603-b003-4e856bfb8a97)

**Comment by bhuvanyuguru** [comment]
Hi @rajeshcherukumalli , @Susmitabe , @Ramu-kandimalla 

Working fine in UAT

Refer screenshot

![image](https://github.com/user-attachments/assets/5fcef43d-d612-4917-ab42-34a596e46ab6)

**Comment by anshumanth-egov** [comment]
signed off

**Comment by muhammed-sawad** [comment]
Working as expected

**screenshot for ref**
![case_title_space_filing_no](https://github.com/user-attachments/assets/5fe86f88-58b3-4fc6-85dc-c6938f9ca550)
