### ISSUE TITLE
PROD SUPPORT: The advocate did the payment, but not received the e-receipt  and nyaymitra's portal its showing pending 

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#2548]
**Describe the bug**
The advocate did the payment, but not received the e-receipt and nyaymitra's portal its showing pending but the payment has gone through  , delivery channel - Register post court fee .
This happened while doing payment for issuing notice - BNSS 223 Notice court fee they made online

![image](https://github.com/user-attachments/assets/d3f57cdb-b8c9-4728-9a83-5ea82fb4b0b8)

**Comment by atulgupta2024** [comment]
@Susmitabe what is the expectation from me in this? This is to be resolved by the implementation team. @Ramu-kandimalla @manimaarans

**Comment by rajeshcherukumalli** [comment]
Hi @Susmitabe , another ticket https://github.com/pucardotorg/dristi/issues/2549 is created on the same , closing this ticket with the reference.
