### ISSUE TITLE
SUPPORT PROD: No rounding off - Should be .75 only

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#2549]
**Describe the bug**

Every fee which is getting processed there should be exact amount deducted, not any roundoff amount.
 0.75 is rounding off to RS 1 , should not happen

**Comment by atulgupta2024** [comment]
I don't think we are doing any rounding off in our code. It is mostly happening eTreasury side

**Comment by atulgupta2024** [comment]
@Susmitabe i would think that we should "close as not planned" because the ticket's expectation are not valid anymore. 

we can log a separate ticket for rounding off amounts to next higher number. later if we require to update it, we can open a new ticket.
