### ISSUE TITLE
PROD SUPPORT: Verifying Valid E-Sign for the Case Using Aadhaar

### ISSUE THREAD

**Issue by rajeshcherukumalli** [pucardotorg/dristi#2552]
The system should check the authenticity of the e-signature using a secure and compliant validation method.
The verification status (valid, invalid, or unable to verify) should be displayed clearly.

**Comment by bhuvanyuguru** [comment]
Hi @prasanna2400 , @rajeshcherukumalli 

Verified E-Signature in DPG-DEV

Refer Screenshot 

![Image](https://github.com/user-attachments/assets/7029b2eb-b801-43c4-921a-47dec6673544)

**Comment by prasanna2400** [comment]
production key was updated in prod , not able to test in uat , @tanmaybhateja  please check confirm functionality. staging creds was tested in dpg-dev and its working as expected

**Comment by bhuvanyuguru** [comment]
Hi @Ramu-kandimalla, @rajeshcherukumalli 

Working fine in UAT. 

Refer Screenshot

![image](https://github.com/user-attachments/assets/8eb7b532-7599-4e07-b932-f2374061b3df)

**Comment by Susmitabe** [comment]
Working fine , but need to refresh every time to see the changes. Eg- when E-sign was done for both litigant & advocate and when clicked next button , it showed something went wrong popup and when refreshed the screen was showing pending payment.

**Comment by Ramu-kandimalla** [comment]
This is maybe some browser related issue can you please check once again and confirm

**Comment by Susmitabe** [comment]
its working
