### ISSUE TITLE
PROD SUPPORT: Bench clerk is getting cases without scrutiny check

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#2556]
**Describe the bug**
"3 issues with bench clerk's (CRM's) ID: 
1. Cases directly coming to the bench clerk's (CRM's) ID without scrutiny
2. Lots of test cases on the bench clerk's (CRM's) ID 
3. Cases not filed and merely in draft format are also visible on the bench clerk's (CRM's) ID "

**Comment by anirudh-0** [comment]
> Manimaaran: we need to pass the appropriate filter values so that Courtstaff see only the cases that are in relavant stage 

@vaibhavct can you work on this ?

**Comment by vaibhavct** [comment]
@Taherabharmal @devarajd94  @manimaarans 
We're sending following status in criterea  "PENDING_REGISTRATION", "PENDING_ADMISSION", "ADMISSION_HEARING_SCHEDULED", "CASE_ADMITTED", "PENDING_ADMISSION_HEARING", "PENDING_NOTICE", "PENDING_RESPONSE",
c.c. @Ramu-kandimalla

**Comment by atulgupta2024** [comment]
@vaibhavct @manimaarans  i had pointed out for Judge's case visibility also. if we tightly bind this to workflow states, then it becomes an issue, as when a workflow changes, it will break the flow. 

we need to have a business requirement and then figure out how to control the access. **AVOID** using workflow stages directly

**Comment by vaibhavct** [comment]
@Taherabharmal  @devarajd94  @manimaarans @atulgupta2024 
Let me know how we're going to proceed on it further.
c.c. @anirudh-0  @Ramu-kandimalla

**Comment by atulgupta2024** [comment]
I would think that Judge's access should get enabled once he/she is assigned to the case. So a judge sees only those cases where his/her ID is judge's ID. 

If bench clerks are associated with a Judge, then they should see the same cases. This may not need an explicit assignment. 

if they are not a single judge specific, but are rather court complex/building specific or work across multiple court rooms, judges, then the same logic will apply and will need to search across judges. Will need to figure out a way to optimize this search 

@subhashini-egov thoughts?

**Comment by subhashini-egov** [comment]
A bench clerk is assigned to the case by default basis the judge ID. Judges and bench clerks are linked to each other via court rooms. This is all done in the HRMS. So the logic should be:

- Fetch the judge details from HRMS. Identify the bench clerk for the judge. 
- If current logged in user matches the id fetched from HRMS, then they should see all the cases the judge sees.

If required, we can consider adding an addition param to the APi spec to explicity call out the bench clerk assigned to the case. This can be an array so we can keep deactivating/reactivating as clerks keep changing. And it should listen for changes to bench clerk assignments from HRMS/masters so it can also update the case. This can be documented as workaround in lieu of doing it in code.

**Comment by mehulseg24** [comment]
Sync with Susmita on this conducted with PT as on 28/11

**Comment by anirudh-0** [comment]
@atulgupta2024 @subhashini-egov will this be a backend change ? i.e. recognizing what cases bench clerk should have access to and sending only those cases through the filter ? Frontend is assigning judgeId when FSO forwards case to judge.

cc @manimaarans

**Comment by vaibhavct** [comment]
@manimaarans  @anshumanth-egov @Taherabharmal @devarajd94 Currently we have following filter on cases, with case Status on home page of bench clerk. Please let me know what changes are required with the same.
c.c. @anirudh-0  @Ramu-kandimalla 
All - `[
                "PENDING_REGISTRATION",
                "PENDING_ADMISSION",
                "ADMISSION_HEARING_SCHEDULED",
                "CASE_ADMITTED",
                "PENDING_ADMISSION_HEARING",
                "PENDING_NOTICE",
                "PENDING_RESPONSE",
              ]`
              
Ongoing -  `[
                "PENDING_REGISTRATION",
                "PENDING_ADMISSION",
                "ADMISSION_HEARING_SCHEDULED",
                "CASE_ADMITTED",
                "PENDING_ADMISSION_HEARING",
                "PENDING_NOTICE",
                "PENDING_RESPONSE",
              ]`
              
Registerd - `[
                "PENDING_REGISTRATION",
                "PENDING_ADMISSION",
                "ADMISSION_HEARING_SCHEDULED",
                "PENDING_ADMISSION_HEARING",
                "PENDING_NOTICE",
                "PENDING_RESPONSE",
              ]`

**Comment by vaibhavct** [comment]
@Ramu-kandimalla @manimaarans 
We're sending the same status in criteria of case Search API
c.c. @anirudh-0

**Comment by bhuvanyuguru** [comment]
Hi @Ramu-kandimalla, @rajeshcherukumalli, @Susmitabe 

Working fine in UAT 

Refer Screenshots 

![Image](https://github.com/user-attachments/assets/57a03f7c-047c-496e-a234-f6661cfd06eb)

**Comment by vaibhavct** [comment]
@anshumanth-egov We're fetching all the existing Stages from MDMS data and showing it in a dropbox on bench clerk home page.
Is that okay or do we need any changes in it as well?
c.c. @manimaarans  @anirudh-0  @bhuvanyuguru 
![Image](https://github.com/user-attachments/assets/da6b6ac2-2d9b-4236-8988-17271360fd3d)

**Comment by Ramu-kandimalla** [comment]
Hi @ansh-egov  Please sign off

**Comment by vaibhavct** [comment]
@anshumanth-egov The list is coming from MDMS, we're displaying as it is in the UI, I think recently added stage comes on top.

**Comment by anshumanth-egov** [comment]
I will get back to you on this, need Tahera's inputs

**Comment by atulgupta2024** [comment]
@vaibhavct @anshumanth-egov if I recall correctly, we had said that drop downs should usually show data in alphabetically sorted manner. The list looks fine, except "registration", which is appearing at the top.

**Comment by anshumanth-egov** [comment]
Yes alphabetical is fine. 
Wanted confirmation that we have all these stages, but we can do that later, lets proceed with alphabetical order.

**Comment by atulgupta2024** [comment]
@anshumanth-egov **stage based access is tricky** and that's what I have been explaining to the team, 

Take for example - a Judge (and associated clerk) ideally see a case only when it has come to them for registration i.e. in PENDING_REGISTRATION stage. They should not be seeing the case in stages like pending payment, pending e-sign, pending scrutiny etc. 

But at the time of pending _registration, the judge may find issues and sends the case back to the litigants for update. Now that the Judge has already been assigned to the case, he (and the clerk) **need to continue** to see the case even if they are under pending esign, or pending scrutiny. 

hence stage based access is *not* a good idea 

@manimaarans @anirudh-0 @Taherabharmal @suresh12 @subhashini-egov @vaibhavct @Ramu-kandimalla @Susmitabe

**Comment by atulgupta2024** [comment]
@anshumanth-egov

**Comment by anshumanth-egov** [comment]
<img width="1011" alt="image" src="https://github.com/user-attachments/assets/0904d4f1-c25a-4d57-bcbb-df6b14d98285" />
I logged in with Benchclerk01, I can still see draft cases

**Comment by Ramu-kandimalla** [comment]
Hi @rajeshcherukumalli  @shambhavigoel1002  Please check this issues once

**Comment by bhuvanyuguru** [comment]
Hi @anshumanth-egov  try using  

username : gClerk
password: Beehyv@123

It's working fine for this User, as it has updated roles

![image](https://github.com/user-attachments/assets/0889ce21-b3eb-425d-b386-d27036cd2bd4)

**Comment by shambhavigoel1002** [comment]
Hi @bhuvanyuguru , Changes have been done .Please test the changes in UAT .
cc : @rajeshcherukumalli @Ramu-kandimalla

**Comment by bhuvanyuguru** [comment]
Hi @Ramu-kandimalla, @rajeshcherukumalli , @anshumanth-egov 

Working fine in UAT 

User : gClerk 
Pwd : Beehyv@123


Refer Screenshot
![image](https://github.com/user-attachments/assets/8892e047-da6d-4fa0-a28a-8d2cda4ca982)

**Comment by Ramu-kandimalla** [comment]
Hi @anshumanth-egov  Please verify now

**Comment by anshumanth-egov** [comment]
The numbers for judge and clerk arent matching 

Judge
<img width="363" alt="image" src="https://github.com/user-attachments/assets/d3a555c5-35df-4471-a247-26481ccdd89a" />
<img width="539" alt="image" src="https://github.com/user-attachments/assets/1614c9d9-c9f2-44af-b4fd-7b94299a4f24" />


Benchclerk
<img width="347" alt="image" src="https://github.com/user-attachments/assets/d221d4f9-4e3f-4e58-9ef2-6d613ca04373" />
<img width="532" alt="image" src="https://github.com/user-attachments/assets/3a9f80b1-1cce-4a90-810d-429b95be2c3e" />

**Comment by bhuvanyuguru** [comment]
Hi  @Ramu-kandimalla , @Susmitabe , @shambhavigoel1002 

Resolved in UAT 

Cases shown in Judge and Bench-clerk is same. 

@anshumanth-egov Please verify and Sign-off 

Bench Clerk: 
![Image](https://github.com/user-attachments/assets/df3b81f3-13c4-4cf6-b092-7c4e6f557fea)


Judge : 
![Image](https://github.com/user-attachments/assets/30034c76-6203-4c45-bde0-6a7772d3253c)

**Comment by anshumanth-egov** [comment]
Signed off

**Comment by muhammed-sawad** [comment]
@bhuvanyuguru 
Draft Items and Pending submissions are showing on Bench clerk portal
**Screenshots**
Bench Clerk Portal
![Screenshot 2024-12-18 145334](https://github.com/user-attachments/assets/83bc85a4-e388-4ce6-80d8-d0a458df9290)

**Judge Portal**
![Screenshot 2024-12-18 145356 (1)](https://github.com/user-attachments/assets/57a8617d-4c5c-47cc-bd4b-57975689ae90)

**Comment by suresh12** [comment]
@bhuvanyuguru Is this some role access needs migration in prod?

**Comment by bhuvanyuguru** [comment]
I am checking the issue @suresh12, might be a role issue.

**Comment by muhammed-sawad** [comment]
Working as expected
**screenshot**
**Judge**
![image](https://github.com/user-attachments/assets/f904b165-c557-4bfe-b31c-f564514bdce6)
**Bench clerk** 
![Screenshot 2024-12-19 110241 (1)](https://github.com/user-attachments/assets/40cdccfa-8fb1-4fbb-8738-890572aa8fb7)
