### ISSUE TITLE
PROD SUPPORT: Enhancement /No option to flag complainant's address

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#2571]
**Describe the bug**
No option to flag complainant's address
![Uploading image.png…]()

**Comment by mehulseg24** [comment]
From Tahera - "This was not in the scope so I don’t know. Only complainant details if added via a phone number was not to be changed as per design"

Please do a thorough QA testing on this and report what all fields for which the FSO does not have an option to mark an error. @rajeshcherukumalli @Susmitabe

**Comment by Susmitabe** [comment]
@atulgupta2024 need confirmation on design

**Comment by atulgupta2024** [comment]
@Susmitabe the above image is not showing up. and as for design, again, nothing stopping on tech side. We had taken a call that we will do the profile updates etc, at a later date (time pressures). 

it is more of now prioritizing this feature and adding to the backlog to get done. There is nothing much required on tech design side.

**Comment by Susmitabe** [comment]
@atulgupta2024  currently few of the cases are pending due to this issue , that they provide different address as per their address proof and scrutiny can't flag.

@tanmaybhateja  @devarajd94  @mehulseg24  @ansh-egov

**Comment by Susmitabe** [comment]
Discussed with court magistrate, confirmed that as long as the proof of Id is matching with the name regardless of different address is not an issue. Closing this ticket
