### ISSUE TITLE
PROD SUPPORT: Enhancement/ Scrutiny / Need to change respondent to accused

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#2572]
**Describe the bug**
Need to change respondent to accused

![Image](https://github.com/user-attachments/assets/17f911b2-b580-42d3-939c-c27461a8fddd)

![Image](https://github.com/user-attachments/assets/9dae9913-041a-4c41-bc26-fbda8137f9d7)

**Comment by iknoorkaur** [comment]
Hi @Susmitabe, Tested in UAT Env, in various screens where we need to update the term "respondent" to "accused".
Attaching screenshots for reference:
![image](https://github.com/user-attachments/assets/8550243d-ab1b-420c-9bbb-da13ca567915)
![image](https://github.com/user-attachments/assets/73d3920c-fe65-42a0-9ec6-3e7ae8876f3c)
![image](https://github.com/user-attachments/assets/efc5ab51-d279-46c3-bb3a-a1bd308c13c5)
![image](https://github.com/user-attachments/assets/1122101a-ee60-42ae-a04b-837c4e8aa0f8)
cc: @Ramu-kandimalla @rajeshcherukumalli

**Comment by Susmitabe** [comment]
@ansh-egov please check this in UAT and provide a signoff

**Comment by anshumanth-egov** [comment]
signed off
