### ISSUE TITLE
PROD SUPPORT: Not able to use full stop or any special characters in description for filing a submission by the adv

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#2596]
**Describe the bug**
Not able to use full stop or any special characters in description for filing a submission by the adv

![image](https://github.com/user-attachments/assets/b5947f15-2f37-4e82-b37b-a13606be1e46)

**Comment by Susmitabe** [comment]
@rajeshcherukumalli please check if it is occurring in UAT

**Comment by rajeshcherukumalli** [comment]
Hi @Susmitabe , As design the details field is not accepted the special characters.

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  @ansh-egov  @Taherabharmal  As per the requirement special charterers are not allowed, Please confirm

**Comment by devarajd94** [comment]
@Ramu-kandimalla can you please point me to the design specification doc/ticket. I shall get it clarified as to why it was designed that way

**Comment by Ramu-kandimalla** [comment]
Hi @devarajd94  Please find the below Screen shot from PRD ![Image](https://github.com/user-attachments/assets/f1355e48-83ba-4a91-b6c0-bec41916e086)


All the text feilds should be alpha numeric only

**Comment by Ramu-kandimalla** [comment]
Hi @Susmitabe This is a duplicate ticket please refer to #2598

**Comment by Susmitabe** [comment]
@Ramu-kandimalla  2598 is different ticket , same issue but for different section
