### ISSUE TITLE
PROD SUPPORT: Scrutiny |In the complainant text field the scrolling option is not there for FSO

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#2600]
**Describe the bug**
In the complainant text field the scrolling option is not there for FSO

@rajeshcherukumalli  please confirm in UAT

**Comment by iknoorkaur** [comment]
Hi @Susmitabe, Scrolling functionality is working as expected when no colon (:) is added. However, if we enter colon then the text before the colon disappears, This issue occurs across all text fields.
Attaching jam video for reference: https://jam.dev/c/01b9bb9d-f618-4a21-b71c-06f9eb9f94e8 
cc: @Ramu-kandimalla @rajeshcherukumalli

**Comment by Susmitabe** [comment]
Its  resolved , we can see the scrolling feature in scrutiny for the complainant text
