### ISSUE TITLE
PROD SUPPORT : Courtstaff | There should be confirmation box before accepting registration request

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#2601]
**Describe the bug**
If we click on 'accept' button when we get any advocate registration request, it is getting approved without asking confirmation. It should ask for confirmation as there may be mis-clicks

@ansh-egov & @devarajd94 kindly confirm if we should get this enhancement

**Comment by anirudh-0** [comment]
@devarajd94 @Susmitabe we will also have a confirmation to reject the request, as an extension of this request.

**Comment by anshumanth-egov** [comment]
@anirudh-0 we already confirmation for reject
<img width="590" alt="image" src="https://github.com/user-attachments/assets/5f90f579-8a69-43c5-9006-39b0bd199e31">

**Comment by devarajd94** [comment]
Once confirmed the data cannot be edited. Are you sure you want to accept the registration request?

Yes <the request is accepted>
No < close the confirmation box popup and return to the verification screen of that request>

**Comment by maruthiPhanendra** [comment]
hi @devarajd94 , @Susmitabe  can you provide Malayalam text for below words 
1. Once confirmed the data cannot be edited. Are you sure you want to accept the registration request?
2. Confirm Advocate Application
![image](https://github.com/user-attachments/assets/603f9d32-9b7d-426a-952c-4446342711da)

**Comment by iknoorkaur** [comment]
Hi @Susmitabe, Tested in UAT Env, working as expected.
Attaching jam video for reference: https://jam.dev/c/5f56f544-466c-4067-813e-609ce7c885b6
cc: @Ramu-kandimalla @rajeshcherukumalli

**Comment by Susmitabe** [comment]
@anshumanth-egov  @devarajd94 please test & confirm

**Comment by anshumanth-egov** [comment]
Change text in box to "Advocate details cannot be modified once registration is request is accepted", and the buttons to "Confirm" and "Go Back"

**Comment by iknoorkaur** [comment]
Tested in UAT env, working as expected.
![image](https://github.com/user-attachments/assets/9623ad1d-5a08-4c3a-9b05-0e2bf3362050)
cc : @Ramu-kandimalla @rajeshcherukumalli

**Comment by anshumanth-egov** [comment]
Signed off

**Comment by muhammed-sawad** [comment]
Working as expected
