### ISSUE TITLE
PROD SUPPORT : Advocate | Re-registration with same number

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#2602]
**Describe the bug**
Whenever one advocate registration request is rejected by Nyaymitra, that advocate should be able to do registration again by using same number

**Comment by ashishbeehyv** [comment]
hi @Susmitabe  I am not able to reproduce this issue, I did the above mentioned steps and it is working as expected(UAT). can you please elaborate the exact steps to reproduce this. cc: @Ramu-kandimalla

**Comment by Susmitabe** [comment]
@tanmaybhateja (Program team ) & Highcourt signoff on either enabling address change or letting them re-register again with same number

**Comment by Ramu-kandimalla** [comment]
Hi @Susmitabe  Please confirm

**Comment by Susmitabe** [comment]
working fine
