### ISSUE TITLE
PROD SUPPORT: Scrutiny | not able to flag witness

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#2607]
**Describe the bug**
FSO is not able to see designation of the witness, so if there is any issue in witness designation, he will not be able to mark it. It will make issue in PDF also as Witness designation will be shown in PDF generated automatically

@rajeshcherukumalli please check this in UAT

**Comment by iknoorkaur** [comment]
Hi @Susmitabe, it is a valid issue.
@utpalBeehyv : kindly fix this issue 
Attaching jam video for reference: https://jam.dev/c/48c564ca-5d33-46e7-82f5-834a77fbfd95
cc: @rajeshcherukumalli

**Comment by iknoorkaur** [comment]
Hi @Susmitabe, Tested in UAT env, working as expected.
![image](https://github.com/user-attachments/assets/9643ea93-1f89-4456-a8a9-f8e6a1ab7590)
cc: @rajeshcherukumalli

**Comment by Susmitabe** [comment]
solved
