### ISSUE TITLE
[BUG]: [UAT | Nature of Debt/ Liability field value is not appearing in review case file]

### ISSUE THREAD

**Issue by iknoorkaur** [pucardotorg/dristi#2618]
**Describe the bug**
Nature of Debt/ Liability field value is not appearing in review case file

**To Reproduce**
1. Go to litigent
2. Click on file a new case -> fill the details of nature of debt/ liability field
3. Scroll down to review case file screen.

**Expected behavior**
Nature of Debt/ Liability field value should appear in review case file

**Screenshots**
![image](https://github.com/user-attachments/assets/3522a28f-3b0d-471a-971a-abe6b81b5a07)

**Comment by utpalBeehyv** [comment]
hi @iknoorkaur changes are done, pls check

@Ramu-kandimalla @rajeshcherukumalli

**Comment by iknoorkaur** [comment]
Tested in uat env, working as expected.
![image](https://github.com/user-attachments/assets/1bbe5f6e-5f0d-4f35-8275-17408deca84a)
cc: @rajeshcherukumalli
