### ISSUE TITLE
[BUG]: [UAT | "Take Me Home" button not appearing in advocate.]

### ISSUE THREAD

**Issue by iknoorkaur** [pucardotorg/dristi#2619]
**Describe the bug**
"Take Me Home" button not appearing in advocate.

**To Reproduce**

**Expected behavior**
"Take Me Home" button should appear in advocate screen.
![image](https://github.com/user-attachments/assets/3b46c793-f5be-4e42-847a-f01d84ea24d3)

**Screenshots**
![image](https://github.com/user-attachments/assets/301defb3-fcfb-46b6-924b-9afb1e4a4375)

**Comment by TusharKatiyar2002** [comment]
@rajeshcherukumalli @anirudh-0 adding ADVOCATE_APPLICATION_VIEWER for clerk also

**Comment by iknoorkaur** [comment]
Tested in UAT Env, working as expected
![image](https://github.com/user-attachments/assets/6d35beab-0e34-4e1a-b035-ba450df897cd)
cc: @Ramu-kandimalla @rajeshcherukumalli
