### ISSUE TITLE
[BUG]: [UAT | If we edit "additional comments" in judge while we issue the order, the updated text doesn't reflects.]

### ISSUE THREAD

**Issue by iknoorkaur** [pucardotorg/dristi#2624]
**Describe the bug**
If we edit "additional comments" in judge while we issue the order, the updated text doesn't reflects.

**To Reproduce**

**Expected behavior**
If we edit "additional comments" in judge while we issue the order, the updated text should get updated

**Screenshots**
https://jam.dev/c/681ab7a2-89d6-43da-82c3-e3e79f13a926

**Comment by utpalBeehyv** [comment]
hi @iknoorkaur changes are done in uat, pls check

cc : @rajeshcherukumalli @Ramu-kandimalla

**Comment by iknoorkaur** [comment]
Tested in UAT, working as expected.
Attaching jam video for reference: https://jam.dev/c/0867a637-ca3c-48eb-8615-d1bc03404582
cc: @Ramu-kandimalla @rajeshcherukumalli
