### ISSUE TITLE
PROD SUPPORT: Court staff | Case is appearing twice in hearing view

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#2627]
**Describe the bug**
Case is appearing twice in hearing view

![image](https://github.com/user-attachments/assets/492d0b2f-9629-4c6b-a7f1-c9d3acace7c6)

**Comment by Ramu-kandimalla** [comment]
Hi @Susmitabe  @muhammed-sawad  Please add more details for analysis

**Comment by rajeshcherukumalli** [comment]
Hi @Susmitabe , if the hearing are created with same date then these will be displayed , please check and confirm if two hearings are initiated for the case.

please find the reference in UAT: https://jam.dev/c/7eae016e-b453-4d5a-825e-54663e7f594a

**Comment by Ramu-kandimalla** [comment]
Hi @Susmitabe  Please verify and confirm

**Comment by Susmitabe** [comment]
its working fine
