### ISSUE TITLE
PROD SUPPORT : FSO not able to see documents in Firefox. It became working when we login to Google Chrome

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#2628]
**Describe the bug**
FSO not able to see documents in Firefox. It became working when we login to Google Chrome

**Comment by bhuvanyuguru** [comment]
Hi @Susmitabe, @rajeshcherukumalli, @Ramu-kandimalla

Working Fine in UAT

Refer Screenshots

![image](https://github.com/user-attachments/assets/09f5c494-291c-425d-95ae-3c0ffef725ab)

![image](https://github.com/user-attachments/assets/bf099756-c9a4-46f1-9544-acfde02bc303)

**Comment by Ramu-kandimalla** [comment]
Hi @Susmitabe  Please verify and confirm

**Comment by Susmitabe** [comment]
resolved
