### ISSUE TITLE
SUPPORT PROD:  Change in Cause Title

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#2634]
1. Change in cause title  which is Complainant 1 Vs Accused 1 to be changed to 

In case of 2 accused:
"X vs Y and Another"
In case of three accused:
"X vs Y and two others"
and so on.

In case of 2 complainant and 2 accused:
"X and Another vs Y and Another"
In case of three complainant: 
"X and two others vs Y"
and so on.

**Comment by Ramu-kandimalla** [comment]
Closing this ticket
