### ISSUE TITLE
[BUG]: [PROD SUPPORT]: [REGISTRATION]: [DISABLE ADVOCATE CLERK REGISTRATION]

### ISSUE THREAD

**Issue by muhammed-sawad** [pucardotorg/dristi#2651]
**Describe the bug**
Some of the advocate clerks were registering as a Advocate clerk in our platform and saying that we are not able to proceed further. It will be good if we disable this registration till this feature is available. We can give "Coming soon" or some data like this.
**To Reproduce**
1. Click on Register
2. enter your mobile number
3. Enter all details
4. When it ask about you, click on Advocate Clerk

**Comment by Ramu-kandimalla** [comment]
Hi @anirudh-0  @ashishbeehyv  Please disable the Advocate clerk option in user registration

Hi @Susmitabe @mehulseg24 @ansh-egov @devarajd94 This is new feature please plan this in upcoming sprints

**Comment by bhuvanyuguru** [comment]
Hi @ashishbeehyv , @Ramu-kandimalla , @Susmitabe , @muhammed-sawad 

This Issue is Resolved in UAT 

> TESTED SCENARIO
> - User Registration

Refer screenshot

![image](https://github.com/user-attachments/assets/5f19a51b-fa34-451f-bdef-c49f46bca345)

**Comment by muhammed-sawad** [comment]
Completed
**screenshot for ref**
![advocate_clerk_reg _disable](https://github.com/user-attachments/assets/c154ee83-2356-4aa2-9683-7713e98ca09a)
