### ISSUE TITLE
PROD SUPPORT : In review case file, documents are getting reloaded each and every time 

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#2655]
**Describe the bug**
In review case file, documents are getting reloaded each and every time after we open one document and close that document

https://drive.google.com/open?id=1SpDEd5w5Ejw-BP4olmKu42fweFfGpyM-

**Comment by bhuvanyuguru** [comment]
Hi @Susmitabe, @ashishbeehyv , @rajeshcherukumalli 

Working fine in UAT 

refer video

[Review case page UAT .webm](https://github.com/user-attachments/assets/371c5af2-8d09-4fbf-86a4-4938935976c9)

**Comment by Susmitabe** [comment]
resolved
