### ISSUE TITLE
[BUG]: [Multiple files are loading while marking an Error for FSO user]

### ISSUE THREAD

**Issue by rajeshcherukumalli** [pucardotorg/dristi#2656]
issue: https://github.com/pucardotorg/dristi/issues/2655  is also fixed with this issue.

**Comment by ashishbeehyv** [comment]
hi @bhuvanyuguru this issue is fixed in UAT. please test. cc: @rajeshcherukumalli @Susmitabe

**Comment by bhuvanyuguru** [comment]
Hi @rajeshcherukumalli , @ashishbeehyv , @maruthiPhanendra 

working fine in UAT 

refer video 
[FSO ERROR .webm](https://github.com/user-attachments/assets/af6102ee-a663-43b8-aa15-14a52e06f0de)
