### ISSUE TITLE
SUPPORT PROD : Enhancement in Delay Condonation

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#2658]
**Describe the bug**

If the cause of action is 5th of Nov , the system should consider from next day i.e 6th of nov to 5th nov (It should include the last date as well.

Program team have already provided the sign off .
In case any doubt reach out to Abhishek

**Comment by iknoorkaur** [comment]
Hi @Susmitabe , Tested in UAT env, working as expected,
Attaching jam video for reference:
https://jam.dev/c/a8ec4b50-e801-4f41-bbca-ca365e581f97
cc: @rajeshcherukumalli
