### ISSUE TITLE
PROD SUPPORT: CHANGE NAME OF COURT IN CAUSE LIST

### ISSUE THREAD

**Issue by muhammed-sawad** [pucardotorg/dristi#2660]
**Describe the bug**
Court name in Cause List is wrong. It is showing as " In The Court of: smt Soorya S Sukumaran, Judicial First Class Magistrate III 

**Expected behavior**
There is no need of Magistrate name in Cause List. Add court name as "Special Court of Judicial Magistrate of the First Class, for the trial of cases under section 138 of Negotiable Instruments Act, 1881 at Kollam ('24 x7 ON Court")
![courtname](https://github.com/user-attachments/assets/15245f0f-46e1-4d91-92fc-25719f777498)

**Screenshots**
![image](https://github.com/user-attachments/assets/7117f2b5-b1c3-41ff-9627-a812ab618547)

**Comment by rajeshcherukumalli** [comment]
Hi @ashishbeehyv , This is downloaded file caption change only one place it will impact
please find the reference: https://jam.dev/c/b636ac36-0a58-429a-aad7-6dd140d0a58c

**Comment by muhammed-sawad** [comment]
Hi @Hemadri-Chinna,
"Changes to be made in cause list ensuring configurability; do not hardcode the these items

Remove the slots statement for now; is confusing to users as court is active at 2:30 PM

**Comment by bhuvanyuguru** [comment]
Hi @radheshjoshi1, @Ramu-kandimalla 

Bug is not fixed in UAT 

Refer Screenshot 

![image](https://github.com/user-attachments/assets/4efac560-ba35-469e-bec0-5246ad149a84)

**Comment by bhuvanyuguru** [comment]
Hi @radheshjoshi1 , @Ramu-kandimalla , @Susmitabe , @rajeshcherukumalli 

Working fine in UAT 

![image](https://github.com/user-attachments/assets/fc19b261-f2e5-453d-9bf0-4ab0293d4ad4)

**Comment by Susmitabe** [comment]
This is still showing incorrect name
https://teams.microsoft.com/l/message/19:38da746d354f4ea89abdfa5a61cee436@thread.v2/1734671415579?context=%7B%22contextType%22%3A%22chat%22%7D

**Comment by Susmitabe** [comment]
Its displaying the name as expected
