### ISSUE TITLE
PROD SUPPORT: NOT SHOWING WHETHER A PERSON IS COMPLAINANT OR ACCUSED

### ISSUE THREAD

**Issue by muhammed-sawad** [pucardotorg/dristi#2662]
**Describe the bug**
"While scheduling for Admission hearing, system is not showing whether it is complainant or accused along with their names.
For some the cases, Complainant name is showing multiple times."

**Screenshots**

https://github.com/user-attachments/assets/a16fd68c-d00f-4bc8-ad4b-05f4395ad53b

**Comment by iknoorkaur** [comment]
Tested in UAT Env, working as expected.
Attaching screenshots for reference.
![image](https://github.com/user-attachments/assets/62ba5cda-98ec-4ac9-b1bc-5f3f0f734726)
![image](https://github.com/user-attachments/assets/1114990d-aa00-403e-be23-49f9d10ee363)
![image](https://github.com/user-attachments/assets/fcbf15f6-5c1c-4ad2-9a92-899e2e0ec834)
![image](https://github.com/user-attachments/assets/1a470491-64aa-49a8-81ee-e3284e6cedd5)
cc: @rajeshcherukumalli

**Comment by Susmitabe** [comment]
@ansh-egov  please test & give signoff
