### ISSUE TITLE
PROD SUPPORT: Add Filing Number in 223 Notice

### ISSUE THREAD

**Issue by muhammed-sawad** [pucardotorg/dristi#2667]
**Describe the bug**
Filing number have to be added in 223 notice along with CMP number. Without Filing Number accused's advocate cannot join the case without it

**Screenshots**

https://github.com/user-attachments/assets/20501e88-12b9-4c93-ba3d-ba16d24af412

**Comment by bhuvanyuguru** [comment]
Hi @muhammed-sawad, @Ramu-kandimalla, @rajeshcherukumalli , @Susmitabe 

Currently PDF template is same as given in [DOC FIle](https://docs.google.com/document/d/1OnvQsq0lITOn4KN8FMMcAWLRHfH4bA_LTbTHHmUScSk/edit?tab=t.0) 

![image](https://github.com/user-attachments/assets/669f88f0-ccf9-49e5-aa6b-d1e2642bff40)


![image](https://github.com/user-attachments/assets/3c06bf51-1c37-428f-bce2-c4fab6f46431)

**Comment by Ramu-kandimalla** [comment]
Hi @mehulseg24  @tanmaybhateja @devarajd94  Please update the template

**Comment by Susmitabe** [comment]
Got Signoff from Abhishek , mention the filing number below CMP number in template

**Comment by Ramu-kandimalla** [comment]
Hi @ashishbeehyv  Please do the needful

**Comment by nileshgupta111** [comment]
[notice-1734343412846.pdf](https://github.com/user-attachments/files/18149028/notice-1734343412846.pdf)
 Hi, @mehulseg24  @devarajd94  @tanmaybhateja This is the dummy template generated in local, can you validate and approve it. cc @Susmitabe @manimaarans @Ramu-kandimalla

**Comment by devarajd94** [comment]
@nileshgupta111 Filing No format is KL-001382-2024.. If this is a test number for confirming format, please go ahead for implementation.

**Comment by abhishekrao2024** [comment]
Looks good to go. Have checked that E-filing number addition only. We can release this.

**Comment by bhuvanyuguru** [comment]
Hi @nileshgupta111 , @manimaarans , @muhammed-sawad, @Susmitabe, @Ramu-kandimalla , @rajeshcherukumalli 

Working fine in UAT 

> TESTED SCENARIOS
> - Email
> - POST
> - SMS
> - RPAD 

Refer Screenshot 

![Image](https://github.com/user-attachments/assets/e22169cb-2dbc-45f9-a180-9225bceed0d1)

**Comment by muhammed-sawad** [comment]
Filing is showing on 223 notices
**pdf for ref**
[223_notice_new.pdf](https://github.com/user-attachments/files/18283048/223_notice_new.pdf)
