### ISSUE TITLE
PROD SUPPORT: BUG: SMS: SMS not receiving post registration of case

### ISSUE THREAD

**Issue by muhammed-sawad** [pucardotorg/dristi#2671]
**Describe the bug**
Advocates are not getting messages about the hearing date. They are not getting any messages for the hearing date scheduled, issue of notice, payment pending, payment done,CMP No,ST No,... Last message they are getting is for the case registration.They are not getting message when case is submitted for the first time.

**Screenshots**

![mess](https://github.com/user-attachments/assets/65f6ebb7-cfce-4768-bccd-dd39758ef75e)

**Comment by Ramu-kandimalla** [comment]
Hi @muhammed-sawad  @Susmitabe all the SMS integration are not completed few will be done as part of sprint 14

**Comment by Ramu-kandimalla** [comment]
Its a High Court IT team Issue Closing this since its resolved @devarajd94 @Susmitabe
