### ISSUE TITLE
[BUG]: [UAT | Accused submits the application, but in owners tab, name of the complainant is shown.]

### ISSUE THREAD

**Issue by iknoorkaur** [pucardotorg/dristi#2676]
**Describe the bug**
Accused submits the application, but in owners tab, name of the complainant is shown.

**To Reproduce**

**Expected behavior**
Accused submits the application, but in owners tab, name of the accused should be shown.

**Screenshots**
https://jam.dev/c/7e425d0c-e3c1-4e5f-bbf8-bc0a42d25946

**Comment by iknoorkaur** [comment]
Hi @vaibhavct, no advocate is joined to this case, but party name is displaying as N.A and moreover, party type and date added fields contain values.
![image](https://github.com/user-attachments/assets/fb4524da-38ad-4489-92a0-6444dbafec30)

**Comment by vaibhavct** [comment]
@iknoorkaur The issue which you've mentioned in the comments is not related to Owner column for submissions. Can you create a new github ticket for the same and assign respective dev to it?

**Comment by iknoorkaur** [comment]
Tested in UAT Env, working as expected
![image](https://github.com/user-attachments/assets/1324c3aa-22f3-44b9-8dd4-7ba4efc3d7f9)
cc: @Ramu-kandimalla @rajeshcherukumalli
