### ISSUE TITLE
PROD SUPPORT: 2 cheque amount not adding when we select Full Liability

### ISSUE THREAD

**Issue by muhammed-sawad** [pucardotorg/dristi#2677]
**Describe the bug**
"When a advocate upload two cheques for a single case, he can add amount of both cheques seperately. But when we select Full Liability in the Debt/Liability Details, it is showing only one cheque amount
When someone click on Full Liability, both cheque amount have to be added"

**Screenshots**
[2_cheque_liability_issue.webm](https://github.com/user-attachments/assets/65ec8755-b434-47c6-a643-df90808ec0ca)

**Comment by bhuvanyuguru** [comment]
Hi @anirudh-0 

This Bug is Reproduced in UAT 

Refer Video 

[Cheque Amount Bug.webm](https://github.com/user-attachments/assets/e2b5774e-69fb-4608-8d56-b5cba31a5831)

**Comment by ashishbeehyv** [comment]
hi @bhuvanyuguru  this is fixed in UAT. please test it. cc; @Ramu-kandimalla  @Susmitabe @rajeshcherukumalli

**Comment by bhuvanyuguru** [comment]
Hi @ashishbeehyv, @Ramu-kandimalla , @Susmitabe , @rajeshcherukumalli 

Working fine in UAT 

refer video 

[REVIEW PAGE .webm](https://github.com/user-attachments/assets/c7108c9d-78ed-4874-b756-3a28fadd6051)

**FSO video** 

[FSO CHEQUE DETAILS.webm](https://github.com/user-attachments/assets/bc246ab4-95fa-458c-8ce8-d2e98ad27a01)
