### ISSUE TITLE
BUG || [BLOCKER] UI is calling ADMIT workflow action 2 times

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#2678]
After Clicking on Admit Case, UI is calling "Admit" in workflow, and also while Registering Case "Admit" workflow action is sent. 

Refer screenshot

![image](https://github.com/user-attachments/assets/ad185a5d-9502-4e9a-9449-64faebc9c644)

API Response : "{
    "ResponseInfo": null,
    "Errors": [
        {
            "id": null,
            "parentId": null,
            "code": "WORKFLOW_SERVICE_EXCEPTION",
            "message": null,
            "description": null,
            "params": null
        }
    ]
}
" 

API CURL : `curl 'https://dristi-kerala-dev.pucar.org/case/v1/_update?tenantId=kl&_=1733893465783' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-GB,en;q=0.9' \
  -H 'content-type: application/json;charset=UTF-8' \
  -H 'origin: https://dristi-kerala-dev.pucar.org' \
  -H 'priority: u=1, i' \
  -H 'referer: https://dristi-kerala-dev.pucar.org/digit-ui/employee/orders/generate-orders?filingNumber=KL-000972-2024&orderNumber=KL-000972-2024-OR2' \
  -H 'sec-ch-ua: "Brave";v="131", "Chromium";v="131", "Not_A Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36' \
  --data-raw '{"cases":{"id":"37a50b32-e610-4146-a2b9-ab79070ddd27","tenantId":"kl","resolutionMechanism":"COURT","caseTitle":"Bhuvanyu vs Hemadri","isActive":true,"caseDescription":"Case description","filingNumber":"KL-000972-2024","courtCaseNumber":null,"caseNumber":null,"caseType":"CMP","cnrNumber":"KLKM520002292024","cmpNumber":"CMP/271/2024","accessCode":"810342","outcome":null,"courtId":"KLKM52","benchId":"BENCH_ID","linkedCases":[],"filingDate":1733893106476,"registrationDate":1733893199621,"judgementDate":null,"caseDetails":{"chequeDetails":{"formdata":[{"data":{"ifsc":"TEST012TEST","name":"test","delayReason":{"reasonForReturnCheque":"test"},"depositDate":"2024-11-20","infoBoxData":{"data":["CS_SIX_MONTH_BEFORE_DEPOSIT_TEXT","CS_CHEQUE_RETURNED_INSUFFICIENT_FUND"],"header":"CS_YOU_HAVE_CONFIRMED","scrutinyHeader":"CS_COMPLAINANT_HAVE_CONFIRMED"},"chequeAmount":"123456","chequeNumber":"123123","issuanceDate":"2024-11-20","payeeBankName":"test","payerBankName":"test","policeStation":{"id":6,"code":"KOLLAM_EAST","name":"Kollam East Police Station","isActive":true},"payeeBranchName":"test","payerBranchName":"test","chequeSignatoryName":"test","returnMemoFileUpload":{"document":[{"fileName":"CS_CHEQUE_RETURN_MEMO","fileStore":"8ea12824-17c0-434c-be48-a964cbf66db8","documentName":"bg-logo.jpg","documentType":"case.cheque.returnmemo"}]},"bouncedChequeFileUpload":{"document":[{"fileName":"CS_BOUNCED_CHEQUE","fileStore":"17d481bc-5a13-42c6-ba94-b57e058a1a51","documentName":"bg-logo.jpg","documentType":"case.cheque"}]},"depositChequeFileUpload":null},"isenabled":true,"displayindex":0}],"isCompleted":true},"delayApplications":{"formdata":[{"data":{"delayCondonationType":{"code":"YES","name":"YES","showForm":false,"isEnabled":true},"condonationFileUpload":null},"isenabled":true,"displayindex":0}],"isCompleted":true},"demandNoticeDetails":{"formdata":[{"data":{"proofOfReply":{"code":"NO","name":"NO","isEnabled":true,"isVerified":true,"showProofOfReply":false,"hasBarRegistrationNo":true},"dateOfAccrual":"2024-12-05","dateOfService":"2024-11-20","dateOfDispatch":"2024-11-20","proofOfService":{"code":"NO","name":"NO","isEnabled":true,"isVerified":true,"hasBarRegistrationNo":true,"showProofOfAcknowledgment":false},"proofOfReplyFileUpload":null,"proofOfDispatchFileUpload":{"document":[{"fileName":"PROOF_OF_DISPATCH_FILE_NAME","fileStore":"a42f0c4c-9b8d-4b59-aed1-d525d2b9d3ed","documentName":"bg-logo.jpg","documentType":"case.demandnotice.proof"}]},"legalDemandNoticeFileUpload":{"document":[{"fileName":"LEGAL_DEMAND_NOTICE","fileStore":"0faae9d5-570a-4674-aca2-09d9b872abaf","documentName":"bg-logo.jpg","documentType":"case.demandnotice"}]},"proofOfAcknowledgmentFileUpload":null},"isenabled":true,"displayindex":0}],"isCompleted":true},"debtLiabilityDetails":{"formdata":[{"data":{"totalAmount":"123456","liabilityType":{"id":1,"code":"FULL_LIABILITY","name":"FULL_LIABILITY","isActive":true,"liabilityType":1,"showAmountCovered":false},"liabilityNature":"test","debtLiabilityFileUpload":null},"isenabled":true,"displayindex":0}],"isCompleted":true}},"caseCategory":"CRIMINAL","judgeId":"JUDGE_ID","stage":"Pre-Trial","substage":"Registration","natureOfPleading":null,"statutesAndSections":[{"id":"cfad1137-2bcd-4878-936c-d7d48f403968","tenantId":"kl","statute":null,"sections":["Negotiable Instrument Act","02."],"subsections":["138","03."],"additionalDetails":null,"auditdetails":{"createdBy":null,"lastModifiedBy":null,"createdTime":0,"lastModifiedTime":0},"strSections":null,"strSubsections":null}],"litigants":[{"id":"b8147853-5f0e-442e-879b-67ddcb98402e","tenantId":"kl","caseId":"37a50b32-e610-4146-a2b9-ab79070ddd27","partyCategory":"INDIVIDUAL","organisationID":null,"individualId":"IND-2024-12-10-001554","partyType":"complainant.primary","isActive":true,"documents":null,"auditDetails":{"createdBy":"2d976c7f-62f8-4160-867d-75a978e7a625","lastModifiedBy":"d036eb91-236d-4011-879d-3ab82294ed96","createdTime":1733892975711,"lastModifiedTime":1733893261433},"additionalDetails":{"uuid":"ea7f6434-32da-49fd-af9b-04fad3dd3a40","fullName":"Bhuvanyu"}}],"representatives":[{"id":"308f425d-0fea-4a2a-9426-8354a94abba4","tenantId":"kl","advocateId":"c7692b33-93d6-439c-83a3-bf0ab5abe9d7","caseId":"37a50b32-e610-4146-a2b9-ab79070ddd27","representing":[{"id":"8c578d4e-0418-4c95-96c9-b43c53ecf21f","tenantId":"kl","caseId":"37a50b32-e610-4146-a2b9-ab79070ddd27","partyCategory":"INDIVIDUAL","organisationID":null,"individualId":"IND-2024-12-10-001554","partyType":"complainant.primary","isActive":true,"documents":null,"auditDetails":{"createdBy":"2d976c7f-62f8-4160-867d-75a978e7a625","lastModifiedBy":"d036eb91-236d-4011-879d-3ab82294ed96","createdTime":1733892975711,"lastModifiedTime":1733893261433},"additionalDetails":{"uuid":"ea7f6434-32da-49fd-af9b-04fad3dd3a40","fullName":"Bhuvanyu"}}],"isActive":true,"documents":null,"auditDetails":{"createdBy":"2d976c7f-62f8-4160-867d-75a978e7a625","lastModifiedBy":"d036eb91-236d-4011-879d-3ab82294ed96","createdTime":1733892975711,"lastModifiedTime":1733893261433},"additionalDetails":{"uuid":"2d976c7f-62f8-4160-867d-75a978e7a625","advocateName":"ADV SEVEN FOUR"}}],"status":"ADMISSION_HEARING_SCHEDULED","documents":[{"id":"133dc5d5-4ac4-425e-a899-768b6486f115","documentType":"COMPLAINANT_ID_PROOF","fileStore":"32077365-7504-40b1-af9a-7535dc1f84dd","documentUid":"133dc5d5-4ac4-425e-a899-768b6486f115","additionalDetails":null},{"id":"0173e60c-5111-499a-a5a3-02084cd487ef","documentType":"case.cheque","fileStore":"17d481bc-5a13-42c6-ba94-b57e058a1a51","documentUid":"0173e60c-5111-499a-a5a3-02084cd487ef","additionalDetails":null},{"id":"f3c1a63f-7ab5-4f76-a83f-4715597fce52","documentType":"case.cheque.returnmemo","fileStore":"8ea12824-17c0-434c-be48-a964cbf66db8","documentUid":"f3c1a63f-7ab5-4f76-a83f-4715597fce52","additionalDetails":null},{"id":"a0158e9b-47b5-4d9a-8f16-63f3efd966c1","documentType":"case.affidavit.223bnss","fileStore":"efade5f2-1d77-4149-9b3e-586b0f398122","documentUid":"a0158e9b-47b5-4d9a-8f16-63f3efd966c1","additionalDetails":null},{"id":"94b87929-c85e-4269-8965-4b4c1255dcc2","documentType":"case.demandnotice.proof","fileStore":"a42f0c4c-9b8d-4b59-aed1-d525d2b9d3ed","documentUid":"94b87929-c85e-4269-8965-4b4c1255dcc2","additionalDetails":null},{"id":"f45a8343-4d4b-4450-a5c3-04c6d5735416","documentType":"case.demandnotice","fileStore":"0faae9d5-570a-4674-aca2-09d9b872abaf","documentUid":"f45a8343-4d4b-4450-a5c3-04c6d5735416","additionalDetails":null},{"id":"e7ac1933-f44f-4673-8e64-7b76db43d577","documentType":"VAKALATNAMA_DOC","fileStore":"e7fd1187-3cdf-4e7e-8cb2-2a3b64d55adb","documentUid":"e7ac1933-f44f-4673-8e64-7b76db43d577","additionalDetails":null},{"id":"4f4b12f1-4176-40e0-b524-707bd4e5b06f","documentType":"COMPLAINANT_ID_PROOF","fileStore":"32077365-7504-40b1-af9a-7535dc1f84dd","documentUid":"4f4b12f1-4176-40e0-b524-707bd4e5b06f","additionalDetails":null},{"id":"4d6ffcdc-c450-4a31-8d19-a6030ad5c0f9","documentType":"case.complaint.unsigned","fileStore":"37baf627-a201-4349-af50-1e3d07221bc9","documentUid":"4d6ffcdc-c450-4a31-8d19-a6030ad5c0f9","additionalDetails":null},{"id":"a0b58c9e-2f22-45dd-b9f0-d48deaf40e33","documentType":"case.complaint.signed","fileStore":"fb14c198-1e6d-4bf7-915e-43b97ccea1e3","documentUid":"a0b58c9e-2f22-45dd-b9f0-d48deaf40e33","additionalDetails":null}],"remarks":null,"workflow":{"action":"ADMIT"},"additionalDetails":{"witnessDetails":{"formdata":[],"isCompleted":true},"payerMobileNo":"7700000004","payerName":"ADV SEVEN FOUR ","respondentDetails":{"formdata":[{"data":{"addressDetails":[{"addressDetails":{"pincode":"686002","city":"test","district":"test","locality":"test address","state":"test"},"id":"af1a7931-fbc1-40b2-9608-78421d7433ed"}],"respondentFirstName":"Hemadri","respondentType":{"id":1,"code":"INDIVIDUAL","name":"Individual","isactive":true,"commonFields":true,"isIndividual":true,"complainantTypeId":1,"showCompanyDetails":false,"complainantLocation":true},"companyDetailsUpload":null,"inquiryAffidavitFileUpload":null},"isenabled":true,"displayindex":0}],"isCompleted":true},"complainantDetails":{"formdata":[{"data":{"complainantVerification":{"individualDetails":{"addressDetails-select":{"pincode":"686002","city":"test","district":"test","locality":"test address","state":"Kerala","coordinates":{"latitude":"","longitude":""}},"addressDetails":{"pincode":"686002","city":"test","district":"test","coordinates":{"latitude":"","longitude":""},"locality":"test address","state":"Kerala"},"document":[{"fileName":"PAN_CARD Card","fileStore":"32077365-7504-40b1-af9a-7535dc1f84dd","documentName":"react.jpg"}],"individualId":"IND-2024-12-10-001554"},"mobileNumber":"9914001051","otpNumber":"123456","isUserVerified":true},"firstName":"Bhuvanyu","lastName":"","addressDetails-select":{"pincode":"686002","city":"test","district":"test","locality":"test address","state":"Kerala"},"middleName":"","addressDetails":{"pincode":"686002","city":"test","district":"test","locality":"test address","coordinates":{"latitude":"","longitude":""},"state":"Kerala","typeOfAddress":{"id":1,"code":"RESIDENTIAL","name":"Residential","isActive":true}},"complainantId":{"complainantId":true},"complainantAge":"22","complainantType":{"id":1,"code":"INDIVIDUAL","name":"Individual","isactive":true,"commonFields":true,"isIndividual":true,"complainantTypeId":1,"showCompanyDetails":false,"complainantLocation":true},"companyDetailsUpload":null},"isenabled":true,"displayindex":0}],"isCompleted":true},"judge":{"data":{"caseSpecificDetails":{"chequeDetails":{"form":[{"image":{"fileName":"CS_CHEQUE_RETURN_MEMO","systemError":"Retry with a better quality image"},"returnMemoFileUpload":{"document":{"fileName":"CS_CHEQUE_RETURN_MEMO","systemError":"Retry with a better quality image"}}}]},"demandNoticeDetails":{"form":[{"image":{"fileName":"LEGAL_DEMAND_NOTICE","systemError":"Retry with a better quality image"},"legalDemandNoticeFileUpload":{"document":{"fileName":"LEGAL_DEMAND_NOTICE","systemError":"Retry with a better quality image"}}}]}}},"isenabled":true,"displayindex":0},"scrutiny":{},"reviewCaseFile":{"formdata":[{"data":{},"isenabled":true,"displayindex":0}],"isCompleted":true},"advocateDetails":{"formdata":[{"data":{"advocateId":"c7692b33-93d6-439c-83a3-bf0ab5abe9d7","advocateName":"ADV SEVEN FOUR","numberOfAdvocate":"1","AdvocateNameDetails":{"lastName":"FOUR","firstName":"ADV","middleName":"SEVEN","advocateIdProof":[{"name":"DRIVING_LICENSE","fileName":"ID Proof","fileStore":"b60eb27d-b06f-4b58-97c3-a0e80557737f","documentName":"react.jpg"}],"advocateMobileNumber":"7700000004"},"barRegistrationNumber":"GURU//770004","vakalatnamaFileUpload":{"document":[{"fileName":"VAKALATNAMA","fileStore":"e7fd1187-3cdf-4e7e-8cb2-2a3b64d55adb","documentName":"bg-logo.jpg","documentType":"VAKALATNAMA_DOC"}]},"isAdvocateRepresenting":{"code":"YES","name":"Yes","showForm":true,"isEnabled":true},"advocateBarRegNumberWithName":[{"modified":true,"isDisable":true,"advocateId":"c7692b33-93d6-439c-83a3-bf0ab5abe9d7","advocateName":"ADV SEVEN FOUR","advocateUuid":"2d976c7f-62f8-4160-867d-75a978e7a625","individualId":"IND-2024-12-10-001553","barRegistrationNumber":"GURU//770004","barRegistrationNumberOriginal":"GURU//770004"}],"barRegistrationNumberOriginal":"GURU//770004"},"isenabled":true,"displayindex":0}],"isCompleted":true},"signedCaseDocument":"fb14c198-1e6d-4bf7-915e-43b97ccea1e3","prayerSwornStatement":{"formdata":[{"data":{"swornStatement":{"document":[{"fileName":"CS_SWORN_STATEMENT_HEADER","fileStore":"efade5f2-1d77-4149-9b3e-586b0f398122","documentName":"bg-logo.jpg","documentType":"case.affidavit.223bnss"}]},"memorandumOfComplaint":{"text":"test complaint"},"SelectUploadDocWithName":null,"prayerAndSwornStatementType":{"code":"NO","name":"NO"}},"isenabled":true,"displayindex":0}],"isCompleted":true}},"auditDetails":{"createdBy":"2d976c7f-62f8-4160-867d-75a978e7a625","lastModifiedBy":"d036eb91-236d-4011-879d-3ab82294ed96","createdTime":1733892975711,"lastModifiedTime":1733893261433}},"tenantId":"kl","RequestInfo":{"apiId":"Rainmaker","authToken":"33363a3b-9518-4c3f-ade4-17e4cbae66ed","userInfo":{"id":1981,"uuid":"d036eb91-236d-4011-879d-3ab82294ed96","userName":"Judge","name":"Judge","mobileNumber":"1002335566","emailId":null,"locale":null,"type":"EMPLOYEE","roles":[{"name":"HEARING_VIEWER","code":"HEARING_VIEWER","tenantId":"kl"},{"name":"WORKFLOW_ABANDON","code":"WORKFLOW_ABANDON","tenantId":"kl"},{"name":"ORDER_ESIGN","code":"ORDER_ESIGN","tenantId":"kl"},{"name":"Workflow Admin","code":"WORKFLOW_ADMIN","tenantId":"kl"},{"name":"APPLICATION_CREATOR","code":"APPLICATION_CREATOR","tenantId":"kl"},{"name":"DEPOSITION_PUBLISHER","code":"DEPOSITION_PUBLISHER","tenantId":"kl"},{"name":"HEARING_APPROVER","code":"HEARING_APPROVER","tenantId":"kl"},{"name":"SUBMISSION_RESPONDER","code":"SUBMISSION_RESPONDER","tenantId":"kl"},{"name":"ORDER_VIEWER","code":"ORDER_VIEWER","tenantId":"kl"},{"name":"ORDER_REASSIGN","code":"ORDER_REASSIGN","tenantId":"kl"},{"name":"CASE_EDITOR","code":"CASE_EDITOR","tenantId":"kl"},{"name":"TASK_CREATOR","code":"TASK_CREATOR","tenantId":"kl"},{"name":"APPLICATION_APPROVER","code":"APPLICATION_APPROVER","tenantId":"kl"},{"name":"Employee","code":"EMPLOYEE","tenantId":"kl"},{"name":"ORDER_DELETE","code":"ORDER_DELETE","tenantId":"kl"},{"name":"CASE_VIEWER","code":"CASE_VIEWER","tenantId":"kl"},{"name":"TASK_EDITOR","code":"TASK_EDITOR","tenantId":"kl"},{"name":"APPLICATION_REJECTOR","code":"APPLICATION_REJECTOR","tenantId":"kl"},{"name":"HEARING_EDITOR","code":"HEARING_EDITOR","tenantId":"kl"},{"name":"ORDER_APPROVER","code":"ORDER_APPROVER","tenantId":"kl"},{"name":"HEARING_CREATOR","code":"HEARING_CREATOR","tenantId":"kl"},{"name":"EVIDENCE_CREATOR","code":"EVIDENCE_CREATOR","tenantId":"kl"},{"name":"ORDER_CREATOR","code":"ORDER_CREATOR","tenantId":"kl"},{"name":"CALCULATION_VIEWER","code":"CALCULATION_VIEWER","tenantId":"kl"},{"name":"JUDGE_ROLE","code":"JUDGE_ROLE","tenantId":"kl"},{"name":"EVIDENCE_EDITOR","code":"EVIDENCE_EDITOR","tenantId":"kl"},{"name":"CASE_APPROVER","code":"CASE_APPROVER","tenantId":"kl"},{"name":"SUBMISSION_APPROVER","code":"SUBMISSION_APPROVER","tenantId":"kl"},{"name":"TASK_VIEWER","code":"TASK_VIEWER","tenantId":"kl"},{"name":"HEARING_SCHEDULER","code":"HEARING_SCHEDULER","tenantId":"kl"}],"active":true,"tenantId":"kl","permanentCity":null},"msgId":"1733893465783|en_IN","plainAccessRequest":{}}}'`

**Comment by TusharKatiyar2002** [comment]
@bhuvanyuguru plz check now, Admit button is visible

**Comment by bhuvanyuguru** [comment]
Hi @TusharKatiyar2002 , @anirudh-0 

Resolved in DEV SOL 

![image](https://github.com/user-attachments/assets/b9dde7e7-a520-4aa1-8de3-a62ead36391f)
