### ISSUE TITLE
whitelisting Icops api

### ISSUE THREAD

**Issue by radheshjoshi1** [pucardotorg/dristi#2681]
Need to whitelist /kerala-icops/v1/integrations/iCops/_getAuthToken endpoint, as it is being used by external service(icops) and we are not using any requestinfo for it.

**Comment by atulgupta2024** [comment]
I will let @suresh12  or @devarajd94  approve this, as I don't have much idea on external APIs for integration

**Comment by devarajd94** [comment]
@radheshjoshi1 please go ahead with the whitelisting. I discussed with suresh

**Comment by radheshjoshi1** [comment]
@Rkum113 , can you whitelist the mentioned endpoint cc: @devarajd94

**Comment by Rkum113** [comment]
@radheshjoshi1 , whitelisted /kerala-icops/v1/integrations/iCops/_getAuthToken
