### ISSUE TITLE
PROD SUPPORT : While issuing Order of Acceptance, the pdf generated is not showing the comment added

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#2684]
**Describe the bug**
While issuing Order of Acceptance, the pdf generated is not showing the comment added

**Comment by Susmitabe** [comment]
Currently the comment again not displaying in preview page of order and in second case the order itself did not get generated in preview page

**Comment by Ramu-kandimalla** [comment]
This Issue is fixed @Susmitabe  @suresh12  @muhammed-sawad
