### ISSUE TITLE
PROD SUPPORT: HEARING: 3 dots button near Start Hearing button not working

### ISSUE THREAD

**Issue by muhammed-sawad** [pucardotorg/dristi#2691]
**Describe the bug**
3 dots near to start hearing is not working on both Judge & Bench clerk portal. When we click on 3 buttons, nothing is showing

**Screenshots**

https://github.com/user-attachments/assets/83b719eb-0f52-4f07-8f2b-12c0e39229d1

**Comment by bhuvanyuguru** [comment]
Hi @ashishbeehyv, @rajeshcherukumalli, @Ramu-kandimalla, @Susmitabe 

Working fine in UAT 

> TESTED SCENARIOS
> - Judge
> - Court-staff
> - Bench-Clerk

Refer Screenshot 

![image](https://github.com/user-attachments/assets/4feb745f-ec66-414f-ab08-f4d766382e9d)

**Comment by muhammed-sawad** [comment]
Working fine
