### ISSUE TITLE
PROD SUPPORT: BUG: PAYMENT BUTTON NOT SHOWING FOR PAYMENT FOR NOTICE via RPAD

### ISSUE THREAD

**Issue by muhammed-sawad** [pucardotorg/dristi#2694]
**Describe the bug**
Pay online button is not showing for doing payment for RPAD 223 Notice by the advocate. SMS payment also have the same issue

**Screenshots**
![Screenshot from 2024-12-16 11-06-23](https://github.com/user-attachments/assets/40fd64da-fa66-4ced-81af-4b57c635b386)
![image](https://github.com/user-attachments/assets/57117ce3-b5fc-403c-b49f-0d0e31fb9e95)

**Comment by bhuvanyuguru** [comment]
Hi @muhammed-sawad , @Susmitabe , @Ramu-kandimalla , @rajeshcherukumalli 

Working fine in UAT 

>TEST SCENARIOS
> - SMS
> - RPAD
> - E-POST
>-  E-MAIL

![image](https://github.com/user-attachments/assets/dfde6a70-7b68-402e-b364-660cd1abf5bf)


![image](https://github.com/user-attachments/assets/7c2e73af-e70a-4ea2-a07a-5b44cfff51bf)

![image](https://github.com/user-attachments/assets/9f3fea20-0f62-4651-a5bc-6827b1ed28d0)

**Comment by muhammed-sawad** [comment]
Hi @bhuvanyuguru,
Checking with the advocate for further information

**Comment by muhammed-sawad** [comment]
resolved

**Comment by Ramu-kandimalla** [comment]
Please close the resolved tickets
