### ISSUE TITLE
PROD SUPPORT : While issuing order , the comment section limit, 64 char should be upgraded

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#2695]
![image](https://github.com/user-attachments/assets/8d7be1cf-9eb1-4cd9-835f-746278bb71ec)

**Comment by abhishekrao2024** [comment]
We may increase the character limit for this to the maximum possible.

**Comment by suresh12** [comment]
@manimaarans Please go ahead with 1000 characters.

**Comment by ashishbeehyv** [comment]
hi @bhuvanyuguru  these changes are deployed in UAT, please test. cc: @rajeshcherukumalli @Susmitabe

**Comment by bhuvanyuguru** [comment]
Hi @ashishbeehyv, @Susmitabe , @Ramu-Kandimala, @rajeshcherukumalli 

**Working Fine in UAT** 

Refer Screenshot

![image](https://github.com/user-attachments/assets/92e23d9f-d104-4356-bdb5-0655e50007a8)

![image](https://github.com/user-attachments/assets/3534e55f-1d4f-4be5-9eec-4b2a95d912f7)

![image](https://github.com/user-attachments/assets/09fc957f-8f5b-4ce2-9966-3c709f38eb3f)
