### ISSUE TITLE
PROD SUPPORT: BUG: JOIN CASE: NOT ABLE TO JOIN CASE AS ADVOCATE FOR THE ACCUSED

### ISSUE THREAD

**Issue by muhammed-sawad** [pucardotorg/dristi#2697]
**Describe the bug**
Not able to join case as accused advocate. After we do basic verification of the accused and entering the OTP went to accused mobile number, we have to click on next button which will not show anything further to proceed

**Screenshots**

https://github.com/user-attachments/assets/b5c270a0-9d2d-46d2-844d-addd289ef319

**Comment by bhuvanyuguru** [comment]
Hi @muhammed-sawad, 

In this Case Accused is already registered so, Login with Accused mobile number and then Join case as Accused and Join from  Advocate afterwards when Accused has joined the case.

**Comment by muhammed-sawad** [comment]
Completed
