### ISSUE TITLE
[BUG]: [sol-dev | Other Party (advocate + litigant) are able to see the documents which are marked as Void and pending esign.]

### ISSUE THREAD

**Issue by iknoorkaur** [pucardotorg/dristi#2701]
**Describe the bug**
Other Party (advocate + litigant) are able to see the documents which are marked as Void and also reason for voiding and pending esign.

**To Reproduce**
1. Go to litigent
2. Click on make filings-> submit documents.
3. submit one document by litigent, go to judge mark as void, go to respondent

**Expected behavior**
Other Party (advocate + litigant) should not be able to see the documents which are marked as Void and should not able to view the reason for voiding and should not view pending esign filings.

**Screenshots**
https://jam.dev/c/b1b564ff-33dc-474d-9aeb-13fd4e152805

**Comment by radheshjoshi1** [comment]
for a generic case it is not possible to implement the given scenarios 
@atulgupta2024 , can provide some suggestions
cc: @manimaarans

**Comment by rajeshcherukumalli** [comment]
@radheshjoshi1 , issue is resolved
