### ISSUE TITLE
[BUG]: [sol-dev | while submitting the documents in filings tab, by default the filing is marked as evidence.]

### ISSUE THREAD

**Issue by iknoorkaur** [pucardotorg/dristi#2703]
**Describe the bug**
while submitting the documents in filings tab, by default the filing is marked as evidence.

**Expected behavior**
while submitting the documents in filings tab, by default the filing should not be marked as evidence.

**Screenshots**
![image](https://github.com/user-attachments/assets/26a22883-d0b9-4314-b8cf-1f2c8aa0ba7f)

**Additional context**
curl 'https://dristi-kerala-dev.pucar.org/evidence/v1/_update?_=1734344801041' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'content-type: application/json;charset=UTF-8' \
  -H 'origin: https://dristi-kerala-dev.pucar.org' \
  -H 'priority: u=1, i' \
  -H 'referer: https://dristi-kerala-dev.pucar.org/digit-ui/citizen/submissions/submit-document?filingNumber=KL-001015-2024&artifactNumber=KL-001015-2024-AR11' \
  -H 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36' \
  --data-raw '{"artifact":{"id":"6ec35c0a-9a55-4958-a7df-2ad829c8172b","tenantId":"kl","artifactNumber":"KL-001015-2024-AR11","evidenceNumber":null,"filingNumber":"KL-001015-2024","externalRefNumber":null,"caseId":"7eeb68c9-3ca5-4d7b-8178-cb920279c413","application":null,"hearing":null,"order":null,"cnrNumber":null,"mediaType":null,"artifactType":"MEMOS","sourceType":"COMPLAINANT","sourceID":"IND-2024-12-16-001567","sourceName":null,"applicableTo":null,"createdDate":1734344785080,"isActive":true,"isEvidence":false,"status":"PENDING_E-SIGN","filingType":"DIRECT","isVoid":false,"reason":null,"file":{"documentType":"SIGNED","fileStore":"119473d3-92d5-47b2-abd4-0e5bdca6fac8"},"description":null,"artifactDetails":null,"comments":[],"additionalDetails":{"uuid":"00badb19-3cb2-4be7-a0c0-03ce8e2395d5","formdata":{"documentType":{"id":"1","code":"MEMOS","name":"Memos","isActive":true},"documentTitle":"aa","reasonForFiling":{"text":"aaa"},"submissionDocuments":{"uploadedDocs":[{}]}}},"auditdetails":{"createdBy":"00badb19-3cb2-4be7-a0c0-03ce8e2395d5","lastModifiedBy":"00badb19-3cb2-4be7-a0c0-03ce8e2395d5","createdTime":1734344785080,"lastModifiedTime":1734344785080},"workflow":{"action":"E-SIGN"}},"RequestInfo":{"apiId":"Rainmaker","authToken":"f8666753-a96d-4268-80a5-3a001bc7bb69","msgId":"1734344801041|en_IN","plainAccessRequest":{}}}'

**Comment by radheshjoshi1** [comment]
@iknoorkaur  can test in solution dev the pr is merged and dev tested

**Comment by iknoorkaur** [comment]
tested in sol-dev, working as expected
attaching jam video for reference:
https://jam.dev/c/59aa2a02-f681-4c93-b538-585add9026cb
cc: @Ramu-kandimalla @rajeshcherukumalli
