### ISSUE TITLE
PROD SUPPORT: Notice: 223 Notice not  getting generated for a case

### ISSUE THREAD

**Issue by muhammed-sawad** [pucardotorg/dristi#2709]
**Describe the bug**
"Not able to do e-sign to sent 223 Notice through RPAD and SMS for a single case as notice is not getting generated. When we are trying to download the PDF, it is showing 400 error code with "Invalid filestore or tenantid"
Filing Number - KL-000287-2024

**Screenshots**
![invalid](https://github.com/user-attachments/assets/1106152a-0aef-463a-b310-245f159b5d31)

https://github.com/user-attachments/assets/98f46027-34fc-4529-a4b1-8e7222501c96

**Comment by Susmitabe** [comment]
Will Ask Courtstaff to generate one order/notice
