### ISSUE TITLE
UAT: citizen logged in directly

### ISSUE THREAD

**Issue by atulgupta2024** [pucardotorg/dristi#271]
https://dristi-qa.pucar.org/digit-ui/citizen/select-language
on this page, selected the language and click "Continue" and it logs me in and takes me to a page that shows "You are yet to register yourself"

Is this expected behavior? Am I supposed to be already logged in, even when I am not yet registered?

**Comment by SureshSoren** [comment]
@atulgupta2024  I think this is the expected behaviour. @Taherabharmal can you please confirm it.

**Comment by atulgupta2024** [comment]
as per discussion, there is some issue with DIGIT logout.
