### ISSUE TITLE
[BUG]: [sol-dev | pending sign documents are visible to the judge]

### ISSUE THREAD

**Issue by iknoorkaur** [pucardotorg/dristi#2713]
**Describe the bug**
pending sign documents are visible to the judge

**To Reproduce**

**Expected behavior**
pending sign documents should not be visible to the judge

**Screenshots**
![image](https://github.com/user-attachments/assets/e6f5ade3-446c-4a02-ae7e-6c7de97ebedc)

**Comment by radheshjoshi1** [comment]
ui can send the status criteria accroding to which the documents will be filtered @iknoorkaur, can you assign some ui dev

**Comment by iknoorkaur** [comment]
@nitish-beehyv, can you please look into this

**Comment by nitish-beehyv** [comment]
⁠Hi ⁠@radheshjoshi1 some filings document don't have any status. what should we do for it?

**Comment by Ramu-kandimalla** [comment]
@iknoorkaur  please retest

**Comment by radheshjoshi1** [comment]
@iknoorkaur can you test the changes are deployed

**Comment by rajeshcherukumalli** [comment]
@radheshjoshi1 , issue is resolved in solution dev environment 

https://jam.dev/c/2735c7b3-e911-457e-b940-b1ba267ad6b2
