### ISSUE TITLE
[BUG]: UAT| E-sign issue

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#2717]
**Describe the bug**
File a case_& sign with e-sign option.
**To Reproduce**
1.go to the url https://dristi-kerala-uat.pucar.org/digit-ui/citizen'
2. file a case
3. sign with e-sign.

Reference:
https://jam.dev/c/22c769d3-bf90-41db-a9e5-7fcbdcd9cd02

**Comment by prasanna2400** [comment]
not able to open the video @kashish384  
![image](https://github.com/user-attachments/assets/699423f3-1106-4439-9e74-0d5cce4e56e7)

**Comment by kashish384** [comment]
its working fine.
