### ISSUE TITLE
[BUG]: UAT| judge| pending task issue

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#2718]
**Describe the bug**
register the case & click on 'back to home' button & in home screen select the case see there pending task not created for_schedule admission hearing.

**To Reproduce**
1. Go to the url 'https://dristi-kerala-uat.pucar.org/digit-ui/employee'
2. login with  'judge creds'
3. register the case.
4. click on 'back to home' button & select the case.
5. see error.

reference:
https://jam.dev/c/a9724bc4-2456-4ba9-8bf5-ae0d3e3c5865

**Comment by bhuvanyuguru** [comment]
Pending Task is created after clicking on Schedule Admission Hearing.
