### ISSUE TITLE
[BUG]: UAT| SBI payment issue

### ISSUE THREAD

**Issue by kashish384** [pucardotorg/dristi#2719]
**Describe the bug**
*Generate notice/Summons via_https://dristi-kerala-uat.pucar.org/digit-ui/employee &
*make a  payment via _https://dristi-kerala-uat.pucar.org/digit-ui/citizen

**To Reproduce**
1. login with 'citizen ' creds_9034328347
2. go to 'pending task'  Payment for Notice via post.
3. do sbi 'Delivery Partner Fee' payment.

Reference:
https://jam.dev/c/d54e8357-87e1-425e-8ea4-75af4dfcf089

**Comment by bhuvanyuguru** [comment]
Office IP is white-listed so any Other IP cannot access SBI E-payment
