### ISSUE TITLE
PROD SUPPORT : I see MM/DD/YYYY format for dates everywhere in production 

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/dristi#2751]
**Describe the bug**
![image](https://github.com/user-attachments/assets/546befa4-f85d-4b19-9d4e-88ed1254296b)

**Comment by Susmitabe** [comment]
In Preview page its in DD/MM/YYYY format 
![image](https://github.com/user-attachments/assets/90b1a32f-4d38-4ca7-9387-2c1bcb8d61d7)

**Comment by muhammed-sawad** [comment]
![image](https://github.com/user-attachments/assets/98dea07c-f29b-43f9-a655-2723ad359aca)

**Comment by muhammed-sawad** [comment]
Working as expected

**screenshot**

![Uploading image.png…]()
