### ISSUE TITLE
BUG || Case Details are not shown in UI if number is greater than 7 [UAT]

### ISSUE THREAD

**Issue by bhuvanyuguru** [pucardotorg/dristi#2759]
**UAT**

Case Details are not shown in UI if number is greater than 7

Refer Screenshots

![image](https://github.com/user-attachments/assets/d870e874-c1b0-4f70-a569-74d07ebc3c37)

![image](https://github.com/user-attachments/assets/d3a1d9f3-fc68-4479-970c-b461055f4ef0)

**Comment by bhuvanyuguru** [comment]
HI @ashishbeehyv 

Please add numbering in Legal Demand Notice as well

Refer Screen shot 
![image](https://github.com/user-attachments/assets/84cb4c1f-442d-4eae-a1c6-6022a521b223)

**Comment by Susmitabe** [comment]
https://teams.microsoft.com/l/message/19:ac551e1f-b607-4106-aca5-e370839511c8_b6a1d5bc-a087-404a-ac7e-8009963b61fa@unq.gbl.spaces/1734946251994?context=%7B%22contextType%22%3A%22chat%22%7D   Also its showing 8 times  , the complainant has confirmed

**Comment by ashishbeehyv** [comment]
Changes for the above issues are deployed in UAT, please test @bhuvanyuguru cc: @Susmitabe  @rajeshcherukumalli

**Comment by bhuvanyuguru** [comment]
Hi @Susmitabe, @rajeshcherukumalli 

**Working Fine in UAT** 

> TESTED SCENARIOS
> - Advocate & Litigant User
> - FSO Scrutiny User

Refer Screenshots 

![image](https://github.com/user-attachments/assets/c0272bf1-323e-4d73-8301-5ae23cd9d11f)

![image](https://github.com/user-attachments/assets/7d63cd79-b6ce-429e-a385-b97c21ef2ad7)

**Comment by muhammed-sawad** [comment]
Resolved
