### ISSUE TITLE
UAT: User registration proceeds to the next step without Aadhar file upload

### ISSUE THREAD

**Issue by subhashini-egov** [pucardotorg/dristi#283]
1. Login as citizen
2. Register as a user
3. Fill out Aadhar details. Upload a file.
4. Remove the file.
5. Click on "Next"
6. Registration proceeds to the next stage.

It should fail as no file has been uploaded.

**Comment by Vanshikajain02** [comment]
It is fixed and I have retested it, working fine in QA Environment now

**Comment by Taherabharmal** [comment]
resolved
