### ISSUE TITLE
Writing Test Cases

### ISSUE THREAD

**Issue by krishnaprasadsannidhi** [pucardotorg/dristi#49]
This includes the testcase document for User Registration Module and it includes the following workflows -:
1) Litigant Registration
2) Advocate/Advocate Clerk Registration
3) Nyay Mitra Registration request
4) Login

**Comment by subhashini-egov** [comment]
@krishnaprasadsannidhi who's working on this task? Please add start and end dates.

**Comment by rajeshwarimalik** [comment]
Please refer to the test cases for user registration.

[User Registration.xlsx](https://github.com/pucardotorg/dristi/files/15022001/User.Registration.xlsx)
