### ISSUE TITLE
UAT Bug | E-filing | Editing Complainant 1 Details

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#510]
Module: E-filing
User: Litigant

Description: Currently, the complainant details of complainant 1 cannot be changed. The user, in case required to change some details like address, is not allowed to do so.

Expected behaviour:
Add infobox with Text "Incase your details need to be updated, please contact the Nyay Mitra"

**Comment by Amityadav012** [comment]
This issue is fixed and working fine in UAT Env.

**Comment by Taherabharmal** [comment]
this is not done
