### ISSUE TITLE
UAT | E-filing | Upload ID Card

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#513]
Module: E-filing

Issue: 
On uploading a new ID card, and selecting a doc, the add button is only viewable on scroll.
This confuses the user as to how to proceed

Expected behaviour:
Pop up size is adjusted so entitre content shows up in one go.

![Image](https://github.com/pucardotorg/dristi/assets/132061840/6fd4ceca-e461-42ec-80af-e93627fb0658)

**Comment by Amityadav012** [comment]
This issue is fixed and working fine in UAT Env

**Comment by Taherabharmal** [comment]
resolved
