### ISSUE TITLE
UAT | CSS Issue | Maps

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#518]
Module: E-filing
Screen: Complainant and Respondent Details

Issue: 
CSS Message displayed above map

![Image](https://github.com/pucardotorg/dristi/assets/132061840/dc4e6ec4-3e23-4640-99f3-eecdf4ae2f20)

**Comment by Amityadav012** [comment]
This issue is fixed and working as excepted in UAT env.

**Comment by Taherabharmal** [comment]
resolved
