### ISSUE TITLE
UAT | E-filing | Mandatory Fields

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#519]
Module: E-filing
Screens: All

Description: 
On clicking 'Continue' once a page is filled, if mandatory fields are not filled, an error is displayed asking the user to fill all mandatory fields.

However, the mandatory fields are not highlighted.

Expected behaviour:
Mandatory fields to be highlighted with message "This is a mandatory field".
The design of this can be as per the following design:

![Image](https://github.com/pucardotorg/dristi/assets/132061840/9968a1ee-2871-4f38-b010-eeb4a7f0dac4)

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected in UAT Env.

**Comment by Taherabharmal** [comment]
resolved
