### ISSUE TITLE
UAT | E-filing | Format of IFSC

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#520]
Module: E-filing
Screen: Cheque Details

Issue: For field IFSC Code,
1) Not allowing more than 4 digits. Ideally should be 11 digits following the format Mentioned below
2) Format of IFSC code to be mentioned. This can be displayed by adding an I symbol which displays the information as shown in the image attachment
Format of IFSC Code: ABCD-0-123456

![Image](https://github.com/pucardotorg/dristi/assets/132061840/63dd1c89-4505-4505-88b3-c7ec225193a6)

**Comment by Amityadav012** [comment]
This issue is fixed and working fine in UAT Env.

**Comment by Taherabharmal** [comment]
resolved
