### ISSUE TITLE
UAT | E-filing | Demand Notice Details

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#524]
Module: E-filing

Issue:
1) Files are successfully uploaded for legal demand notice and proof of dispatch.
2) Anwer to question, 
Do you have proof of service of legal demand notice? is selected as No.
3) Toggle back to Yes for this question and the file uploads are automatically removed.

Expected behaviour:
File uploads remain as is.

Same Issue with IFSC Code. If IFSC Code is issued, value of cheque field becomes blank

**Comment by SureshSoren** [comment]
@Taherabharmal unable to reproduce the issue with IFSC code, fixed part 1 of the issue however (in dev)

**Comment by Amityadav012** [comment]
This issue is fixed and working fine in UAT Env

**Comment by Taherabharmal** [comment]
resolved
