### ISSUE TITLE
UAT | E-filing |Adding complainants

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#534]
Once a complainant's phone number is verified by OTP, they cannot change it. We should add a message warning them: "Please ensure you enter the phone number on which you want to receive case updates. You cannot change this number after OTP verification" 

When an advocate is adding a new new complainant, Aadhar is auto verified saying verification done during registration: but they need to verify as they are filing for somebody else.

**Comment by anirudh-0** [comment]
@anshumanth-egov aadhar verification happens in a 3rd party application (meri pehchan) and integration details of that is not yet there so there's not much we can add FE wise

**Comment by SureshSoren** [comment]
@anshumanth-egov can you remove the bug label as Aadhar verification is out of scope of dpg for v1

**Comment by anshumanth-egov** [comment]
dont see the option to do that, can you do it from your end?
