### ISSUE TITLE
UAT | E-filing | Mandatory file upload highlighting

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#536]
On clicking Continue without filling in mandatory fields, they should be highlighted as shown in https://github.com/orgs/pucardotorg/projects/1/views/1?pane=issue&itemId=68076996 . 

File upload fields also need to be flagged similarly. 

Clicking Next on Delay Condonation page doesn't do anything if I havent uploaded the file, needs to show error that I haven't filled mandatory fields.

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected in UAT Env.
