### ISSUE TITLE
UAT | E-filing | Date of issuance of legal demand notice

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#537]
We have a check for Date of Issuance of Legal Demand Notice cannot be before before date of cheque deposit.
In case there are multiple checks, then this check should be against the deposit date of the latest cheque. Currently, its checking against the earliest one.

**Comment by anirudh-0** [comment]
@anshumanth-egov  can you share this in PRD if possible
What happens if someone's payment is paid in multiple instalments, and only one of the cheques is the bounced cheque and is dated earlier. Is the litigant expected to not upload any subsequent cheques ?

**Comment by anshumanth-egov** [comment]
Yes only bounced cheques need to be uploaded

**Comment by Amityadav012** [comment]
This issue is fixed and working fine in UAT Env.

**Comment by anshumanth-egov** [comment]
@Taherabharmal closing this issue as per our discussion on this matter, but just bringing it to your attention so you're aware
