### ISSUE TITLE
UAT | E-filing |  Date of Service or Deemed Service of Legal Demand Notice

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#538]
- In case 15 days havent elapsed since date of service, then the error message can have a "Edit date" button (in case I selected wrong data and want to fix it).

<img width="679" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/99e365ab-7dd9-4315-b417-b9d5e65a9e7e">

- After I close the above popup, then css error message is visible:

<img width="861" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/9a1ced7d-647d-4cfd-86d1-44d28f2d48b6">

- If I close the pop-up and continue editing, the popup keeps appearing everytime i edit some other field.

**Comment by anirudh-0** [comment]
We will clear out the date of service field as this popup needs to show on every form update with invalid time elapsed
@anshumanth-egov

**Comment by anshumanth-egov** [comment]
It was appearing even after I updated the date to make it valid, please confirm that too please

**Comment by SureshSoren** [comment]
Cannot reproduce appearance after valid date re-input

**Comment by Amityadav012** [comment]
This issue is fixed and working fine in UAT Env.
