### ISSUE TITLE
UAT | E-filing | Adding witness phone number

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#541]
If i enter phone number but dont add and click on continue, shows this error message:
<img width="937" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/db30e051-524c-4761-a03c-86d3f6523f15">

Needs to be changed to something that captures the error better: "Please add number" maybe?

**Comment by anirudh-0** [comment]
This is default browser behaviour @anshumanth-egov 
When form have invalid inputs browser has builtin behaviours and this is not possible to change

**Comment by Amityadav012** [comment]
This issue is fixed based on the anirudh comment, and working fine in UAT Env.
