### ISSUE TITLE
UAT | E-filing | Crash on incomplete witness details

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#542]
If i fill witness name but no phone number, email, or description:
<img width="1003" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/2ba6edff-ba88-44d0-be5d-f103d3269b6a">

and click continue, then it crashes:

<img width="1468" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/50f2786c-fdb2-4bc2-ad4a-ca17f5534170">

(on the bright side, it seems to autosave the draft :) )

**Comment by anshumanth-egov** [comment]
Update: same issue even if i fill in details

**Comment by Amityadav012** [comment]
This issue is fixed and working fine in UAT Env.
