### ISSUE TITLE
UAT | E-filing | Complainant fields get disabled when advocate is filing

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#543]
Entered name, phone number, and verified phone number -> Clicked continue without completing address -> Got error saying fill mandatory fields but now the fields are disabled and cant edit further

<img width="1061" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/38ff0aa8-31ee-46be-b837-ab4f340df7c3">

**Comment by anirudh-0** [comment]
data issue, this state of UI shouldn't be reachable

**Comment by Amityadav012** [comment]
This issue is fixed and working fine in UAT Env.
