### ISSUE TITLE
UAT | E-filing | Inconsistent file upload and view experience

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#548]
During registration, when I upload ID, I can see the file in preview. 
Everywhere else, I cannot see what I just uploaded, have to delete and reupload if Im unsure. Ideally, if I click on the file again, I'd want to see what the file is, its how it works in most sites.

In Nyay mitra registration approval, clicking on the application number downloads file fully.
In other places, like when I click on "Download template" during registration, it opens it in a new tab.

Some consistency here might be good, something to work on later down the line.

**Comment by SureshSoren** [comment]
@anshumanth-egov I've added enhancement label to this, can you remove the bug label ?

**Comment by Beehyv-Vinod** [comment]
Tested in QA Env, Working as Expected. User able to view the uploaded files

1. E-filing --https://jam.dev/c/6c35c50e-f726-442b-9888-c1052d2417f6
2. User registration --https://jam.dev/c/429d7d81-ae9c-48a8-9974-24fe95008ca1
