### ISSUE TITLE
UAT | E-filing | Adding advocate

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#550]
Clicking on Yes here crashed the app:
<img width="989" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/e1594944-a0eb-4ca0-ab50-ca4fba8d0802">

<img width="1443" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/c553317c-c1a1-4649-b58d-fbcbebc2718a">

**Comment by Amityadav012** [comment]
This issue is fixed and working fine in UAT Env.
