### ISSUE TITLE
UAT | E-filing | Payment status not updating

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#554]
Status remains payment pending even after I go through the Record Payment flow and mark paid
<img width="1424" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/177ccd20-406f-48eb-8ebd-9e1b07f763e3">
<img width="1411" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/72cbc3c1-4c11-4b7a-ac05-c86aade0c138">

**Comment by Amityadav012** [comment]
This issue is fixed and working fine in UAT Env.

**Comment by Taherabharmal** [comment]
i am assuming this will come as part of home screen, keeping this open

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected.
