### ISSUE TITLE
UAT | Collect Payment | Navigation to Pending Payment

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#563]
Module: E-filing

Issue:
1) Once case file is submitted, status is pending payment
2) However when you go to view case, the user can only see only to "Go back to home'

Expected behaviour: 
1) User should be able to see option to make payment

**Comment by SureshSoren** [comment]
View case is not yet implemented, that is the review page kept as placeholder

**Comment by Amityadav012** [comment]
This issue will fix after home page development.
