### ISSUE TITLE
UAT | Overall | Access for Advocate

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#564]
Issue:
1) Advocates are able to see all cases irrespective of who created them
2) Login via the following phone numbers: 9999999901 and 9999999902 - The list of cases are the same across both these advocates

Expected behaviour:
1) Advocates are only able to see cases drafted by them or assigned to them

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected in UAT Env.
