### ISSUE TITLE
UAT | E-filing | Deleted Drafts

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#576]
Issue:
1) There is no confirmation seeked from user to delete e-filing, currently by only clicking delete e-filing, the file is deleted
2) Deleted drafts are still available in the list of cases
2) On opening the file, the case file opens with a pop-up where nothing is clickable.

Expected behaviour:
1) confirmation seeked from user to delete e-filing, currently by only clicking delete e-filing, the file is deleted
2) Deleted drafts are not available in the list of cases

![Image](https://github.com/pucardotorg/dristi/assets/132061840/7032542b-4978-4491-806d-41263bfc0d55)

**Comment by Amityadav012** [comment]
This issue is fixed and working fine in UAT Env
