### ISSUE TITLE
UAT | E-filing | View Documents

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#580]
Module: E-filing

Issue: 
Currently, only small thumbnails of docs are available once case is being filed or reviewed.

Expected behaviour:
Pop up showing entire doc is visibile while clicking on the doc

design:
https://www.figma.com/design/fwFYdlymVjggLOltqnXWsY/Hand-off-(Digit)?node-id=538-6734&t=yHW9JjTvr2ffZrWK-0

**Comment by SureshSoren** [comment]
@Taherabharmal  the design you referenced is from is from scrutiny.

**Comment by Taherabharmal** [comment]
Yes, but preview of documents needs to be available even in view case for litigant

**Comment by Amityadav012** [comment]
This issue is fixed and working fine in UAT Env.
