### ISSUE TITLE
UAT | E-filing | Success Screen

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#582]
Issues:
1) Localization missing in success screen post filing
2) Copy button not working
3) No way to go back home from success screen

![Image](https://github.com/pucardotorg/dristi/assets/132061840/e56bd8c5-d89e-4246-9f26-65b5a8ace23e)

**Comment by Amityadav012** [comment]
This issue is fixed and working fine in UAT Env.
