### ISSUE TITLE
UAT | E-filing | Viewing Case file from Complainant Login

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#583]
Module: E-filing

Issue:
1) Cases filed with complainant phone number not viewable in complainant list of cases

Expected behaviour: 
1) Cases filed by advocate with complainant phone number should be viewable in complainant list of cases

Advocate Phone number: 
9999999906

Litigant Phone Number: 
9999999908

**Comment by Amityadav012** [comment]
This issue is fixed and working fine in UAT Env.
