### ISSUE TITLE
UAT | E-filing | Review case Fields not displayed

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#584]
Module: E-filing
Screen: Review Case

Issue:
1) Fields for Memorandum of Complaint are not available in review case
2) Fields for additional comments of all sections are not displayed across sections
3) Field for additional sections and acts is not displayed

Expected behaviour:
1) All fields filled by the user are displayed in Review case page

**Comment by Amityadav012** [comment]
This issue is fixed and working fine in UAT Env.
