### ISSUE TITLE
UAT | E-filing | Payment Screen

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#590]
Describe the bug
1) Localization for Payment Screen not loading

To Reproduce
1) Create Case
2) Submit Case
3) Log in to collector screen
4) Go to record payment
5) Click on Confirm

Expected behavior
1) Proper localization is in place
2) Payment confirmation screen to follow the components as in the design below:
https://www.figma.com/design/fwFYdlymVjggLOltqnXWsY/Hand-off-(Digit)?node-id=194-42917&t=zKvgUt1UFcG3WtOs-0
3) The following details need to be added to the page:
Below the success confirmation box, add the following text:
"A notification regarding payment has been sent to the registered mobile number of the complainant and complainant's advocate"
4) Add Payment receipt number

Screenshots
![Image](https://github.com/pucardotorg/dristi/assets/132061840/25795223-f91d-42e4-880f-e375c458750f)

Desktop (please complete the following information):

OS: iOS
Browser: Chrome

**Comment by Amityadav012** [comment]
This issue is fixed and working fine in UAT Env.
