### ISSUE TITLE
UAT | E-filing | Collect Payment

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#591]
The fields in the payment screen need to be updated

To Reproduce Steps to reproduce the behavior:
1. File and Submit Case
2. Login to FSO screen, and go to view cases
4. Navigate to Record Payment for a case
5. The following fields need to be filled for Record Payment: Paid by and Mode of Payment

Expected behavior:
The following fields needs to be present along with the following values:
1) Paid by to be renamed as Payee and autopopulated with the name of the user who has filed the case
2) Mode of Payment: Drop down with following values: Cash, Cheque, Demand Draft, Stamps
3) If cheque or DD is selected, show field to capture Cheque number/Demand Draft number.

**Comment by Ramu-kandimalla** [comment]
This issue is fixed and working as expected in UAT
