### ISSUE TITLE
UAT | Scrutiny : Infobox

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#592]
**Describe the bug**
Localization for Infobox not updated

**To Reproduce**
1. Login Via FSO login
2. Go to case pending for Scrutiny

**Expected behavior**
Text for Infobox is localization

**Screenshots**

![Image](https://github.com/pucardotorg/dristi/assets/132061840/5b92d8a1-ca89-4ba8-bb64-b81d7d3ec948)

**Comment by nandinilp** [comment]
This issue is fixed. I tested in QA env.
Please check the screenshot for reference [https://jam.dev/c/b34af955-e267-47d1-b0eb-cbd16f9f7b81](url)
