### ISSUE TITLE
UAT | Scrutiny | Document Display

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#593]
**Describe the bug**
Issue with Document display across all documents in scrutiny: Documents are blurred with all text displaying twice

**To Reproduce**
1. Login as FSO
2. Go to Case pending for Scrutiny
3. Click on any document

The same issue is appearing in documents uploaded for user registration

**Expected behavior**
Document view is clear

**Screenshots**

![Image](https://github.com/pucardotorg/dristi/assets/132061840/41530532-015a-4ad6-bf82-2a79352c217e)
![Image](https://github.com/pucardotorg/dristi/assets/132061840/a7aaf9bd-cf0a-4417-a729-61d6b0edd5a0)
![Image](https://github.com/pucardotorg/dristi/assets/132061840/69a99b87-008c-440d-a900-13c57892ad88)

**Desktop (please complete the following information):**
 - OS: iOs
 - Browser Chrome
 - Version 125.0.6422.113

**Comment by nandinilp** [comment]
This issue is fixed. I tested in QA env.
Please check the video link for https://jam.dev/c/0312b357-1e58-41dd-986b-35b47b1c0328
