### ISSUE TITLE
UAT | Scrutiny | Case View

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#594]
**Describe the bug**
All sections are visible at all times irrespective of errors

**Expected behaviour**
Only sections with errors are visible. Rest of the sections remain collapsed

**Comment by nandinilp** [comment]
This issue is fixed. I tested in QA env.
Please check the video link for reference - https://jam.dev/c/d4e8c5ef-f666-432d-b0d5-f8f06f47e202
