### ISSUE TITLE
UAT | E-filing | View Case

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#604]
Post filing a case and submitting it, the litigant/advocate can view the case in My cases. The case at that point is in Payment Pending/Under scrutiny stage. 
At this point, the case file cannot be edited.
However, in the UI, Edit icons are displayed on View case screen which gives the user the idea that a case can be edited

To Reproduce Steps to reproduce the behavior:
1. Login as Litigant
2. Create and Submit Case
3. Go to View Case

Expected behaviour:
Edit icons are not displayed

Screenshots If applicable, add screenshots to help explain your problem.

![Image](https://github.com/pucardotorg/dristi/assets/132061840/b5f33df8-a23e-4aca-bd40-d4a3a46bf4bf)

**Comment by Amityadav012** [comment]
This issue is fixed and working fine in UAT Env.
