### ISSUE TITLE
UAT | E-filing | Cases not visibile in list of Cases

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#605]
On creation of a new draft case for a litigant, old case is not visible in list of cases.

Case 1 (Created on 24th June, in Payment Pending stage)
Litigant | 9999999911 | Mathews jospeh
Respondent | 90000000001 | Vibhor Dubey
Case filing number: F-C.1973.002-2024-000038

Case 2 (In draft Stage)
Litigant | 9999999911 | Mathews jospeh | Mathews and Company
Respondent |  90000000001 | Vibhor Dubey | Vibhor Dubey and company

Cannot see Case 1 in list of cases once case 2 was created

To Reproduce Steps to reproduce the behavior:
1. Login as Litigant
2. Create case and Submit
3. Create new case and Save in draft
4. Go to list of cases

Expected behavior: All cases irrespective of stage should be visible in list of cases

**Comment by Amityadav012** [comment]
This issue is fixed and working fine in UAT Env
