### ISSUE TITLE
UAT | Scrutiny | Only 1 case visibile at a time

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#610]
Only 1 case visible at a time in the Scrutiny inbox.
Once you either send back the case or Admit the case, the next case is visibile.

To Reproduce Steps to reproduce the behavior:
1. Create 2 cases and submit
2. Complete payment
3. Login as FSO
4. Go to My Cases
5. You will see the first case
6. Admit the case
7. Go back to list of cases and you will see the second case.

Expected behavior: All cases to be visible together.

Screen Recording:

**Comment by nandinilp** [comment]
This issue is fixed. I have tested in QA env.
Please check video link for reference - https://jam.dev/c/bb288c98-92c1-4315-a163-e4451ef3a5d2
