### ISSUE TITLE
UAT | Scrutiny | Total Errors Marked by FSO

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#611]
A design element is introduced in the Screen that the litigant/advocate views post FSO marking errors to enable the litigant/advocate to see the number of errors and navigate across errors.
This is not included in the screen

See design here: 
https://www.figma.com/design/fwFYdlymVjggLOltqnXWsY/Hand-off-(Digit)?node-id=489-32392&t=VjrdXSFKTIcw997C-0

How to replicate:
1) File case
2) Make Payment
3) FSO marks errors and sends back for correction
4) Litigant/Advocate Views case

**Comment by nandinilp** [comment]
This issue is fixed. I tested in QA env.
Please check the video link for reference - https://jam.dev/c/fa69174d-8564-410b-8cd4-80300234eb28
