### ISSUE TITLE
UAT | E-filing | Search on list of cases not working

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#613]
Actors: Litigants and Advocates

Issue: 
Search in list of cases is not working

Steps to replicate:
1) Login as litigant/advocate
2) Type filing number
3) Click on Search
4) No matches found is displayed

Expected behaviour:
1) Full and part search should be working

Screen Recording:
Screen Recording 2024-06-24 at 6.09.06 PM.mov

**Comment by Amityadav012** [comment]
This issue is fixed and working fine in UAT Env. But currently user able to search the case with Case ID (Full and part) only.
