### ISSUE TITLE
UAT | Scrutiny | Update Case Details

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#614]
As per scope, litigant/advocate can only edit fields that are marked as errors by FSO.
The following fields, irrespective of errors still appear editable:
1) document Uploads
2) Respondent Type (Individual/Entity)
3) All address fields 
4) Optional fields skipped by user
5) Whether user is willing to settle via ADR
6) Memorandum of Complaint
7) Prayer and Sworn statement
8) Advocate details
9) Mode of dispatch of demand notice

Steps to replicate:
1) Login as litigant
2) Submit Case
3) Make payment
4) Add errors via FSO login and send back case for correction
5) Login via litigant and view case

Expected behaviour:
Only fields marked as errors are editable including documents

Screenshots:
[![Image](https://github.com/pucardotorg/dristi/assets/132061840/675b4282-4c92-4a82-8edd-24135e96ab8b)
](url)
Screen Recording 2024-06-24 at 6.21.13 PM.mov

**Comment by Taherabharmal** [comment]
Send screen recording on slack: Screen Recording 2024-06-24 at 6.42.06 PM.mov

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected in UAT Env.
