### ISSUE TITLE
UAT | Scrutiny | Display of Errors

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#616]
Issues:
Once a case has been sent back for correction, post marking of errors by FSO, when a litigant/advocate views a case:

1) Section wise errors are showing up only for inidividual fields selectively in the section.
In the video recording, FSO marked error for the entire complainant section, but litigant could view it only for name and no other fields in the section were editable
Expected beviour:
The entire section shows an error and all fields are editable

2) For documents, error is showing for the wrong document:
In the video, FSO marked error for the Cheque Return memo.
Error is showing for the Proof of cheque deposit
Expected behaviour:
The error is displayed for the correct document

**Comment by Taherabharmal** [comment]
Not being able to upload recording. Sent on slack - File name: Screen Recording 2024-06-24 at 6.24.49 PM.mov

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected in UAT Env.
