### ISSUE TITLE
UAT | E-Filing | Adding advocate

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#617]
Clicking Yes in advocate details crashed the application:
<img width="993" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/fbb6a930-0c41-4afb-bd94-322126f96cc2">

<img width="737" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/fe48bd9b-3426-4df2-90c0-34ea99853ac3">

Further, Go to home doesnt return to home page
<img width="1454" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/d8b1f794-4f7c-4ffe-9c3e-cb2058655e0a">

**Comment by Amityadav012** [comment]
This issue is fixed and working fine in UAT Env.

**Comment by Amityadav012** [comment]
This issue is happening due to bad data (User Role update) .
It is working fine for new created user.
