### ISSUE TITLE
UAT | Scrutiny | No home button

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#620]
Once I am in the View Cases section, there is no back or home button if I want to go to home page and view pending registrations instead.

![image](https://github.com/pucardotorg/dristi/assets/173333707/4aa6ae34-e429-4351-98d2-23675d7c2824)

**Comment by vaibhavct** [comment]
We have a back button according to figma designs which will take you back to home button.
If we need to have another home button, please let us know where should it be placed.
c.c. @Ramu-kandimalla

**Comment by anshumanth-egov** [comment]
A back button should be fine but don't see it here.

**Comment by vaibhavct** [comment]
@anshumanth-egov The FSO user won't have access to see the pending registrations. The inbox component itself is a home screen for FSO user.
I will remove the employee card and make the relevant changes

**Comment by nandinilp** [comment]
I checked in Dev env, able to view the list of cases screen directly after login with FSO credentials
