### ISSUE TITLE
UAT | Bug | E-Filing

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#621]
Stage of case is shown as PAYMENT_PENDING etc, change to proper message of Payment pending and so on

<img width="292" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/e4c8c565-f802-4a61-8abe-c57efbba1e46">

**Comment by Amityadav012** [comment]
This issue is fixed and working fine in UAT Env.
