### ISSUE TITLE
UAT | E-Filing | Mandatory field flagging

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#622]
In cheque details: when I click on continue without entering the cheque amount, I get an error saying enter mandatory fields, but the cheque field is not highlighted in red

I would expect the UI to show me the fields im missing

<img width="1128" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/2d7cfb70-b995-421a-85b9-1d1f4dbe4021">

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected in UAT Env.
