### ISSUE TITLE
UAT | E-FIling | Status not updated after payment

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#624]
After I submit case, if i click on make payment and reach the Payment Successful page:
<img width="1057" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/b7cf71a4-87c5-481f-9279-c3eff0febce6">
The status of the case is still payment pending:
<img width="1347" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/5a773f25-5541-49d6-8143-3619c3e85319">

**Comment by Amityadav012** [comment]
We don't have API integration for online payment that's why the status is not changing.
