### ISSUE TITLE
UAT | E-Filing | Errors not flagged to FSO

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#625]
Submitted a case with incorrect demand notice dates (service date before demand notice send date and cheque issue date):
<img width="792" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/de8b47d0-00ae-4d42-97da-3ac562467d5d">

<img width="809" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/4d62f244-7d1f-4c1b-a303-5bec3bbab361">

These are not flagged as errors
<img width="349" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/f114fb24-bddc-4371-b80b-f4c8c7c7ef02">

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected in UAT Env.

**Comment by Taherabharmal** [comment]
@anshumanth-egov can you confirm this

**Comment by anshumanth-egov** [comment]
@Taherabharmal System doesnt allow submitting the case anymore if these errors are present, so don't think relevant any longer
