### ISSUE TITLE
UAT | Round 2 | All mandatory fields not flagged

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#698]
Cheque Details->dont fill any fields->click continue. Only some mandatory fields are highlighted, no indication for any of the document upload fields. 
Some fields like cheque amount also only have an outline, no text saying mandatory.

<img width="921" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/d28253f8-40ad-4e51-bc6c-320a4d1fd88c">

<img width="960" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/b9f5e7dd-4fe5-4370-9a09-709ae72842b1">

<img width="923" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/28dd1dc7-f02e-4611-b0b6-fa11a0565d0d">

The documents not being flagged seems to be the case across all sections

**Comment by anirudh-0** [comment]
the other fields are marked mandatory once currently mandated fields are filled

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected in UAT Env.
