### ISSUE TITLE
UAT Round 2 | E-filing | Drafts not accessible

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#699]
I am creating a case as a litigant and adding Complainant Details. 
Post this, clicking on Save Draft.
Receiving confirmation message that draft has been saved successfully.
However, the Draft is not visible in the list of cases. 

To Reproduce Steps to reproduce the behavior:
1. Login as Litigant
2. Create Case
3. Add Complainant Details
4. Save Draft
5. Go to home page

For reference, created a case by user Complainant 1|  Mobile Number 9999999914 | Vijay Jonathan Srinivasan  and saved draft.
Cannot view Draft.

Expected behavior: Draft cases are visible in list of cases

Desktop (please complete the following information):
* Browser: chrome
* Device: Macbook

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected in UAT Env.

**Comment by Taherabharmal** [comment]
This is still not working @Amityadav012

**Comment by Taherabharmal** [comment]
working as expected
