### ISSUE TITLE
UAT | Round 2 | Incorrect flagging of 15 days since accrual with no error message

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#701]
Selected date of legal notice as 3rd june
<img width="890" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/eccfd5ab-bc0e-4166-b7e9-8dfd0a67311a">

Date of service as 3rd june
<img width="1003" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/5c3ea0c9-4bca-47aa-9fe7-50b0289eba9c">

The date of 15 days, calculated automatically, is flagged as an error, cannot continue. But what's the error here?

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected in UAT Env.
