### ISSUE TITLE
UAT | Round 2 | Adding advocate crashes system

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#705]
Clicking Yes on Do you have an advocate leads to this error:

<img width="1459" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/0ce82402-19c7-4fb4-9d09-5058495e7954">

**Comment by Amityadav012** [comment]
Hi @anshumanth-egov Not able to reproduce this bug PLease find the below video reference.
https://jam.dev/c/4c236693-aebc-4c7b-967a-70d0223defb9

**Comment by anshumanth-egov** [comment]
Issue still happening at my end

**Comment by Amityadav012** [comment]
This issue is happening due to bad data.
Now it's working fine.
