### ISSUE TITLE
UAT | Round 2 | Mouse pointer on FSO screen

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#706]
On hovering over a case, mouse pointer doesn't change to Hand, no indication that I need to click on the name to go to case scrutiny.

<img width="1128" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/02787430-7c6b-470b-b796-785a41be9591">

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected in UAT Env.
