### ISSUE TITLE
UAT | Round 2 | Cheque details not editable on reassign

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#707]
Cheque details are not editable after FSO has assigned it back.

<img width="1103" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/6f9f1424-0325-4d24-bc72-bcdc188b2228">

**Comment by anshumanth-egov** [comment]
Screen Recording 2024-07-02 at 2.08.34 PM

All sections are not editable on reassign

**Comment by vaibhavct** [comment]
If FSO has marked IFSC Code as error, only that field will be editable. Rest of the fields will be disabled

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected in UAT Env.
