### ISSUE TITLE
UAT Round 2 | E-filing | Highlighting Mandatory Fields <P2>

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#708]
Describe the bug A clear and concise description of what the bug is:
Incase the user presses continue without filling all mandatory fields, the mandatory fields are highlighted.
However, if both text and doc upload fields are mandatory, only text fields are getting highlighted
Once text fields are filled, and the user continues submit, the doc upload mandatory fields are highlighted.

To Reproduce Steps to reproduce the behavior:
 See Video

Expected behavior A clear and concise description of what you expected to happen:
All mandatory fields to be highlighted together.

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected in UAT Env.
