### ISSUE TITLE
UAT Round 2 | Discrepancy in Behaviour

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#709]
In the cheque details screen, the  Continue button is clickable and highlights all mandatory fields if not filled
In Demand notice screen, the continue button is not clickable untill all mandatory fields are filled. 
This is a discrepancy and we should follow standardization across the product.

Expected behaviour: Continue button is clickable throughout and highlights any mandatory filled not filled.

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected in UAT Env.
