### ISSUE TITLE
Executing Test Cases - User Registration

### ISSUE THREAD

**Issue by krishnaprasadsannidhi** [pucardotorg/dristi#71]
User Registration Testcase document for Web includes the following workflows with QA Status as Pass/Fail -:
1) Litigant Registration
2) Advocate/Advocate Clerk Registration
3) Nyay Mitra Registration request
4) Login

User Registration Testcase document for Mobile includes the following workflows with QA Status as Pass/Fail -:
1) Litigant Registration
2) Advocate/Advocate Clerk Registration

**Comment by Amityadav012** [comment]
We have executed the test cases. Please find the attached report file

[User_Registration web.xlsx](https://github.com/pucardotorg/dristi/files/15220300/User_Registration.web.xlsx)



[User Registration Mobile.xlsx](https://github.com/pucardotorg/dristi/files/15220301/User.Registration.Mobile.xlsx)
