### ISSUE TITLE
UAT Round 2 | E-filing | Mandatory Field highlight for delay condonation

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#710]
Mandatory field not highlighted when clicking on continue.
Expected behaviour: Mandatory field is highlighted

![Image](https://github.com/pucardotorg/dristi/assets/132061840/01a1a43c-ed53-4be7-80f7-32bca1e86f32)

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected in UAT Env.
