### ISSUE TITLE
UAT | Round 2 | Complainant details disabled when advocate is filing

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#776]
Logged in as advocate -> File a case
The complainant details are disabled. If I am an advocate, there should be nothing autofilled here, I would manually add my litigant

<img width="1111" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/d506d02f-e0c8-47bd-9215-451c55ada092">

**Comment by Amityadav012** [comment]
This issue is occurred due to bad data.
Now it's working fine.
