### ISSUE TITLE
API Compliance || Discrepancies Between Hearing API Spec and POJOs

### ISSUE THREAD

**Issue by varunreddy-egov** [pucardotorg/dristi#779]
**Description:**
There are discrepancies observed between Hearing APIs and its documented specification.

**Details:**

**Hearing POJO:**
 - `hearingId` field present in POJO but not documented in the API spec

**Expected Behavior:**
The Hearing service API responses should accurately reflect the fields and data types as specified in the API documentation.

**Actual Behavior:**
- Hearing POJO:
  - `hearingId` field is present in the response but not documented in the API spec.
 
**Proposed Solution:**
1. Update the Hearing service API specification to include all fields consistently returned in the API responses (hearingId).

**Additional Information:**
[API Specification](https://github.com/pucardotorg/dristi/blob/develop/api_specifications/hearing-api-0.1.0.yaml)

**Comment by storm20198** [comment]
https://github.com/pucardotorg/dristi/pull/784
@varunreddy-egov  please verify this pr
