### ISSUE TITLE
UAT | Round 2 | Hide 202 message if not asking for the file

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#805]
The infobox saying that the 202 inquiry is mandatory can be hidden if the pincode of complainant and respondent is the same (as we are hiding the file upload box)
<img width="981" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/1c70a7cb-bcc7-4402-8c55-57f7fec6d14a">

**Comment by Beehyv-Vinod** [comment]
Working As per the latest issue, we made it as Optional. Latest bug Ref -- "https://github.com/pucardotorg/dristi/issues/1188"
