### ISSUE TITLE
UAT | Round 2 | Hand pointer instead of mouse pointer always visible

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#806]
In the home screen for litigant, I see the Hand Pointer no matter where I am located. I would expect that I see the mouse pointer unless I am hovering over a clickable element, and the mouse should change to hand only then.
Here especially, the mouse changing to hand is needed for user to know that the case name row is to be clicked to view case details.

https://github.com/pucardotorg/dristi/assets/173333707/7f44967b-4427-44d1-beab-3ac211d24344

**Comment by Amityadav012** [comment]
Hi Team, this issue is fixed and working as expected
