### ISSUE TITLE
UAT | Round 2 | Change Days Since Filing column

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#807]
The last column: either change value to show days instead of date so it matches the heading, or change heading to say case creation date (exact wording needs to be thought through)

<img width="1442" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/63386708-088c-424c-bbbf-37b43570c122">

**Comment by Amityadav012** [comment]
Hi team, this issue is fixed and working as expected.
