### ISSUE TITLE
UAT | Round 3 | User Registration

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#808]
**Describe the bug**
Loading time for map is too high in user registration in Incongito mode (accessing website for first time)

**To Reproduce**
1. Enter Unregistered mobile number
2. Enter Name
3. Click Next

**Expected behavior**
All UI and mobile screens to load in less than 1 second

**Desktop (please complete the following information):**
 - OS:  iOS
 - Browser: Chrome

**Comment by Taherabharmal** [comment]
still open

**Comment by Beehyv-Vinod** [comment]
Tested in QA Working fine.

Ref Video, https://jam.dev/c/b617872a-dca9-42a5-af5c-d14513057a18
