### ISSUE TITLE
UAT |. Round 2 | App freezes on entering url for filed case

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#833]
I start typing the URL in search bar -> I see the pucar URL and click enter -> it happens to be the URL for a previously created case -> screen is frozen, cant do anything, it has taken me to the file case view and is stuck there
Expected behaviour: Redirect to home page instead

<img width="1450" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/5cb8d247-1029-4664-b17b-b6d6874f392b">

**Comment by Amityadav012** [comment]
Hi team, this issue is fixed and working as expected.
