### ISSUE TITLE
UAT | Round 2 | Inconsistency in case search parameter

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#834]
If I click on "Search", the error message tells me to enter application ID
The search box asks me for Filing ID
The table column has Case ID
But all of these refer to the same thing. Needs to all be called the same name.

<img width="1467" alt="image" src="https://github.com/pucardotorg/dristi/assets/173333707/9b67af53-bfb6-4f8b-b8d9-77aa7137601c">

**Comment by Amityadav012** [comment]
Hi team, this issue is fixed and working as expected.
