### ISSUE TITLE
UAT | Round 2 | Judge sees all cases

### ISSUE THREAD

**Issue by anshumanth-egov** [pucardotorg/dristi#835]
In judge home screen, all cases are visible: even those pending payment and in draft. Only pending admission and admitted should be seen?
![image](https://github.com/pucardotorg/dristi/assets/173333707/c5e2ef20-72c2-4562-8bfa-a764db61f277)

**Comment by Amityadav012** [comment]
Hi team, this issue is fixed and working as expected.
