### ISSUE TITLE
UAT | View a case | Case Substage is not visible

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#878]
**Describe the bug**
As part of view a case, the case stage and substage needs to be delivered. Examples include: Trial: Inquiry.
However, only stage is visible now. 

**To Reproduce**
1. Login as judge
2. Navigate to Case in stage appearance or later
3. View case header

**Expected behavior**
Both Stage and substage are visible

**Comment by Beehyv-Vinod** [comment]
Tested in QA env, Working as Expected. Both Case Stage & Substage 

1. Complainant -- https://jam.dev/c/c4e9ea21-9a47-45e3-8517-356c45a86c34
2. Judge --   https://jam.dev/c/22039681-ce02-4c84-bdb0-e062cc622f27
3. Advocate -- https://jam.dev/c/ee871389-6344-4e53-9ba1-c2ee8e041c42
