### ISSUE TITLE
UAT | View a Case

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#889]
**Describe the bug**
Code to join a case is not visible

**To Reproduce**
Login as Litigant/Advocate/Judge
Go to view a case

**Expected behavior**
6 Digit code to view a case is viewable on the header.

**Screenshots**
Design here: 
https://www.figma.com/design/fwFYdlymVjggLOltqnXWsY/Hand-off-(Digit)?node-id=2577-76455&t=ibPqyxyd9mSJZL54-0

**Comment by Amityadav012** [comment]
Hi team, this issue is fixed and working as expected.
