### ISSUE TITLE
UAT | View a Case | Localization

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#890]
**Describe the bug**
Tab heading needs to be changed from 'Complaints' to 'Complaint'

**Comment by Amityadav012** [comment]
Hi team, this issue is fixed and working as expected.

**Comment by Amityadav012** [comment]
Hi team, this issue is fixed and working as expected in UAT env.

Ref:- 
![Image](https://github.com/user-attachments/assets/56bfc293-3f2d-4dba-abe6-9cbeb73f2a7a)
