### ISSUE TITLE
UAT | List of Draft Cases

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#894]
**Describe the bug**
Currently, status of draft case in list of cases shows as NA. 
Status should be Draft.
Secondly, drafts should be visible in a tab called drafts

**To Reproduce**
1) Login as complainant
2) File a new case
3) Save as draft

**Expected behavior**
1) List of cases in draft should show status us draft
2) Drafts are available in a seperate home screen

**Screenshots**
See design here:
https://www.figma.com/design/fwFYdlymVjggLOltqnXWsY/Hand-off-(Digit)?node-id=1853-22177&t=ec0QesnwZsea3CXe-0

**Comment by Beehyv-Vinod** [comment]
Tested in QA env, Working fine.

Ref,
https://jam.dev/c/da8917ca-747d-4e7a-8ffc-aeaddc7dc572
