### ISSUE TITLE
UAT | E-filing | Advocate cannot see case filed

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#904]
**Describe the bug**
Created a case with Mobile number  9999999901
Case number 000289
Added advocate  with mobile number  9999999914 | Aveek Singh | 1111111114
Case is not visible in advocate list of cases

**Expected behavior**
Case is visible in advocate list of cases

**Screenshots**

![Image](https://github.com/user-attachments/assets/a84b0473-2878-4c21-b400-5f9b481ea47f)
![Image](https://github.com/user-attachments/assets/981b8575-820f-4fdf-865c-d8440e1613ec)

**Comment by Amityadav012** [comment]
Hi Team, this issue is fixed and working as expected.
