### ISSUE TITLE
UAT | View a case | List of documents

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#910]
A list of documents filed as part of a case should be visible in the list of documents in a case file. Currently, no documents are available. 

**Expected behavior**
All documents expect ID card, submitted as part of file a case and join a case are displayed in the documents section

![Image](https://github.com/user-attachments/assets/f6ee592c-5a3f-4fbd-b5e3-5e484063d7e0)

**Comment by Amityadav012** [comment]
Hi Team, this issue is fixed and working as expected.

**Comment by Amityadav012** [comment]
This issue is fixed and working as expected.
Ref:- 
![Image](https://github.com/user-attachments/assets/b5b2fe6d-d1f6-4342-a8c2-49e9f7c7d429)

Currently we displaying all the document in document tab which is uploaded during the case filling.
