### ISSUE TITLE
UAT | Orders | Draft orders created during case admission

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#911]
**Describe the bug**
On case admission, 2 draft orders for bail are created by default viewable by Litigants
For the judge, 17 orders are visited by default

**To Reproduce**
1. Admit a case
2. View Case
3. Navigate to Orders tab
4. View draft orders

**Expected behavior**
Orders are not drafted/issued on case admission

Screenshot:
![Image](https://github.com/user-attachments/assets/67a17168-71ae-48d2-9db0-50b32a798296)

**Comment by Amityadav012** [comment]
Hi Team, this issue is fixed and working as expected

**Comment by Amityadav012** [comment]
Reference Video:- https://jam.dev/c/1088cfbe-a701-4f13-b1bd-c25e46228990
