### ISSUE TITLE
UAT | Join a case | Party name not visible post joining case

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#917]
**Describe the bug**
Once a new advocate joins a case,  the party should be visible in the list of cases. 
However, currently it shows a new party has joined but not details are visible. 

**To Reproduce**
1. File a case and admit the same
2. Login as an advocate who is not part of the case and join the case
3. Success screen displayed.
4. Login from any other user (complainant/advocate previously a part of the case)
5. Navigate to Parties

**Expected behavior**
Name and party type should be correctly displayed.

**Screenshots**

![Image](https://github.com/user-attachments/assets/92d8faef-31a5-4359-9d4f-6e44dcf28c0e)
![Image](https://github.com/user-attachments/assets/1515b576-9305-447e-a4ed-2e7d8922d888)

**Comment by Amityadav012** [comment]
HI Team,This issue is fixed and working as expected.
