### ISSUE TITLE
UAT | Join a case | Unable to join case for 2 complainants

### ISSUE THREAD

**Issue by Taherabharmal** [pucardotorg/dristi#921]
**Describe the bug**
For a case, an advocate can represent 2 complainants or 2 respondents at once.
However, if an advocate has joined once, the system is not allowing them to join again.

**Expected behavior**
An advocate can join the case twice. However, error messages are displayed in the following cases:
1) If the advocate tries to join a case for a party he/she is the advocate for
2) If the advocate is joining a case for a party when he is already an advocatre for the opposite party

**Comment by Amityadav012** [comment]
Need to check with dev team on this, currently we are not allowing advocate to join a case twice.

**Comment by Beehyv-Vinod** [comment]
Tested in QA env, Working fine. Same Advocate can join multiple Complainants

Ref,
https://jam.dev/c/080c6d11-d084-4bca-af74-e51fbb86ec91
