### ISSUE TITLE
UI: While litigant filling case if  he/she choses Complainant Type as Entity , Then he/she should able to change or select a different Company’s address 

### ISSUE THREAD

**Issue by mustakim-egov** [pucardotorg/dristi#965]
**Describe the bug**
While litigant filling case if  he/she choses Complainant Type as Entity then Complainant’s Location text changes to Company’s Location but when Complainant wants change the address then it should possible to change the address.

**To Reproduce**
Steps to reproduce the behaviour:
1. login as litigant
2. Click on File case button
3. Select Complainant Type radio button as Entity
4. Fill all the mandatory details 
5.Change the Company’s Location 
6.Click on continue button 
7)Now again go back to Complainant Details
8)Check for the Company’s Location
  

**Expected behaviour**
 Company’s Location should not select the same litigant or Complainant address, it should select the  changed address

**Actual behaviour**
it should able to update the  Company’s Location

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome
 - Version:126.0.6478.182

**Comment by Amityadav012** [comment]
Hi @mustakim-egov  This issue is fixed and working as expected.
Please find reference video :- https://jam.dev/c/1cf7f03a-d9ca-48eb-8c50-488c6a036f88

**Comment by mustakim-egov** [comment]
The issues got fixed.
