### ISSUE TITLE
UI: Complainant should able to add advocate while filling case.

### ISSUE THREAD

**Issue by mustakim-egov** [pucardotorg/dristi#966]
**Describe the bug**
Complainant while filling the Advocate Details , he/she  should not able to add BAR Registration  of advocate

**To Reproduce**
Steps to reproduce the behaviour:
1. Login as litigant
2. Click on File case button
3. Add  Litigant Details ,Case Specific Details 
4. Select Additional Details dropdown 
5.Click on Advocate Details
6.Click on "Is an advocate representing the complainant(s) in this case?"  radio button as yes
7.Enter BAR Registration number in BAR Registration dropdown 
8.upload Upload Vakalatnama and click on continue

**Expected behaviour**
The BAR Registration dropdown  should not be blank

**Actual behaviour**
The BAR Registration dropdown  is getting be blank when click on continue button

**Desktop (please complete the following information):**
 - OS: windows
 - Browser :chrome
 - Version :126.0.6478.182

**Comment by Amityadav012** [comment]
Hi Team, this issue is fixed and working as expected.

Current behaviour: - After selecting yes API is taking time to load advocate details.
