### ISSUE TITLE
UI: When advocate filling case ,advocate by default  should not be selected as Complement 1 Instead advocate details should store in   Advocate Details of Additional Details Section.    

### ISSUE THREAD

**Issue by mustakim-egov** [pucardotorg/dristi#968]
Describe the bug
When advocate filling case ,advocate by default  should not be selected as Complement 1 Instead advocate details should store in   Advocate Details of Additional Details Section.

To Reproduce
Steps to reproduce the behaviour:
1)Login as Advocate
2)Click on File case button

Expected behaviour
advocate by default  should not be selected as Complement 1 Instead advocate details should store in Advocate Details of Additional Details Section.

Actual behaviour
Advocate Details are not got selected in Additional Details Section.

OS: windows
Browser :chrome
Version :126.0.6478.182

**Comment by Amityadav012** [comment]
HI @mustakim-egov, Need more information on this, can you please share screen shoot for this.

**Comment by mustakim-egov** [comment]
This issue got closed as advocate details are getting stored in Advocate Details of Additional Details Section and complainant details are blank.
