### ISSUE TITLE
UI: Advocate not able add advocate while filling case

### ISSUE THREAD

**Issue by mustakim-egov** [pucardotorg/dristi#970]
**Describe the bug**
Advocate not able add advocate while filling case

**To Reproduce**
Steps to reproduce the behaviour:
1. login as advocate
2. Click on File case button
3. Fill all mandatory details , go to  Additional Details 
4. Select Advocate Details 
5.click yes on "Is an advocate representing the complainant(s) in this case?" radio button

**Expected behavior**
Advocate should able to add Advocate

Actual behaviour
Advocate is not able to add Advocate

OS: windows
Browser :chrome
Version :126.0.6478.182

**Comment by SureshSoren** [comment]
@mustakim-egov  Based on the figma https://www.figma.com/design/fwFYdlymVjggLOltqnXWsY/Hand-off-(Digit)?node-id=179-39194&t=GnR1lSjDZY4BnaLR-0  and PRD advocate should not be able to select other advocate.

**Comment by Amityadav012** [comment]
@mustakim-egov  This functionality is not there in PRD. so marking this issue as Invalid.
